### ISSUE TITLE
Wetek Play error

### ISSUE THREAD

**Issue by lookshe** [asciidisco/plugin.video.netflix#101]
I compiled latest LibreELEC from Github to test this new addon, but I get the following error in log file:

```
21:27:23.446 T:2736620448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.OSError'>
                                            Error Contents: [Errno 38] Function not implemented
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 7, in <module>
                                                from resources.lib.KodiHelper import KodiHelper
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 11, in <module>
                                                from MSL import MSL
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 11, in <module>
                                                import random
                                              File "/usr/lib/python2.7/random.py", line 885, in <module>
                                              File "/usr/lib/python2.7/random.py", line 97, in __init__
                                              File "/usr/lib/python2.7/random.py", line 113, in seed
                                            OSError: [Errno 38] Function not implemented
                                            -->End of Python script error report<--
21:27:23.454 T:3017418848   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
```

I am not really sure, but looking at the affected source from python, this error looks way strange, because a fallback is implemented: https://github.com/python/cpython/blob/2.7/Lib/random.py#L115

**Comment by MilhouseVH** [comment]
Post a link to your entire log file - what specific version of LibreELEC/Kodi is this? Are you building LibreELEC from master or libreelec-8.2?

**Comment by lookshe** [comment]
Here the entire log file: http://paste.thedevstack.de/view/1408621a

But as I could find so far, this seems to be a bug in Python 2.7: https://archlinuxarm.org/forum/viewtopic.php?f=60&t=11670

**Comment by lookshe** [comment]
Oh and I build LibreELEC from master

**Comment by lookshe** [comment]
I am building latest master with Python 2.7.12 to test it again.
But I think I will open an issue in LibreELEC.tv, because the problem is not specific to this addon.
As described in archlinuxarm forum `python2.7 -c "import random"` on shell is enough to get the error.

**Comment by asciidisco** [comment]
@lookshe Is it okay to close this here? I also think that this should be moved to the LibreElec Bugtracker.

**Comment by lookshe** [comment]
Yes it's fine. I already opened a bug repot (https://forum.libreelec.tv/thread/9671-wetek-play-python-2-7-3-bug-perhaps-arm-related/) and testing the mentioned patch.
