### ISSUE TITLE
[Settings/Library] Custom library path results in error

### ISSUE THREAD

**Issue by hawkeyexp** [asciidisco/plugin.video.netflix#107]
It seems only local paths would work atm. if setting library to paths in special: nfs: or cifs: results in errors like this:

Error Contents: [Error 123] Die Syntax f��en Dateinamen, Verzeichnisnamen oder die Datentr娥rbezeichnung ist falsch: 'nfs:'

Would be great to fix for using centralized netflix library for multiple clients (in my case one win and two rpi's share same sources).

**Comment by tonyschuite** [comment]
same problem here as well.

**Comment by hawkeyexp** [comment]
Is fixed with pull request #111

**Comment by trummerjo** [comment]
Is fixed with pr #111
