### ISSUE TITLE
[Inputstream] Misleading message "Missing Inputstream addon" when it's disabled

### ISSUE THREAD

**Issue by ligfx** [asciidisco/plugin.video.netflix#109]
Ideally, this would distinguish between missing and disabled. This would make it easier on users to set this up the first time, since in current Kodi nightly the Inputstream addon is installed but disabled.

One way this could be done is to modify `KodiHelper.get_inputstream_addon()` to return a tuple `(url, enabled)`, and then add an additional error message in `KodiHelper.play_item`. If this sounds reasonable, I can throw together a PR.

Let me know!

**Comment by zombielinux** [comment]
Did you find out where to enable this setting?

Or did you have to install it seperately?

**Comment by ligfx** [comment]
@zombielinux Yes, you can enable the addon using the normal addon information/configuration page. It should come pre-installed on Kodi nightlies.

**Comment by trummerjo** [comment]
Sounds good to me. So feel free to make a PR!
