### ISSUE TITLE
Optionally skip intro

### ISSUE THREAD

**Issue by konstantinblaesi** [asciidisco/plugin.video.netflix#114]
Netflix' HMTL5 player displays a "skip intro" button on the bottom right when watching series. Is this possible to implement?

**Comment by trummerjo** [comment]
i dont think that it is possible the skip the intro on a lets call it "video" basis.
This would - if it is possible - a general preference so that all intros are skipped.

**Comment by asciidisco** [comment]
It *might* be possible to do this by using event listener to key actions, etc.,
but I´d not prefer going down that road.

Another option could be (as I tried to implement this once), to provide a new context menu item for the video , that starts the video after the intro timestamp we received from the API.

As said, tried to implement this once, didn't work for *I don't know* reasons.

Any help appreciated: https://github.com/asciidisco/plugin.video.netflix/issues/34

**Comment by asciidisco** [comment]
Closing this, as any further discussion should happen in issue #34
