### ISSUE TITLE
[Profiles] Editing profiles

### ISSUE THREAD

**Issue by gregoir3** [asciidisco/plugin.video.netflix#120]
It says under functionality; Multiple profiles. Does this mean multiple profiles by Netflix or by Kodi? Yes, I do see multiple profiles in Netflix but I can't edit them individually, like for instance, language or subtitles. I found a way around this by using the Kodi profiles (adding an new one and using it) and edit the prefered language in settings. Unfortunately loading Netflix in the new profile stopped working in the latest version of Kodi Leia (experimental amlogic s905x), therefore I was looking if it was possible in the addon itself.

**Comment by asciidisco** [comment]
@gregoir3 

You can edit the individual settings for the profiles in the Netflix Settings section of the website, they should have an effect in the plugin as well.

```
Unfortunately loading Netflix in the new profile stopped working in the latest version of Kodi Leia (experimental amlogic s905x), therefore I was looking if it was possible in the addon itself.
```

Can you send a debug.log? I´d like to investigate this, but I´m not able to reproduce the problem.

Btw.: There is an issue about editing Netflix profiles from within Kodi, but that is far future stuff: https://github.com/asciidisco/plugin.video.netflix/issues/51

**Comment by gregoir3** [comment]
With the latest alpha version this kodi profile swapping install problem was solved.

**Comment by asciidisco** [comment]
@gregoir3 Glad to hear that :)

**Comment by Aimost** [comment]
Guys, I have a similar problem. My netflix account is in Spanish. But when I'm going to play an episode the default language is German. 

To fix it, I have to go to sound and change the audio channel there, which by the way does not appear as Spanish, it appears as "UNKNOWN" / (DESCONOCIDO in Spanish). 

How could I set the language for all content?

https://i.imgur.com/wFSM6Wu.png

I'm in the last version. With Raspberry pi 3.
