### ISSUE TITLE
Subtitles language not available

### ISSUE THREAD

**Issue by nemphys** [asciidisco/plugin.video.netflix#124]
I got the plug-in working properly (works quite well, way to go!) but I have an issue with the available subtitles languages.

I am Greek and Netflix was only recently made available in my country.

On my phone/tablet I can watch most of the movies/TV shows with Greek subtitles, but when I try to watch the same content in Kodi using this plugin, I only get English and Turkish (!) as available options.

Kodi and Netflix language settings are both set to English (but so is the relevant settings on my phone, so I don't think this is the cause of the problem).

I saw somewhere in the Netflix forums that it is advised to switch the Netflix language preference to one's native language in order to always get the this language available for subtitles, but Greek is not available as an option in Netflix languages setting.

Strangely, I have exactly the same problem in the Netflix app on my Samsung TV (quite old one, not Android)  so it might not be related to the plug-in.

Any help/ideas would be appreciated.

**Comment by Uukrull** [comment]
Read this: https://github.com/asciidisco/plugin.video.netflix/issues/95

**Comment by nemphys** [comment]
I don't think this has anything to do with my problem, since Greek is not image-based and Kodi already has system wide support for greek.

**Comment by asciidisco** [comment]
@nemphys I haven't found an episode with Greek subtitles to test with, but I found Russian subtitles & they´re image bases (which makes me think that this may be the case with other languages containing cyrillic chars as well).

If you could do me a favour & start an episode with greek subtitles enabled in a web browser & have look at the `developer tools -> network panel -> filter by "img"` while it´s running?!

![screen shot 2017-09-11 at 14 58 20](https://user-images.githubusercontent.com/805339/30275604-3582366c-9702-11e7-93f5-304dd01f10c7.png)

**Comment by nemphys** [comment]
Jesus, you're right. For some reason, Netflix does serve greek subtitles as images (can't imagine why).
Does that mean I am out of luck?
Has there been any progress on making image subtitles work?

PS. Sorry for my initial insistence, but I still find it hard to believe that they would use images for subtitles.

**Comment by asciidisco** [comment]
No need to feel sorry, and I fear that you´re indeed out of luck for the time being.
This needs to be adressed in inputstream.adaptive as well as Kodi core.
To be honest, I´m not sure if there´s a chance that this will be implemented some time soon. If somebody would volunteer to get this into both codebases, then maybe...

Another option might be, to sniff what the official Netflix app is doing, maybe it requests subtitles in a more digestible format.

Sorry for the bad news...
Hope it´s okay to close this & to have further discussions here: https://github.com/asciidisco/plugin.video.netflix/issues/95
