### ISSUE TITLE
[Subtitles] Subtitles support

### ISSUE THREAD

**Issue by Uukrull** [asciidisco/plugin.video.netflix#13]
Will this be added?
As a reference, here is a youtube video that shows how to get the subtitles urls (I tried it and it works) but I guess it won't be an easy task to do the same from the addon:

https://www.youtube.com/watch?v=UTaIBamGJTI

**Comment by trummerjo** [comment]
we already have the subtitle urls.
dont know if the format is supported in kodi right now.

**Comment by Uukrull** [comment]
I don't think so. It looks like they are in dxfp format:

Netflix subtitle example:

`<p begin="719478760t" end="763682920t" region="Region_00" xml:id="subtitle0">Dichiarate tutto ciò che avete.<br/>Quello che non dichiarate sarà confiscato.</p>`

Amazon subtitle example:

`<tt:p begin="00:00:02.570" end="00:00:05.739">&quot;CHEERS&quot; IS FILMED<tt:br/>BEFORE A LIVE STUDIO AUDIENCE.</tt:p>`

And here is how Sandmann79's Amazon addon converts them to .srt:
https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py#L1298

**Comment by asciidisco** [comment]
@Uukrull You´re correct. Isn't supported yet & is dxfp (https://www.w3.org/TR/ttaf1-dfxp/)
Instead of writing or copying a converter, it might be a good idea to bring it to Kodi directly & write a proper dxfp parser in C.

**Comment by Uukrull** [comment]
It's more like a hack than proper code, but:
https://github.com/Uukrull/plugin.video.netflix/commit/7a5c07d8281e3b073537ad06bc9b98d5c4ccce6e

I'm using this python [code](https://github.com/isaacbernat/netflix-to-srt/blob/master/to_srt.py) for the dfxp to srt converter and only downloading the Castilian and English subs to special://temp (that is set as the default subtitles folder in Kodi).
Because the manifest is created after play_item is called, I can't use setSubtitles; is there a way to be able to do that?

**Comment by asciidisco** [comment]
@Uukrull I've started implementing a C based dfxp parser for Kodi yesterday. Might take some time until it hits agile, but's on the way.
I'd rather not like to put some hacks into the plugin in the meantime.

**Comment by Uukrull** [comment]
Great! It wasn't a PR, just a (dirty) way to get subtitles working for those interested :)

**Comment by trummerjo** [comment]
@asciidisco please note that inputstream.adaptive needs support for subtitles too. I'm not sure but i think they are not supported yet.

**Comment by joaosagrath** [comment]
the subtitles still don't work? or we have a "temporary solution"?

**Comment by asciidisco** [comment]
@joaosagrath I think @Uukrull has a temporary solution in his fork: https://github.com/Uukrull/plugin.video.netflix/tree/subtitles

**Comment by Uukrull** [comment]
I updated my subtitles branch and now there is no need to browse for the downloaded subtitle. You only have to set your language code and you're ready to go :)

![image](http://i.imgur.com/SSmI609.png)

![image](http://i.imgur.com/2SUm5iO.jpg)

https://github.com/Uukrull/plugin.video.netflix/commit/689cd54dc3c682cc81f8223070c34d772d713293

**Comment by MediaBrasil** [comment]
Uukrull, work great, congratulations.

**Comment by joaosagrath** [comment]
@Uukrull Congratulations brother!! this is awesome!!

**Comment by mirkorobocop** [comment]
@Uukrull Everything works, thanks!

**Comment by Uukrull** [comment]
Done. https://github.com/asciidisco/plugin.video.netflix/pull/35

**Comment by asciidisco** [comment]
👍

**Comment by Uukrull** [comment]
I guess my patch won't be needed anymore after this commit from peak3d :)
[Subtitles (TTML-SRT)](https://github.com/peak3d/inputstream.adaptive/commit/61397dfa2784a118f8cb019ae06f51e163669392)

**Comment by asciidisco** [comment]
He told me today, that he started working on something. So yeah, maybe we can ditch the PR :D

**Comment by asciidisco** [comment]
Update: We´re (and with we, I mean @trummerjo :D) need to adapt the MSL service so that Inputstream can handle the subtitle files. If all goes well, "native" support should be in sometime soon :)

**Comment by trummerjo** [comment]
Your wish is my command: https://github.com/asciidisco/plugin.video.netflix/commit/0345351fac6664b768036a87c3e504a9729b5816

**Comment by Uukrull** [comment]
@trummerjo : it'd be better to use the simplesdh profile instead of the dfxp-ls-sdh one. The dfxp-ls-sdh profile only makes sense for converting to the ssa format not srt, the file size is much bigger (300 KB vs 800KB for the movie "Pain & Gain", for example) and doesn't look good with multiple lines.

simplesdh:
```
<p begin="3419255005t" end="3437605003t" xml:id="subtitle95"><span style="style_0">Shit, otherwise</span><br/><span style="style_0">I was looking at</span><br/><span style="style_0">another 40 years</span></p>
```
![image](http://i.imgur.com/N8eFcGL.jpg)


dfxp-ls-sdh:
```
<p begin="3419255005t" end="3437605003t" region="region_00" tts:extent="60.00% 5.33%" tts:origin="32.50% 73.96%" xml:id="subtitle175"><span style="style_0">Shit, otherwise</span></p>
<p begin="3419255005t" end="3437605003t" region="region_01" tts:extent="62.50% 5.33%" tts:origin="32.50% 79.29%" xml:id="subtitle176"><span style="style_0">I was looking at</span></p>
<p begin="3419255005t" end="3437605003t" region="region_02" tts:extent="62.50% 5.33%" tts:origin="32.50% 84.62%" xml:id="subtitle177"><span style="style_0">another 40 years</span></p>
```
![image](http://i.imgur.com/PVx9Gaj.jpg)

**Comment by trummerjo** [comment]
switched to the simplesdh profile
