### ISSUE TITLE
[Lists] Posters from Netflix Originals

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#134]
The Netflix website has some great posters for the "Netflix Originals"

These posters are exclusives from this category of movies/series made by Netflix.

When we navigate on addon, we receive landscape images.

Is there some way to parse these poster only to Netflix Originals?
These way, when we enter on category "Netflix Originals", we receive theses poster instead landscapes images.

Here a screenshot of theses posters:

![clipboard02](https://user-images.githubusercontent.com/16491360/30356311-b6b61bc4-980e-11e7-8103-d8563dc1b645.jpg)

**Comment by asciidisco** [comment]
Probably yes, we only need to find the name of the key to query Netflix for the URLs of those.

**Comment by joaosagrath** [comment]
Hi, I've beem digging in the code of Netflix website, and found the URL's of these posters. I don't know if this can help in some way, but, don't hurt show here hehehe

This is the URL por the normal image:
https://occ-0-1429-1567.1.nflxso.net/art/38cba/24a7c4961bf2c2137c552a7c183260f56e938cba.jpg

And this is the URL for the poster image: 
https://occ-0-1429-1567.1.nflxso.net/art/c4596/10ab762ec1f050420f7326d3c7ae19b815bc4596.webp

Hope this help!

Cheers

**Comment by nigeldixon** [comment]
I might counter this...  the dimensions are totally wrong for use as Kodi posters.

I am finding other dimensions for art in some shows within the meta response though so will take a closer look.

**Comment by caphm** [comment]
Fixed in #396
