### ISSUE TITLE
Kodi 17

### ISSUE THREAD

**Issue by matejmosko** [asciidisco/plugin.video.netflix#14]
Hello, I have just a quick question. Is kodi 18 really necessary? Any plans for current kodi release build?

**Comment by asciidisco** [comment]
@matejmosko From what I know, there is no intention to backport the changes in current kodi-agile to the already stable Kodi 17.
And yes, they are necessary & so I highly believe there´s no way that this will ever work with Kodi 17.

In regards to your second question, I have no idea about how the Kodi release process works (especially with things that live in kodi-agile only atm.), but I´ll ask someone who knows & keep you updated.

Cheers

**Comment by matejmosko** [comment]
Hi, there is no need to answer my second question. My wording was a bit confusing. I was just asking if you plan to release kodi 17 version (current) of netflix addon. I will keep myself updated about kodi 18 release :). Thanks for your great work. I am looking forward the time I will try it myself. Have a nice day.
