### ISSUE TITLE
[Lists] Add high quality wallpapers

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#146]
I've notice that every show or movie, has a wallpaper when the episode or movie reach the end. In this screen we have three things: The current episode/movie in a small window on the upper left of the screen (normally on final credits at this time), The next episode (for series) or some recommended movie/series on botton right of the screen. And a big image in full screen of the movie/serie we just watch.

So, the addon pull from netflix some "fanart" already, but normally is a screenshot for the movie/serie. I believe if the addon uses this wallpapers, it would be much better, because this arts has great quality 

Here the screenshot of the screen:

![sasadx](https://user-images.githubusercontent.com/16491360/30766931-e12b724c-9fce-11e7-8fb5-d2daece98694.jpg)

And digging into de netflix code of this screen, i've found tha URL of this wallpaper:

https://occ-0-1429-1567.1.nflxso.net/art/230e6/9e9113e015bf5ba34591c40248d87ebef58230e6.webp

Is the a way to use this?
And hope this can help to something ;)

**Comment by asciidisco** [comment]
Thanks for helping out. My problem is, that I need to find the correct key to request that url for a show/movie within the JSON request. I´ll do some try & error games to see if I can fetch it. Thanks for the URL & the related show, at least I know have something to compare 👍

**Comment by caphm** [comment]
Fixed in #396
