### ISSUE TITLE
Netflix is crashing :(

### ISSUE THREAD

**Issue by ymca11** [asciidisco/plugin.video.netflix#152]
Hi,

Looks like a nice plugin.
The problem is, it's not working for me.

Here is my Kodi log.
https://pastebin.com/1UH890Hx

I hope this can help with the problem.

Cheers.
ymca11

**Comment by trummerjo** [comment]
Please install Cryptodomex.
There are a lot of closed issues regarding this problem.
You may check this one: https://github.com/asciidisco/plugin.video.netflix/issues/85

**Comment by ymca11** [comment]
Thanks. I will continue there.
