### ISSUE TITLE
[Lists] Ability to set default profile (and temporary switch)

### ISSUE THREAD

**Issue by kat953162** [asciidisco/plugin.video.netflix#157]
Title says it all.

Some devices are more personal, (like phones and laptops) while other devices are more shared (televisions, laptops, etc.). Ideally, it should be up to the user.

**Comment by kat953162** [comment]
A temporary solution is to just save it to Favorites. However, this should be implemented fully.

**Comment by hawkeyexp** [comment]
Possible solution as pull request:

Enable auto login #160

**Comment by hawkeyexp** [comment]
related pr is merged - available in next build.
