### ISSUE TITLE
Kodi 18 alpha, armV7, Android--DRM issue

### ISSUE THREAD

**Issue by pjiko** [asciidisco/plugin.video.netflix#164]
Hi 
I've installed right now the addon, trying to play some contents I'm receiving the following errors in the log:
E/Drm     (  175): Failed to find drm plugin
V/Kodi    (11202): Debug Print: AddOnLog: InputStream Adaptive: Unable to install Event Listener (-10003)
V/Kodi    (11202): Debug Print: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
V/Kodi    (11202): Debug Print: CVideoPlayer::OpenInputStream - error opening [http://localhost:34999/manifest?id=80160358]
V/Kodi    (11202): Debug Print: CVideoPlayer::OnExit()
V/Kodi    (11202): Debug Print: Invalid media type ""
I/MediaFocusControl(  482):  AudioFocus  abandonAudioFocus() from android.media.AudioManager@2467beb3org.xbmc.kodi.interfaces.XBMCAudioManagerOnAudioFocusChangeListener@3e66fbe9

can someone help me please?

**Comment by asciidisco** [comment]
Please reopen a new issue, containing all the information requested in the Readme:

- Enable verbose logging in the plugin settings
- Enable the Debug log in you Kodi settings
- Open an issue with a titles that summarises your problems and include:
  1.) Kodi version (git sha if possible)
  2.) Inputstream.adaptive version (git sha if possible)
  3.) Your OS and OS version
  4.) Libwedevine version (In your case, Widevine Level available on your Android system)
  5.) A full Kodi debug log
