### ISSUE TITLE
[Video playback] Stream/Service not available OSMC (RPi 2)

### ISSUE THREAD

**Issue by strzmiele** [asciidisco/plugin.video.netflix#168]
Hello,
I've tried to install Netflix Plugin on Raspberry Pi2. 
First manual for OSMC taken from :
[https://discourse.osmc.tv/t/how-to-use-netflix-on-osmc-rpi2/11478/18](https://discourse.osmc.tv/t/how-to-use-netflix-on-osmc-rpi2/11478/18)

I've triead on LibreElec for RPi2 with LibreELEC-RPi2.arm-8.0-Milhouse build but in that all cases I've got same errors while start playing movie.... I can normal navigate all movies, categories etc... 
What is wron , where have I to search for problems , any ideas ?

Piotr

> 13:16:12.414 T:1621357552  NOTICE: Opening stream: 1 source: 256
> 13:16:12.481 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.134/?o=AQH8uKZckcYZrt6ndKq3u7eKo7WkEf0CI_BQwIboc_abM1abcMG8-UdyndL0cJnp14dlMjHBRvkbM2RPHpQXV6MFwgCWjID1SXO8XJAF6r7cxJoTuj1eNCUOLaELaMLpzWilXNKftpLMxAVTYWqgcAtN5HRUA2mCOv6DeMLdMlqobLOIDm3i7WoyBTAquxGnKLuNBHo0Q616NL8_-Ak1&v=3&e=1507418011&t=J3STpty37KCuvvcF6TwcKjvWlAw|Range=bytes%3d0-40340&seekable=0
> 13:16:12.481 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.481 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.481 T:1621357552 WARNING: OpenStream - Unsupported stream 1. Stream disabled.
> 13:16:12.481 T:1621357552  NOTICE: Opening stream: 2 source: 256
> 13:16:12.548 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.160/?o=AQH8uKZckcYZrt6ud6iyuLyOorqyVuccOLkMnt_pML7IN16ZddH-oBlwmNvwbIGigcpuKlrUca0FRHRBM6kWTp8xvlvHzcucc0KVdb8C3r7Vvd4UvxlHIxIgNq0tdM-sjn_qUNGfoN2YrmULUQfDB15KrWRND2eEPeecb5DZKluvdvqEGT_1_mk1EDIi7V60KrO5anxyAa9tdK90tR8&v=3&e=1507418011&t=khbt4w532uZIwe7u6NgbIG35HDQ|Range=bytes%3d0-40340&seekable=0
> 13:16:12.549 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.549 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.549 T:1621357552 WARNING: OpenStream - Unsupported stream 2. Stream disabled.
> 13:16:12.549 T:1621357552  NOTICE: Opening stream: 3 source: 256
> 13:16:12.555 T:1956835328  NOTICE: m_playbackStarting
> 13:16:12.556 T:1956835328  NOTICE: StereoscopicsManager::IsPlaying
> 13:16:12.615 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.160/?o=AQH8uKZckcYZrt6ud6iyuLuNobSyVuccOLkMnt_pML7IN16ZddH-oBlwmNvwbIGigcpuKlrUca0FRHRBM6kWTp8xvlvHzcucc0KVdb8C3r7Vvd4UvxlHIxIgNq0tdM-sjn_qUNWfoN2YrmULUQfDB15KrWRND2eEPeecb5DZKluvdvqEGT_1_mk1EDIi7V60KrO5anxyAa9tdK90tR8&v=3&e=1507418011&t=DJmvRjgS9TUn03jsT45diIlvdm8|Range=bytes%3d0-40340&seekable=0
> 13:16:12.615 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.615 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.616 T:1621357552 WARNING: OpenStream - Unsupported stream 3. Stream disabled.
> 13:16:12.616 T:1621357552  NOTICE: Opening stream: 4 source: 256
> 13:16:12.682 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.134/?o=AQH8uKZckcYZrt6ndKq3u7eFp7WqEf0CI_BQwIboc_abM1abcMG8-UdyndL0cJnp14dlMjHBRvkbM2RPHpQXV6MFwgCWjID1SXO8XJAF6r7cxJoTuj1eNCUOLaELaMLpzWilXNKYs5LMxAVTYWqgcAtN5HRUA2mCOv6DeMLdMlqobLOIDm3i7WoyBTAquxGnKLuNBHo0Q616NL8_-Ak1&v=3&e=1507418011&t=VHU2wYZMYh9HHmriEw5Vf40uEqU|Range=bytes%3d0-40340&seekable=0
> 13:16:12.682 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.682 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.683 T:1621357552 WARNING: OpenStream - Unsupported stream 4. Stream disabled.
> 13:16:12.683 T:1621357552  NOTICE: Opening stream: 5 source: 256
> 13:16:12.749 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.160/?o=AQH8uKZckcYZrt6ud6iyuLqPpLayVuccOLkMnt_pML7IN16ZddH-oBlwmNvwbIGigcpuKlrUca0FRHRBM6kWTp8xvlvHzcucc0KVdb8C3r7Vvd4UvxlHIxIgNq0tdM-sjn_qU9CfoN2YrmULUQfDB15KrWRND2eEPeecb5DZKluvdvqEGT_1_mk1EDIi7V60KrO5anxyAa9tdK90tR8&v=3&e=1507418011&t=5RuGQVnFoxxfACtvkqgiWUzmg38|Range=bytes%3d0-40340&seekable=0
> 13:16:12.749 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.749 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.750 T:1621357552 WARNING: OpenStream - Unsupported stream 5. Stream disabled.
> 13:16:12.750 T:1621357552  NOTICE: Opening stream: 6 source: 256
> 13:16:12.816 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.134/?o=AQH8uKZckcYZrt6ndKq3u7eFobOoEf0CI_BQwIboc_abM1abcMG8-UdyndL0cJnp14dlMjHBRvkbM2RPHpQXV6MFwgCWjID1SXO8XJAF6r7cxJoTuj1eNCUOLaELaMLpzWilXNGatpLMxAVTYWqgcAtN5HRUA2mCOv6DeMLdMlqobLOIDm3i7WoyBTAquxGnKLuNBHo0Q616NL8_-Ak1&v=3&e=1507418011&t=ga8uKFl4OZ76rjlQQ8Qn6R2p-yg|Range=bytes%3d0-40340&seekable=0
> 13:16:12.817 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.817 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.817 T:1621357552 WARNING: OpenStream - Unsupported stream 6. Stream disabled.
> 13:16:12.817 T:1621357552  NOTICE: Opening stream: 7 source: 256
> 13:16:12.883 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.160/?o=AQH8uKZckcYZrt6ud6iwvL6JobeyVuccOLkMnt_pML7IN16ZddH-oBlwmNvwbIGigcpuKlrUca0FRHRBM6kWTp8xvlvHzcucc0KVdb8C3r7Vvd4UvxlHIxIgNq0tdM-sjn_qUtafoN2YrmULUQfDB15KrWRND2eEPeecb5DZKluvdvqEGT_1_mk1EDIi7V60KrO5anxyAa9tdK90tR8&v=3&e=1507418011&t=NCnI7jMXMIe17yTt_m2DQvFEnOg|Range=bytes%3d0-40340&seekable=0
> 13:16:12.883 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.884 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.884 T:1621357552 WARNING: OpenStream - Unsupported stream 7. Stream disabled.
> 13:16:12.884 T:1621357552  NOTICE: Opening stream: 8 source: 256
> 13:16:12.949 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.114.152/?o=AQH8uKZckcYZrt6ud6uzv7aLorCyVuccOLkMnt_pML7IN16ZddH-oBlwmNvwbIGigcpuKlrUca0FRHRBM6kWTp8xvlvHzcucc0KVdb8C3r7Vvd4UvxlHIxIgNq0tdM-sjn_qVdqfoN2YrmULUQfDB15KrWRND2eEPeecb5DZKluvdvqEGT_1_mk1EDIi7V60KrO5anxyAa9tdK90tR8&v=3&e=1507418011&t=Ao-bEllqFHw30IH417VA1t3BwyQ|Range=bytes%3d0-40340&seekable=0
> 13:16:12.949 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:12.950 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:12.950 T:1621357552 WARNING: OpenStream - Unsupported stream 8. Stream disabled.
> 13:16:12.950 T:1621357552  NOTICE: Opening stream: 9 source: 256
> 13:16:13.015 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.134/?o=AQH8uKZckcYZrt6ndKq3u7eFr7KrEf0CI_BQwIboc_abM1abcMG8-UdyndL0cJnp14dlMjHBRvkbM2RPHpQXV6MFwgCWjID1SXO8XJAF6r7cxJoTuj1eNCUOLaELaMLpzWilXNaftpLMxAVTYWqgcAtN5HRUA2mCOv6DeMLdMlqobLOIDm3i7WoyBTAquxGnKLuNBHo0Q616NL8_-Ak1&v=3&e=1507418011&t=IplwEEj6__56uAyqbHsISqyFQmQ|Range=bytes%3d0-40340&seekable=0
> 13:16:13.016 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:13.016 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:13.016 T:1621357552 WARNING: OpenStream - Unsupported stream 9. Stream disabled.
> 13:16:13.017 T:1621357552  NOTICE: Opening stream: 10 source: 256
> 13:16:13.084 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.116.157/?o=AQH8uKZckcYZrt6ud6uzvr2Kp7eyVuccOLkMnt_pML7IN16ZddH-oBlwmNvwbIGigcpuKlrUca0FRHRBM6kWTp8xvlvHzcucc0KVdb8C3r7Vvd4UvxlHIxIgNq0tdM-sjn_qVtKfoN2YrmULUQfDB15KrWRND2eEPeecb5DZKluvdvqEGT_1_mk1EDIi7V60KrO5anxyAa9tdK90tR8&v=3&e=1507418011&t=fJznLHxXOATWsXuK3vqdo0Go2HA|Range=bytes%3d0-40340&seekable=0
> 13:16:13.084 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:13.085 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:13.085 T:1621357552 WARNING: OpenStream - Unsupported stream 10. Stream disabled.
> 13:16:13.085 T:1621357552  NOTICE: Opening stream: 11 source: 256
> 13:16:13.142 T:1956835328  NOTICE: m_playbackStarting
> 13:16:13.142 T:1956835328  NOTICE: StereoscopicsManager::IsPlaying
> 13:16:13.152 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.160/?o=AQH8uKZckcYZrt6ndKq3u7eEoLOkEf0CI_BQwIboc_abM1abcMG8-UdyndL0cJnp14dlMjHBRvkbM2RPHpQXV6MFwgCWjID1SXO8XJAF6r7cxJoTuj1eNCUOLaELaMLpzWilXNKcs4SDkG8zOVrNE3wY4z1EGmWMPPmaZ9WPNkKpa6nBAnqw-nkxAiUos0foO7mFMBQyBe94I_8vs0Qjlg&v=3&e=1507418011&t=inB0dtMuogphc1RsonWPEvqrnd8|Range=bytes%3d0-40340&seekable=0
> 13:16:13.152 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:13.152 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:13.153 T:1621357552 WARNING: OpenStream - Unsupported stream 11. Stream disabled.
> 13:16:13.153 T:1621357552  NOTICE: Opening stream: 12 source: 256
> 13:16:13.222 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.115.134/?o=AQH8uKZckcYZrt6ndKq3u7eKo7WkEf0CI_BQwIboc_abM1abcMG8-UdyndL0cJnp14dlMjHBRvkbM2RPHpQXV6MFwgCWjID1SXO8XJAF6r7cxJoTuj1eNCUOLaELaMLpzWilXNKftpLMxAVTYWqgcAtN5HRUA2mCOv6DeMLdMlqobLOIDm3i7WoyBTAquxGnKLuNBHo0Q616NL8_-Ak1&v=3&e=1507418011&t=J3STpty37KCuvvcF6TwcKjvWlAw|Range=bytes%3d0-40340&seekable=0
> 13:16:13.222 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:13.222 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:13.222 T:1621357552 WARNING: OpenStream - Unsupported stream 12. Stream disabled.
> 13:16:13.224 T:1621357552  NOTICE: Opening stream: 13 source: 256
> 13:16:13.236 T:1956835328  NOTICE: m_playbackStarting
> 13:16:13.236 T:1956835328  NOTICE: StereoscopicsManager::IsPlaying
> 13:16:13.293 T:1621357552   ERROR: CCurlFile::Open failed with code 404 for http://198.38.116.157/?o=AQH8uKZckcYZrt6ndKWyvLiJo7qqEf0CI-dQwIboc_abM1abcMG8-UdyndL0cJnp14dlMjHBRvkbM2RPHpQXV6MFwgCWjID1SXO8XJAF6r7cxJoTuj1eNCUOLaELaMLpzWilXNKWtJLMxAVTYWqgcAtN5HRUA2mCOv6DeMLdMlqobLOIDm3i7WoyBTAquxGnKLuNBHo0Q616NL8_-Ak1&v=3&e=1507418011&t=B_Mp5M1w8GMFJQ45AgLeDnSFM-o|Range=bytes%3d0-40340&seekable=0
> 13:16:13.293 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Download SIDX retrieval failed
> 13:16:13.294 T:1621357552   ERROR: AddOnLog: InputStream Adaptive: Unable to select stream!
> 13:16:13.294 T:1621357552  NOTICE: Finding audio codec for: 86057

**Comment by asciidisco** [comment]
Can you please post a complete debug log, also as a link to an external service, because GitHub issues are a bad logviewer.

**Comment by strzmiele** [comment]
Hello,

here you can find my whole Kodi log. I 've tried after booting navigate to the film 'To the Bone' and I've tried to start them...

Piotr

[https://drive.google.com/open?id=0B8FqkCEL3IRrbzh6aG1wU0J1MnM](url)

**Comment by asciidisco** [comment]
@matejmosko Maybe you can help with this, I have absolute no background using OSMC

**Comment by matejmosko** [comment]
Hi, I have just tried the osmc nightly build and installed everything according to manuals (with slight modifications I have described at osmc forums). For me this seems as a connectivity issue as well. Have you tried to access 198.38.115.148 from different computer on same network or directly from ssh with wget or curl? 

I have tried now from my laptop and the result is 403 (forbidden = good result). 404 means it does not exist (or is unreachable). Maybe there is something on your network preventing access to the server.

As far as the errors are same for libreelec and osmc, it is probably not related to osmc, but to (a) network (b) kodi (c) inputstream.adaptive

**Comment by strzmiele** [comment]
Hello matejmosko,
that was great idea to check restrictions in my home network. I'm connected to the internet via FritzBox Router and all devices use Standard-Connection-Profil where is filter  [BPjM-Modul](http://www.bundespruefstelle.de/bpjm/Service/english.html) set. I've changed settings for Raspbery Pi so it can connect without restrictions and it has solved my problem.
Thank You :)
Piotr
