### ISSUE TITLE
Add Ultra HD 4K list

### ISSUE THREAD

**Issue by im85288** [asciidisco/plugin.video.netflix#187]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

## General infomration
Now that 4K streams are working it would be nice to get back the Ultra HD 4K listing netflix provides

### Prerequisites

* [x] Are you running the latest version?

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

**Comment by asciidisco** [comment]
Referencing & closing this in favour of https://github.com/asciidisco/plugin.video.netflix/issues/115

**Comment by im85288** [comment]
I’m not sure they are related. When you have an ultra hd sub to Netflix the row below continue watching is one for ultra hd content.

I debugged the code and could not locate this entry in the list of available sections (where you have the user/genre/recommendations) I did find others like spotlight but not the ultra hd one.
