### ISSUE TITLE
[Profiles] Problem with unicode chars in profile names

### ISSUE THREAD

**Issue by anthonws** [asciidisco/plugin.video.netflix#189]
* **I'm submitting a ... **
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Android 7.0.1
Asus Transformer Prime (Tegra 3)
Netflix oficiall app works without issues

### Prerequisites

* [x ] Are you running the latest version?
Yes. Both for Kodi and Netflix plugin.

### Description

[Description of the bug or feature]
Netflix plugin crashes with the following exception:

21:35:18.996 T:1443973408   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\xea' in position 2: ordinal not in range(128)
(...)

Logfile available at http://paste.ubuntu.com/25728379/

### Steps to Reproduce

1. Install latest version of Kodi Master nigthly
2. Download plugin.video.netflix.zip from master
3. Enable inputstream.adaptive (leave defaults) and install Netflix plugin
4. Insert Netflix credentials
5. Error "ascii codec can't encode character u'\xea' in position 2: ordinal not in range(128)"

**Expected behavior:** [What you expected to happen]
Login succssefully and see users profile.

**Actual behavior:** [What actually happened]
Error "ascii codec can't encode character u'\xea' in position 2: ordinal not in range(128)"

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional informatin on the environment

Android 7.1.2
Asus Transformer Prime (Tegra 3)
Netflix oficiall app works without issues

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by VincentMarnier** [comment]
Error reproduced for 0.12.0 on OSMC (Linux ARM):
https://pastebin.com/raw/sVyNsvNM

Error wasn't there in 0.11.25

Same steps except I'm using the netflix repo.

**Comment by asciidisco** [comment]
That happens when a special char is part of a profile (üä$? etc.),
I have made a fix here: https://github.com/asciidisco/plugin.video.netflix/pull/191

Until they´re not released, you could try the zip from here: https://github.com/asciidisco/plugin.video.netflix/archive/fix/profile-unicode-failure.zip
