### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by marianorenzi** [asciidisco/plugin.video.netflix#199]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Movie/TV Show fails to reproduce on Kodi 18, showing the following error message: "One or more items failed to play. Check the log for more information about this message."

### Steps to Reproduce

1. Open Netflix Addon
2. Reproduce a Movie or TV Show

**Expected behavior:** Movie or TV Show is played.

**Actual behavior:** Error message is shown.

## Context (Environment)

Raspberry Pi 3 with Kodi 18

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Kodi 18.0-ALPHA1 Git:8afa041
LibreELEC (Milhouse) devel-20171018210302

## Debug log
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1399745/kodi.log)

**Comment by ASHJG** [comment]
I had this issue as well, i upgraded the addon to 0.12.2 and it appears to have fixed it...

**Comment by marianorenzi** [comment]
Updated to 1.22.2 and I am experiencing the same issue. Thanks for the suggestion, though.

**Comment by asciidisco** [comment]
No chance to help without a Debug Log.

**Comment by marianorenzi** [comment]
Updated original report and attached debug log.

**Comment by cy8aer** [comment]
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1402233/kodi.log)

Will that help?

**Comment by IchSkill** [comment]
I have the same issue

**Comment by asciidisco** [comment]
@cy8aer I´d be only able to exactly tell what´s going on if you post a full log. But the lines reported in your error snippet indicate you´re using an old version.

**Comment by cy8aer** [comment]
hm, seems to work again with 0.12.2...

**Comment by asciidisco** [comment]
Version 0.12.3 should fix the issues, please retest & report.
(You may need to clean your addons userdata in order to be able to retain the functionality)

**Comment by IchSkill** [comment]
Fixed, thanks

**Comment by cy8aer** [comment]
works for me too.

**Comment by Perris74** [comment]
sorry for my reply , but i've the same problem. i use kodi 18 and nexflix 0.12.7 . can help me?

**Comment by LtOrangeINC** [comment]
Hello, i have the same issue that @Perris74 describes, i'm using kodi 18 on rpi 3 and i also have the netflix addon version 0.12.7, i tried reverting back to 0.12.3 but i still had the same problem, heres the log file and i am also kinda of new to this linux thing.
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1609878/kodi.log)

**Comment by LtOrangeINC** [comment]
Hello, guys ,i found a solution for the error message, in my kodi log i found out that the libwidevinecdm i was using wasn't the correct version, so after searching on the internet the correct version, i download it and i installed it using this command:

 curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh -o /tmp/getwidevine.sh && sh /tmp/getwidevine.sh .

This fix the message for me .Hope i helped you.
