### ISSUE TITLE
[Subtitles] Movies/Tv shows made by Netflix (AKA Netflix Originals) don't show subtitles.

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#201]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?
0.12.2

### Description

[Description of the bug or feature]
Movies/Tv shows mae by Netflix (AKA Netflix Originals) don't show subtitles.

### Steps to Reproduce

1. [Open Netflix Addon]
2. [Play Some title made by Netflix like Better Call Saul]

**Expected behavior:** [Show subtitles]

**Actual behavior:** [None of subtitles avaliable is showing]

## Context (Environment)
Windows 7 Ultimate x64 With Kodi 18

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
New instalation of windows (3 days old) Full updated Windows via windows update, fresh install of kodi with only a couples metadata addons instaled.

## Debug log

https://pastebin.com/VQzXe5vF

## Other information

Other Movies/Tv Shows not made by NETFLIX show the subtitles normally (see screenshot from Friends (not made By Netflix)

### Screenshots

![screenshot005](https://user-images.githubusercontent.com/16491360/31800765-f6e4b450-b521-11e7-9633-8e5dff2c1a7d.png)
1# Screenshot Froom Better Call Saul (Netflix Originals) on a part that Saul is speaking (without subtitle)

![screenshot006](https://user-images.githubusercontent.com/16491360/31800801-2f368ce8-b522-11e7-8d5e-1af85fc3ad42.png)
2# Screenshot from Friends (Not Netflix Original) with Joey talking (with subtitle)

I'm on Brazil

**Comment by asciidisco** [comment]
Thanks for the report, haven't noticed that as I´m usually not using subtitles. Will have a look soon-ish.

**Comment by joaosagrath** [comment]
It's working again om 0.12.4. Tested with MINDHUNTER, Bettr Call Saul and Marvel's Daredevil. I think it's enough to be certain that it's all good again.I'm closing this, I'll reopen if the issue came back.

Cheers
