### ISSUE TITLE
Kodi restarts when a video is selected to play

### ISSUE THREAD

**Issue by toffis81** [asciidisco/plugin.video.netflix#203]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Kodi restarts whenever I try to play something from Netflix.

### Steps to Reproduce

1. Go into Netflix addon
2. Select movie/TV episode to play
3. Screen goes black and Kodi restarts

**Expected behavior:** Video to play

**Actual behavior:** Kodi restarts

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional information on the environment

I am using Kodi 18 (#1020 20-Oct-2017) running on Raspberry Pi Zero W.

## Debug log

https://paste.ubuntu.com/25788758

## Other information

I have tried downgrading to other versions. The one before the latest version (0.12.3) saw the same behaviour. All the rest would give me a playback error.
NB I'm aware that the addon probably wasn't designed with the Zero W in mind and if that's the case, will withdraw this bug request.

**Comment by asciidisco** [comment]
Where did you get a Widevine version for the RPi 1/Zero?
Need to close this, as simply the hardware isn't powerful enough to software decode/decrypt a video. Even the RPi2 can't barely do it for the lowest SD res.
