### ISSUE TITLE
[Search] Not working, bails out with error

### ISSUE THREAD

**Issue by Durzo198** [asciidisco/plugin.video.netflix#204]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
I'm getting an error when attempting to search.

### Prerequisites

* [x] Are you running the latest version?

**Expected behavior:** To be able to search...

**Actual behavior:** I can't even get to a place to search, I'm hit with an error log notification error.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Using Libreelec latest nightly.

## Debug log

http://sprunge.us/VQPE

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by asciidisco** [comment]
Will look into this.

**Comment by blu3bird** [comment]
This bug was introduces in 0.12.2. Downgrading to 0.12.1 makes search work again.

**Comment by hawkeyexp** [comment]
Bug solved and merged by pr #207
