### ISSUE TITLE
Empty search result from netflix

### ISSUE THREAD

**Issue by hawkeyexp** [asciidisco/plugin.video.netflix#208]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
After fix with pr #207 search is working again. But search result is always empty.

### Prerequisites

* [x] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

`21:42:22.052 T:3792   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.netflix/?action=search_result&term=star+trek
21:42:22.063 T:3792   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?action=search_result&term=star+trek) failed`
## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by asciidisco** [comment]
Already on it, Netflix changed the API, implemented the new one already, but still need to adapt the lists.
Should be able to finish it today.

**Comment by asciidisco** [comment]
Search is up an running, not as beautiful as before, but this will be tackled in the upcoming refactorings

**Comment by hawkeyexp** [comment]
ok perfect - have you noticed my message on kodinerds ?
