### ISSUE TITLE
[Bug report} Error Contents: No module named Cryptodome  

### ISSUE THREAD

**Issue by awesomeness872** [asciidisco/plugin.video.netflix#214]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
OSMC Kodi 18.0 Latest versions Raspberry Pi 3
### Prerequisites
Installed but says unavailable
* [x] Are you running the latest version?

### Description
When trying to launch it says check log for errors and It says 'Error Contents: No module named Cryptodome'

I have gone into an SSH session and use pip to install pycryptodome but it still doesn't work
### Steps to Reproduce
1. Install OSMC on Raspberry Pi 3 (I used NOOBS, not sure if that makes a difference)
2. Update to Kodi 18
3. Follow directions to install addon (except the obvious of installing and updating libreelec)
4. try to launch the addon

**Expected behavior:** [What you expected to happen]
Netflix
**Actual behavior:** [What actually happened]
Not Netflix
## Context (Environment)
OSMC Kodi 18.0 Raspberry Pi 3
### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

## Debug log

https://pastebin.com/CxYcjXb5

**Comment by zapinator3000** [comment]
Getting same error on Ubuntu 64 bit

**Comment by asciidisco** [comment]
This is not a plugin Problem, it´s a problem related to the Distro you are using.
For OSMC, @matejmosko was so kind to write something up: https://discourse.osmc.tv/t/how-to-use-netflix-on-osmc-rpi2/11478/18

For Ubuntu, have a look at this thread here: https://github.com/asciidisco/plugin.video.netflix/issues/30
