### ISSUE TITLE
playback: black screen, audio playing alright

### ISSUE THREAD

**Issue by svage** [asciidisco/plugin.video.netflix#220]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ x] Are you running the latest version? 0.12.7

### Description

First time Netflix Addon user!!!

(Pi 3) When playing any video with this addon, the screen stays black, only audio is playing alright. This applies to movies and series. Selecting different stream qualities did not do any good.
I don't have issues with the Amazon Prime plugin, so i'd rule out any problems with widevine, imho.

### Steps to Reproduce

1. play any video from netflix
2. black screen, audio playing

**Expected behavior:** video and audio

**Actual behavior:** only audio

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x ] Linux (ARM) (Pi 3)
* [ ] Android

#### Additional informatin on the environment

Pi 3.
I'm running the next to latest LibreElec Testbuild from Milhouse: #1026
Everything is set up correctly for weeks now with Amazon Prime plugin. Started yesterday with the Netflix plugin.

## Debug log

This happens right after starting playback until i stop it.
http://sprunge.us/UVgG

## Other information

First time Netflix Addon user. I cannot give any other information than this, sorry. Reporting anyway, because all other streaming addons work fine.

**Comment by pinoelefante** [comment]
Have you disabled MMAL and enabled OMX hardware acceleration? if yes, try disabling OMX and enabling MMAL (raspberry default). Otherwise, wait for asciidisco :)

**Comment by svage** [comment]
@pinoelefante , tried every combination to no avail. Thanks anyway!

**Comment by svage** [comment]
I got it working! It had nothing to do with this addon: my AV receiver decided to stop playing 5.1 sound. After installing the latest firmware, everything is alright!
Apollogies!

**Comment by asciidisco** [comment]
@svage No worries. Glad it works now. At least it pressured me enough to update my PI test installation here, which I was planning to do for weeks now...

**Comment by pinoelefante** [comment]
@svage All's well that ends well
