### ISSUE TITLE
Can't browse season folders anymore

### ISSUE THREAD

**Issue by walinsky** [asciidisco/plugin.video.netflix#221]
*I'm submitting a ...*
  - [*] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Season folders seem to be broken. Can still see 'Season 1', 'Season 2', ... folders; but opening them throws an error.

### Prerequisites

 [*] Are you running the latest version?
Found on 0.12.6; can reproduce on 0.12.5

### Description
Opening a Title throws error:
`13:31:26.811 T:140160447330048 WARNING: Invalid media type ""
`
Opening a season folder throws:
`
13:31:49.246 T:140160333301504 WARNING: Previous line repeats 42 times.
13:31:49.246 T:140160333301504   ERROR: Traceback (most recent call last):
13:31:49.246 T:140160333301504   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
13:31:49.246 T:140160333301504   ERROR:     self.process_request(request, client_address)
13:31:49.246 T:140160333301504   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
13:31:49.246 T:140160333301504   ERROR:     self.finish_request(request, client_address)
13:31:49.246 T:140160333301504   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
13:31:49.246 T:140160333301504   ERROR:     self.RequestHandlerClass(request, client_address, self)
13:31:49.246 T:140160333301504   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
13:31:49.246 T:140160333301504   ERROR:     self.handle()
13:31:49.246 T:140160333301504   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
13:31:49.246 T:140160333301504   ERROR:     self.handle_one_request()
13:31:49.246 T:140160333301504   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
13:31:49.246 T:140160333301504   ERROR:     method()
13:31:49.246 T:140160333301504   ERROR:   File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpRequestHandler.py", line 60, in do_GET
13:31:49.246 T:140160333301504   ERROR:     result = getattr(RES_HANDLER, method)(params)
13:31:49.246 T:140160333301504   ERROR:   File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 215, in fetch_episodes_by_season
13:31:49.246 T:140160333301504   ERROR:     response_data=raw_episode_list)
13:31:49.246 T:140160333301504   ERROR:   File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 1242, in parse_episodes_by_season
13:31:49.247 T:140160333301504   ERROR:     genres=response_data.get('value', {}).get('genres'))
13:31:49.247 T:140160333301504   ERROR:   File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 1301, in parse_episode
13:31:49.247 T:140160333301504   ERROR:     'plot': episode['info']['synopsis'],
13:31:49.247 T:140160333301504   ERROR: KeyError: 'info'
13:31:49.248 T:140160447330048   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'httplib.BadStatusLine'>
                                            Error Contents: ''
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/addon.py", line 42, in <module>
                                                NAVIGATION.router(paramstring=REQUEST_PARAMS)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 45, in wrapped
                                                result = func(*args, **kwargs)
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 140, in router
                                                tvshowtitle=params.get('tvshowtitle'))
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 342, in show_episode_list
                                                'cache': True}))
                                              File "/home/kodi/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 883, in call_netflix_service
                                                data = urllib2.urlopen(full_url).read(opener)
                                              File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
                                                return opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 429, in open
                                                response = self._open(req, data)
                                              File "/usr/lib/python2.7/urllib2.py", line 447, in _open
                                                '_open', req)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
                                                return self.do_open(httplib.HTTPConnection, req)
                                              File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
                                                r = h.getresponse(buffering=True)
                                              File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
                                                response.begin()
                                              File "/usr/lib/python2.7/httplib.py", line 453, in begin
                                                version, status, reason = self._read_status()
                                              File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
                                                raise BadStatusLine(line)
                                            BadStatusLine: ''
                                            -->End of Python script error report<--
13:31:49.267 T:140163585194304   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?action=episode_list&season_id=80025272&tvshowtitle=TmFyY29z
13:31:49.267 T:140163585194304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?action=episode_list&season_id=80025272&tvshowtitle=TmFyY29z) failed
`

**Comment by asciidisco** [comment]
Already fixed in latest version 0.12.7

**Comment by walinsky** [comment]
I just noticed that on the master branch; 0.12.7 doesn't show up in the Addon as an update however.

**Comment by asciidisco** [comment]
Maybe you need to refresh the Repo itself. Kodi 18 sometimes has this problem (it’s still pre-alpha)

**Comment by walinsky** [comment]
Working now. Thanks!
