### ISSUE TITLE
[Core] Plugin stopped working after update

### ISSUE THREAD

**Issue by Dis90** [asciidisco/plugin.video.netflix#223]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Updated to latest version and plugin stopped working. If I don't remember wrong plugin version before updating was 0.11.24.

### Prerequisites

* [x] Are you running the latest version?

### Description

When I try to start plugin it shows "Netflix error"

### Steps to Reproduce

1. Enter credentials
2. Start plugin

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

https://pastebin.com/7zmw7dzK

## Other information

I removed all files from "addon_data/plugin.video.netflix" and re-entered my credentials and still not working.

**Comment by rogercorrea** [comment]
I have installed in a day ago and worked for me.
You can verify if your system date and Netflix login is right.

I'm use ARM version with the Raspberry Pi 3.

**Comment by Dis90** [comment]
Tested this little bit more and version 0.12.1 is last version which works for me.

**Comment by asciidisco** [comment]
@Dis90 Is this still an issue? Did you gave version 0.12.7 another try, deleting everything (including your settings) & installing from scratch?

**Comment by Dis90** [comment]
Yes this is still issue when using latest version. I deleted folders addon_data/plugin.video.netflix and addons/plugin.video.netflix and installed latest version 0.12.7 from repo.

Debug log: https://pastebin.com/HDeAh425

**Comment by caphm** [comment]
Closing because of age and inactivity. Feel free to reopen if the issue still persist (several releases later)...
