### ISSUE TITLE
Error when opening Netflix

### ISSUE THREAD

**Issue by tonyschuite** [asciidisco/plugin.video.netflix#230]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?
Yes 0.12.7

### Description

addon seems broken

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Libreelec millhouse nightly

## Debug log

20:46:36.465 T:140268224399104   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named urllib3
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/addon.py", line 11, in <module>
                                                from resources.lib.KodiHelper import KodiHelper
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 21, in <module>
                                                from resources.lib.MSL import MSL
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 25, in <module>
                                                import requests
                                              File "/storage/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 43, in <module>
                                                import urllib3
                                            ImportError: No module named urllib3
                                            -->End of Python script error report<--
20:46:36.492 T:140269684732480   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?Return
20:46:36.493 T:140269684732480   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?Return) failed

**Comment by tonyschuite** [comment]
sorry for the paste, seemed faster.

**Comment by tonyschuite** [comment]
crap... close this... fixed by reinstall

**Comment by pinoelefante** [comment]
This is caused by some modules update of kodi. Restart it and all works again

**Comment by manayak** [comment]
Uninstall the netflix addon, reinstall and reboot .... all works
