### ISSUE TITLE
Netflix german stream

### ISSUE THREAD

**Issue by Keniir** [asciidisco/plugin.video.netflix#232]
So I installed the latest libreelec release with the update from milhouse on my raspberry pi 2 and installed everything important. I installed the netflix addon from the zip file. Everything works fine and the titles and descriptions are in german but not the stream itself. Is there any way to change this?

**Comment by DeProf90** [comment]
This is already possible. Just choose your language under audio and subtitle settings the streams are all there. If it is availlable in German you can select it under audiostream.

**Comment by Keniir** [comment]
Where exactly do I find these settings?

**Comment by Keniir** [comment]
Okay i found it, thank you :)
