### ISSUE TITLE
[Bug Report] Not able to see if episode/movie has been watched

### ISSUE THREAD

**Issue by awesomeness872** [asciidisco/plugin.video.netflix#236]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
OSMC on Raspberry Pi 3
### Prerequisites

* [x] Are you running the latest version?

### Description
I was looking through the code in the NetflixSession.py and KodiHelper.py files and it seems to be get information on if an episode has been watched and at what you are in in the episode/movie, but in using the plugin I'm noticing none of this functionality

### Steps to Reproduce

1. Look at episode watch status

**Expected behavior:** [What you expected to happen]
The episode/movie shows up as watched or where I am in watching if I have watched it on Netflix outside of Kodi
**Actual behavior:** [What actually happened]
The episode/movie doesn't show up as watched or show where I am in it
## Context (Environment)
OSMC Raspberry Pi 3
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

**Comment by raven6679** [comment]
Same on PC. There is no sign, which ones are already viewed, which one are in progress, etc.

**Comment by Wheemer** [comment]
Yes I see this also, kodi knows if it is watched or not based on what option it shows in the context menu. But nothing is displayed in the interface.

**Comment by helioshk** [comment]
Same on Linux/x64.

**Comment by rezizter** [comment]
Same on libreelec

**Comment by asciidisco** [comment]
Known issue. I´ll see what can be done about it.

**Comment by caphm** [comment]
I have created a PR that should resolve this.
