### ISSUE TITLE
[ESN] Playback is not working

### ISSUE THREAD

**Issue by ikarusnc** [asciidisco/plugin.video.netflix#238]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description
Playback is not working, player show just noise and glitchy ui (screenshots below). Plugin version is latest from repo, kodi version is latest alpha arm64. 
![screenshot_20171121-013312](https://user-images.githubusercontent.com/6529699/33049430-5cc7b694-ce60-11e7-95f3-12bbf168c5be.png)
![screenshot_20171121-020335](https://user-images.githubusercontent.com/6529699/33049431-5ce8f728-ce60-11e7-9067-c079b12d452c.png)
![screenshot_20171121-020421](https://user-images.githubusercontent.com/6529699/33049432-5d06f3ea-ce60-11e7-8ac3-938cc966a5fc.png)

[Description of the bug or feature]

[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/1489663/kodi.log)

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [X] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by asciidisco** [comment]
Have you tried to add the ESN that is displayed within the Netflix settings to the Kodi Plugin Config, then restarted Kodi & tried again?

ESN calculation is somewhat glitchy still.

**Comment by asciidisco** [comment]
Closing this in favour of: https://github.com/asciidisco/plugin.video.netflix/issues/155
