### ISSUE TITLE
[Playback] Video suddenly stops

### ISSUE THREAD

**Issue by Amelsfort** [asciidisco/plugin.video.netflix#239]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Running the latest Kodi 18 nightly 64 bit.

### Prerequisites

* [ ] Are you running the latest version?
Yes

### Description
Since a little while I have issues playing the whole movie/episode. For a while (about 45 minutes) everything is fine. Then suddenly the video hangs, but audio plays fine. I tried pausing, stopping and rewinding, but the same thing happens at the same moment. I have seen this with several videos now. Most recently with the episodes of The 100 - Season 2.

### Steps to Reproduce

1. Play a video from Netflix
2. Try to watch in to the end

**Expected behavior:** [What you expected to happen]
I would expect the video to play to the end.

**Actual behavior:** [What actually happened]
The video stops. Audio and susbtitles are playing fine. 

## Context (Environment)
Windows 10 64 bit

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by asciidisco** [comment]
Could you please add a link to a debug log? Otherwise it´s not possible to track down what´s happening.

**Comment by Amelsfort** [comment]
I still haven't managed to get a debug log because it has been working fine for a while now. Unfortunately, today this issue occured again. I checked the Kodi log file (no debug log) and noticed a http error 416. It looks like the plugin is trying to request part of the stream (for buffering?), but the requested bytes don't exist in the stream.
It only seems to happen on longer episodes (1h+).

**Comment by caphm** [comment]
It's an inputstream.adaptive issue then.
