### ISSUE TITLE
Jerky playback

### ISSUE THREAD

**Issue by extremeaudio** [asciidisco/plugin.video.netflix#243]
I'm submitting a ...support request

I'm running the latest version of the addon

Description

I have an Amlogic 912 box running a Libreelec Leia build. I first tried with settings of inputstream set to max resolution but there was jerky playback. Now I have set everything to 720 and HEVC to off but yet the video is not smooth. 

I´m using the Netflix Repo

Linux (ARM)

Debug Log - https://paste.ee/p/VkVHU

**Comment by Uukrull** [comment]
This has nothing to do with the plugin itself. I have an Amlogic 905X box and also the playback is jerky at 720p with the max bandwidth set to 4000000. So, if your box has Widevine L1 support, use Kodi on Android to get smooth 1080p playback like mine does.

**Comment by asciidisco** [comment]
Exactly what @Uukrull said.
Closing.
