### ISSUE TITLE
[Bug Report] A thin green line appears at the bottom of the screen during playback

### ISSUE THREAD

**Issue by TheSquirrelMan** [asciidisco/plugin.video.netflix#245]
*I'm submitting a ...*
- [x] bug report

### Prerequisites

- [x] Are you running the latest version?

### Description
  - [Once HD playback is paused then resumed a thin green line appears at the bottom of the screen.]

### Steps to Reproduce

1. [Set input stream addon settings to 720p or above.]
2. [Play any HD video then pause it.]
3. [Resume the video and the green line appears at the bottom.]

**Expected behavior:** [After resuming a video no green line appearing.]

**Actual behavior:** [After resuming videos a green line always appears.]

### Installation

* [x] I´m using the Netflix Repo

### Operating System

* [x] Windows (x86/x64)

#### Additional information on the environment

[Windows 10 64 bit, using Kodi leia nightly 64 or 32bit, core i5, 16gb ram, gtx 1080 video, samsung 55" ks8000 tv]

## Debug log

https://gist.github.com/TheSquirrelMan/e85e14b3fc88810c97d6585ffd463dab

## Other information

[This only happens when playing HD video, if I set the input stream addon settings to cap at 480p its perfect. I tried using both 32 and 64 bit Kodi and Widevine.  Both produce the same green line.  No other video file or video streaming add on has ever done this before so I am not sure.

In the 32 bit version of Kodi and Widevine all it takes is simply moving the mouse to show the video OSD controls/menu during playback to cause the green line to appear.  In the 64 bit version the same green line appears only delayed maybe a minute or so after the OSD disappears.

*Update* It also happens if I toggle fullscreen view and go from window to fullscreen or back. It also happens if I skip forward or backwards in the video.

I thought maybe it could be resolution related.  I switched from my default 3840 x 2160 to various other resolutions and all produced the same green line during playback.  

In any case it is easy enough to stop playback then resume to get rid of the line.  If I do not pause and skip around it works wonderfully and I am grateful for all the hard work that went into this add on.]

### Screenshots
![untitled](https://user-images.githubusercontent.com/34028985/33277369-5a7aaca6-d366-11e7-8f06-44c979edbfc3.png)

**Comment by TheSquirrelMan** [comment]
It looks like its a problem with the Render Method I was using.  In video settings the default render method  was set to auto select.  Once I chose DXVA and enabled hardware acceleration, the green bar is gone on HD videos I can pause, replay, skip, its amazing.

**Comment by asciidisco** [comment]
Thanks for getting back with the root cause & explanation how to solve it 👍
