### ISSUE TITLE
Frame and sound stuck after buffering

### ISSUE THREAD

**Issue by Jip-Hop** [asciidisco/plugin.video.netflix#247]
*I'm submitting a ...*
  - [ x ] bug report
  - [ ] feature request
  - [ ] support request

## General information
Stream hangs after buffering (sometimes)

### Prerequisites
Raspberry Pi 3 with plugin.video.netflix for Kodi 18

* [ ] Are you running the latest version?
yes
### Description

[Description of the bug or feature]
Sometimes the video will hang after buffering. The progress bar continues (time elapsing) but the video frame is stuck, as well as the audio.

### Steps to Reproduce

Watch a movie on Netflix, wait until it has to buffer at some point, see it getting stuck.

**Expected behavior:** [What you expected to happen]
Movie should continue to play.

**Actual behavior:** [What actually happened]
The progress bar continues (time elapsing) but the video frame is stuck, as well as the audio.

## Context (Environment)
Kodi Nightly build #1130, 30-Nov-2017 from here: https://forum.kodi.tv/showthread.php?tid=298461

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec, connected via WiFi

## Debug log

https://www.dropbox.com/s/g1kxt392cf2c03f/log-2017-12-01-09.59.52.zip?dl=0

**Comment by pinoelefante** [comment]
The only error i can find related to netflix is this: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)

Just follow this guide: [Installation](https://github.com/asciidisco/plugin.video.netflix/wiki/Installation)

**Comment by Jip-Hop** [comment]
Well spotted. That error is from before I installed widevine.

I installed widevine like this:

Ssh in to libreelec and paste the following: curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh -o /tmp/getwidevine.sh && sh /tmp/getwidevine.sh

Without it Netflix won't be able to stream video at all. My issue is that it streams fine, until it needs to buffer again. Happened several times. Sometimes after a few minutes, sometimes 15 minutes, sometimes it also continues playing like it should but I haven't been able to complete a movie without this happening.

**Comment by asciidisco** [comment]
@Jip-Hop Can you please link to a debug log that shows the behaviour, otherwise it´s not possible to help.

**Comment by Jip-Hop** [comment]
The log I linked to is the log that should show the behavior. Can't help the fact that it didn't log the issue. I'm not using the Plugin any more so can't test again.

**Comment by paulvanliedekerke** [comment]
I am having exactly the same problem here on RPI3. Seems not to depend on resolution. 
Anyone else ? Should one try another build ?

**Comment by JohnSmithDoe** [comment]
Me too. Same thing on RPI3. (Milhouse Update Branch). Is there a solution to this? Its so sad because it streams for a while and then it freezes and it wont start again after that (till restart of Kodi).
