### ISSUE TITLE
Unable to Configure in Aeon Nox 5 Skin

### ISSUE THREAD

**Issue by aaronc1976** [asciidisco/plugin.video.netflix#248]
I love this add-on but was wondering if there was a way to configure in Aeon Nox 5.  Currently in order to adjust any settings I have to switch to Estuary skin to make any configuration changes.  I want to be able to change the viewmode in Aeon Nox 5 so that I a can get plot iinfortmation. I am trying to set the viewmode to tripanel.  I enabled custom views and changed the viewmode id within the add-on settings but nothing happens.  I also tried editing the MyVideoNav.xml in my skin folder without success.

This is running on Windows 10 64bit OS and I am running Kodi 18 alpha.

Any help wold be greatly appreciated.

**Comment by Wheemer** [comment]
Sounds like t's a incompatibility between aeon nox and kodi 18... I use Estuary mod and the settings look fine.

**Comment by asciidisco** [comment]
I´m pretty sure this is not a plugin issue, more like a skin incompat.
Can you access the configuration of other plugins?
