### ISSUE TITLE
LibreELEC 9.x - script.module.pycryptodome not available

### ISSUE THREAD

**Issue by alexhass** [asciidisco/plugin.video.netflix#252]
There is no pycryptodome available, nor can I manage to install in any way. pip is not available... where can I get this dependency from for Generic builds?

**Comment by MilhouseVH** [comment]
It is installed, you are not correct. I've replied in all your posts on this subject - please continue the discusson on the [forum](https://forum.libreelec.tv/thread/10921-le-9-0-script-module-pycryptodome-missing/?postID=72673#post72673).
