### ISSUE TITLE
Installing on Kodi 18 Win 7

### ISSUE THREAD

**Issue by SquigglyDog** [asciidisco/plugin.video.netflix#253]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X ] support request

## General infomration
Win 7, Kodi 18 nightly Dec92017

### Prerequisites

* [YES ] Are you running the latest version?

### Description
"Note: The link to download the Widevine Libary for none ARM Systems can be found in the Firefox Sources & needs to be placed in the cdm folder in special://home. "
I am having problems installing this on Win 7 Kodi 18. I am not clear how to pick the appropriate Windows file from the json file you linked. Also I have no idea where this file goes

### Steps to Reproduce

1. [First Step] I have the addon installed
2. [Second Step]I am able to search Netflix videos but no playback
3. [and so on...]

**Expected behavior:** Expect to be able to play Netflix

**Actual behavior:** [Error message one or more items failed to play check log

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X ] Windows (x86/x64)WIN 7
* [ ] Linux (ARM)
* [ ] Android

**Comment by SquigglyDog** [comment]
I am asking for clear instructions for Windows install of plugin  ....Thanks

**Comment by SquigglyDog** [comment]
Do I install the zip file at https://redirector.gvt1.com/edgedl/widevine-cdm/970-win-x64.zip
and place it in CDM in %APPDATA%\kodi\userdata?

**Comment by SquigglyDog** [comment]
That worked a treat. Thanks so much for providing the addon

**Comment by asciidisco** [comment]
With one of the next versions, there will be an automatic downloader integrated as a 3rd party dependency. Glad you were able to solve it on your own.
