### ISSUE TITLE
Low quality playback (and low network usage)

### ISSUE THREAD

**Issue by delleceste** [asciidisco/plugin.video.netflix#255]
*I'm submitting a ...*
  - [x ] bug report
  - [] feature request
  - [ ] support request

## General infomration
Netflix plugin on Linux / KODI 18 plays movies at an extremely low resolution.

### Prerequisites

* [ x] Are you running the latest version?
Yes
### Description

[Description of the bug or feature]

Netflix plugin on Linux / KODI 18 plays movies at an extremely low resolution.
The same content watched on Chrome plays fine. In this case, using a network traffic
measurement tool, I can see bursts up to 50Mbit/s when buffering. On the other hand,
Netflix KODI plugin uses a very limited bandwidth (less than 1Mb/s) during playback.
Video is very low quality and many times stops or stutters.

The tests have been performed on the same Linux machine, so in the same network 
conditions.

### Steps to Reproduce

1. [Start plugin]
2. [Search a movie]
3. [Play a movie]

**Expected behavior:** [Watch movies in full HD]

**Actual behavior:** [Watching movies at an extremely low quality / stuttering]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Arch linux/ KODI 18 alpha from xbmc git

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by ulysse31** [comment]
Similar setup here and same results : 
- Gentoo x86_64
- build kodi-9999 ebuild (gitub source leia 18-ALPHA)
- Installed latest inputstream-adaptive and inputstream-rtmp
- Installed latest Netflix plugin (from here ...)

Result:
- can access to netflix content
- can launch a content
- content starts, plays for about 20 secs, then have : 

19:04:37.725 T:139719006430976  NOTICE: CVideoPlayerAudio::Process - stream stalled
19:04:39.288 T:139719031609088 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer

- player starts buffering, once buffer completed (about 30/50 seconds), content playing starts again, for about 20 secs ... then it starts stuttering (video and sound) and the following messages appears on kodi.log file : 

19:05:19.757 T:139721716975360 WARNING: ActiveAE - large audio sync error: -2181.172845
19:05:19.790 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.860752
19:05:19.790 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.859552
19:05:19.790 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.859573
19:05:19.790 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.859571
19:05:19.885 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.857657
19:05:20.037 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.852538
19:05:20.038 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.852402
19:05:20.038 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.852153
19:05:20.038 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.852113
19:05:20.099 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.851988
19:05:20.131 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.851284
19:05:20.194 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.846507
19:05:20.257 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.843712
19:05:20.289 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.843654
19:05:20.352 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.837687
19:05:20.384 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.836745
19:05:20.447 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.830933
19:05:20.479 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.830125
19:05:20.543 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1849.826972
19:05:20.606 T:139721716975360 WARNING: ActiveAE - large audio sync error: -1850.823721
[...]

- then, a few seconds after, no more sound at all, and video still stuttering ...

**Comment by Sjaakafhaak** [comment]
I got the same issue.

Playback is in 512x384px , 1.78 AR, 24.000FPS
Pi2 CPU is doing around 25% work.

I have a 500mbit fibre with directly wired pi
My setup is LibreElec Millhouse and i installed

curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh \| bash

to get video in the first place.

Hope that someone know's whats wrong.

Thanks in advance

**Comment by nicolascarrara** [comment]
I had the same problem, in InputStream addon settings i change the Min Bandwith to 2500 ,I also change the value of playback settings in netflix accounts settings to high and now the quality is much better, hope it can help.

**Comment by asciidisco** [comment]
I´m closing this as it seems not related to the plugin itself, but more to Inputstream & its configuration
