### ISSUE TITLE
Unable to instal plugin from repo (inputstream.adaptive unavaliable)

### ISSUE THREAD

**Issue by michal-grega** [asciidisco/plugin.video.netflix#256]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Unable to install plugin from the repo due to unresolved dependencies (inputstream.adaptive unavaliable)
### Prerequisites

* [X] Are you running the latest version?
Yes, Nightly build of Kodi 18 x64 dated 13th December. 

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Fresh install of Kodi 18
2. Install repo from zip https://github.com/kodinerds/repo/raw/master/repository.netflix/repository.netflix-1.0.1.zip
3. Install plugin from repo

(same happens when installing from release zip)

**Expected behavior:** [What you expected to happen]
Plugin installs

**Actual behavior:** [What actually happened]
Plugin fails to install (inputstream.adaptive unavaliable)

### Installation

* [X] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x64 - tested 10 and 7)
* [ ] Linux (ARM)
* [ ] Android

**Comment by Norien** [comment]
Did you enable inputstream.adaptive in Kodi settings first?

**Comment by michal-grega** [comment]
Feel stupid right now. 
However it may be usefull for someone. 

I have upgraded over an old Kodi installation and the installer seems to follow the old installation type. You need to make sure that you coose Insputstream Adaptibe to be installed (or select "full"). Otherwise inputsream adaptive will not be  avaliable in "my addons" menu. 

May be marked as resolved
![inputstreamadaptiveinstall](https://user-images.githubusercontent.com/29427896/33963974-29fca5c2-e057-11e7-949e-e80405bb7156.PNG)

**Comment by SaulFemm** [comment]
I'm having the same problem even though I definitely enabled inputstream.adaptive in the Kodi setup.

**Comment by Wheemer** [comment]
It's probably just disabled... find it and enable it.

**Comment by SaulFemm** [comment]
Ah, I didn't realize it had to be enabled in settings. Here's an article detailing how to enable it for newbies such as myself.

http://www.ares-project-blog.com/kodi-add-on-reviews/enable-inputstream-adaptive-kodi-krypton/

**Comment by asciidisco** [comment]
Kodi should enable it by default, I guess that needs to be ironed out before Kodi 18 gets Beta.

**Comment by Pysis868** [comment]
That link is gone, but this one with pictures confirms I still don't have the addon with the Mac installation.  All I did was drag the app over, so not an installer option like those Windows users had.

https://www.tvaddons.co/rtmp-streams-krypton/
I just see Video add-ons and then Web Interface.

Don't see it under addons either:
```
~ find '/Applications/Kodi.app/Contents/Resources/Kodi' -iname '*input*'
/Applications/Kodi.app/Contents/Resources/Kodi/addons/kodi.binary.instance.inputstream
/Applications/Kodi.app/Contents/Resources/Kodi/addons/peripheral.joystick/resources/buttonmaps/xml/directinput
/Applications/Kodi.app/Contents/Resources/Kodi/addons/peripheral.joystick/resources/buttonmaps/xml/xinput
```

#### Aside
I have enabled it on my RetroPi with the beta channel, I think that's at beta 4 right now, but the Netflix proxy isn't running there, so I can't activate the login process in the add-on.  I think Cryptodome was still missing I saw in the logs further up?

For my Mac, I did find that library at `/Applications/Kodi.app/Contents/Libraries/lib/python2.7/site-packages/Cryptodome` and then `/Applications/Kodi.app/Contents/Resources/Kodi/addons/script.module.pycryptodome`.

`https://github.com/eirki/script.module.pycryptodome` doesn't exist anymore =/.

Kodi 18.0-RC1 Git:20181103-4dda45ca29
OS X 10.12.6

**Comment by caphm** [comment]
Since a couple of days Kodi doenst come with some addons preinstalled anymore. You need to install them separately.

**Comment by Pysis868** [comment]
I have the other problem fixed from these series of posts:

https://github.com/asciidisco/plugin.video.netflix/issues/426#issuecomment-405034280
`sudo python2.7 /usr/bin/pip install pycryptodomex` (My system had pythons 2.7, 3.5, and 3 =/)

https://github.com/asciidisco/plugin.video.netflix/issues/307#issuecomment-418289135
Works when using this 'background' method, but Kodi is still missing the proper script package addon.

Example:
```
pi@retropie ~> find  ~/.kodi/ /usr/lib/python*/ -type d -iname '*crypto*'
/usr/lib/python2.7/dist-packages/cryptography
/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/commoncrypto
/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/commoncrypto
/usr/lib/python2.7/dist-packages/cryptography-1.7.1.egg-info
/usr/lib/python2.7/dist-packages/Crypto
/usr/lib/python2.7/dist-packages/pycryptopp-0.7.1.egg-info
/usr/lib/python2.7/dist-packages/pycryptopp
```

Some of those entries are some packages I thought would help along the way just ot try, but they didn't work, like `pycryptopp`.

So that's nice, and I think I saw in the most recent release, at least in the Mac version, that `script.module.pycryptodome` is included with the application.

Hopefully that is true, if that could be confirmed, and then maybe the Widevine depdency could be added to the rest to be installed together that way?
