### ISSUE TITLE
AutoPlay

### ISSUE THREAD

**Issue by iptvcld** [asciidisco/plugin.video.netflix#259]
*I'm submitting a ...*
  - [ ] bug report
  - [ X] feature request
  - [ ] support request

I have installed Kodi 18 with this Netflix addon but can not locate the autoplay option when a episode is finished in a series. 

### Prerequisites

* [ ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by iptvcld** [comment]
This is on a Android Buzz Box

**Comment by hawkeyexp** [comment]
The Option is not included yet - you can use nextup service notification if your tvshow for example is exported.
