### ISSUE TITLE
Cannot enable or set default subtitles

### ISSUE THREAD

**Issue by jvdurme** [asciidisco/plugin.video.netflix#262]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

Yes, downloaded on Dec 29th 2017.

### Description

While I am able to enable the subtitles and to select dutch as a language while I'm viewing a video, it seems to be impossible to make these choices default for other media.
When I go to the in-view Settings and select "Audio and subtitle settings" and in that menu select "Set as default for all media", it just doesn't stick.
When loading a new video or resuming the same video, subs are disabled again.

Glad to see a solution. And thanks for this amazing plugin!

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] LibreElec  
* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

LibreElec 9.0 Milhouse on RPI3

**Comment by asciidisco** [comment]
This is rather a Kodi or Inputstream issue as the Plugin doesn't tinker or have access to the sub control of the Kodi player.
