### ISSUE TITLE
Playback failed "One or more items failed to play. Check the log for more information about this message"

### ISSUE THREAD

**Issue by matteozambon89** [asciidisco/plugin.video.netflix#263]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Receiving **One or more items failed to play. Check the log for more information about this message** instead of playing the movie.

### Steps to Reproduce

1. After installing both latest version of LibreElec (alpha), Netflix Plugin and installed **wedevine**
2. Login into Netflix account
3. Choose a movie and play it

**Expected behavior:** It should play the movie

**Actual behavior:** It fails showing **One or more items failed to play. ...**

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

- RaspberryPi 1
- 4Mbps internet speed
- Wired network

## Debug log

```
23:03:08.011 T:1483731856   ERROR: CCurlFile::FillBuffer - Failed: Timeout was reached(28)
23:03:08.013 T:1483731856   ERROR: CCurlFile::Open failed with code 0 for http://localhost:50677/manifest?id=80011806|acceptencoding=gzip&seekable=0&user-agent=Mozilla%2f5.0%20(X11%3b%20CrOS%20armv7l%207$
23:03:08.019 T:1483731856   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:50677/manifest?id=80011806
23:03:08.026 T:1483731856   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:50677/manifest?id=80011806)
23:03:08.087 T:1483731856   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:50677/manifest?id=80011806]
23:03:08.102 T:1483731856  NOTICE: CVideoPlayer::OnExit()
23:03:08.185 T:1942511632  NOTICE: m_playbackStarting
```

**Comment by matteozambon89** [comment]
The plugin is also slow on responding at each click

**Comment by hawkeyexp** [comment]
RPi1 is not supported cause CPU is only single core and widevine is not available for this architecture - RPi2 is possible (slow and only lower res) but RPi3 is recommended.

**Comment by RenaKunisaki** [comment]
I'm having the same problem on Pi 3.
