### ISSUE TITLE
can't see greek subs

### ISSUE THREAD

**Issue by gergeo86** [asciidisco/plugin.video.netflix#264]
*I'm submitting a ...*
  - [ }bug report

### Prerequisites

* [x] Are you running the latest version?kodi 18 x86

### Description

[Description of the bug or feature] only english and turkish subs.not greek.i have greek account

### Installation

* [x] I´m using the Netflix Repo

### Operating System

* [x] Windows (/x64)

[You can erase any parts of this template not applicable to your Issue.]

**Comment by asciidisco** [comment]
Duplicate of https://github.com/asciidisco/plugin.video.netflix/issues/95
