### ISSUE TITLE
No Playback

### ISSUE THREAD

**Issue by goake** [asciidisco/plugin.video.netflix#265]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Everything works, apart from I cant play back anything

### Prerequisites

* [x ] Are you running the latest version?

### Description
Attempting to play something:

Prompted with the message box:
_Playback failed
One or more items failed to play. Check the log for more information about this message._

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Ubuntu 16.04.3 LTS
Kodi 18.0-ALPHA1 Git:20180101-dc587bd

## Debug log

https://pastebin.com/DHQkr34p

## Other information
I think the important part of the log is:

ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library

But, widevine has all been installed correctly as far as I know, and libwidevinecdm.so copied to the right place. Annoying thing is that everything worked yesterday, but did a fresh install this morning - I believe I did the exact same thing as yesterday, but now doesn't work.

**Comment by goake** [comment]
I really dont get this...

I installed chrome, cleared the cdm directory, and copied libwidevinecdm.so back in, and now everything works.

**Comment by hawkeyexp** [comment]
solved
