### ISSUE TITLE
Request: Remember Audio/Sub preference per profile or grab ir from netflix 

### ISSUE THREAD

**Issue by dudumaroja** [asciidisco/plugin.video.netflix#266]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

This addon is amazing and made my HTPC almost the perfect media center, but one thing is missing, a way to set or grab from netflix language settings for audio and subtitle..

Im from brazil, i mainly watch content subbed, and my Wife Dubed ( yeah Sub vs. Dub war everyday ) but everytime we want to watch something, i had to change the sub or audio channel everytime

is there a way to use the preference set in netflix? l

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]
remember audio/subtitles per profile or respect the profile preference from netflix

**Actual behavior:** [What actually happened]
Video plays with original audio no subs everytime

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Libreelec milhouse build kodi Leia

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by asciidisco** [comment]
You can't set the preferences in the plugin, there´s no way we could make this work.
I believe that the suggestion I made here: https://github.com/asciidisco/plugin.video.netflix/issues/271#issuecomment-359811439
also could apply to your problem.
