### ISSUE TITLE
[ESN] Black screen on android device with RK3328

### ISSUE THREAD

**Issue by BrownEmmett** [asciidisco/plugin.video.netflix#270]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

**I have a android box with cpu: RK3328 / 2GB RAM - and when try play any title from plugin - video start but in background so there is no video (only black screen), I can go to fullscreen but the screen is black. Any ideas why?** 

### Prerequisites

* [x] Are you running the latest version?
Plugin ver 0.12.7

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

**Comment by nicolascarrara** [comment]
Can you post a debug log ?

**Comment by asciidisco** [comment]
Probably a problem with a miscalcuated ESN, can you please post a proper debug log?

**Comment by asciidisco** [comment]
Closing this in favour of: https://github.com/asciidisco/plugin.video.netflix/issues/155
