### ISSUE TITLE
OSX - UI works but no video played

### ISSUE THREAD

**Issue by mysiar** [asciidisco/plugin.video.netflix#273]
Can't get any video to play. Getting error:
```
Playback failed.
One or more items failed to play. 
...
```
### Steps to Reproduce

try to play any movie or tv series episode 

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [x] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log
https://pastebin.com/Zsa3UHRF

**Comment by nicolascarrara** [comment]
Hi,
Look like you dont have Libwidevine librarie,
Did you install it correctly like it’s explained in thé wiki ? 
https://github.com/asciidisco/plugin.video.netflix/wiki/Installation
Hope it can help
Nikoala

**Comment by mysiar** [comment]
wiki explain how to get it on linux nothing about osx

**Comment by mysiar** [comment]
wiki is about linux not osx.

I did download the libwidevinecdm.so and copied to $HOME/$USER/.kodi/cdm/
But not sure if this is the right place for this lib and if this is going to work on osx

Stil the same problem.
Is there anybody who has this run on OSX ?

**Comment by nicolascarrara** [comment]
You can download the libwidevinecdm.so with the link in the readme : 
https://hg.mozilla.org/mozilla-central/raw-file/31465a03c03d1eec31cd4dd5d6b803724dcb29cd/toolkit/content/gmp-sources/widevinecdm.json

This provide you the choice of your architecture, I think this is the good link for mac : 
https://redirector.gvt1.com/edgedl/widevine-cdm/970-mac-x64.zip

Look like it's the good path 👍  
Can you reboot and send another debug log to check it's still the same problems ?
I'll try it on my macbook asap

**Comment by mysiar** [comment]
Thanks @nicolascarrara for the hints, but the cdm path is different for  libwidevine.dylib :

$HOME/Library/Application Support/Kodi/cdm

**Comment by aintnogeek** [comment]
mysiar - So did you get it working finally on Mac OS?
