### ISSUE TITLE
480p when should be 1080p

### ISSUE THREAD

**Issue by Wheemer** [asciidisco/plugin.video.netflix#277]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
I'm getting 480p streams when they should be 1080p, everything is set correctly yet this addons keeps only showing me 480p
### Prerequisites
Happens on LibreELEC and windows 10, some shows are 1080p while other than should also be 1080p are only shown in 480p
* [ ] Are you running the latest version?
YES

**Comment by dr88dr88** [comment]
I have the same issue.

**Comment by xenophobentx** [comment]
Same issue on some movies(inception, catch me if you can)  even in the manual selection no hd stream is listed only 480p. However on native up hd is avaliable. Most likely somehow those movies provide stream list in a different way.

**Comment by asciidisco** [comment]
Nothing we can do about it (Not even Netflix can do something about it), this is due to the fact that content providers restrict quality for certain systems. More details here: https://github.com/asciidisco/plugin.video.netflix/issues/184

**Comment by Wheemer** [comment]
This happens not only in Linux but in windows where DRM should be good. Why can I get 1080p in the windows 10 app yet not in Kodi running on the same machine?

**Comment by asciidisco** [comment]
It can´t be boiled down to the operating system alone. Some content providers f.e. only allow SD when software decoding is the method used. The only way to always receive the best available quality for all content is only a proper Widevine L3 certified Android device.

**Comment by basha1963** [comment]
I have same on my T95z and work find only sd but I can not get 1080p  or 720 any solution for it

**Comment by dagwieers** [comment]
There was a bug in **inpustream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259
