### ISSUE TITLE
Is this addon dead?

### ISSUE THREAD

**Issue by tonyschuite** [asciidisco/plugin.video.netflix#278]
since there has not been a commit in 2 months... I was just wondering.
for me it works great, a little slow, but great...

**Comment by Wheemer** [comment]
![tumbleweed-on-road jpg 653x0_q80_crop-smart](https://user-images.githubusercontent.com/17601242/35188305-7ba33f98-fe0d-11e7-83e2-cd26ed13310b.jpg)

**Comment by im85288** [comment]
I think the answer is yes, a PR I made more than 3 months ago is still pending and there has been no developments since. This will be a great addon but I feel someone needs to step up and continue the development before it becomes obsolete

**Comment by Norien** [comment]
Such a good addon, I'm saddened to see it stall

**Comment by blackman91** [comment]
Do you guys know of any decent alternatives to this addon? Other than the crappy netflix app.

**Comment by joaosagrath** [comment]
It's sad see that every addon to Netflix get stuck in some point. This is the most important Addon to Kodi from 2017. Hope Asciidisco return soon.

**Comment by Wheemer** [comment]
All plugin that allow legal content should be picked up by official Devs of Kodi. Instead of saying they supply no cotent, maybe they should start.

**Comment by asciidisco** [comment]
No it´s not.
I´ve been not able to take of this in the past 2 1/2 months due to personal reasons.
I think I´ll be able to continue working on it in February.
