### ISSUE TITLE
login fail request error unable to complete check your credential

### ISSUE THREAD

**Issue by javcarbe** [asciidisco/plugin.video.netflix#285]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

### Prerequisites

* [ x] Are you running the latest version?

### Description
login fail request error unable to complete check your credential, i tried many times the email and password and always the same error

version im using

addon netflix 0.12.7

os libreelec 8.90.3 LibreELEC-S905.arm-8.90.3.img
### Steps to Reproduce

1. install LibreELEC-S905.arm-8.90.3.img
2. install repo 
3. doesnt work

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

"/storage/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 696, in before_routing_action

credentials = self.kodi_helper.get_credentials()

File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 172, in get_credentials

'email': self.decode(enc=email),

File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/KodiHelper.py", line 205, in decode

cipher = AES.new(self.crypt_key, AES.MODE_CBC, iv)

File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 264, in new

File "/usr/lib/python2.7/site-packages/Crypto/Cipher/__init__.py", line 130, in _create_cipher

File "/usr/lib/python2.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 247, in _create_cbc_cipher

File "/usr/lib/python2.7/site-packages/Crypto/Cipher/_mode_cbc.py", line 101, in __init__

ValueError: Error 65537 while instatiating the CBC mode

-->End of Python script error report<--

13:47:32.118 T:4096311312 ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/

13:47:32.119 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

13:47:35.936 T:4096311312 ERROR: GetDirectory - Error getting addons://sources/

13:47:35.937 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(addons://sources/) failed

13:54:24.663 T:4096311312 ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/

13:54:24.664 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

13:54:41.731 T:4096311312 ERROR: GetDirectory - Error getting addons://sources/

13:54:41.731 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(addons://sources/) failed

05:58:11.249 T:4096311312 ERROR: GetDirectory - Error getting /storage/.kodi/media/Fonts/

05:58:11.249 T:4096311312 ERROR: GetDirectory - Error getting special://home/media/Fonts/

05:58:11.302 T:4096311312 ERROR: GetDirectory - Error getting /storage/.kodi/media/Fonts/

05:58:11.302 T:4096311312 ERROR: GetDirectory - Error getting special://home/media/Fonts/

06:03:51.242 T:4096311312 ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/

06:03:51.242 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

06:03:54.275 T:4096311312 ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/

06:03:54.276 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

06:06:04.632 T:4096311312 NOTICE: Samba is idle. Closing the remaining connections

06:15:01.718 T:4096311312 ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/

06:15:01.719 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

06:15:30.752 T:4096311312 ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/

06:15:30.753 T:4096311312 ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
It's having trouble reading and decrypting your stored credentials. Have you tried resetting the addon settings, such that there are no credentials previously stored?

**Comment by asciidisco** [comment]
It doesn't work with your Libreelec Version, you haven't posted a full debug log, but I also assume you´re running Kodi 17.

You need Kodi 18 & the development builds of Libreelec for this to work.

**Comment by javcarbe** [comment]
Im new in this im using the kodi 18 , i am attaching the last zip 
[log-2018-01-31-12.34.41.zip](https://github.com/asciidisco/plugin.video.netflix/files/1681886/log-2018-01-31-12.34.41.zip)
