### ISSUE TITLE
doesnt show all the episodes per season stop in 42

### ISSUE THREAD

**Issue by javcarbe** [asciidisco/plugin.video.netflix#288]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ yes] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by mdh-cc** [comment]
Hi there,

I encountered the exact same problem yesterday. The TV show "Fullmetal Alchemist" contains 51 episodes in its first season, but only 42 are shown. Is there a workaround to access those missing episodes in the current version until this bug got fixed?

**Comment by heisiheisi** [comment]
I also encountered the same problem. Look forward to the day the bug was fixed. Thanks very much!

**Comment by urbanboy** [comment]
Hi everybody, Me too encountered exactly the same problem in RPi3 milhouse testbuild. Thanks you very much when this bug got fixed.

**Comment by urbanboy** [comment]
Hi everybody, Me too encountered exactly the same problem in RPi3 milhouse testbuild. Please fix the bug.

**Comment by rolnick** [comment]
Hi,
I had the same problem. It looks like number of episodes it hard-coded from:
[https://github.com/asciidisco/plugin.video.netflix/blob/f29f030ba4b301284e4ed7fc10a75d3313b64f4c/resources/lib/NetflixSession.py#L1554](url)

I change it to 50 to get list off all Pokemon episodes. Then restarted kodi.

Regards

**Comment by caphm** [comment]
This is by design, as the API doesn't let you query for for in a single session.

**Comment by bast69** [comment]
have you solved this issue ? for an exemple "fairy tail" have 52 episodes in season 3.
thanks for your work
