### ISSUE TITLE
[Playback] German Audio / greenish screen

### ISSUE THREAD

**Issue by cliverenwood** [asciidisco/plugin.video.netflix#289]
*I'm submitting a ...*
  - [x ] bug report

### Prerequisites

* [x ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Switch preferred player language to german
2. try to stream a netflix episode (rick&morty S2E2 in my case)

**Expected behavior:** [What you expected to happen]

Picture with german audio

**Actual behavior:** [What actually happened]

Just greenish Pixel Errors, German audio works fine. When you switch back to english as the preffered language, i get video and audio without errors.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM) PI3
* [ ] Android

**Comment by cliverenwood** [comment]
It's the latest nightly build of milhouse, by the way

**Comment by asciidisco** [comment]
@cliverenwood Is this fixed for you with a later version? If not, please feel free to reopen. If you do, please provide a Debug Log.
