### ISSUE TITLE
[Playback/Bug] ESN mismatch on Z11 Pro

### ISSUE THREAD

**Issue by kuzbx** [asciidisco/plugin.video.netflix#290]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?

### Description
if ESN is automatically generated: playback starts but is black w/ no video / no audio
If ESN copied from Netflix apk: unable to playback
if ESN is copied from another device: same

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional informatin on the environment
Widevine is supported.

Don't think is an hardware capability related issue: in Samsung Galaxy Tab A 2016, which has inferior CPU and same RAM amount goes flawlessy.

Android 6.1.1, Amlogic S905X, 2 GB RAM

## Debug log
Don't have the log: I'm on office now. If necessary I'll upload it when I'll be at home.

## Other information
I know someone has already discussed this before but I don't know if they have find a solution.

**Comment by liberty-developer** [comment]
Pls. try the current version 0.13.0 with your original ESN (netflix apk)
