### ISSUE TITLE
subtitles auto enable upon playback ?

### ISSUE THREAD

**Issue by gibman** [asciidisco/plugin.video.netflix#292]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

When I initiate playback of a netflix video it seems subtitles are default disabled.
It would be nice to have a few settings on the configure add-on section

autoselect subtitle language: text-input (language codes, comma separated list)
subtitles enabled: checkbox

Maybe same stuff for audio streams.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by yonubear** [comment]
ok i got it to load if i went back to v0.12.3  however i get a message in my log that it can't load AppData\Roaming\Kodi\cdm\widevinecdm.dll

**Comment by lameventanas** [comment]
I would also like this feature.

**Comment by 9shearer** [comment]
It seems to be working for me, but I'm not 100% sure what I have done.
I am currently watching a French-language series and the English subtitles come on by default.

**Comment by alonronin** [comment]
It seems like the addon automatically download subtitles, but only for english, even configuring kodi for other language didn't help.

It would be great to add in the Addon's configuration screen the possibility to specify which subtitle language/s you want to download and as @gibman suggested to enable them by default.

Great addon!

**Comment by squeepip** [comment]
The issue is that the default 'English' subtitles should really be labelled as 'English Forced', as that is what they are in this context. 

Then Kodi simply honours the subtitle settings, meaning Forced Only will enable Forced English by default.

**Comment by caphm** [comment]
Integrated Kodi settings for audio and subtitle streams work fine (as long as your desired subtitles are available, see #95).
In the newest version, there's the ability to save and restore audio/subtitle settings for all episodes across a show.
