### ISSUE TITLE
Randomly No Video (always sound) - Win10-64

### ISSUE THREAD

**Issue by nvgiers** [asciidisco/plugin.video.netflix#294]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

Although there is always audio, at random no video is shown (approximately 50%). There seems to be no pattern. One episode might show correct one time but not another time.

### Steps to Reproduce
Select episode

### Expected behavior: [What you expected to happen]

Watch episode/movie

### Actual behavior: [What actually happened]

The episode/movie doesn't show video in 50% of the times

### Installation

* [X] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Installed latest Kodi Leia 64 bit, enabled InputStream + RTMP Input, installed widevinecdm (by extracting "970-win-x64.zip"), installed Netflix addon

## Debug log

https://ufile.io/fme9y

## Other information

Above please find the log-file for my NUC6i3SYH. The same problem also occurs on my desktop and laptop.
I noticed a "WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer" in the log-file, hence I increased the memorysize and readfactor in the advancedsettings.xml, but this didn't solve the problem.

**Comment by BlaQPhoeniX** [comment]
I've got the same issue. Black screen but there is still audio playing.

## General infomration

### Prerequisites

* [x] Are you running the latest version?

### Description

Stream opens but there is no video displayed, just a black screen with the audio playing in the background.

## Context (Environment)

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Using nightly build of Kodi 18 with a clean user profile. Downloaded latest [widevine-cdm zip](https://dl.google.com/widevine-cdm/1.4.8.1008-win-x64.zip) and extracted to special://home/cdm. Enabled inputstream.adaptive from addons list and installed the plugin from netflix plugin repository.

## Debug log

[kodi_debug.log](https://github.com/asciidisco/plugin.video.netflix/files/1714924/kodi_debug.log)

**Comment by 9shearer** [comment]
+1, exact same issue.
The same Netflix movie plays occasionally fine and then (subsequent playback attempt) stops working. My empirical tests show it happens typically when / after scrolling in the movie.
Kodi 18 nightly, Win10 Pro 64b, tried various Widevine versions (both the one linked by @BlaQPhoeniX  above and the one linked in the Firefox sources on the initial page).

**Comment by 9shearer** [comment]
Any idea on this one? The addon is practically unusable due to this (works in about 10% of the cases for me).

**Comment by lameventanas** [comment]
It happens for me too, around 50% of the time.
But once it starts playing it works fine, even after seeking.

**Comment by caphm** [comment]
Both logs show a lot of `WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer` messages, suggesting it's an issue with the Kodi video player.

Try changing the render method in Kodi settings and see if this alleviates the issue.

Does it happen only with netflix playbacks or other media as well?

**Comment by lameventanas** [comment]
It only happens with netflix playbacks, it never happens with Youtube or local media.

**Comment by Wheemer** [comment]
I am now experiencing this also. It has rendered the plugin useless, as for me it seems to happen 90% of the time.

**Comment by Wheemer** [comment]
In an effort to try to fix this problem, I tried updating widevinecdm.dll from my chrome beta install and I could not get playback at all. I then downloaded Firefox nightly and tried the widevinecdm.dll from that, to my excitement, it seems to be working well now. I've only tried half a dozen videos, but they all worked perfectly.

**Comment by Wheemer** [comment]
Sorry I jumped the gun on this, it's still failing with the black screen sometimes.

**Comment by 9shearer** [comment]
I still have it occasionally. It seems to happen after I jump back and forth in a video. Subsequent video playback attempts result (randomly) in black screens and a "still" picture every 30 seconds or so - while the sound keeps going as normal. After restarting Kodi, the issue usually goes away.
If I don't try to skip back/forth, the playback is working fine. I have watched several episodes of a series in a row without any sort of problems.

**Comment by bomke** [comment]
This issue was actually unrelated to the netflix addon. peak3d took care of it and put in pull request for leia... A test build for win64 is avalble here: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20180316-cd0c0105-repeat-x64.exe

**Comment by bomke** [comment]
That's the pull request: https://github.com/xbmc/xbmc/pull/13653

**Comment by BlaQPhoeniX** [comment]
Confirmed that fixes it (after fixing the video list issue).

**Comment by TGRHavoc** [comment]
> after fixing the video list issue

How did you manage to fix this?

**Comment by BlaQPhoeniX** [comment]
@TGRHavoc performed the edits from the PR #312

**Comment by nvgiers** [comment]
I can confirm that "KodiSetup-20180318-277d75c1-master-x64" has fixed the problem!

**Comment by raven6679** [comment]
URL is not working anymore.
Any mirror?

**Comment by BlaQPhoeniX** [comment]
@raven6679 it's merged already, just install latest nightly from http://mirrors.kodi.tv/nightlies/windows/win64/master/
