### ISSUE TITLE
Open failed with code 420

### ISSUE THREAD

**Issue by panachoi** [asciidisco/plugin.video.netflix#296]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [X ] support request

### Prerequisites

* [Yes] Are you running the latest version?
Built from libreelec.tv git repo this morning

### Description

Netflix does not play any content, although I'm able to navigate all around, images load fine, but no content can be played at all.

### Steps to Reproduce

1. Build and install from libreelec.tv GitHub
PROJECT=Amlogic DEVICE=WeTek_Hub ARCH=arm make image
PROJECT=Amlogic DEVICE=WeTek_Hub ARCH=arm ./scripts/create_addon inputstream.adaptive

2.  Install resulting image, configure, then install inputstream addon, netflix repo, and finally netflix plugin
3. Configure inputstreamadaptive and netflix plugin, 

**Expected behavior:**
Expected Netflix content to actually play.

**Actual behavior:** 
I can browse to content, the images load, but attempting to play *ANY* content does not work. Not even an error message that the content cannot be played. Had to look at the kodi.log to see what was going on

## Context (Environment)

Wetek Hub
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

I've made "custom" build of LibreElec, with a 64bit kernel and 32bit userland, similar to the images available here (https://github.com/Raybuntu/LibreELEC.tv/releases/tag/rb-leia23) for the Wetek Hub. I then built and install inputstream.adaptive from the libreelec.tv repo, then installed and activated the netflix repo, and installed the netflix plugin.

I should note that I'm using a OpenWRT router, with a tunnel to a VPN provider in the US, so that I can watch that content. However, I do not believe this is the problem as I can view the same content on a normal Linux laptop connected to the same router, and in addition, attempting to retrieve the URL contained in the error(s) gives me a http 403 error, not 420.

## Debug log

https://pastebin.com/5B8RdZdB

(this is an excerpt showing just the error, I can paste more if necessary)

# Other information

I thought there was another similar issue, where http returned 404, and the suguestion was that the router was getting in the way, and to reboot/reconfigure the router (I cannot find that issue somehow now). I dont think this is the problem -- if I configure the US Tunnel directly on the hub, I get the same errors. I can also change VPN endpoints and use different source networks, all to no avail.

Again, I can view the exact same content (not available outside the US) on my Linux laptop in the browser without problems.

**Comment by caphm** [comment]
The VPN is the issue. Don't know why it works on your laptop, but Netflix is refusing to serve the manifest to you because you're using a VPN.
