### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by ervy1** [asciidisco/plugin.video.netflix#297]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [x ] support request

## General infomration
Failed to start Netflix video - suspecting widevine issue

### Prerequisites

* [x ] Are you running the latest version?

### Description
Netflix addon is loading up fine but cannot play videos. Getting message: 'One or more items failed to play. Check error log... '

The following error lines from my log (see link) may be suspect:

InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
[Description of the bug or feature]
InputStream Adaptive: OpenDRMSystem failed

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
HP Chromebox, Latest build LibreELEC-Generic.x86_64-9.0-Milhouse-20180209013556-#0208-g7f93f94,
Kodi 18.0-ALPHA1 Git:4de5826 running off USB Flash stick

Added also the following command through shell:
`curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash
`
[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log
http://ix.io/GfC

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]
[log](http://ix.io/GfC)

## Other information
Saw a [post ](https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/8)from emilsvennesson with a possible fix on a Raspberry Pi 3 - wondering if it may work on my config.. 
Tnx.

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Aragrohl** [comment]
I've had that problem try downgrading to 0.12.6 by uninstalling Netflix then reinstalling it by choosing 0.12.6 on this [page](https://github.com/asciidisco/plugin.video.netflix/releases) and installing according to these [instructions](https://github.com/asciidisco/plugin.video.netflix/wiki/Installation)

**Comment by Aragrohl** [comment]
Erm.. ok I rebooted my raspberry pi and my Netflix wouldn’t let me see the episodes in a series and would give me an error but films would play fine, so then I decided to update it to 0.12.7 and 
I don’t know what happened but it works now, also I have rebooted it and it still works.

**Comment by ervy1** [comment]
New error log [here](http://ix.io/H9j):
Updated my Libreelec build and tried downgrading netflix addon as you did  but to no avail. Note that I am on x86/x64 architecture (HP Chromebox)  and not Raspbery pi. The widevine loading issue still seems to be present..

**Comment by pinoelefante** [comment]
@ervy1 LibreELEC is Linux as you can read in the log you posted

> 04:53:51.626 T:140349170507072  NOTICE: Starting Kodi (18.0-ALPHA1 Git:54b1a2e). Platform: Linux x86 64-bit

**Comment by ArisB52** [comment]
Same issue here, but on Intel NUC DC53427HYE.

LibreELEC-Generic.x86_64-9.0-Milhouse-20180213230411-%230213-g3e167d2.tar
Tried installing the netflix-addon with zipfile and repository but both say:
ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)

The libwidevinecdm.so is installed with the command:
curl -Ls http://nmacleod.com/public/libreelec/getwidevine.sh | bash

LibreELEC:~/.kodi/cdm # ldd libwidevinecdm.so 
        linux-vdso.so.1 (0x00007ffc91745000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007ff617511000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007ff617181000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007ff616dfa000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007ff616bf6000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007ff6169ee000)
        libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007ff617ed5000)
        libnss3.so => /usr/lib/libnss3.so (0x00007ff6166ce000)
        libnssutil3.so => /usr/lib/libnssutil3.so (0x00007ff6164a0000)
        libnspr4.so => /usr/lib/libnspr4.so (0x00007ff617e96000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007ff616289000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007ff615eda000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007ff617dc9000)
        libplc4.so => /usr/lib/libplc4.so (0x00007ff617e90000)
        libplds4.so => /usr/lib/libplds4.so (0x00007ff617e89000)

**Comment by ervy1** [comment]
@pinoelefante - thank you Pino. Any ideas on the bug at hand?

**Comment by ervy1** [comment]
Bueller? Anyone?

**Comment by zag2me** [comment]
Same issue here on NUC, anyone know whats going on?

**Comment by caphm** [comment]
The problem does not seem directly related to netflix plugin. Did you test with any other plugins (like Amazon Video)?

You might want to try downloading the current widevine version (at time of this posting from https://dl.google.com/widevine-cdm/1.4.9.1070-linux-x64.zip, current version number can always be found at https://dl.google.com/widevine-cdm/current.txt and swapped in between the last slash and `-linux` part following it) and install it manually into ~/.kodi/cdm

**Comment by ervy1** [comment]
My issue was resolved - goog updates it's libwidevinecdm.so file which wasn't working for my configuration. I included an older version by extracting the file from older linux goog chrome package and copied it to .kodi/cdm/  and rebooted.
See this issue [here](https://github.com/peak3d/inputstream.adaptive/issues/118)

**Comment by Pysis868** [comment]
Just looking for some CDM choices for my RPi.  Hate to get this entire Chrome OS Recovery image just for that file.  Not seeing an ARM option, but found these: https://bugzilla.mozilla.org/show_bug.cgi?id=1475260
