### ISSUE TITLE
Subtitles should be moved above controls, when they are visible

### ISSUE THREAD

**Issue by helioshk** [asciidisco/plugin.video.netflix#298]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

When subtitles are enabled and the controls are visible, the subtitles are underneath the controls and barely readable.
Example: 
![pn](https://user-images.githubusercontent.com/20465551/36171789-3a73cf1a-1104-11e8-93e1-474d9f2e2a01.jpg)

**Expected behavior:** Subtitles should be above the controls.

**Actual behavior:** Subtitles are a layer underneath the controls

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Debian sid. Tried self compiled kodi as well as kodi nightly binary from repo.

**Comment by raven6679** [comment]
Yeah, this is not dependent on Netflix addon, it's common Kodi issue and you should report this bug there.
