### ISSUE TITLE
Plugin Error

### ISSUE THREAD

**Issue by sirtow** [asciidisco/plugin.video.netflix#30]
I'm running Ubuntu 16.10

I have build Kodi 18 (https://github.com/FernetMenta/kodi-agile) master branch

I have build inputstream.adaptive (https://github.com/liberty-developer/inputstream.adaptive.git) agile branch

I tried to run this plugin but getting the following error in kodi.log:

`
11:00:05.604 T:139643773998848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named Cryptodome.PublicKey
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.video.netflix/service.py", line 11, in <module>
                                                from resources.lib.MSLHttpRequestHandler import MSLHttpRequestHandler
                                              File "/home/xbmc/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 9, in <module>
                                                from MSL import MSL
                                              File "/home/xbmc/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 17, in <module>
                                                from Cryptodome.PublicKey import RSA
                                            ImportError: No module named Cryptodome.PublicKey
                                            -->End of Python script error report<--
`

I tried to install pycrypto:
`pip install pycrypto`
Still, same error
I tried to install python-paramiko, siggested on some forums, still, same error.
What am i missing?

**Comment by asciidisco** [comment]
Passing the question on to @trummerjo

**Comment by whirm** [comment]
Try with `pip install pycryptodome`

**Comment by trummerjo** [comment]
The solution Form whirm sould be correct

**Comment by sirtow** [comment]
Thank you guys for the quick response! Unfortunatly didnt help. I did install (as root) :
`Successfully installed pycryptodome-3.4.5`
but yet, same error.

**Comment by trummerjo** [comment]
Whoops sorry its:

pip install pycryptodomex

**Comment by sirtow** [comment]
That was it, Can browse my account but cannot play yet.
Thank you for your help!
P.S Can submit a PR for dependencies section in Readme, if you are interested

**Comment by lozbrown** [comment]
@sirtow I dont suppose you could share the build instructions for inputstream.adaptive?

**Comment by asciidisco** [comment]
@lozbrown 
If you´re using `cmake`to build Kodi Agile, you can try this path:

Note:
I assume here,  that `:gco:` is the folder you checked out `kodi` into & that you´ve build `kodi-agile` in the folder `:gco:/build`.

Then:
  - cd into your `:gco:` folder & do `git clone github.com/liberty-developer/inputstream.adaptive -b agile`
  - `mkdir build-addons`
  - `cd build-addons`
  - `cmake -DADDONS_TO_BUILD="inputstream.adaptive" -DADDON_SRC_PREFIX=":gco:" -DCMAKE_INSTALL_PREFIX=":gco:/build" -DPACKAGE_ZIP=1 ":gco:/cmake/addons"`
- `make -j[n]`

After that, you´ll need to build the `wvdecrypter` as explained [here](https://github.com/liberty-developer/inputstream.adaptive/tree/agile/wvdecrypter) & link that to you `.cdm` folder

Guess that should be it, I might have a typo here & there in the instructions (mostly copy pasted that stuff from somewhere else). So, if something isn't working, you might need to go doen the try & error route ;)

**Comment by sirtow** [comment]
@lozbrown , @asciidisco I wish i could find those instruction before :) Anyway, ill post my steps here. maybe they will be usefull for anyone else. 

**Disclaimer**: This is definitly is not the best option nor the reference guide but rather my attemps to run netflix on kodi with information i could gather on the internet. Im pretty sure there is more secure/faster/correct way of doing this. Your commenst are most welcomed!

- Build kodi

1. `cd /usr/src`
2. `git clone https://github.com/FernetMenta/kodi-agile`
3. `cd kodi-agile && mkdir kodi-build && cd kodi-build`
4. `cmake ..`
5. `make -j[n] && make install`

Note:  I needed to move kodi-agile folder somewhere out of /usr/src as it caused missing cmake files while building `inputstream.adaptive`.  I saw partial references to kodi src in kodi-platform cmake which were causing plugins's cmake to fail

-  Build kodi-platform
As  `inputstream.adaptive` cmake were failing due to missing  cmake files from kodi-buil, i tried to build kodi-platform locally.

1. `cd /usr/src`
2. `git clone //github.com/xbmc/kodi-platform.git`
3. `cd kodi-platform && mkdir build && cd build`
4. `cmake ..` (Note: needed to move kodi-agile folder otherwise cmake would pickup kodi-agile src includes)
5. `make && make install`

- Build `inputstream.adaptive` plugin

1.  `cd /usr/src/`
2. `git clone //github.com/liberty-developer/inputstream.adaptive.git`
3. `git checkout origin/agile`
4. `cd inputstream.adaptive` && make build && cd build`
5. `cmake ..`
6. `make && make install`

- Build libssd_wv.so
1. `cd /usr/src/inputstream.adaptive/wvdecrypter`
2. `cmake .`
3. `make`

-Prepare `plugin.video.netflix` plugin

1. `cd /usr/src`
2. `git clone //github.com/asciidisco/plugin.video.netflix.git`
3. `zip -r ~/plugins/plugin.video.netflix.zip plugin.video.netflix/`


-Glue it all together

Note: Bellow commands to be run with user you are going to lunch kodi with.

1. `pip install pycryptodomex`
2. Run `http://nmacleod.com/public/libreelec/getwidevine.sh` to get `libwidevinecdm.so`
3. `cp /usr/src/inputstream.adaptive/wvdecrypter/libssd_wv.so ~/.kodi/cdm/`
4. Run kodi and install `plugin.video.netflix` from zip (~/plugins/plugin.video.netflix.zip)
5. Profit!

**Comment by cape** [comment]
HI, I followed @sirtow instructions the result is a kodi that can't install or update any plugins.
I get a message "this plugin can't be configured" on each plugin that I have installed.
also I have 4 plugins marked as ready to update but I can't update them.. any idea?
thanks!

**Comment by gotschmarcel** [comment]
I cannot install the plugin zip, because it says "Failed to install a dependency". I also cannot install any addons or even configure them.

**Comment by shinkyo20** [comment]
Hello there, newbie beware here. I cannot run "cmake .." succesfully on Raspberry Pi 3, under Kodi 17. Constantly getting all these "Could NOT find <package> (missing:" errors. I am manually installing the needed packages but I reached a point I do not know which package it is required (GIF). Help and thanks in advanced! 👍

**Comment by jet86** [comment]
@shinkyo20 I've written up [step-by-step instructions for setting it up on a Raspberry Pi 3](https://github.com/jet86/plugin.video.netflix/blob/patch-1/RPi3-installation.md) and [submitted a pull request](https://github.com/asciidisco/plugin.video.netflix/pull/81) to add it as a file in this repo.

**Comment by shinkyo20** [comment]
@jet86 you are the best! I will try following your tutorial this evening. I want to dual boot RetroPie and LibreElec, so I will prepare the card using [PINN](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574) and follow your steps.

**Comment by shinkyo20** [comment]
Thank you very much, @jet86. It worked like a charm. Now I might need to make Amazon Video run on my RPi and I'll be a happy lad. :)

**Comment by nykroy** [comment]
I have the same problem with dependency that @gotschmarcel  
I install in my Linux system .deb package host in that url for solved that: https://www.ubuntuupdates.org/package/xbmc/xenial/main/base/kodi-inputstream-adaptive

Now I have de Inputstream.adaptative installed on my kody an update to 1.8.1 througth kodinerds repository. 

I have configured Libwidevine like in the forum: https://www.kodinerds.net/index.php/Thread/51486-Kodi-17-Inputstream-HowTo-AddOns-f%C3%BCr-Kodi-17-ab-Beta-6-aktuelle-Git-builds-Updat/ 

And Final Install de addons for netflix, but, when i try to connect with my credencials the plugin notify me than cant login in netflix. Could you help me please?

Sorry for my English and for my poor knowledge

**Comment by asciidisco** [comment]
@nykroy 
No need to excuse either for missing knowledge and especially not for lacking language skills.
We´ve all been there (or still are).

Regarding your problem:

```
 Inputstream.adaptative installed on my kody an update to 1.8.1
```

Recent nightlies of Kodi 18 already contain Inputstream.adaptive (a version >= 2.0.4 is required) & more important, they contain the decrypter. You probably just need to place the widevine lib & enable inputstream in your addon on browser.

My suggestions for you is: Uninstall everything Kodi related, wipe the Kodi user data & start from scratch.
Use:

```
wget http://nmacleod.com/public/libreelec/getwidevine.sh  && sh getwidevine.sh
```

to install widevine & then you should be good to go.
Also, a [debug.log](http://kodi.wiki/view/Log_file/Easy) is needed to help debug your problem further.
