### ISSUE TITLE
Export to library doesn't work - using MySQL

### ISSUE THREAD

**Issue by lameventanas** [asciidisco/plugin.video.netflix#302]
*I'm submitting a ...*
  - [x] bug report

## General infomration

The export function doesn't work for me. I see it works for other people, could it be because I use MySQL to store my libraries?

### Prerequisites

* [x] Are you running the latest version?

### Description

When I try to export a TV show, I get the progress dialog showing that it is being exported, but then the show is not in my library

### Steps to Reproduce

1. Configure MySQL for library storage
2. Export a tv show from Netflix
3. The show doesn't show up in the library

## Context (Environment)

Using Kodi from git 2017-02-19 313d88b0a820e13c8453603aa22ca139ea0bc261

### Installation
* [x] I´m using the Netflix Repo

### Operating System

* [x] Linux (x86/x64)

**Comment by caphm** [comment]
Did you add the appropriate paths in your media sources? They are below [kodi_home]/userdata/addon_data/plugin.video.netflix/shows for tv shows and [kodi_home]/userdata/addon_data/plugin.video.netflix/movies for movies. Add these paths to your library and set their content to shows or movies appropriately, then do a library refresh.

**Comment by lameventanas** [comment]
Ah that key information is missing in the README / wiki.
Now the exported shows are in the library, but some aren't picked up by the scraper for some reason.
I guess it has to do with the setting "Always use the original title on export"?

**Comment by raven6679** [comment]
Now, sir, it's working like a charm! 👍
