### ISSUE TITLE
Sound / Buffer problems after ca. 10 minutes

### ISSUE THREAD

**Issue by Chillkroete42** [asciidisco/plugin.video.netflix#303]
*I'm submitting a ...*
  - [X] bug report

* [ ] Are you running the latest version?
Yes
LibreELEC (Milhouse): devel-20180222210252-#0222-gc06f971 [Build #0222]
Netflix 0.12.7 
Netflix Addon Repo 1.01
InputStream Adaptive 2.1.13

### Description
After a while whatching netflix (10-15 Min) the sound is delayed and the red thermometer comes. It seems to me like a buffer problem. 

### Installation

* [X] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreELEC (Milhouse): devel-20180222210252-#0222-gc06f971 [Build #0222]
Raspi3 on Samsung TV

**Comment by MilhouseVH** [comment]
> After a while whatching netflix (10-15 Min) the sound is delayed and the red thermometer comes. It seems to me like a buffer problem.

No it's a thermal problem, resulting in the CPU throttling to avoid cooking itself. Install a small heatsink (or use a Kodi FLIRC case), or some active cooling. If you are overclocked then reduce your overclock.

**Comment by Chillkroete42** [comment]
Alright, i just ordered a FLIRC case (cause it looks pretty awesome). I just wondered, because i was using a standard pi case and no other applications had thermal problems.

**Comment by jayMcoder** [comment]
I have the same issue with 720p video with Dolby passthrough. 
I modified the Inputstream setting Max. Resolution secure decoder to 480p, now I can play netflix video without any hiccups. 
@MilhouseVH - Do you think is this Inputstream addon issue or Rpi3 buffer issue?

@Chillkroete42 - Do you overclock Rpi3 to play netflix video in 720p resolution?
I have the following in my config.txt
gpu_mem=256
force_turbo=0
arm_freq=900
core_freq=450
sdram_freq=450

**Comment by Chillkroete42** [comment]
@jayMcoder No i didnt overclock my Rpi3, its running on default settings. 
I just used the FLIRC case, it works fine i got no more thermal issues so far. thanks @MilhouseVH :)

**Comment by MilhouseVH** [comment]
> I have the following in my config.txt
>arm_freq=900

@jayMcoder why are you *underclocking* your RPi3 - the default arm frequency is 1200. No wonder you're having trouble with 720p.

**Comment by jayMcoder** [comment]
@MilhouseVH thanks for the response.
Default libreelec Rpi2/Rpi3 build sets the arm_freq to 800, I just bumped up to 900. I was happy with 900 for most of my playback and applications. I am relatively new to netflix plugin. 
As you suggested and as netflix plugin dose not support hardware acceleration could be the reason I need to bump up the arm_freq to 1200.
Will try that and update how that works out for 720p, thanks for the update again.

**Comment by MilhouseVH** [comment]
>  Default libreelec Rpi2/Rpi3 build sets the arm_freq to 800,

LibreELEC has never configured a default `arm_freq` (or any other frequency such as core or gpu, or voltage), for any RPi0/1/2/3 device - LibreELEC leaves that to the firmware as the RPi firmware knows best what the default frequencies and voltages should be.

**Comment by jayMcoder** [comment]
@MilhouseVH Thanks for clarifying that. I have to blame my limited knowledge on this. When I am back at home I will try arm_freq=1200 and see how that works.

**Comment by MilhouseVH** [comment]
Better to not set `arm_freq` at all, unless you are overclocking.
