### ISSUE TITLE
Exported episodes not marked as "watched" after playing

### ISSUE THREAD

**Issue by lameventanas** [asciidisco/plugin.video.netflix#305]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ x] Are you running the latest version?

### Description

I exported a TV show.  Now when I play an unwatched episode until the end, it isn't marked as "watched".  However, if I manually select "mark as watched", it is marked as watched.

### Steps to Reproduce

1. Export TV show
2. Play unwatched episode

**Expected behavior:** [What you expected to happen]

The episode is marked as watched.

**Actual behavior:** [What actually happened]

The episode is not marked as watched.

## Context (Environment)

Kodi built from source, using MySQL to store libraries.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Using MySQL to store libraries

## Other information

After watching an exported episode, these queries are executed:
`
insert into files (idFile, idPath, strFileName) values(NULL, xxxxx, 'plugin://plugin.video.netflix/?action=play_video&video_id=xxxxxxxx')
update files set playCount=1,lastPlayed='YYYY-MM-DD HH:mm:ss' where idFile=xxxxx
`

But when marking an episode as watched manually, I see these queries:
`
DEBUG: Mysql execute: delete from bookmark where idFile=xxxxx and type=1
DEBUG: Mysql execute: update files set playCount=1,lastPlayed='YYYY-MM-DD HH:mm:ss' where idFile=xxxxx
`
And I can see that the row was already in the table (inserted when exporting?), but strFileName is something like 'SxxExx.strm' instead of 'plugin://plugin.video.netflix/?action=play_video&video_id=xxxxxxxx'.

So there is an inconsistency in the usage of strFileName on exported videos.

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
This not natively supported by Kodi because it treats *.strm files like playlists (see https://forum.kodi.tv/showthread.php?tid=229951).

It's the addon's job to track viewing progress and mark library items as watched, however this is currently not implemented. There is an open pull request (#293) to add this functionality, but it's currently stale.

**Comment by DiR3Wolf** [comment]
@caphm  Have you been testing this code (#293)? Is it working correctly? I may try to implement on mine if you think it is good enough.

**Comment by caphm** [comment]
Yes, I'm using it as my daily driver. It works well, especially if you also implement #313 alongside it. I'm regularly pushing a "beta" version that includes these changes to my kodi repo at https://github.com/caphm/kodi-repo. Feel free to install from there :)

**Comment by DiR3Wolf** [comment]
Great. Thanks!!!

**Comment by joaosagrath** [comment]
This is very very good!

**Comment by hawkeyexp** [comment]
Fixed with #293
