### ISSUE TITLE
Two dependencies showing "unavailable"

### ISSUE THREAD

**Issue by teredactle** [asciidisco/plugin.video.netflix#307]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Unable to install plugin from the repo due to unresolved dependencies (inputstream.adaptive unavaliable and script.module.pycryptodome unavailable)

### Prerequisites
Kodi 18 nightly build, Running Kodi 18-alpha1 20180308  on FireTV gen1 (also tried on MiBox same issue)

* [x] Are you running the latest version?

### Description

[Unable to install plugin from the repo due to unresolved dependencies (inputstream.adaptive unavaliable and script.module.pycryptodome unavailable)]

### Steps to Reproduce

1. [Installed Kodi 18 nightly]
2. [Installed Netflix repository]
3. [Installed Add-on from Netflix repository]

**Expected behavior:** [Netflix add-on to install]

**Actual behavior:** [Won't install, dependencies (inputstream.adaptive unavaliable and script.module.pycryptodome unavailable)]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x
![2018-03-10 10 44 15](https://user-images.githubusercontent.com/37247773/37244600-6b9e4080-2459-11e8-99cc-949a033d895e.jpg)
] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
android packages provided from kodi come together with pycryptodomex and inputstream.adaptive.
No need to install anything, just activate inputstream.adaptive (if not done automatically)

**Comment by shampyon** [comment]
I'm having the same issue with a Windows 10 install, same version of kodi.

InputStream Adaptive and RMTP  Input are both marked as activated in the Addons interface, but script.module.pycryptodome and inputstream.adaptive aare both marked as unavailable in the Netflix addon config window. Playback always fails.

I thought it might have something to do with widevine, and when I look into kodi's widevine folder it's empty (or has an empty subfolder or two with long random-string looking names). I've tried copying the DLLs over from Chrome's Local AppData, but that has no effect.

**Comment by caphm** [comment]
The dependencies are being shown as unavailable on some systems. When they are installed and activated, this is usually not an issue and everything works fine.
