### ISSUE TITLE
launch error : CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by BouletNC** [asciidisco/plugin.video.netflix#309]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## General infomration

Error when trying to launch Netflix add-on

### Prerequisites

* [x] Are you running the latest version? 0.12.7

### Description

Error when trying to launch Netflix add-on

### Steps to Reproduce

1. Boot LibreElec
2. Done

**Expected behavior:** Open add-on

**Actual behavior:** Error info - check the log

## Context (Environment)
RPi3 LibreElec kodi 18 alpha

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x ] Linux (ARM) RPI3
* [ ] Android

#### Additional informatin on the environment

RPi3 LibreElec kodi 18 alpha

## Debug log

[https://pastebin.com/abLw3UDi](url)

## Other information

It seems to a certificate error :

`19:58:41.094 T:1743606656   DEBUG: [Netflix] [GET] Error <class 'requests.exceptions.SSLError'> HTTPSConnectionPool(host='www.netflix.com', port=443): Max retries exceeded with url: /profiles/manage (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)'),))
19:58:41.162 T:1743606656   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'text'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.netflix/service.py", line 16, in <module>
                                                from resources.lib.NetflixHttpRequestHandler import NetflixHttpRequestHandler
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpRequestHandler.py", line 30, in <module>
                                                netflix_session=NETFLIX_SESSION)
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 31, in __init__
                                                self.prefetch_login()
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/NetflixHttpSubRessourceHandler.py", line 48, in prefetch_login
                                                if self.netflix_session.login(account=self.credentials):
                                              File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/NetflixSession.py", line 290, in login
                                                content=page.text)
                                            AttributeError: 'NoneType' object has no attribute 'text'
                                            -->End of Python script error report<--`

Thank you for your help.

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
Deinstall netflix addon (if asked if you want to remove user data say yes) and install again (with the correct credentials)

**Comment by BouletNC** [comment]
Thank you for your answer. 
I did this many times. I even reinstalled LibreElec ...
I verify my credentials on the netflix website, I did not make mistake with them.
I deinstall another time and I entered my credentials very carefully.
I have the same error.

**Comment by laclaro** [comment]
I had the same error using the github-snapshot just now.
1. uninstall netflix addon
2. make sure everything gets deleted (addons/plugin.video.netflix and userdata/addon_data/plugin.video.netflix)
3. reinstall repo version via kodi

Best,

Henning

**Comment by BouletNC** [comment]
Hi Henning,

Thank yo for helping but this not solve my problem.

I reinstall my raspberry with OSMC instead of Libreelec and I do not have this problem.

**Comment by ccope** [comment]
are you able to curl https://www.betflix.com? or does it throw an SSL error?

**Comment by caphm** [comment]
I assume this issue has been resolved, as there has not been any further activity. Feel free to reopen if the issue still persists.

**Comment by laclaro** [comment]
I just had this error again after updating OSMC (package rpi2-mediacenter-osmc). Can't one catch this misleading exception? It is about the addon not able to login and has not much to do with certificates...

best,

Henning
