### ISSUE TITLE
Playback failure

### ISSUE THREAD

**Issue by sirtow** [asciidisco/plugin.video.netflix#31]
kodi-agile hash a29705b3b7
inputstream.adaptive hash 3afbfba31c8b

kodi.log :
`11:58:49.109 T:139837237405440    INFO: AddOnLog: InputStream Adaptive: SetVideoResolution (1920 x 1080)
11:58:49.109 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: Open()
11:58:49.109 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_key: [not shown]
11:58:49.109 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.license_type: com.widevine.alpha
11:58:49.109 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.manifest_type: mpd
11:58:49.109 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: found inputstream.adaptive.server_certificate: [not shown]
11:58:49.109 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: Initial bandwidth: 0
11:58:49.109 T:139837237405440   DEBUG: kodi::General::get_setting - add-on 'InputStream Adaptive' requests setting 'MAXRESOLUTION'
11:58:49.110 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTION selected: 0
11:58:49.110 T:139837237405440   DEBUG: kodi::General::get_setting - add-on 'InputStream Adaptive' requests setting 'MAXRESOLUTIONSECURE'
11:58:49.110 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: MAXRESOLUTIONSECURE selected: 1
11:58:49.110 T:139837237405440   DEBUG: kodi::General::get_setting - add-on 'InputStream Adaptive' requests setting 'STREAMSELECTION'
11:58:49.110 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: STREAMSELECTION selected: 0
11:58:49.110 T:139837237405440   DEBUG: kodi::General::get_setting - add-on 'InputStream Adaptive' requests setting 'MEDIATYPE'
11:58:49.110 T:139837237405440   DEBUG: kodi::General::get_setting - add-on 'InputStream Adaptive' requests setting 'DECRYPTERPATH'
11:58:49.110 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /home/xbmc/.kodi/cdm
11:58:49.111 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: Supported URN:
11:58:49.111 T:139837237405440   DEBUG: CurlFile::Open(0x7f2e90652680) http://localhost:43661/manifest?id=80113577

....
11:58:49.486 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: Download http://localhost:43661/manifest?id=80113577 finished
11:58:49.486 T:139837237405440    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 6 Download speed: 0.0000 Bytes/s
11:58:49.486 T:139837237405440   ERROR: AddOnLog: InputStream Adaptive: Unable to handle decryption. Unsupported!
11:58:49.487 T:139837237405440   DEBUG: AddOnLog: InputStream Adaptive: GetStreamIds()
11:58:49.487 T:139837237405440   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:43661/manifest?id=80113577]
11:58:49.487 T:139837237405440  NOTICE: CVideoPlayer::OnExit()
`

I can playback netflix from chrome. `libwidevinecdm.so` is the same:

`
xbmc@mbhtpc:~$ md5sum /opt/google/chrome/libwidevinecdm.so
1270ddce835c71888457337ed1214c5a  /opt/google/chrome/libwidevinecdm.so
xbmc@mbhtpc:~$ md5sum .kodi/cdm/libwidevinecdm.so
1270ddce835c71888457337ed1214c5a  .kodi/cdm/libwidevinecdm.so
`

**Comment by Uukrull** [comment]
At least of Windows, I have to use the widevine 1.4.8.962 version. Go [here](https://www.slimjet.com/chrome/google-chrome-old-version.php), download the 56.0.2924.87 deb and extract the libwidevinecdm.so included (md5 = a649358a9749c346c39f6bf0dec11337)

**Comment by sirtow** [comment]
Unfortunatly same result with same error. 
This is my current hash:
`
xbmc@mbhtpc:~/.kodi/cdm$ md5sum /home/xbmc/.kodi/cdm/libwidevinecdm.so
a649358a9749c346c39f6bf0dec11337  /home/xbmc/.kodi/cdm/libwidevinecdm.so
`

**Comment by asciidisco** [comment]
@sirtow Might be a stupid question, but have you linked the `libssd_wv.so` from inputstream.adaptive in your `.cdm`folder as well?

**Comment by Uukrull** [comment]
@sirtow , what @asciidisco said. You have to compile https://github.com/liberty-developer/inputstream.adaptive/tree/agile/wvdecrypter

**Comment by sirtow** [comment]
@asciidisco, @Uukrull  Actually that was THE question... I didnt have such file in my sustem. I went back to InputStream.Adaptive git repo and it has the `wvdecrypter` folder. I did as Readme says , compiled and put it under `.kodi/cdm` and it worked!
Thank you all for your time and support !
