### ISSUE TITLE
Playback failing on 0.12.7

### ISSUE THREAD

**Issue by flanabode** [asciidisco/plugin.video.netflix#310]
*I'm submitting a ...*
  - [x ] bug report

## General information
Consistent playback failures on 0.12.7 
### Prerequisites

* [X ] Are you running the latest version?

### Description

[Description of the bug or feature]
Just installed and configured 0.12.7 - I can browse Netflix and export to my library, but when I try to play any content, I get a playback failure.

You can find my full log here:
http://ix.io/WDB

### Steps to Reproduce

This was on a fresh install of the latest Kodi 18 nightly on a 64-bit Windows 10 laptop.

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Windows (x86/x64)

## Debug log

http://ix.io/WDB

**Comment by flanabode** [comment]
Nevermind, I had my libwidevine files in the wrong place :P

**Comment by zag2me** [comment]
@flanabode What location did you install the file in on windows?

**Comment by liberty-developer** [comment]
@zag2me [user]/AppData/Roaming/Kodi/cdm/
