### ISSUE TITLE
Video playback issue with latest Intel Video Driver

### ISSUE THREAD

**Issue by pierretje** [asciidisco/plugin.video.netflix#314]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [X] support request

### Prerequisites

* [ ] Are you running the latest version? Yes. My version is 0.12.7 (On Kodi 18 Alpha)

### Description

[Description of the bug or feature]

I recently received the weekly Windows updates. The next thing that happened is that the plugin stopped playing video's. The library search works fine, but when you select a video for playback, Kodi crashes directly. The Kodi logfile doesn't show any errors. Also the debugger mode doesn't show any specific errors. Therefore I started looking in the Windows EventViewer. There I saw the following message:

"Naam van toepassing met fout: kodi.exe, versie: 17.9.701.0, tijdstempel: 0x5a9c03ef
Naam van module met fout: igd10iumd64.dll, versie: 23.20.16.4973, tijdstempel: 0x5a96aeda
Uitzonderingscode: 0xc0000005
Foutmarge: 0x00000000007e6040
Id van proces met fout: 0xef8
Starttijd van toepassing met fout: 0x01d3bfbcc3da50b9
Pad naar toepassing met fout: C:\Program Files (x86)\Kodi\kodi.exe
Pad naar module met fout: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_250db833a1cd577e\igd10iumd64.dll
Rapport-id: 9d4e10d0-36de-4046-821d-14bd7c372854"

(Sorry, my PC has Dutch language)

So I started Googling and figured out it has something to do with the Intel Video Drivers. And it's the same intel drivers that just received an update by Windows update. So, I used a driver tool for reïnstalling the older version of the driver and voila, the problem was fixed. 

### Steps to Reproduce

1. Use a Windows computer with on-board Intel Graphics (I have the HD Graphics 630)
2. Upgrade to the latest driver version 
3. After installing the graphics update, start a video from Plugin Video Netflix and you'll notice that Kodi 18 crashes. 
 
**Expected behavior:** [What you expected to happen] That the video I selected started playting

**Actual behavior:** [What actually happened] Kodi 18 crashes

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by caphm** [comment]
Since Kodi 18 is still a pre-release state, issues like these are to be expected. This is probably fixed with the current Leia Beta. Otherwise, there is a suitable workaround (use an older driver).
In any case, it's not plugin related.
