### ISSUE TITLE
Auto-add new episodes of exported shows to library

### ISSUE THREAD

**Issue by caphm** [asciidisco/plugin.video.netflix#316]
*I'm submitting a ...*
  - [x] feature request

This is more of a question: Would you be willing to merge a feature, that periodically checks for new episodes of shows that were exported to the library and automatically exports/adds them?

I've currently got this in the works and will be using it personally. If this feature were welcome, I'll clean up the code and make PR.

**Comment by joaosagrath** [comment]
This sound awesome!
+1 to this !

**Comment by hawkeyexp** [comment]
yes - sounds really good - sometimes i thinked about it but never done any try :-)
The manual solution was the update in db feature in the context menu i released.
