### ISSUE TITLE
No Videoplayback

### ISSUE THREAD

**Issue by kevsei** [asciidisco/plugin.video.netflix#319]
*I'm submitting a ...*
  - [ x ] bug report 
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ ] Are you running the latest version?
yes

### Description

I cant play Movies and TV-Shows since 1.April 2018. There is no Error or something. I start playing a Movie - then the Loading Circle comes and after a few seconds the Circle expires and iam back in the Movie-Menu.

On my Windows PC in the same Network Netflix works perfect.

The Native App on the Shield is working too,

Other Addons for Kodi, like Amazon are working too.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x ] Android (Nvidia Shield 2017)

#### Additional informatin on the environment

- Iam using the newest Nvidia Shield Experience 6.3 and newest Kodi Nightly. 
- New Clean Installation

## Debug log

https://pastebin.com/uT6N6mCy

**Comment by CWftw** [comment]
I'm having the same issue. Key exchange not working on Android devices?

**Comment by khasenklever** [comment]
Same issue here: 
- Netflix Plugin revision 0.12.8 (repo install)
- target: Intel Nuc i5, Libreelec (Testing rev. from April, 1st)

**Comment by KrX3D** [comment]
hello,
i got the same problem. but i got 3 different behavors.

1. cant play, i see the loading cycle and after some seconds im back to the menu
2. some videos like Top Gear: i see the loading cycle and  after that im back to the menu BUT i see that it is "played" and when i go the the Main Menu and hit back to see the video it is "played". i see the time progress but no video or sound (black screen)
3. some videos and series can be played normally like johnny englisch

**Comment by plneappl** [comment]
I have the same issue on Windows 10 x64. When I click on any series, the loading cycle shows for some seconds, then I'm back on the browse screen, only the "stop" icon is replaced by a "play" icon and Kodi uses one CPU core. I shouldn't be CPU-throttled though, since I have an Intel i7-920.
![netflix-kodi](https://user-images.githubusercontent.com/4385742/38428713-c0403990-39bc-11e8-82e6-defbdcdac0fc.jpg)

**Comment by mkreisl** [comment]
Same here, using XBian on Raspberry Pi 3B+, Kodi v18a2 and binary addons built Apr 6

**Comment by lllavado** [comment]
Same here in MINIX NEO U1.

**Comment by liberty-developer** [comment]
For android: Pls. use Version 0.13.0+ and insert your correct ESN (from apk app) in the settings.

**Comment by lllavado** [comment]
Should I insert the all ESN code? I tried that with version 0.13.0 and it gave me an error when inserting the email. It doesn’t even let me introduce the password.

**Comment by VaughanCrash** [comment]
There's no 0.13.0+ in the repo.

**Comment by caphm** [comment]
Issues should be fixed in 0.13.10+. Feel free to reopen if there are still problems.
