### ISSUE TITLE
Crash on playing video

### ISSUE THREAD

**Issue by Backdoorek** [asciidisco/plugin.video.netflix#320]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

After trying to play anything with this plugin Kodi Crashes...
I think it can be related with this [issue](https://github.com/asciidisco/plugin.video.netflix/issues/78) 

### Steps to Reproduce

1. Run Kodi
2. Open Netflix Plugin
3. Open Your Profile
4. Select Series (i tested Rick and Morty & Jessica Jones)
5. Select Season
6. Select Episode
7. Enjoy with your crash

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Just simple PC with xone pad (gen. 2)
[DxDiag](https://gist.github.com/Backdoorek/dd998d03b4b34ef1f595784fee2931f3)

## Debug log

[Gist](https://gist.github.com/Backdoorek/ac1136888ada15da72ceaefbb74bd1d6)
[DMP File](https://drive.google.com/file/d/11Gor8FPg0q9CI7WoBKQUiicZtidUXyEa/view?usp=sharing)

## Other information

Netflix medium account (1080p playback)
DLL downloaded from mozilla sources
Using Py3.6.4

### Screenshots

[Laggggy Screen Record](https://youtu.be/1e8kQKh-udg)

**Comment by caphm** [comment]
Nothing suspicious in the logfile. Try with the newest version and have widevine installed via the helper.
Win10 x64 usually works fine when widevine is properly setup. Feel free to reopen if the issue still persist with the newest version.
