### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by tredmanz** [asciidisco/plugin.video.netflix#321]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ x] Are you running the latest version?

### Description

I login, with correct details, and get an error message saying check log. 

I have seen previous issues around non-ascii characters causing this, but have checked and all profiles only have standard characters. 

### Steps to Reproduce

1. Reset all addon settings to default
2. Attempt to start addon
3. Enter username and password
4. Failure message appears. 

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Latest milhouse LE 9 build on chromebox 

## Debug log

https://pastebin.com/Lfp46Lxm

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
The background service is trying to bind to a port that is already in use. Try with the newest version and report back if the issue persists.
