### ISSUE TITLE
Netflix plugin subtitles list incomplete

### ISSUE THREAD

**Issue by themiszamani** [asciidisco/plugin.video.netflix#322]
*I'm submitting a ...*
  - [x] bug report
  - [] feature request
  - [ ] support request

## General infomration
The list of subtitles in the netflix plugin is not the same as the list of subtitles in the official web netflix app. In the plugin i see only english and turkish , but in the official i also see greek. 

### Prerequisites

* [x ] Are you running the latest version?
Yes

### Description

The list of subtitles in the netflix plugin is not the same as the list of subtitles in the official web netflix app. In the plugin i see only english and turkish , but in the official i also see greek. 

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
I expect to see the same list of subtitles. 

**Actual behavior:** [What actually happened]

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Haris1977** [comment]
Are you going to update it for greek/hebrew subs as well?
