### ISSUE TITLE
Wall view showing screenshots instead of posters

### ISSUE THREAD

**Issue by oomek** [asciidisco/plugin.video.netflix#325]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## General information
When I set the view to Wall the plugin is showing screenshots instead of posters

### Prerequisites

* [x] Are you running the latest version?

### Description

How can I force the plugin to show posters in the Wall view?

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

https://paste.ubuntu.com/p/7VhxFPkJWw/

### Screenshots

![2018-04-22](https://user-images.githubusercontent.com/2974860/39098776-9da6d738-4667-11e8-85b6-56181f921c02.png)

**Comment by oomek** [comment]
It seem that Netflix has only horizontal posters in their database. Would it be possible to scrap for posters from tmdb instead?

**Comment by oomek** [comment]
A little bump on the topic, I hope you don't mind.

**Comment by asciidisco** [comment]
Should´ve been fixed with the merge of #396
