### ISSUE TITLE
Categorize by Movies/TV Shows

### ISSUE THREAD

**Issue by oomek** [asciidisco/plugin.video.netflix#326]
*I'm submitting a ...*
  - [ ] bug report
  - [x] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Would it be possible to make two main categories for Movies and TV Shows? Now when I select any of the entries in the main menu I get Movies and TV shows all mixed up. It also affects the active View type so it switches to the view according to the first entry on the list.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

### Screenshots

![2018-04-22 1](https://user-images.githubusercontent.com/2974860/39098907-88eb4c46-4669-11e8-88c2-fd1714c46e74.png)

![2018-04-22 4](https://user-images.githubusercontent.com/2974860/39098939-dee7f108-4669-11e8-86e0-eaca9bded3ce.png)

**Comment by asciidisco** [comment]
Unfortunately you can't due to the fact the Netflix API is structured.
We do get the information for each item, but there is no way to build a UI like the
the Amazon plugin does.
