### ISSUE TITLE
No video playback on Windows 7 X64

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#334]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
No image or sound on video playback. It's possible to navigate through lists on Netflix Addon, but, Kodi when something is played, not show image or audio.

### Prerequisites

* [x] Are you running the latest version?
Yes, It's 0.12.9

### Description
[Description of the bug or feature]

After start some video, we get a "play icon" on top of screen, showing the movie is played, but can't show image or sound (kodi sounds is off too.)

### Steps to Reproduce

1. Open Netflix addom
2. Enter in some list (E.g My List)
3. Start some video
4. The play icon will be show on top of screen
5. Nothing is show

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Windows 7 Ultimate X64

## Debug log

https://pastebin.com/8c2fDw9n

## Other information

Plugin was working fine untill 04/24/2018. In 04/25/2018 it's stopping workin in a full working Kodi install. Did a clean install of Kodi 18, because I believe that was a problem with my kodi install. 

### Screenshots

Navigating in My List
![screenshot022](https://user-images.githubusercontent.com/16491360/39320619-050a2358-495b-11e8-879f-663bb32645ee.png)
Selecting some to play
![screenshot023](https://user-images.githubusercontent.com/16491360/39320620-0539d6b6-495b-11e8-9b4a-83c0bbeefb0d.png)
The movie is playing (the play icon on top os screen), but no image or sound.
![screenshot024](https://user-images.githubusercontent.com/16491360/39320621-05697c04-495b-11e8-8e0a-37d675e9158e.png)

**Comment by liberty-developer** [comment]
Should be reported in kodi forum (windows section). But pls. enable Debug logging in the log you provide there. For me it seems to be a window driver issue / but without Debug log activated hard to say.

**Comment by asciidisco** [comment]
@joaosagrath Do you still experience this issue? If you do, please feel free to reopen.
