### ISSUE TITLE
[0.13.1] Can't enable autologin

### ISSUE THREAD

**Issue by pinoelefante** [asciidisco/plugin.video.netflix#336]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Can't save autologin

### Prerequisites

* [x] Are you running the latest version?
I am using 0.13.1 from encode branch

KodiHelper doesn't have set_setting

Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'KodiHelper' object has no attribute 'set_setting'
File "KodiHelper.py", line 204, in save_autologin_data
       self.set_setting('autologin_user', autologin_user)
       AttributeError: 'KodiHelper' object has no attribute 'set_setting'

**Comment by liberty-developer** [comment]
should be fixed with: https://github.com/asciidisco/plugin.video.netflix/pull/335
Thank your for the report
