### ISSUE TITLE
[0.13.1] Can't access Netflix or play a video

### ISSUE THREAD

**Issue by pinoelefante** [asciidisco/plugin.video.netflix#337]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Encode error starting Kodi (it happens even when try to play a video)

### Prerequisites
* [x] Are you running the latest version?
0.13.1 from encode branch

### Description

##Debug log
https://pastebin.com/EjwGQYVQ

**Comment by peak3d** [comment]
Thx for reporting!

https://github.com/asciidisco/plugin.video.netflix/pull/335

**Comment by pinoelefante** [comment]
@liberty-developer i have updated the addon with your last commits.
now i get this error: https://pastebin.com/Ak1M7F9W

**Comment by liberty-developer** [comment]
Sorry, yes, this one is fixed in the next PR (branch library)
