### ISSUE TITLE
Wrong usage of ListItem.Art values

### ISSUE THREAD

**Issue by sualfred** [asciidisco/plugin.video.netflix#340]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

- ListItem.Art(foo) is filled wrong everywhere and doesn't follow the rules what has to be filled to which value.
- ListItem.Art(tvshow.foo) is always empty for TV shows content. ListItem.Art(foo) is used instead

The biggest issue:
ListItem.Art(poster) is used for a 16:9 thumb of the item. That causes a lot of issues in different skins with wrong aspect ratios. If no poster is available -> keep this value empty

### Steps to Reproduce

Not required.

## Context (Environment)

Not required.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by asciidisco** [comment]
Should´ve been fixed with #396
