### ISSUE TITLE
Plugin is not able to play all movies.. looks like only older movies will play.. and newer are not.

### ISSUE THREAD

**Issue by osdieman** [asciidisco/plugin.video.netflix#341]
*I'm submitting a ...*
  - [ ] bug report
## General infomration

Raspberry PI 3b millhouse test builds and other

### Prerequisites

* [x] Are you running the latest version?
yes
### Description

The plugin seems not to be able to play all movies .. some movies just stops before lt is loading
### Steps to Reproduce
Find a Movie on netflix ( preferred a newer one ) and try to play it.. some do manny dont play.

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x] I´m using the Netflix Repo

### Operating System

Libreelec but also on mac this happens

**Comment by liberty-developer** [comment]
not enough information provided,

- Full debug log
- Short description what you have tried (e.g. name of movie)
