### ISSUE TITLE
Cant play any video or movie

### ISSUE THREAD

**Issue by Flyffies** [asciidisco/plugin.video.netflix#342]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

Raspberry PI 3 millhouse builds

### Prerequisites

* [X] Are you running the latest version?

### Description

Can't play any video from Netflix.  The plugin wants to install WideVine when starting a video, 
but after letting it install and again trying to install it via sshit does not detect it/ play videos.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android
* [X] LibreELEC

**Comment by cy8aer** [comment]
Yup same effect for me.

`12:50:50.117 T:1499804528  NOTICE: running thread: video_thread
12:50:50.118 T:1491411824  NOTICE: Opening stream: 2 source: 256
12:50:50.178 T:1491411824  NOTICE: Finding audio codec for: 86056
12:50:50.179 T:1491411824  NOTICE: Creating audio thread
12:50:50.179 T:1406985072  NOTICE: running thread: CVideoPlayerAudio::Process()
12:50:50.180 T:1491411824  NOTICE: Opening stream: 15 source: 256
12:50:50.307 T:1406985072  NOTICE: Creating audio stream (codec id: 86056, channels: 6, sample rate: 48000, no pass-through)
12:50:51.342 T:1499804528 WARNING: CRenderManager::Configure - timeout waiting for configure
12:50:51.342 T:1499804528   ERROR: OutputPicture - failed to configure renderer
12:50:51.845 T:1499804528 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer`

**Comment by cy8aer** [comment]
Works with Milhouse build #0429, Addon 1.3.2 (!) and WideVine actualisation by plugin. It does not work with build #0504 so there may be a problem with the later Milhouse builds. Also problems with bug #346.

**Comment by liberty-developer** [comment]
Issue is under investigation of the rbpi developer team members
