### ISSUE TITLE
 The dependency on script.module.pycryptodome version 3.4.3 could not be satisfied

### ISSUE THREAD

**Issue by fpoto** [asciidisco/plugin.video.netflix#345]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

## General information

LibreElec 8.2.5 on RPi2.arm
installing from repo, version 0.13.2

### Description

After pressing the install button and choosing the latest version from the list, a note appears saying:

> Netflix
> The dependency on 
> script.module.pycryptodome version

and nothing happens

## Debug log

DEBUG: CAddonInstallJob[plugin.video.netflix]: requires script.module.pycryptodome version 3.4.3 which is not available
ERROR: CAddonInstallJob[plugin.video.netflix]: The dependency on script.module.pycryptodome version 3.4.3 could not be satisfied.

**Comment by MilhouseVH** [comment]
There's no `pycryptodome` in LibreELEC 8.2.5 because this add-on (and the associated DRM decoding) is not supported by Kodi 17, so there is no point installing this add-on in LibreELEC 8.2.5.

You need to use a [LibreELEC 9.0](https://forum.kodi.tv/showthread.php?tid=298461) test build with Kodi 18 as this includes `pycryptodome`, or wait until LibreELEC 9.0 is released later in the year.

**Comment by fpoto** [comment]
Thank you for your answer, and thanks for writing the add-on in the first place.
I see that the build is still quite buggy, and unfortunately I have little time to follow development and reinstall when needed, so I fear I'll wait for it to become more stable.

**Comment by fmeneuhe** [comment]
Same here

**Comment by Hgetis** [comment]
I just tried to install the repo and had the same issue arised (with the pycryptodome dependency)
I have the latest osmc kodi on rpi3

**Comment by andersmmg** [comment]
Does the add-on actually work when you remove the dependency?

**Comment by Hgetis** [comment]
no unfortunately

**Comment by SWDietrich** [comment]
Hey Hgetis,

i'm new into rpi and got stuck at the same point. 
Where did you find the xml, how do you edited an reintegrated it?
