### ISSUE TITLE
login error on pi3 kodi 18a 

### ISSUE THREAD

**Issue by ejantzen** [asciidisco/plugin.video.netflix#348]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

## General information
on PI3 with osmc and kodi 18 alpha
### Prerequisites

* [x ] Are you running the latest version?

work well before last version

### Description

Start plugins, enter username and password
login error

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

osmc with kodi 9 alpha

## Debug log
0:38:38.437 T:1897919200   DEBUG: Previous line repeats 3959 times.
20:38:38.437 T:1897919200   DEBUG: CLibInputKeyboard::ProcessKey - using delay: 250ms repeat: 33ms
20:38:38.438 T:1579152096   DEBUG: Thread Timer start, auto delete: false
20:38:38.448 T:1918296672   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
20:38:38.455 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:38.456 T:1690301152   DEBUG: Previous line repeats 5 times.
20:38:38.456 T:1690301152   DEBUG: [Netflix] "KodiMonitor::update_playback_progress" called
20:38:38.457 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:38.457 T:1690301152   DEBUG: [Netflix] "KodiMonitor::update_playback_progress" returned: None
20:38:38.457 T:1690301152   DEBUG: [Netflix] Auto-update disabled or schedule check interval not complete yet (2018-05-04 20:38:38.457409 / 2018-05-04 20:14:53.777864).
20:38:38.458 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:38.599 T:1579152096   DEBUG: Previous line repeats 136 times.
20:38:38.599 T:1579152096   DEBUG: Thread Timer 1579152096 terminating
20:38:38.600 T:1918296672   DEBUG: Keyboard: scancode: 0x1c, sym: 0x000d, unicode: 0x000d, modifier: 0x0
20:38:38.600 T:1918296672   DEBUG: HandleKey: return (0xf00d) pressed, trying keyboard action 7
20:38:38.604 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:39.045 T:1918296672   DEBUG: Previous line repeats 383 times.
20:38:39.045 T:1918296672   DEBUG: ------ Window Deinit (DialogKeyboard.xml) ------
20:38:39.045 T:1918292704   DEBUG: CAnnouncementManager - Announcement: OnInputFinished from xbmc
20:38:39.045 T:1918292704   DEBUG: GOT ANNOUNCEMENT, type: 128, from xbmc, message OnInputFinished
20:38:39.048 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:39.154 T:1347785440   DEBUG: Previous line repeats 12 times.
20:38:39.154 T:1347785440   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting definitions
20:38:39.154 T:1347785440   DEBUG: CAddonSettings[plugin.video.netflix]: trying to load setting definitions from old format...
20:38:39.156 T:1347785440   DEBUG: CAddonSettings[plugin.video.netflix]: loading setting values
20:38:39.158 T:1347785440   DEBUG: [Netflix] "Navigation::establish_session" called
20:38:39.158 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:40.380 T:1261613792   DEBUG: Previous line repeats 155 times.
20:38:40.380 T:1261613792   DEBUG: [Netflix] [GET] Req. for "https://www.netflix.com/profiles/manage" took 1.21021914482 sec
20:38:40.389 T:1261613792   DEBUG: [Netflix] Parsing inline data...
20:38:40.456 T:1261613792   DEBUG: [Netflix] Parsing inline data parsing successfull
20:38:40.458 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:41.503 T:1261613792   DEBUG: Previous line repeats 129 times.
20:38:41.503 T:1261613792   DEBUG: [Netflix] [POST] Req. for "https://www.netflix.com/login" took 1.04570293427 sec
20:38:41.510 T:1261613792   DEBUG: [Netflix] Parsing inline data...
20:38:41.547 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:41.557 T:1261613792   DEBUG: Previous line repeats 12 times.
20:38:41.557 T:1261613792   DEBUG: [Netflix] Parsing inline data parsing successfull
20:38:41.635 T:1261613792   DEBUG: [Netflix] Ignoring exception for non Android devices
20:38:41.635 T:1261613792   DEBUG: [Netflix] Found ESN "NFCDCH-01-EFTA5HNXA2CTN2GP0N5DXQMAGNPKTK"
20:38:41.643 T:1347785440   DEBUG: [Netflix] "Navigation::establish_session" returned: True
20:38:41.655 T:1347785440   DEBUG: [Netflix] "Navigation::before_routing_action" returned: {}
20:38:41.655 T:1347785440   DEBUG: [Netflix] "Navigation::show_profiles" called
20:38:41.656 T:1918296672   DEBUG: ------ Window Init (DialogNotification.xml) ------
20:38:41.660 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:41.666 T:1347785440   DEBUG: Previous line repeats 14 times.
20:38:41.666 T:1347785440   DEBUG: [Netflix] "Navigation::show_profiles" returned: None
20:38:41.666 T:1918296672   DEBUG: GLES: Extension Support Test - GL_EXT_texture_format_BGRA8888 YES
20:38:41.666 T:1347785440   DEBUG: [Netflix] "Navigation::router" returned: None
20:38:41.667 T:1347785440    INFO: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.video.netflix/addon.py): script successfully run
20:38:41.668 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:41.881 T:1347785440   DEBUG: Previous line repeats 16 times.
20:38:41.882 T:1347785440 WARNING: CPythonInvoker(5, /home/osmc/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
20:38:41.882 T:1347785440    INFO: Python script stopped
20:38:41.882 T:1347785440   DEBUG: Thread LanguageInvoker 1347785440 terminating
20:38:41.882 T:1918296672   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
20:38:41.883 T:1918296672   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/
20:38:41.883 T:1918296672   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/) failed
20:38:41.884 T:1918296672   DEBUG: CGUIMediaWindow::GetDirectory ()
20:38:41.884 T:1918296672   DEBUG:   ParentPath = [plugin://plugin.video.netflix/]
20:38:41.893 T:1347785440   DEBUG: Thread BackgroundLoader start, auto delete: false
20:38:41.902 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:41.903 T:1347785440   DEBUG: Previous line repeats 3 times.
20:38:41.903 T:1347785440   DEBUG: Thread BackgroundLoader 1347785440 terminating
20:38:41.905 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.
20:38:43.458 T:1690301152   DEBUG: Previous line repeats 830 times.
20:38:43.458 T:1690301152   DEBUG: [Netflix] "KodiMonitor::update_playback_progress" called
20:38:43.458 T:1690301152   DEBUG: [Netflix] "KodiMonitor::update_playback_progress" returned: None
20:38:43.459 T:1690301152   DEBUG: [Netflix] Auto-update disabled or schedule check interval not complete yet (2018-05-04 20:38:43.458954 / 2018-05-04 20:14:53.777864).
20:38:43.487 T:1918296672   DEBUG: CSettingsManager: requested setting (videoscreen.limitedrange) was not found.

**Comment by liberty-developer** [comment]
0.13.3 should fix the issue. There have been changes on Netflix site

**Comment by ejantzen** [comment]
Good, thanks

Éric Jantzen
envoyé depuis mon OnePlus 5

Le sam. 5 mai 2018 à 16:55, liberty-developer <notifications@github.com> a
écrit :

**Comment by asciidisco** [comment]
@ejantzen Is this one fixed? As there have been no further comments from your side, I assume yes & will close this one.
If it isn't solved, please feel free to reopen.

**Comment by ejantzen** [comment]
Hello. All is good. Thank's

Éric Jantzen
envoyé depuis mon OnePlus 5
