### ISSUE TITLE
Kodi crash after attempting to install.

### ISSUE THREAD

**Issue by paranoiid** [asciidisco/plugin.video.netflix#349]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Kodi crashes during install of addon (and then goes on to keep crashing).

### Prerequisites
* [x] Are you running the latest version?

### Description
See general information.

[Description of the bug or feature]
Installing from repository results in crash. Installing from github results in a crash. Having followed the instructions to the letter in the wiki (although that was for a raspberry pi).

Have tried manually installing the required things (widevine, pythong thingie, still crashes when trying to install). And will sometimes crash just when trying to navigate to "Install from repository" or "Install from zip-file" (this happens after installing the addon).

The kodi.log contains nothing that hints at the error (these are the last lines of the crash log).

20:58:26.314 T:140580470363904  NOTICE: ADDON: pvr.filmon v999.2.3.4 installed
20:58:26.314 T:140580470363904  NOTICE: ADDON: kodi.binary.instance.visualization v2.0.1 installed
20:58:26.314 T:140580470363904  NOTICE: ADDON: pvr.hts v999.4.2.14 installed
20:58:26.314 T:140580470363904  NOTICE: ADDON: xbmc.addon v17.9.702 installed
20:58:26.314 T:140580470363904  NOTICE: ADDON: skin.estuary v2.0.8 installed
20:58:26.632 T:140580809432384 WARNING: Repository LibreELEC Add-ons uses plain HTTP for add-on downloads - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
20:58:26.635 T:140580809432384 WARNING: Repository LibreELEC Retroplayer Add-ons uses plain HTTP for add-on downloads - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
20:58:26.648 T:140579556017920 WARNING: Repository LibreELEC Add-ons uses plain HTTP for add-on downloads - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!
20:58:26.651 T:140579556017920 WARNING: Repository LibreELEC Retroplayer Add-ons uses plain HTTP for add-on downloads - this is insecure and will make your Kodi installation vulnerable to attacks if enabled!

### Steps to Reproduce

1. [First Step]
Download the latest LibreElec (8.2.5)
2. [Second Step]
Upgrade to Kodi latest nightly (05/04)
3. [Third Step]
Attempt to install the addon manually or through repository.

**Expected behavior:** [What you expected to happen]
Installed addon.

**Actual behavior:** [What actually happened]
Kodi crash.

## Context (Environment)
Intel NUC (Celeron, dual core), LibreElec

### Installation

* [x] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
Known issue in kodi -> under investigation

**Comment by paranoiid** [comment]
@liberty-developer 
Thanks, do you know where this issue is being tracked?

**Comment by liberty-developer** [comment]
Can we close this issue? Latest versions should work OK.

**Comment by paranoiid** [comment]
Haven't tested yet but it's OK to close, I'll open another issue with more information if it doesn't work.
