### ISSUE TITLE
Stream start error

### ISSUE THREAD

**Issue by MrMilk23** [asciidisco/plugin.video.netflix#350]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X ] Are you running the latest version?

### Description
When I have selected a series and want to start it, I get the following message.
"One or more items failed to play. Check the log for more information about this message."

### Steps to Reproduce

1. Select a Episode (For example Sons of Anarchy)
2. Get the Error Message.

**Expected behavior:** [What you expected to happen]
Stream Start

**Actual behavior:** [What actually happened]
Not Starting.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Windows 10 Kodi-18.0-Leia_alpha1-x64]

## Debug log

https://pastebin.com/ZrL9Lg1T
## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
If you use VPN, please disable.

**Comment by MrMilk23** [comment]
I am not using vpn

**Comment by liberty-developer** [comment]
Ok, then try 0.13.4, there is an issue fixed for stream start on very new kodi master

**Comment by MrMilk23** [comment]
Thank you. I'm going to try it later.

**Comment by theboy181** [comment]
This is happening g to me on both my media players. Both a Linux. :( has there been a compromise with the plugin?

**Comment by MrMilk23** [comment]
Does not work with the new version either.
As soon as I select the series on Yatse the error message appears.

**Comment by Basti890** [comment]
I got the same issue triying to watch Netflix from Germany on the same kodi(x64) 
here is my log:
```
13:41:24.362 T:10100 WARNING: CPythonInvoker(10, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
13:41:32.004 T:204  NOTICE: VideoPlayer::OpenFile: http://localhost:58370/manifest?id=80064515&dolby=true&hevc=false
13:41:32.007 T:7244  NOTICE: Creating InputStream
13:41:32.213 T:9312 WARNING: CPythonInvoker(11, C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py): the python script "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\addon.py" has left several classes in memory that we couldn't clean up. The classes include: class XBMCAddon::xbmcaddon::Addon
13:41:33.231 T:9048   ERROR: Traceback (most recent call last):
13:41:33.231 T:9048   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 290, in _handle_request_noblock
13:41:33.231 T:9048   ERROR:     self.process_request(request, client_address)
13:41:33.231 T:9048   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 318, in process_request
13:41:33.232 T:9048   ERROR:     self.finish_request(request, client_address)
13:41:33.232 T:9048   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 331, in finish_request
13:41:33.232 T:9048   ERROR:     self.RequestHandlerClass(request, client_address, self)
13:41:33.232 T:9048   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 652, in __init__
13:41:33.232 T:9048   ERROR:     self.handle()
13:41:33.232 T:9048   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 340, in handle
13:41:33.232 T:9048   ERROR:     self.handle_one_request()
13:41:33.232 T:9048   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 328, in handle_one_request
13:41:33.232 T:9048   ERROR:     method()
13:41:33.232 T:9048   ERROR:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSLHttpRequestHandler.py", line 64, in do_GET
13:41:33.233 T:9048   ERROR:     dolby, hevc)
13:41:33.233 T:9048   ERROR:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSL.py", line 181, in load_manifest
13:41:33.233 T:9048   ERROR:     request_data = self.__generate_msl_request_data(manifest_request_data)
13:41:33.233 T:9048   ERROR:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSL.py", line 481, in __generate_msl_request_data
13:41:33.233 T:9048   ERROR:     plaintext=self.__generate_msl_header())
13:41:33.233 T:9048   ERROR:   File "C:\Users\Media\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\MSL.py", line 574, in __encrypt
13:41:33.233 T:9048   ERROR:     return json.dumps(self.crypto.encrypt(plaintext, self.nx_common.get_esn(), self.sequence_number))
13:41:33.233 T:9048   ERROR: AttributeError: 'MSL' object has no attribute 'sequence_number'
13:41:33.234 T:7244   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
13:41:33.234 T:7244   ERROR: CCurlFile::Open failed with code 0 for http://localhost:58370/manifest?id=80064515&dolby=true&hevc=false|acceptencoding=gzip&seekable=0&user-agent=Mozilla%2f5.0%20(Windows%20NT%206.1%3b%20WOW64)%20AppleWebKit%2f537.36%20(KHTML%2c%20like%20Gecko)%20Chrome%2f59.0.3071.115%20Safari%2f537.36
13:41:33.234 T:7244   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:58370/manifest?id=80064515&dolby=true&hevc=false
13:41:33.234 T:7244   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:58370/manifest?id=80064515&dolby=true&hevc=false)
13:41:33.234 T:7244   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:58370/manifest?id=80064515&dolby=true&hevc=false]
13:41:33.234 T:7244  NOTICE: CVideoPlayer::OnExit()

```
I just downloaded all the newst software today and installed averything inside of kodi from the repo in the latest versions. I don't use any proxy.

I hope theese logs my help you to figure out whats going wrong

**Comment by retrofreak83** [comment]
I am also affected by this bug.
Platform: Kodi 18, RPi 3, I tried different versions from repo (0.13.5, 4, 3).
Here is the relevant output from kodi.log:
`22:14:54.632 T:1941879968  NOTICE: VideoPlayer::OpenFile: http://localhost:51115/manifest?id=215309
22:14:54.633 T:1358549888  NOTICE: Creating InputStream
22:14:54.931 T:1432998784 WARNING: CPythonInvoker(35, /storage/.kodi/addons/plugin.video.netflix/addon.py): the python script "/storage/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
22:14:56.914 T:1358549888   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
22:14:56.914 T:1358549888   ERROR: AddOnLog: InputStream Adaptive: OpenDRMSystem failed
22:14:56.916 T:1358549888   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:51115/manifest?id=215309]
22:14:56.916 T:1358549888  NOTICE: CVideoPlayer::OnExit()
22:14:57.824 T:1333384064 WARNING: CPythonInvoker(36, /storage/.kodi/addons/plugin.video.netflix/addon.py): the python script "/storage/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
`

I checked, the lib-file exists.

**Comment by retrofreak83** [comment]
@liberty-developer You are right. I did some research and found out that I had to update my core libreelec (to a current milhouse build) to get the current version of inputstream.adaptive (which apparently was the root of the problem, not libwidevine).

**Comment by mrfixit2001** [comment]
It would appear this issue is not yet resolved. I just installed the newest version 0.13.7, as well as the most updated version of inputstream.adaptive and the helper. I am also seeing the MSL error reference sequence_number:

22:03:10.903 T:3760190416   DEBUG: Exception happened during processing of request from
22:03:10.903 T:3760190416   DEBUG: ('127.0.0.1', 53838)
22:03:10.904 T:3760190416   ERROR: Traceback (most recent call last):
22:03:10.904 T:3760190416   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
22:03:10.904 T:3760190416   ERROR:     self.process_request(request, client_address)
22:03:10.904 T:3760190416   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
22:03:10.904 T:3760190416   ERROR:     self.finish_request(request, client_address)
22:03:10.904 T:3760190416   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
22:03:10.904 T:3760190416   ERROR:     self.RequestHandlerClass(request, client_address, self)
22:03:10.904 T:3760190416   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
22:03:10.904 T:3760190416   ERROR:     self.handle()
22:03:10.905 T:3760190416   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
22:03:10.905 T:3760190416   ERROR:     self.handle_one_request()
22:03:10.905 T:3760190416   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
22:03:10.905 T:3760190416   ERROR:     method()
22:03:10.905 T:3760190416   ERROR:   File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 63, in do_GET
22:03:10.905 T:3760190416   ERROR:     dolby, hevc)
22:03:10.905 T:3760190416   ERROR:   File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 181, in load_manifest
22:03:10.905 T:3760190416   ERROR:     request_data = self.__generate_msl_request_data(manifest_request_data)
22:03:10.905 T:3760190416   ERROR:   File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 485, in __generate_msl_request_data
22:03:10.905 T:3760190416   ERROR:     plaintext=self.__generate_msl_header())
22:03:10.905 T:3760190416   ERROR:   File "/recalbox/share/system/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 578, in __encrypt
22:03:10.905 T:3760190416   ERROR:     return json.dumps(self.crypto.encrypt(plaintext, self.nx_common.get_esn(), self.sequence_number))
22:03:10.906 T:3760190416   ERROR: AttributeError: 'MSL' object has no attribute 'sequence_number'

**Comment by Basti890** [comment]
@liberty-developer I tested it yesterday, kodi did update everything automatically (even it said update was not successful).
The following behavior I noticed:
1. Start of the Plugin fails, but when i open it imidently again it works great and i can finally watch streams in 4K and 5.1 Sound .

For me the bug seems to be solved as it works now.

**Comment by liberty-developer** [comment]
thx

**Comment by mrfixit2001** [comment]
This isn't isn't resolved for me :(

**Comment by ido-ran** [comment]
I've also run into this issue, I see the following line in my log:

`AttributeError: 'MSL' object has no attribute 'sequence_number'`

this is the full error:

```
21:24:22.528 T:1403945840  NOTICE: Creating InputStream
21:24:23.594 T:1520227184   ERROR: Traceback (most recent call last):
21:24:23.595 T:1520227184   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
21:24:23.595 T:1520227184   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
21:24:23.595 T:1520227184   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
21:24:23.595 T:1520227184   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
21:24:23.596 T:1520227184   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
21:24:23.596 T:1520227184   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
21:24:23.596 T:1520227184   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 63, in do_GET
21:24:23.596 T:1520227184   ERROR:     dolby, hevc)
21:24:23.596 T:1520227184   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 181, in load_manifest
21:24:23.597 T:1520227184   ERROR:     request_data = self.__generate_msl_request_data(manifest_request_data)
21:24:23.597 T:1520227184   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 485, in __generate_msl_request_data
21:24:23.597 T:1520227184   ERROR:     plaintext=self.__generate_msl_header())
21:24:23.597 T:1520227184   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 578, in __encrypt
21:24:23.597 T:1520227184   ERROR:     return json.dumps(self.crypto.encrypt(plaintext, self.nx_common.get_esn(), self.sequence_number))
21:24:23.597 T:1520227184   ERROR: AttributeError: 'MSL' object has no attribute 'sequence_number'
21:24:23.598 T:1403945840   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
21:24:23.598 T:1403945840   ERROR: CCurlFile::Open failed with code 0 for http://localhost:37075/manifest?id=80117040&dolby=true&hevc=false|acceptencoding=gzip&seekable=0&user-agent=Mozilla%2f5.0%20(X11%3b%20CrOS%20armv7l%207647.78.0)%20AppleWebKit%2f537.36%20(KHTML%2c%20like%20Gecko)%20Chrome%2f59.0.3071.115%20Safari%2f537.36
21:24:23.598 T:1403945840   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:37075/manifest?id=80117040&dolby=true&hevc=false
21:24:23.598 T:1403945840   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:37075/manifest?id=80117040&dolby=true&hevc=false)
21:24:23.601 T:1403945840   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+2%2C+%27plot%27%3A+u%27A+field+trip+goes+from+awkward+to+mortifying+as+Jessi+navigates+the+demands+of+coupledom+and+gets+her+first+period+--+inside+the+Statue+of+Liberty.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Big+Mouth%27%2C+%27title%27%3A+u%27Everybody+Bleeds%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27TV+Comedies%27%2C+%27year%27%3A+2017%2C+%27duration%27%3A+1521%7D&video_id=80117040&pin=False&start_offset=-1]
21:24:23.602 T:1403945840  NOTICE: CVideoPlayer::OnExit()
```

**Comment by mrfixit2001** [comment]
For those of you with this issue:
https://github.com/asciidisco/plugin.video.netflix/pull/414

**Comment by sk2212** [comment]
Thanks for that! Why has been this fix not already integrated into an update package?

**Comment by mateusfccp** [comment]
I'm having this error too using the last version of the add-on with last inputstream (compiled from source) and last kodi (compiled from source)

**Comment by Abady1988** [comment]
[url=https://up.top4top.net/][img]https://1.top4top.net/p_13880kld70.jpg[/img][/url]

Please help
