### ISSUE TITLE
Playback does not start, version 0.13.4

### ISSUE THREAD

**Issue by ickam** [asciidisco/plugin.video.netflix#352]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Tried versions 0.13.2 and 0.13.4 on Fedora 28 and Windows 10. Netflix logs in fine, but there's no playback

### Prerequisites

* [x ] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

**Expected behavior:** [What you expected to happen]
Play stream
**Actual behavior:** [What actually happened]
No stream playing, message to check log
## Context (Environment)
Fedora 28 64bit Windows10 64bit
### Installation

* [x ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
Kodi alpha 1 on Windows, kodi alpha 2 built today from git repository today on Fedora. Tried both xbmc repo version and kodi-agile
## Debug log
Windows log: https://pastebin.com/d48hDwBk
Fedora log to follow
[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
Is inputstream.adaptive addon activated?

**Comment by ickam** [comment]
Yes, it is.

**Comment by NoahLutz** [comment]
I'm having the same issue with the same error logs running Ubuntu 18.04, Kodi 18.0-ALPHA2, and version 0.13.4. Here are the debug [logs](https://pastebin.com/MiRYh5Hp)

**Comment by liberty-developer** [comment]
Pls. check again with 0.13.6, if issues still exist, we can get deeper into it

**Comment by ickam** [comment]
It is working on my windows machine. Thank you.

**Comment by NoahLutz** [comment]
0.13.6 works for me as well! Thanks!!

**Comment by victorparragarcia** [comment]
I'm having the same problem but in Android (beelink gt1 ultimate with stock room 7.1.2 and Kodi 18 alpha)  inputstream is activated, I can be logged and I can see everything from my account but when I push play, it seems loading and then it stops, nothing played.

**Comment by retorquere** [comment]
Seems to be the case for me too (LibreElec Milhouse). In the plugin settings, I don't see an option to enable debug logging though. I see Account/Library/Views/Expert/Auto Login, but none of those say anything about logging.

**Comment by caphm** [comment]
Not in the plugin settings, in Kodi settings => System => Logging.
