### ISSUE TITLE
0.13.4 fails to launch: MacOS, Kodi18 nightly

### ISSUE THREAD

**Issue by dgktkr** [asciidisco/plugin.video.netflix#357]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

MacOS 10.13.4
Kodi nightly dmg (May 10, 2018)
Fresh install of plugin (May 11, 2018)

### Prerequisites

* [X ] Are you running the latest version?

### Description

Plugin fails on launch. Popup window says to check log.

### Steps to Reproduce

1. Start Kodi. Auto login for the plugin is set so no further action is required

**Expected behavior:** 

The screen should update and allow selection of a Netflix profile

**Actual behavior:** 

Popup indicating error shows up momentarily and screen updates allowing choice of
1) Files
2) Playlists
3) Video add-ons

## Context (Environment)

MacOS desktop

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ X] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

https://pastebin.com/EwkQ21yP

## Other information

From my reading of the log, it looks like the function get_profiles() in NetflixSession.py is not detecting the delimiter it expects.

[You can erase any parts of this template not applicable to your Issue.]

**Comment by dgktkr** [comment]
I've dug into it a bit and it looks like part of the problem is that Netflix is using invalid JSON. For the login process, in NetflixSession.py the add-on calls get_profiles() which tries to read a JSON called falkorCache. It then calls json.loads(falkorCache), which chokes because falkorCache is an invalid JSON, which is confirmed by [https://jsonlint.com/](url). It appears the problem is nested quotes. Here is a snippet: 
`"80240177":{"BGImages":{"513":{"jpg":
[{"focalPoint":"{"x":0.5643,"y":0.3625}","height":513,"width":912,"url":"https://occ-0-1377-2219.1.nflxso.net/art/f934c/0e11a6eca8c7fb27631cd332dcc7e94456cf934c.jpg"},
{"focalPoint":"{"x":0.5367,"y":0.5718}","height":513,"width":912,"url":"https://occ-0-1377-2219.1.nflxso.net/art/44afa/bb452e231161d7e90f4d87428b722f167d844afa.jpg"},
{"focalPoint":"{"x":0.3651,"y":0.2597}","height":513,"width":912,"url":"https://occ-0-1377-2219.1.nflxso.net/art/76dcf/0dbf140dc9d73d9d87a5c50d37e865662c276dcf.jpg"}]`

Chrome and Firefox don't seem to have a problem with this. I wonder how they handle it.

dgktkr

**Comment by knappster1** [comment]
I am experiencing similar issues.  I am using an Arch based 64-bit linux and I built 18 Alpha 1 from source.  Have you tried Netflix version 0.13.2?  It still works for me.  I'm not sure why upgrading to 0.13.4 breaks it.

Let me know if you would like me to post any logs for comparison.  Maybe there is something unique about the profiles we have?  The only "special character" that I have in any of mine is an ampersand &.  Everything else is letters and spaces.

**Comment by dgktkr** [comment]
As of this morning, Netflix doesn't seem to be emitting invalid JSON, and the plugin seems to work. You might try and see if that's true for you.

I've upgraded to 0.13.5, but, at first glance, the code for get_profiles() seems unchanged.

My profile name is just my first name and still I saw problems, so I don't think that was the cause.

**Comment by dgktkr** [comment]
It turns out that the original problem detailed above occurred again. Netflix once more was sending falkorCache data that resulted in invalid JSON. The culprit, however, has been plugin.video.netflix.

The diagnosis and solution are given by Dodobibi in this thread: [https://github.com/asciidisco/plugin.video.netflix/issues/362](url)

**Comment by liberty-developer** [comment]
Can we close this?

**Comment by dgktkr** [comment]
@liberty-developer 

Please do. 

It was resolved by the fix for #362 

dgktkr
