### ISSUE TITLE
Stream works but not on all the tv shows

### ISSUE THREAD

**Issue by chicungunya** [asciidisco/plugin.video.netflix#360]
*I'm submitting a ...*
  - [x] support request

### Prerequisites

* [x] Are you running the latest version? Yes 0.13.4

### Description

Stream works but not on all TV shows, why ? I don't use VPN. For example, La casa de papel does not work. 

Thank you

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Libreelec Milhouse #0429

## Debug log

https://pastebin.com/UWN7V9dN (Sorry if I put much..)

**Comment by peak3d** [comment]
pls attach full debug log / component logging disabled

**Comment by peak3d** [comment]
Yes, the complete kodi.log file is fne.

But pls. enable in kodi settings::system::logging the switch Debug logging and create a new log file.

**Comment by chicungunya** [comment]
I think i'm good now : https://pastebin.com/5bdBcnKj

**Comment by peak3d** [comment]
In your folder .kodi/userdata/addon_data/plugin.video.netflix/ should be a manifest.json file.
Can you pls. pastebinit / provide it? Pls. make sure that the timestamp of the file is from previous playback.

**Comment by chicungunya** [comment]
{"serverTime": 1526461387163, "result": {"viewables": []}, "success": true}

**Comment by peak3d** [comment]
Ok, so it seems that netflix does not provide the stream (for whatever reasons)
Could be, that the stream is only available in HEVC codec which is not supported by the current widevine implementation.

Can you play this stream on a linux machine with Google chrome browser?

**Comment by chicungunya** [comment]
It's weird because it's only with La Casa de Papel. When I play it with Google Chrome (on a macbook), it works..
I don't have Linux.

**Comment by chicungunya** [comment]
I can test what you told me with Parallels Desktop with Ubuntu ? Or Do I really have to test with a Linux Machine ?

**Comment by chicungunya** [comment]
I tried with Parallels Desktop with Ubuntu last version and Chrome Browser and it was working !
So I don't understand..

**Comment by peak3d** [comment]
In case you have selected "HEVC" in netflix settings menu, pls. disable.
But I'll try to reproduce here

**Comment by chicungunya** [comment]
HEVC was already disabled.
I tried to change settings of InputStream but it's the same...
Unbelievable it's just for La Casa de Papel. I live in Spain so it's maybe the problem ? But it works without VPN on my laptop on netflix so...

**Comment by peak3d** [comment]
Yes, never see this before that the response is success but no content in there.
Could have several reasons (User-Agent / ESN / country settings / account settings) but impossible for me to solve because I cannot reproduce.

Maybe someone else from spain can confirm that it is working or not ??

**Comment by caphm** [comment]
The VPN is causing the problem. Netflix blocks access over VPN. They used to return an empty manifest, by now you should actually see an error message in the manifest.json telling you about not using a VPN.
