### ISSUE TITLE
Netflix addon play not all content

### ISSUE THREAD

**Issue by renemaes** [asciidisco/plugin.video.netflix#364]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
OS Windows 7 and Windows 10 Latest updates
Kodi Alpha release Kodi v18 "Leia" Alpha 1
and Nightly latest release
Netlix addon V 0.13.5

Country (Netherlands)

### Prerequisites

* [X ] Are you running the latest version?
Yes

### Description
for Example
All episodes of "Lost in space" play
and
All episodes of "Stranges things" won't play

### Steps to Reproduce
I tried the same on multiple computers and even OS
Exactly the same happen on all systems and platforms 
In Chrome all content play (same computer as Kodi installed on)
In netflix app for Windows 10 all play (same computer as kodi installed on)

**Expected behavior:** 
Should not all content play in Kodi?

**Actual behavior:** [What actually happened]
When it plays the content, it plays as it should, all works fine
When it does noet play, nothing happen, (nightly release) and a message in de the alpha release show up, unable to play.

## Context (Environment)
Multi Hardware and platform and OS

### Installation

* [X] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Windows 64 bit

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by renemaes** [comment]
https://pastebin.com/ggqC1uqV

Kodi Log when netflix content play

**Comment by renemaes** [comment]
https://pastebin.com/PpsfE3Bb

Kodi log when netflix content dont play

**Comment by liberty-developer** [comment]
duplicate to #360
