### ISSUE TITLE
Search returns error, no results

### ISSUE THREAD

**Issue by chris42** [asciidisco/plugin.video.netflix#365]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

When using search, no response is generated, but only error is given "Netflix Fehler, für mehr Informationen Log Datei einsehen"

### Steps to Reproduce

1. Open Netflix
2. Login with User
3. Start search (Used "thor" to test, as it is in Netflix available for sure)
4. Wait for response

**Expected behavior:** Thor Movies are returned

**Actual behavior:** Error is displayed, search results only include "(thor)", which starts search over

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional information on the environment

Using libreelec Milhouse build #0517, but problem is persisting for months, hence also previous versions. 
Netflix Version 0.13.5

## Debug log

https://pastebin.com/MZqJhrmT

## Other information

Thought it would have been fixed with #208 , however no change. Not sure if it is the same bug or a different error.

**Comment by MosDos96** [comment]
Same here (but on Windows 10), I was searching for "Last" (a Korean series) which is on Netflix and every time I try it, it show me an "**_error_**" message. The workaround for me was to replace "Last" with "Last1" :)

_**Here is the error log:**_
`File "C:\Users\X\AppData\Roaming\Kodi\addons\plugin.video.netflixsubs\resources\lib\KodiHelper.py", line 457, in build_video_listing`

`params['pin'] = (True, False)[int(video.get('maturity', {}).get('level', 1001)) >= 1000]`

`TypeError: int() argument must be a string or a number, not 'NoneType'`

**Comment by chris42** [comment]
Using CastagnaITs fork now and search works.
Closing this issue as repository seems to be unmaintained.
