### ISSUE TITLE
FireTV 2015 loading video causes crash

### ISSUE THREAD

**Issue by duk81** [asciidisco/plugin.video.netflix#366]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

While using FireTV 2015, whenever I try to load a video inside the app it starts to load then crashes Kodi before video playback starts.

### Steps to Reproduce

1. Open Netflix app
2. Select video to watch
3. Crash

**Expected behavior:** 

Play videos like on all other Android devices that I have.

**Actual behavior:** 

Crashes Kodi whenever a Netflix video is tried to load.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional informatin on the environment

N/A

## Debug log

https://pastebin.com/Yhxg2ceq

**Comment by peak3d** [comment]
Pls. provide a logcat:

- Navigate to the stream
- adb logcat -c
- play video until crash
- adb logcat -d | pastebinit
