### ISSUE TITLE
Wrong audio stream / default audio stream

### ISSUE THREAD

**Issue by beatwiz** [asciidisco/plugin.video.netflix#367]
## Platform
Latest Milhouse Kodi + RPI3 + 0.13.5

## General information
A weird bug that has started on 0.13.3 where the selected audio stream defaults to english and on the audio stream selection, some audio streams seem to be missing.

### Description

Perfect example of this is the "La casa de papel" show. The show's default language is Spanish, and 0.13.2 would play the spanish audio stream and let you choose the others if needed.

Using subsequent versions (0.13.3+), when playing that show, the default language is English, and you cannot pick the default language, which would be spanish, from the audio stream selector. The only spanish audio stream that exists on the list must be something like "spanish for the visually impaired", because it also has the background voice narrating the environment and what people are doing.

Sadly the 0.13.2 version no longer works with the most recent LibreElec / Widevine, it immediately exits with Netflix Error (worked all the way up to the 0.13.5 release).

Before the 0.13.5 release and widevine update, you could see this happening clearly, as 0.13.2 would play the spanish language as default and subsequent versions would play english, while having the issue described.

0.13.2 was doing something well regarding this! :)

Thanks in advance!

**Comment by beatwiz** [comment]
Found #64 . Sorry for not searching in advance!

**Comment by beatwiz** [comment]
Reopened because even if following #64 instructions, prefer default language / language selection on kodi player settings, has no impact on the plugin and it plays "La casa de papel" always in english and the spanish aduio track you can select is for the visually impaired as described in the initial post.

Thanks in advance!

**Comment by peak3d** [comment]
This issue is not netflix addon related, changes appeared in inputstream.adaptive
