### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by YellowOnion** [asciidisco/plugin.video.netflix#369]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [ ] Are you running the latest version?

0.13.5

### Description
Connection issue.

### Steps to Reproduce

open plugin.

**Expected behavior:** [What you expected to happen]
No error.

**Actual behavior:** [What actually happened]

please check logs.

"No connection could be made because the target machine actively refused it"

## Context (Environment)
Windows 10 x64

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Describe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://gist.github.com/YellowOnion/12258e258b90242d760db63f33ffbafa

**Comment by liberty-developer** [comment]
Your scanner (whatever it is) starts before the netflix service addon is up and running.
Will not be fixed - try to increase the time in your scanner addon to delay scan start

**Comment by YellowOnion** [comment]
Disabled on startup scan, and now I get another error:

https://gist.github.com/YellowOnion/03073caa14124d70a5421aacc0c0b53f
