### ISSUE TITLE
Input stream unable to handle decryption

### ISSUE THREAD

**Issue by mihailescu2m** [asciidisco/plugin.video.netflix#37]
I can browse Netflix, but I cannot play any media.
I get this error in the log:
``
21:03:45.275 T:2125033888   DEBUG: AddOnLog: InputStream Adaptive: Download http://localhost:47279/manifest?id=80037591 finished
21:03:45.275 T:2125033888    INFO: AddOnLog: InputStream Adaptive: Successfully parsed .mpd file. #Streams: 2 Download speed: 0.0000 Bytes/s
21:03:45.276 T:2125033888   ERROR: AddOnLog: InputStream Adaptive: Unable to handle decryption. Unsupported!
21:03:45.276 T:2125033888   DEBUG: AddOnLog: InputStream Adaptive: GetStreamIds()
21:03:45.276 T:2125033888   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:47279/manifest?id=80037591]
21:03:45.276 T:2125033888  NOTICE: CVideoPlayer::OnExit()
21:03:45.276 T:2125033888   DEBUG: AddOnLog: InputStream Adaptive: Close()
21:03:45.276 T:2125033888   DEBUG: SECTION:UnloadDll(/usr/local/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.1.0.8)
21:03:45.277 T:2125033888    INFO: ADDON: Dll Destroyed - InputStream Adaptive
21:03:45.277 T:2125033888   DEBUG: OnPlayBackStopped: play state was 1, starting 1
21:03:45.277 T:2125033888   DEBUG: Thread VideoPlayer 2125033888 terminating
21:03:45.278 T:2923620880   DEBUG: OnPlayBackStopped: play state was 3, starting 0
21:03:45.279 T:2923620880   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.netflix/?action=play_video&video_id=80037591&start_offset=-1]
21:03:45.279 T:2923620880   DEBUG: Playlist Player: no more playable items... aborting playback
``

I have widevine installed.... am I missing anything?

`odroid@odroid:~$ ARCH=arm sh /tmp/getwidevine.sh 
Detected ARCH: arm
Successfully installed libwidevinecdm.so!
odroid@odroid:~$ ls -lah ~/.kodi/cdm/
total 4.9M
drwxr-xr-x 2 odroid odroid 4.0K Apr  6 16:45 .
drwxr-xr-x 8 odroid odroid 4.0K Apr  6 16:45 ..
-rwxr-xr-x 1 odroid odroid 4.9M Apr  6 16:45 libwidevinecdm.so
`
Thanks!

**Comment by asciidisco** [comment]
@mihailescu2m 
Can you please give us some more details:
https://github.com/asciidisco/plugin.video.netflix#something-doesnt-work

Also, i doesn't seem like you´ve build the decrypter, see: https://github.com/asciidisco/plugin.video.netflix/issues/31#issuecomment-290808142

**Comment by mihailescu2m** [comment]
@asciidisco yes that was the issue, i did not know i have to :)
it would be useful to add this information to the front page, since looks like i'm not the only one that skipped this step :)

thank you!

**Comment by asciidisco** [comment]
@mihailescu2m We´d basically didn't make anything public (on our own) regarding this plugin. Once Agile is merged back & we´ve proper prebuilds of the Inputstream plugin, that shouldn't be necessary. That´s basically the reason why we´re not promoting this thingie here anywhere.

Btw.: If you´re on Odroid, I can recommend the agile builds from @raybuntu they´ve everything included & prebuild. Also, they contain the Repo the Netflix plugin is in by default. So you also get automatic updates: http://forum.odroid.com/viewtopic.php?f=144&t=24753

**Comment by mihailescu2m** [comment]
Thanks @asciidisco 
I am on an odroid, but not C2. I am on a XU4 running gnome3: 
https://www.youtube.com/watch?v=CXcoha4eNoo

**Comment by asciidisco** [comment]
@mihailescu2m 
Oh, that´s actually pretty cool. Can you tell me if it´s powerful enough to do 1080p?

**Comment by mihailescu2m** [comment]
yes, it can do 720p with ~120%CPU (out of 800%), and 1080p with ~180%CPU.
I am pretty sure it can do HEVC 1080p.

of course, you also got hw decoding, up to 1080p H264 60Hz (no HEVC). I got that in kodi 18, but not in kodi agile (yet) because of the API changes.

and also it can do 1080p hw encoding (ffmpeg and gstreamer), i send a patch to Emby media center to use hw trascoding, and i hope i have time to see if i can hw transcode in plex (patch their custom ffmpeg).

i actually got hw decoding in ffmpeg too, but only for annexB files, i got issues implementing a bitstream filter in the ffmpeg decoder :( so i gave up...

also hw scaling and csc works in gstreamer :)

**Comment by Raybuntu** [comment]
The C2 is also powerfull enough to decode 1080p in SW in Kodi but widevine struggles a bit.
That hw transcoding feature would be nice. I think I need to extend my device portfolio with a XU4 and make a LE9 agile build ;)

You can change the limit in addon settings of inputstream.adaptive.
