### ISSUE TITLE
Netflix error, tried installing for days. Even new update does not work

### ISSUE THREAD

**Issue by slayerkodi** [asciidisco/plugin.video.netflix#370]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen] install repo, install Netflix add-on, use Netflix addon

**Actual behavior:** [What actually happened]
install repo, install Netflix add-on, error check log

## Context (Environment)
Shield TV updated to latest version, same thing on Samsung s8+ updated to latest version using Kodi 18 alpha
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [X] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://paste.ubuntu.com/p/jCyv2wqwqT/

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by peak3d** [comment]
The kodi version you try is too old -> try kodi nightly
