### ISSUE TITLE
Doesn't show up under video addons

### ISSUE THREAD

**Issue by mattreecebentley** [asciidisco/plugin.video.netflix#371]
*I'm submitting a ...*
  - [o] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

Using nightly from 23/05/18, installs fine, doesn't show up under video/addons

### Prerequisites

* [o] Are you running the latest version?

Latest repository as supplied in readme.md.

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [o] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [o] Windows (x86/x64) Win7
* [ ] Linux (ARM)
* [ ] Android

#### Additional information on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
nightly what?

**Comment by mattreecebentley** [comment]
Nightly Kodi.

**Comment by peak3d** [comment]
You'll have to install the addon either via zip file (there is an option here on git which lets you download the zip archive) or install this repo: https://github.com/kodinerds/repo/raw/master/repository.netflix/repository.netflix-1.0.1.zip

**Comment by mattreecebentley** [comment]
That's exactly what I did.
But like I said, it installed fine, just didn't show up under video/addons.

**Comment by mattreecebentley** [comment]
Just tried this. It started installing, but stayed on 0% and then said installation failed.
Internet connection working fine, obviously.

**Comment by liberty-developer** [comment]
repo server seems to be broken.
You can download addon from here: https://github.com/asciidisco/plugin.video.netflix/releases
and install in kodi with "Install from zip file"

**Comment by mattreecebentley** [comment]
That works-
thank you.
BTW experiencing some weird behaviours when trying to remove shows from 'my list' within the plugin/kodi.

**Comment by liberty-developer** [comment]
"my list" things are handled in #383
