### ISSUE TITLE
Netflix error (some exceptions in the log)

### ISSUE THREAD

**Issue by madadam** [asciidisco/plugin.video.netflix#373]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Netflix addon won't start. Shows just "Netflix error: check the log for more information" message.
 
There are two exceptions raised by the Netflix addon in the log: the first is a "index out of range" and the second "urlopen error [Errno 111] Connection refused". See the attached log for more details. 

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

OSMC with latest Kodi Leia on Raspberry Pi

## Debug log

https://gist.github.com/madadam/b2c3284898be9599d40f63d1219022d5

**Comment by darpakiss** [comment]
I got the same exception.

- **OS:** Ubuntu 18.04 x86-64
- **Kodi:** 2:18.0+git20180526.0201-8a6c6c7-0bionic
- **Netflix plugin:**  0.13.5, but 0.13.4 and 0.13.2 give the same error.

**Comment by liberty-developer** [comment]
Are there still issues with 0.13.8? or can we close this issue report?

**Comment by madadam** [comment]
All good here, closing.
