### ISSUE TITLE
WIDevine Installation Fails in 0.13.6

### ISSUE THREAD

**Issue by mrfixit2001** [asciidisco/plugin.video.netflix#376]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X] support request

## Description
I can install and run the newest version, even login to netflix. When I select an episode to play it goes thru the process of downloading large file and then prompts me that it may take 10 minutes to extract and I say ok. It thinks for a few minutes and then fails. "One of more items failed to play. Check the log for more information about this message."

### Prerequisites

* [X] Are you running the latest version? YES

### Installation

* [X] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo (THE REPO IS CURRENTLY DOWN)
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
See debug log for kodi version.

## Debug log
https://pastebin.com/AZXCAmVR

It looks like the downloaded file fails a CRC32 check?

**Comment by hodor22** [comment]
same problem here , I cannot play an episode I get the two messages shown below. And I dont know what to do. I chose No
![img_20180527_192144508](https://user-images.githubusercontent.com/10690055/40588852-4160c41e-61e4-11e8-8e8e-c0cc6615b2fa.jpg)
![img_20180527_192215222](https://user-images.githubusercontent.com/10690055/40588853-4185b580-61e4-11e8-8a88-a019aef6c189.jpg)

**Comment by mrfixit2001** [comment]
hodor - you will have to say yes to that message. The issue I am experiencing is that even when I say yes, the process completes and then fails to play. Trying to play after that just prompts to do the update again. 

This seems to be a glitch in inputstreamhelper. Either with the downloaded file CRC check, or with correctly identifying a related path. I have seen both errors in the log in my many attempts.

**Comment by hodor22** [comment]
I pressed yes - but it doesnt solve the problem. No playback possible

**Comment by asciidisco** [comment]
The place to find help regarding Widevine installation issues is the repo of [script.module.inputstreamhelper](https://github.com/emilsvennesson/script.module.inputstreamhelper) which provides the functionality for the plugin.
The video plugin itself just calls that one & itself has nothing to do with the Widevine installation itself.

**Comment by hodor22** [comment]
problem solved after I updated to a new kodi alphabuild!

**Comment by mrfixit2001** [comment]
hodor - wondering what commit you used?

**Comment by hodor22** [comment]
milhouse alpha from 28.5 arm-9.0-Milhouse-20180523224632

**Comment by mrfixit2001** [comment]
Just to update - tested that kodi commit and sadly it did not resolve for me. Something else going on in my case.
