### ISSUE TITLE
Can't run Netflix

### ISSUE THREAD

**Issue by TheCazz** [asciidisco/plugin.video.netflix#377]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x ] Are you running the latest version?

**Expected behavior:** [What you expected to happen]
Show the netflix list of Movie and serie

**Actual behavior:** [What actually happened]
Show that is a error and then just show
-Files
-Playlists
-Video add-ons

* [x ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (ARM) raspberry Pi 3

#### Additional informatin on the environment
Run LibreElect the latest night build from milhouse

## Debug log
https://paste.ubuntu.com/p/HWK2ZtSF9X/

I have write my email address and password (it ask for that when I inside "Video add-ons"
But same error

I also have Viaplay on same machine and it also use Libwidevine and Inputstream.adaptive and it running fine.

**Comment by TheCazz** [comment]
Here
https://paste.ubuntu.com/p/QWsVmprYXW/

**Comment by dgktkr** [comment]
OK. The initial error is list index is out of range. And the only element referenced is react_context[0]. So does that mean react_context = None? If so, why did line 146 of NetflixSession.py fail to find "netflix.reactContext" in "content"?

I can monitor the contents of "content", so if the error would occur for me (which it doesn't for 0.13.5 or 0.13.6) I might get a better idea of whats going on.

Is this issue the same as #373?

**Comment by TheCazz** [comment]
A Little update
I did notice it was a new version of Netflix Add-on so I did install the older one 0.13.5 and now it works :)
I guess it upgrade to 0.13.6 when I did not notice it and that version does not my system like at all

**Comment by liberty-developer** [comment]
@TheCazz can you pls. install 0.13.7, and if working close the issue? Thx

**Comment by TheCazz** [comment]
It working :)
