### ISSUE TITLE
Addon is failing to download

### ISSUE THREAD

**Issue by Shaboobala** [asciidisco/plugin.video.netflix#379]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Addon is stuck at 0% before failing
### Prerequisites

* [ ] Are you running the latest version?
Yes
### Description

Repository is loaded and all prerequisites but the addon will not download

### Steps to Reproduce

1. install repo from zip
2. click install addon

**Expected behavior:** [What you expected to happen]
To download and run addon
**Actual behavior:** [What actually happened]
Addon download freezes and is stuck at )5 before giving a fail message

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
using Libreelec with nightly milhouse build
## Debug log

https://paste.ubuntu.com/p/YfrPGGRPN3/

Thanks for any help

**Comment by liberty-developer** [comment]
repo server seems to be broken.
You can download addon from here: https://github.com/asciidisco/plugin.video.netflix/releases
and install in kodi with "Install from zip file"
