### ISSUE TITLE
[Library] Suggestions about including to library

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#38]
hey guys!

After a serie of tests, the addon ir workin great, the subtitles is very smooth. Still facing some issues with the resolution of the stream, is aways displayed a low resolution, so this way, I need to change manually, not a big deal anyway.

But, I like to suggest an improvement when we save the movies/series to our library:

For the movies, it saves the .strm file inside a folder with the name of the movie. E.g: Watchmen (and inside this: Watchmen (2008).strm).
It would be nice if the folder has the "(2008)" on the name too, to avoid movies with the same name has some problem (like remakes and refilms. E.g. Total Reacall: For this one we have the movie from 1990 with Schwarzenegger, and we have the remake from 2012).

For the shows, it saves the .strm files within a folder with the name of the shows. E.g: Friends (and inside this: S01E01.strm, S01E02.strm.... S02E01.strm....).
It would be nice if inside the folders, we have seasons folders. E.g: Season 01, Season 02 (and inside os each season, his respectives .strm seasons files)

An option to save ALL "My List" into the library it would be nice too. This way, we don´t need to pull one by one, with one command, all "My List" is saved in library folder

Hope you don´t get mad with the long post. It just a suggestion and attempt to be clear as much I can. Loving the addon. Congratulations for your awesome work.

**Comment by asciidisco** [comment]
@joaosagrath Some very good suggestions. That´s indeed very helpful (and very welcome). I´ll give you more detailed feedback, when I find the time to do so.

**Comment by asciidisco** [comment]
I´ve planned to do a rework of the export feature in the v0.14 release. So, it´ll take some time, as there are more pressing fixes & features in the making & I do have to do some reading/digging up regarding best practices and Kodis behaviour of library contents. 

I´d also want to go in touch with some people who are experienced in using media managers (like Emby) on how they behave, if they encounter content like this.

That being said, here are my thoughts on an improved library experience:

a) Add the changes you mentioned in regards of naming the files. I do have one question though, you mentioned that subfolders for seasons should be created. Is this a purely cosmetic thing, or does it prevent Kodi from indexing properly, or are there any other functional impediments when not doing so?

b) Ability to export "My List" & "Currently watching" into the library & adding a watcher as part of the existing service that syncs up changes. The options to enable this should be placed in the settings & off by default. Sync should be done on Kodi startup, in addition, it should be optional & a button to manually sync changes should be present in the settings.

c) An option to automatically sync & update currently exported shows should be given in the settings. Same rules as for b) should apply here.

d) A few people have mentioned this, so I´ll add a few thoughts on syncing up the full Netflix catalog here, like it´s possible with the [Amazon plugin](https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon/service.py): I do not have any objections against this, but I´m a bit scared by the amount of API calls this would take, as well as possible bugs that such an sophisticated feature could bring along. 
That being said, I´m not going to implement this now & maybe also not going to do this later on.
I´m open for pull requests that add this feature & also suggestions on proper ways how to realise & test this. But for now, this is out of scope.

That are all the features that are planed for now & scheduled for the v0.14 release (hope to make it, before the plugin related changes are merged from agile to master).

If you´ve got any questions, feature requests or comments, they´re very welcome.

**Comment by joaosagrath** [comment]
Great!!! Thumbs up for this! 

About seasons subfolders, it´s half cosmetic, and half indexing. The cosmetic half is because a lot of skins download specific arts of seasons (season poster, season banner, etc). If all episodes is stored in only one folder, the art will be replaced by others. With seasons folders, all the arts will be stored in a correct way. 

The other half is about loading and display this images. If we have a poster of second season stored in folder, when we navigate, it display a poster of second season for the third, fourth season etc.

This way we prevent wrog indexing, and we have a correct way to stored the arts inside our library.

The rest of your coment, I don´t need to say something, because it´s very very good changes.
Thanks for your hard work!

**Comment by skarragallagher** [comment]
I got this working on my development box. My main Media Center is on Kodi 17.4 and uses PlayOn to watch netflix. I can't wait for Kodi 18 for full release and also continued dev of this awesome addon. I would love to see better built in library support. I currently use MyLibrary which is stand alone script that basically parses different sources (including playon) and then generates streams. I literally import the entire kids selection in Netflix into Kodi Library. This works quite well most of the time but is a really pain to configure and is quite time consuming. I just mentioned it because maybe there are some useful bits of code there that can be easily integrated.

**Comment by matejmosko** [comment]
The problem with same name movies with different years affects show as well. I have found a problem with Doctor Who. Your addon exports it as ./Doctor Who/*.strm. The TVDB scrapers thinks that it is the original series Doctor Who (1963), but on nertflix there is only resurrected series Doctor Who (2005). Both of them started with season 1.

**Comment by asciidisco** [comment]
Thanks to @hawkeyexp we now have a pretty solid implementation for library exports.
There are a few glitches we still need to work around tho, but those should be (and already are) treated as separate issues.

**Comment by Wheemer** [comment]
We are still locked in the profile folder when choosing where the exports should go. I edited the settings file and pointed it to the proper smb location, however it adds the folder "shows" to the path.

**Comment by im85288** [comment]
I set mine up a while back to point at a shared directory (direct from the addon, I did not need to edit the settings file directly) and yes it does create both shows and movies folders...but that’s correct as you can export movies too. I have my shows folder being scraped by both the Emby for Kodi addon and the Plexkodiconnect addon (mostly using Plex but both work well) and just as a side note the strm files work well with my nextup notification addon for Kodi

**Comment by Wheemer** [comment]
Weird I was not able to navigate outside of the profile folder within the interface. Yeah I also noticed additional folder the plugin is creating that are not needed. I got around the problem by adding my servers root to the settings file while sharing my "Series" share also as "tv", now it exports into my series folder perfectly.
