### ISSUE TITLE
Error when rating a movie

### ISSUE THREAD

**Issue by Dodobibi** [asciidisco/plugin.video.netflix#381]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [x] I´m using a different source (Please tell which): **github**

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

The method `def rate_video(self, video_id, rating):` in [NetflixSession.py line 429](https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/NetflixSession.py#L429) always return false and not execute the query.

replace `ratun = int(rating)` by `rating = int(rating)` resolve this issue

However, Netflix deprecate the rating with star in favor of the 👍 and 👎 ...

**Comment by liberty-developer** [comment]
If you have a working PR I'm more than happy to review / merge

**Comment by Dodobibi** [comment]
Ok, it's do #384
