### ISSUE TITLE
Won't play videos when switching between videos without pressing stop on the first video

### ISSUE THREAD

**Issue by mattreecebentley** [asciidisco/plugin.video.netflix#385]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

[Description of the bug or feature]

If 'stop' button is pressed prior to switching to a new video, playback works fine. If stop is not pressed (video is currently playing), new video never starts playback (stays on 'waiting' rotating logo).

### Steps to Reproduce

1. [First Step]

Win10 x64 Kodi nightly 27/05/2018, latest netflix build installed from zip file.
Start any video.

2. [Second Step]

WIthout stopping the first video, start another video on netflix.

3. [and so on...]

You can also change videos fine if you quit out of the netflix plugin, play a video from somewhere else (youtube, hard drive etc) then go back to netflix.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by liberty-developer** [comment]
Not reproducable here (Win10 / latest kodi master),. sry

**Comment by mattreecebentley** [comment]
Do you mean, only one user allowed?
Shouldn't matter.
Plugin should stop the first movie before playing the second anyway.
Will try and later build

**Comment by marco6971** [comment]
it happens even to me on raspberry pi 3 with osmc

**Comment by mattreecebentley** [comment]
I can confirm this still occurs with most recent nightly, however it's not consistent. Sometimes it works, sometimes not. It may be a timeout thing due to a lower internet connection speed (~200kbps) or not. But the plugin doesn't report a timeout, it just keeps spinning the kodi 'waiting gif'

**Comment by peak3d** [comment]
Latest kodi nightlies should solve the issues:
https://github.com/xbmc/xbmc/pull/13982
