### ISSUE TITLE
Netflix error, not even asking for credentials.

### ISSUE THREAD

**Issue by rcojr** [asciidisco/plugin.video.netflix#388]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Netflix was working great, today I had to format and reinstall my sdcard due to a problem. Now I'm trying to get it working, but it's showing an error, not even asking for my credentials to login, already tried to downgrade to 0.12.8, which asks for credentials but give the same error.
### Prerequisites

* [x] Are you running the latest version?
Latest 0.13.7 and latest librelec kodi v18 test build.
### Description
Kodi error, asking to view the log.

### Steps to Reproduce

Open Netflix addon

**Expected behavior:** To ask credentials and login

**Actual behavior:** Got an error

## Context (Environment)
Raspberry Pi3, with the latest milhouse testbuild from 2018/06/05
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM) (RPI3)
* [ ] Android

#### Additional informatin on the environment

Raspberry Pi3, with the latest milhouse testbuild from 2018/06/05

## Debug log

http://ix.io/1cqs

**Comment by hawkeyexp** [comment]
Same problem here

**Comment by hbbernardo** [comment]
Same here.

**Comment by mattreecebentley** [comment]
UPDATE: managed to fix on my system. Procedure:
Go to https://github.com/asciidisco/plugin.video.netflix
Clone or download button-> Download as zip
Kodi->system->addons->install from zip->select downloaded zip.
Kodi should show netflix plugin updated.
Close kodi, then re-open.
Netflix started running fine on my system at this point,.

**Comment by rcojr** [comment]
@mattreecebentley Version from GitHub is still the same 0.13.7, I still can't get to work,

it seems that Netflix may changed something related to login, since my other raspberry from the tv room which was previously logged in is still working fine..

**Comment by rcojr** [comment]
I finally got it working, it seems to be something related to libreelec build #0604, #0605..
What I did was:

1. Formatted my sdcard and installed LibreElec 8.2.5
2. Updated to LibreElec Milhouse Testbuild #0516 17-May-2018
3. Installed Netflix, logged in, played a movie to test: Worked ok
4. Updated to latest LibreElec Milhouse Testbuild #0605 05-Jun-2018: Got the error again
5. Downgrade to LibreElec Milhouse Testbuild #0603 03-Jun-2018: Worked ok

**Comment by peak3d** [comment]
@rcojr there are odd things with latest milhouse, you may want to check 0.13.8 (you have to install via zip)

**Comment by rcojr** [comment]
@peak3d I'm going to update later to test it, thanks!

**Comment by liberty-developer** [comment]
assume this is slved, pls. reopen if not
