### ISSUE TITLE
What are the custom views ids for the addon?

### ISSUE THREAD

**Issue by rcojr** [asciidisco/plugin.video.netflix#389]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

What are the custom views for the addon? I tried searching on google but didn't find.
I would like to show the Netflix Menu as a banner (if possible) and movies/tvseries as poster, what should be the ids?

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM) (RPi3)
* [ ] Android

#### Additional informatin on the environment

LibreElec Milhouse TestBuild #0603

**Comment by ASHJG** [comment]
banners: = 501
posters  = 51,

Although i guess it depends on the Skin you are using.

**Comment by mac1202** [comment]
Yep It depends on the skin you use.
