### ISSUE TITLE
[Errno 111] Connection refused

### ISSUE THREAD

**Issue by simonbuehler** [asciidisco/plugin.video.netflix#390]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Plugin throws error immediately
### Prerequisites

* [X] Are you running the latest version?

### Description
Hi,

installed 0.13.8 on a gentoo kodi 18git, but getting a connection refused when starting/trying to configure 

### Steps to Reproduce
install latest, addon error

**Expected behavior:** 
netflix&chill

**Actual behavior:** 
no netflix & scratching head

## Context (Environment)
gentoo amd64, kodi 18 git

### Installation

* [X] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android
## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

https://pastebin.com/3zqEWFcm

**Comment by liberty-developer** [comment]
Pls. provide a full debug log

**Comment by jstam84** [comment]
Same problem with the same error message in the log!

**Comment by simonbuehler** [comment]
debug on: https://pastebin.com/MMjQ8jt0

**Comment by liberty-developer** [comment]
Still not a full debug log.

**Comment by simonbuehler** [comment]
https://pastebin.com/ND6ay0Ba

 No module named Cryptodome.Random import erro?

**Comment by liberty-developer** [comment]
pip install pycryptodomex

**Comment by ido-ran** [comment]
I see this error but after about a minute or so after Kodi starts (LibreElec in my case) the error goes away. It looks like it's an issue of starting another service but I'm not sure.

**Comment by simonbuehler** [comment]
`pip intall cryptodomex --user ` didn't work, installing the system (distribution) package fixed it, thanks for the support, may be a missing dependency notice would help
