### ISSUE TITLE
Failed: Server returned nothing (no headers, no data)(52)

### ISSUE THREAD

**Issue by Catscrash** [asciidisco/plugin.video.netflix#391]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

I'm running libreelec milhouse #0608 - Netflix is installed via github-zip from today (v0.13.8). In the Log I can see

15:30:21.332 T:1359999856   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)

### Steps to Reproduce

1. Open Netflix
2. Start a movie
3. Movie doesn't start

**Expected behavior:** Movie should start

**Actual behavior:** Movie doesn't start

## Context (Environment)
RPi 3, Milhouse #0608, Netflix v0.13.8

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

RPi 3, Milhouse #0608, Netflix v0.13.8

## Debug log

https://pastebin.com/bL0Hy0h6

**Comment by liberty-developer** [comment]
Thanx for reporting the issue, can you pls. download thi addon version:

https://github.com/asciidisco/plugin.video.netflix/archive/msl.zip

and provide a new log after producing the issue again?

**Comment by Catscrash** [comment]
This one seems to work, thanks :-)

**Comment by liberty-developer** [comment]
The version I provided is pure 0.13.8 with an additional log output.
So it seems that there was something wrong yesterday on netflix side or whatever.

Please reopen if the issue pops up again.

**Comment by anthonws** [comment]
I'm getting the same behavior with the latest version (0.13.19) with CoreElec nightlies + Beelink GT1 (S912).

> 11:45:45.856 T:3581899568   DEBUG: ----------------------------------------
11:45:45.856 T:3581899568   DEBUG: Exception happened during processing of request from
11:45:45.856 T:3581899568   DEBUG: ('127.0.0.1', 57506)
11:45:45.856 T:3581899568   ERROR: Traceback (most recent call last):
11:45:45.857 T:3581899568   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
11:45:45.857 T:3581899568   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
11:45:45.857 T:3581899568   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
11:45:45.857 T:3581899568   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
11:45:45.857 T:3581899568   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
11:45:45.858 T:3581899568   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
11:45:45.858 T:3581899568   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 69, in do_GET
11:45:45.859 T:3581899568   ERROR:     dolby, hevc, hdr, dolbyvision, vp9)
11:45:45.859 T:3581899568   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 225, in load_manifest
11:45:45.861 T:3581899568   ERROR:     return self.__tranform_to_dash(data)
11:45:45.861 T:3581899568   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 311, in __tranform_to_dash
11:45:45.861 T:3581899568   ERROR:     manifest = manifest['result']['viewables'][0]
11:45:45.861 T:3581899568   ERROR: KeyError: 'viewables'
11:45:45.861 T:3581899568   DEBUG: ----------------------------------------
11:45:45.862 T:3509543728   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
11:45:45.862 T:3509543728   ERROR: CCurlFile::Open failed with code 0 for http://localhost:52177/manifest?id=80242926&dolby=false&hevc=false&hdr=false&dolbyvision=false&vp9=false:
11:45:45.862 T:3509543728   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:52177/manifest?id=80242926&dolby=false&hevc=false&hdr=false&dolbyvision=false&vp9=false
11:45:45.862 T:3509543728   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:52177/manifest?id=80242926&dolby=false&hevc=false&hdr=false&dolbyvision=false&vp9=false)
11:45:45.862 T:3509543728   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
11:45:45.866 T:3509543728   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+%27%27%2C+%27plot%27%3A+u%22Stacy+makes+delicious+confections.+Her+look-alike+has+royal+connections.+Swapping+lives+gives+both+a+taste+of+what+they%27re+missing.%22%2C+%27season%27%3A+None%2C+%27tvshowtitle%27%3A+%27%27%2C+%27title%27%3A+u%27The+Princess+Switch%27%2C+%27mediatype%27%3A+%27movie%27%2C+%27mpaa%27%3A+%27NFLX-All%27%2C+%27cast%27%3A+%5Bu%27Robin+Soans%27%2C+u%27Pavel+Douglas%27%2C+u%27Mark+Fleischmann%27%2C+u%27Sam+Palladio%27%2C+u%27Amy+Griffiths%27%2C+u%27Suanne+Braun%27%2C+u%27Alexa+Adeosun%27%2C+u%27Natali+Yura%27%2C+u%27Calliope+Taylor%27%2C+u%27Nick+Sagar%27%2C+u%27Vanessa+Hudgens%27%2C+u%27Sara+Stewart%27%5D%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27Dramas%27%2C+%27year%27%3A+2018%2C+%27duration%27%3A+6114%7D&video_id=80242926&pin=True]

>

**Comment by simonbuehler** [comment]
same here: gentoo, quite recent git
```
19:47:33.639 T:140629619230464   DEBUG: [Netflix] StreamContinuityManager: Loading enabled setting from store
19:47:33.639 T:140629619230464   DEBUG: [Netflix] StreamContinuityManager: Initialiized (enabled=1, current_show=801245                   22)
19:47:33.776 T:140629627623168   DEBUG: Skin Helper Service --> Kodi_Monitor: sender plugin.video.netflix.SIGNAL - meth                   od: Other.playback_initiated  - data: ["7b22747673686f775f766964656f5f6964223a2038303132343532322c202274696d656c696e655                   f6d61726b657273223a207b22637265646974734f6666736574223a20323235382c202277617463686564546f456e644f6666736574223a20323236                   307d7d"]
19:47:34.656 T:140627863897856   DEBUG: ----------------------------------------
19:47:34.656 T:140627863897856   DEBUG: Exception happened during processing of request from
19:47:34.656 T:140627863897856   DEBUG: ('127.0.0.1', 37734)
19:47:34.657 T:140627863897856   ERROR: Traceback (most recent call last):
19:47:34.657 T:140627863897856   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 290, in _handle_request_nob                   lock
19:47:34.657 T:140627863897856   ERROR:     self.process_request(request, client_address)
19:47:34.657 T:140627863897856   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 318, in process_request
19:47:34.657 T:140627863897856   ERROR:     self.finish_request(request, client_address)
19:47:34.657 T:140627863897856   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 331, in finish_request
19:47:34.657 T:140627863897856   ERROR:     self.RequestHandlerClass(request, client_address, self)
19:47:34.657 T:140627863897856   ERROR:   File "/usr/lib64/python2.7/SocketServer.py", line 652, in __init__
19:47:34.657 T:140627863897856   ERROR:     self.handle()
19:47:34.657 T:140627863897856   ERROR:   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
19:47:34.657 T:140627863897856   ERROR:     self.handle_one_request()
19:47:34.657 T:140627863897856   ERROR:   File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_reques                   t
19:47:34.657 T:140627863897856   ERROR:     method()
19:47:34.657 T:140627863897856   ERROR:   File "/home/simon/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequ                   estHandler.py", line 69, in do_GET
19:47:34.657 T:140627863897856   ERROR:     dolby, hevc, hdr, dolbyvision, vp9)
19:47:34.657 T:140627863897856   ERROR:   File "/home/simon/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", li                   ne 225, in load_manifest
19:47:34.657 T:140627863897856   ERROR:     return self.__tranform_to_dash(data)
19:47:34.657 T:140627863897856   ERROR:   File "/home/simon/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", li                   ne 311, in __tranform_to_dash
19:47:34.657 T:140627863897856   ERROR:     manifest = manifest['result']['viewables'][0]
19:47:34.658 T:140627863897856   ERROR: KeyError: 'viewables'
19:47:34.658 T:140627863897856   DEBUG: ----------------------------------------
19:47:34.658 T:140627631486720   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(5                   2)
19:47:34.658 T:140627631486720   ERROR: CCurlFile::Open failed with code 0 for http://localhost:46173/manifest?id=80149                   397&dolby=false&hevc=false&hdr=false&dolbyvision=false&vp9=false:
19:47:34.658 T:140627631486720   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:46173/manifest                   ?id=80149397&dolby=false&hevc=false&hdr=false&dolbyvision=false&vp9=false
19:47:34.658 T:140627631486720   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost                   :46173/manifest?id=80149397&dolby=false&hevc=false&hdr=false&dolbyvision=false&vp9=false)
19:47:34.658 T:140627631486720   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
19:47:34.658 T:140627631486720   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?a                   ction=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27plot%27%3A+u%27A                   ufgrund+seiner+Schizophrenie+ist+Owen+das+schwarze+Schaf+seiner+Industriellenfamilie.+Als+er+seinen+Job+verliert%2C+mel                   det+er+sich+freiwillig+f%5Cxfcr+eine+Medikamentenstudie.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Maniac%27%                   2C+%27title%27%3A+u%27Der+Auserw%5Cxe4hlte%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27dire                   ctor%27%3A+%27%27%2C+%27genre%27%3A+u%27Mysteryserien%27%2C+%27year%27%3A+2018%2C+%27duration%27%3A+2472%7D&video_id=80                   149397&pin=False&start_offset=-1]
19:47:34.658 T:140627631486720  NOTICE: CVideoPlayer::OnExit()
19:47:34.659 T:140627631486720   DEBUG: AddOnLog: InputStream Adaptive: Close()
19:47:34.659 T:140627631486720   DEBUG: SECTION:UnloadDll(/usr/lib64/kodi/addons/inputstream.adaptive/inputstream.adapt                   ive.so.2.3.11)
19:47:34.659 T:140627631486720    INFO: ADDON: Dll Destroyed - InputStream Adaptive
19:47:34.659 T:140627631486720   DEBUG: Thread VideoPlayer 140627631486720 terminating
19:47:34.661 T:140627673261824   DEBUG: DoWork - Saving file state for video item plugin://plugin.video.netflix/?action                   =play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27plot%27%3A+u%27Aufgru                   nd+seiner+Schizophrenie+ist+Owen+das+schwarze+Schaf+seiner+Industriellenfamilie.+Als+er+seinen+Job+verliert%2C+meldet+e                   r+sich+freiwillig+f%5Cxfcr+eine+Medikamentenstudie.%27%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Maniac%27%2C+%2                   7title%27%3A+u%27Der+Auserw%5Cxe4hlte%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%                   27%3A+%27%27%2C+%27genre%27%3A+u%27Mysteryserien%27%2C+%27year%27%3A+2018%2C+%27duration%27%3A+2472%7D&video_id=8014939                   7&pin=False&start_offset=-1
19:47:34.675 T:140627673261824   DEBUG: OnPlayBackStopped: CApplication::OnPlayBackStopped
19:47:34.675 T:140630965700992  NOTICE: CVideoPlayer::CloseFile()
19:47:34.675 T:140630965700992  NOTICE: VideoPlayer: waiting for threads to exit
19:47:34.675 T:140630965700992  NOTICE: VideoPlayer: finished waiting
19:47:34.675 T:140630965700992   DEBUG: DeleteRenderer - deleting renderer
19:47:34.675 T:140630965700992   DEBUG: LinuxRendererGL: Cleaning up GL resources
19:47:34.679 T:140630505047808   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
19:47:34.679 T:140630505047808   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
19:47:34.707 T:140630965700992   DEBUG: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
19:47:34.712 T:140630965700992   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
19:47:34.730 T:140629636015872   DEBUG: [plugin.video.youtube] Cleared home window properties: []
19:47:35.030 T:140629627623168   DEBUG: Skin Helper Service --> Kodi_Monitor: sender xbmc - method: Player.OnStop  - da                   ta: {"end":false,"item":{"episode":1,"season":1,"showtitle":"Maniac","title":"Der Auserwählte","type":"episode"}}
19:47:35.031 T:140629619230464   DEBUG: [Netflix] PlaybackController: Notifying all managers of on_playback_stopped (da                   ta=None)

```

**Comment by tanis2000** [comment]
I'm experiencing the same issue on the latest alpha of Libreelec and with version 0.13.19 of this addon on an RPi3.

**Comment by simonbuehler** [comment]
See #550 for a fix

Am 26. November 2018 21:46:12 MEZ schrieb Valerio Santinelli <notifications@github.com>:
>I'm experiencing the same issue on the latest alpha of Libreelec and
>with version 0.13.19 of this addon on an RPi3.
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/asciidisco/plugin.video.netflix/issues/391#issuecomment-441791751

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
