### ISSUE TITLE
Attempting to play any item results in 'one or more items cannot be played'.

### ISSUE THREAD

**Issue by nzsjb** [asciidisco/plugin.video.netflix#392]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Win 7 x86

### Prerequisites

* [x] Are you running the latest version?
Kodi 18 Alpha 1 from 4th March 2018
Netflix plugin 0.13.8

### Description

Attempting to play any Netflix item results in 'one or more items cannot be played'. Log suggests Widevine cdm cannot be loaded although it is present in the directory mentioned in the log. It was installed automatically when the plugin was installed.

### Steps to Reproduce

1. [Access Netflix plugin]
2. [Chose item]
3. [Try to play it]

**Expected behavior:** [What you expected to happen]

Item should play.

**Actual behavior:** [What actually happened]

Error message indicating one or more items cannot be played.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

Log attached.

[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/2087492/kodi.log)

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
13:37:53.643 T:4280   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (C:\Users\User\AppData\Roaming\Kodi\cdm\widevinecdm.dll)

What date / filesize has this file?

**Comment by liberty-developer** [comment]
Pls. update your kodi version to latest nightly, should solve your issue.
