### ISSUE TITLE
not loading libwidevine even though its installed

### ISSUE THREAD

**Issue by rijnhard** [asciidisco/plugin.video.netflix#393]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Ubuntu 18.04
kodi 18 alpha 89A53E4
netflix 0.13.8
inputstream adaptive 2.1.13

### Prerequisites

* [x] Are you running the latest version?

### Description
netflix errors when trying to play video (it did work before). In the logs it says it cant load libwidevine.
Tried to change permissions, didnt work.
Tried to replace it with libwidevine from chrome, didnt work.
Tried to wipe the directory and have it installed again by the addon, didnt work.

### Steps to Reproduce

1. install libwidevine via nay method
2. try to play netflix video 

**Expected behavior:** [What you expected to happen]
should load libwidevine
**Actual behavior:** [What actually happened]
does not load libwidevine even though installed

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Raw Ubuntu 18.04 with Gnome shell in an X session, AMDGPU drivers. Running test version of pretty much the entire display stack, but all seems stable and that seems unrelated to it being able to find the lib. 

## Debug log
[chrome libwidevine](https://pastebin.com/vTJbiP9i)
[fresh addon libwidevine](https://pastebin.com/yWEBD5gR)

## Other information
strangely the size of the libwidevine lib varies greatly. 

Addon installed:
```
lrwxrwxrwx 1 htpc htpc   90 Jun 10 21:04 libwidevinecdm.so -> /home/htpc/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm/libwidevinecdm.so*
```

Chromes:
```
-rw-r--r-- 1 root root 6920724 Jun  6 02:20 /opt/google/chrome/libwidevinecdm.so
```

**Comment by rijnhard** [comment]
@peak3d so I'm using the kodi-unstable ppa from team-xbmc, and it looks like it was last built in march. And running nightlies is a bit much imho. I'll wait till they push another update. 
In the meantime you can close this, and/or I will gladly update this issue when the update is pushed to confirm that it works.

**Comment by rijnhard** [comment]
On a side note, I do think that (if possible) the plugin should check for this and error accordingly. It will make the user experience a lot better, since debugging the libwidevine issues is a bit unuserfriendly

**Comment by peak3d** [comment]
For newer versions the implemented API version is in noted hidden in settings.xml and inputstreamhelper will check the version in one of the next versions (as best as possible, not possible for ARM devices for example)

**Comment by rijnhard** [comment]
Just updating, last update on the ppa fixed this.
