### ISSUE TITLE
[Core] Generate esn dynamically

### ISSUE THREAD

**Issue by asciidisco** [asciidisco/plugin.video.netflix#4]
The ESN is hardcoded in the MSL service [see here](https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/MSL.py#L42) & the one (https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/NetflixSession.py#L319-L338)[retrieved from Netflix] always resolves to a platform specific Chrome one, because of the (https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/NetflixSession.py#L111)[hardcoded user agent].

I´m currently not sure if this could cause problems. Solutions would be either to generate the ESN on our own, or to generate a proper user agent to get back a platform specific one from Netflix. Either way, we would need to find out the users Device/OS (maybe used widevine lib as well???). Both options seem rather unstable & work/maintenance intensive.

Would love to get @liberty-developer & @trummerjo opinions on that topic.

**Comment by trummerjo** [comment]
I would prefer to generate the esn on our own.
At least at a linux machine it is possible to use `sys.platform` - dont know if this is possible on other platforms as well
https://docs.python.org/2/library/sys.html

**Comment by asciidisco** [comment]
@trummerjo You´re fine with me closing this? We´re now fetching the ESN using a platform specific UA & users are able to change it on their own in the settings.

**Comment by trummerjo** [comment]
I think we will still have problems on android devices with the esn!

**Comment by asciidisco** [comment]
Okay. Leaving this open then.

**Comment by asciidisco** [comment]
So, @liberty-developer proposed an implementation here: https://github.com/asciidisco/plugin.video.netflix/pull/79

I´ll try to verify, check & merge this asap.

**Comment by asciidisco** [comment]
Fixed in https://github.com/asciidisco/plugin.video.netflix/commit/eae6850e82683605d0426dd36a34020919301798

Released with 0.11.15
