### ISSUE TITLE
Error and wrong credentials

### ISSUE THREAD

**Issue by TheCazz** [asciidisco/plugin.video.netflix#402]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Trying to Watch Netflix

* [x ] Are you running the latest version?
Yes

**Expected behavior:** [What you expected to happen]
Show my list in netflix

**Actual behavior:** [What actually happened]
Say error and wrong credentials even if I know it is right.

I just start the Kodi to Watch Netflix and I get error.
did notice it have been a update so I did try to downgrade but same error.

Have even reinstall the Netflix.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
The latest version of Kodi on Windows

## Debug log
http://c-media.se/kodi/kodi.log

**Comment by jackieatgit** [comment]
Just chiming in to report that I'm having this issue on LibreElec/RPI aswell

**Comment by NiekeA** [comment]
Me too: osmc/RPI3 (was working last week)

**Comment by ASHJG** [comment]
Yep same here, on Android Nvidia Shield and RPi running libreelec millhouse tests build 609

**Comment by ASHJG** [comment]
latest Netflix addon master solves this issue

**Comment by montvid** [comment]
yes, deleted and reinstalled the latest master, it works, rock on guys. :)

**Comment by knappster1** [comment]
I uninstalled 0.13.8 and tried upgrading to 0.13.9 from master and I am still having the same issue as https://github.com/asciidisco/plugin.video.netflix/issues/398

**Comment by husqar** [comment]
The error still exists in current master (version 0.13.9 ) RPi3 with current libreelec milhouse build.

**Comment by knappster1** [comment]
@husqar it may be different for you, but I've confirmed that Netflix forced a password reset due to suspicious activity while I was trying to get this to work.  Might be worth checking out...

**Comment by liberty-developer** [comment]
No log, no issue. @husqar pls. provide a debug log if you wnat your issue analyzed.
Just writing that something doesn't work doesn't help.

**Comment by Mediel** [comment]
Hello, 

I have the same problem, there is my log
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/2108008/kodi.log)

**Comment by liberty-developer** [comment]
@Mediel pls. update to 0.13.10, if the issue still exisis, pls. provide a new log.

B.t.w. thx for providing a full log with debug enabled, there are not many getting this right

**Comment by liberty-developer** [comment]
👍
