### ISSUE TITLE
Addon only get fanart from titles from netflix

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#408]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
If the movie/tv show are from another producer (e.g. Breaking Bad (tv show), Watchmen (movie) and others), fanart and clearlogo doesn't show (empty).
### Prerequisites

* [ ] Are you running the latest version?
0.10.13
### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Show fanart and clearlogo on all itens.
**Actual behavior:** [What actually happened]
Fanart and clearlogo only show on movies/tv shows from netflix.
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]
Breaking Bad has only poster
![screenshot071](https://user-images.githubusercontent.com/16491360/41503981-c5a7be5c-71b7-11e8-9ca2-dea27d3a18f6.png)
Fanart and clearlogo is empty, but thumbnail (miniatura in portuguese) is get it.
![screenshot077](https://user-images.githubusercontent.com/16491360/41503990-01cf26cc-71b8-11e8-9d41-ac0d011bf1ee.png)
![screenshot078](https://user-images.githubusercontent.com/16491360/41503991-01edd7b6-71b8-11e8-8e9b-dfafec30097c.png)
![screenshot079](https://user-images.githubusercontent.com/16491360/41503992-020c748c-71b8-11e8-956b-2061e48a1755.png)
![screenshot080](https://user-images.githubusercontent.com/16491360/41503993-022935c2-71b8-11e8-84fe-2a80467409ab.png)

If the movie/tv show are from netflix, all art is get it
![screenshot072](https://user-images.githubusercontent.com/16491360/41504005-5f2eb3d2-71b8-11e8-8dc2-a728d8564794.png)
![screenshot073](https://user-images.githubusercontent.com/16491360/41504006-5f524e8c-71b8-11e8-8d1e-08f59f5a1f4d.png)
![screenshot074](https://user-images.githubusercontent.com/16491360/41504007-5f72119a-71b8-11e8-9740-a038ba6d6687.png)
![screenshot075](https://user-images.githubusercontent.com/16491360/41504008-5f926a76-71b8-11e8-9671-9dc88a5cdb2c.png)
![screenshot076](https://user-images.githubusercontent.com/16491360/41504009-5fafcbc0-71b8-11e8-92e0-dc7541efc2e0.png)

Cheers

[You can erase any parts of this template not applicable to your Issue.]

**Comment by liberty-developer** [comment]
@caphm can you pls look at fanart issues? I also have noticed that for != Netflix there are things missing.
Maybe my comment in https://github.com/asciidisco/plugin.video.netflix/pull/396 was correct?

**Comment by caphm** [comment]
Sorry, the mention got lost in my notifications during vacation.

I have created a PR that fixes the issue with the fanarts. Clearlogo is unfortunately not available for all shows it seems. At least for breaking bad there is no logo displayed in the web frontend either and I assume this might be the case for other shows / movies as well.

If you can find a show / movie that shows a logo in the webinterface but not the addon, please report them here so I can have a look and maybe determine the yet unknown path property to query for it.
