### ISSUE TITLE
Netflix error check log information

### ISSUE THREAD

**Issue by ervy1** [asciidisco/plugin.video.netflix#412]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Netflix addon won't load up. 
### Prerequisites

* [ ] Are you running the latest version?
plugin.video.netflix v0.12.6

### Description

Was working great until a few weeks ago on HP ChromeBox running an older milhouse version then stopped working on its own. Tried updating to latest milhouse LibreELEC-Generic.x86_64-9.0-Milhouse-20180617210312-#0617-gdd4eaa1 but nothing. I previously resolved a [libwidevine issue](https://github.com/asciidisco/plugin.video.netflix/issues/297) back in February but I dont think that is related here.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

## Context (Environment)
LibreElec Linux (x86/x64) running off HP ChromeBox

### Installation

* [x] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[[debug link](http://ix.io/1dQe)]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by MilhouseVH** [comment]
The version of this add-on you have is months out of date, upgrade it.

**Comment by ervy1** [comment]
Same problem. Just upgraded it to plugin.video.netflix v0.12.7 (latest release) - here is the new [error log link](http://ix.io/1dTp)
Although the add-on information shows v0.12.7 installed there is a flashing message on the screen saying v0.12.6 (2017-10-27) Adapt the Netflix AP. Not sure what that means. Tnx.

**Comment by debutanker** [comment]
0.12.6/0.12.7? Meanwhile recent version is 0.13.10 https://github.com/asciidisco/plugin.video.netflix/releases

**Comment by ervy1** [comment]
my bad.. works ok now. tnx.
