### ISSUE TITLE
OSMC RPI3: Video not starting

### ISSUE THREAD

**Issue by malapascua** [asciidisco/plugin.video.netflix#415]
*I'm submitting a  bug report

## General infomration
System: Raspberry Pi 3
latest OSMC
Kodi 18 ALPHA2
### Prerequisites

* [ ] Are you running the latest version?
yes
### Description
Whenever I try to start a Video/series/movie the rotating "loading" icon appears for a couple of seconds and it returns my to the episodes list
### Steps to Reproduce
Play a Video/series/movie 

**Expected behavior:** [What you expected to happen]
Video starts playing
**Actual behavior:** [What actually happened]
returns to episodes list
### Installation

 I´m using the Netflix Repo

### Operating System

 Linux (ARM)

#### Additional informatin on the environment

OSMC and Kodi Leia nightly 17.8-252

## Debug log

LINK: https://files.fm/u/nmp8mpsf

**Comment by jakey1995abc** [comment]
I am having same issue with latest LibreElec nightly build for Raspberry Pi 3

**Comment by caphm** [comment]
It's the MSL attribute sequence_number bug. See #431 for a possible fix.

**Comment by liberty-developer** [comment]
The  "MSL attribute sequence_number bug" can be solved by restarting kodi once after the first successful login
