### ISSUE TITLE
Unable to load widevine shared library 

### ISSUE THREAD

**Issue by mrfixit2001** [asciidisco/plugin.video.netflix#417]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

I encountered this issue on a compiled commit of kodi and inputstream from a month ago and saw another similar issue from 15 days ago that said to update everything. So I have now compiled these commits, which are about as new as they get:
inputstream.adaptive: 4db421d679b371a9ec6519548cc395a33da2a6e5
Kodi: 2ab16beeeaf67e3b8dca703d96615bd80aca7c35

Same issue, so the newest versions did not resolve, as can be seen here in the pastebin:
https://pastebin.com/F7fsU6dj

I've confirmed the file libwidevinecdm.so is a link to the library downloaded from inputstreamhelper, which I also have updated to the newest commit. Please advise next steps.

## Context (Environment)
ROCK64 ARM 64-bit kernel with 32-bit userspace in buildroot

### Installation
* [X] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

**Comment by danielchc** [comment]
Same here

**Comment by liberty-developer** [comment]
ldd /recalbox/share/system/.kodi/cdm/libwidevinecdm.so

**Comment by mrfixit2001** [comment]
Thank you for replying. Yes, there was an initial issue with dependencies.
Due to lack of response on this issue, I opened the issue with the
inputstream repo and have been trying to troubleshoot from there since
peak3d has been more responsive. Here is that thread:
https://github.com/peak3d/inputstream.adaptive/issues/175

As you can see, after the initial dependency issue was resolved, there is
now the issue of the ESN being "mismatched" with the device, which is
causing a python error after that. Here's the most recent log, which shows
the entire process of installing widevine and trying to start playback.

Part 1 - https://pastebin.com/cAZSTLY4
Part 2 - https://pastebin.com/dNdSzpB9

You might see a few extra unfamiliar log lines that I've added here and
there when debugging, just fyi.

Looking forward to your help and reply!

On Thu, Aug 9, 2018 at 11:12 AM, liberty-developer <notifications@github.com

**Comment by caphm** [comment]
Closing because widevine issue is resolved and model Device mismatch is addressed in #430

**Comment by mrfixit2001** [comment]
FYI - I am still experiencing this error but the details have changed. I am creating a new issue report now.
