### ISSUE TITLE
explanation login process

### ISSUE THREAD

**Issue by nekcorp** [asciidisco/plugin.video.netflix#419]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version? YES

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Windows 7 64bit

## Debug log

No debug

## Other information

Hi, 
Very good job with this Addon, congratulation.
I have a question about the python code, I would like to know what is the process to check an account (login and password). I have read the login function in NetflixSession.py but it is very difficult to understand all of process without explanations. I use logging.warning() to write variables in kodi.log but I am losted.

Can you tell me where the user_data are created in a first time and particulary authURL ?

Regards and thank you.

**Comment by liberty-developer** [comment]
Kodi actions are handled in: addon.py + Navigation.py
Then there is a service.py which spawns 2 threads, one for MSL and one for Web communication.

If you enter the router in Navigation.py, and it is not yet logged in, navigation.py asks for user + pwd, passes this via TCP to NetflixHTTPHandler.py and the login is handled in the service addon.

**Comment by caphm** [comment]
`user_data` (and specifically authURL) are extracted from the Netflix website. When not logged in, the site at https://www.netflix.com/profiles/manage is requested, which contains the required information in its contents. It's extracted in `extract_inline_netflix_page_data` in NetflixSession.py.
