### ISSUE TITLE
Unable to login to Netflix with V88 android box but ok on Leelbox ...

### ISSUE THREAD

**Issue by Nux007** [asciidisco/plugin.video.netflix#420]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

### Prerequisites

* [X ] Are you running the latest version?

### Description
Unable to login to my Netflix account on my V88 box but ok with my leelbox !!
[Description of the bug or feature]

### Steps to Reproduce

1. Install clean kodi 18 nightly
2. Install Netflix addon repo
3. Activate Inputstream adaptive
4. Activate Netflix addon
5. Enter ESN from android Netflix app
6. Start Netflix addon inside kodi ( after a restart )
7. Any attempt to start Netflix addon inside kodi will trigger a 111 erno

**Expected behavior:** [What you expected to happen]
Login successfull to enjoy my legal streaming :-)

**Actual behavior:** [What actually happened]
Not possible to connect to my netflix account with the right credentials.

## Context (Environment)
V88 Android box ( android 6 )

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ x] Android

#### Additional informatin on the environment
Rooted Android tv box.

## Debug log

[https://pastebin.com/7FAaa3zS]

## Other information

Fresh install with inputstream adaptive enabled.
Thank's for the help.

**Comment by caphm** [comment]
The background services of the addon haven't started yet. Wait a little after starting Kodi and it'll work.

**Comment by Nux007** [comment]
Thank's for the help, will give it a try this week end ....
