### ISSUE TITLE
Login always fails if credentials are saved from previous run

### ISSUE THREAD

**Issue by ksl1989** [asciidisco/plugin.video.netflix#421]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General ~~infomration~~ information

Whenever I try to open the add-on, having used it on a previous run, login always fails with a login error and a message to check credentials.

### Prerequisites

* [x] Are you running the latest version?

### Description

Whenever I try to open the add-on, login always fails with a login error and a message to check credentials. If I logout in the settings and try to open the add-on again, sometimes it'll ask for the login information, sometimes still throw an error. If I reboot after logging out, when I open the add-on it just works, showing the profiles in the account (sometimes it still gives an error once or twice before finally opening). I can open the add-on as many times as I want after that  and it always works, but if reboot it goes back to failing to login

### Steps to Reproduce

Process shown in the log:
1. Boot OSMC and open the add-on. Result: login fails with message to check credentials.
2. Repeat several times. Same result.
3. Go in to the settings and choose "logout".
4. Try to open the add-on again. Result: fails again, now there is no message mentioning credentials.
5. Repeat several times. Same result.
6. Reboot the device (still not having been able to login).
7. Try to open the add-on again. It asks for the login information. I input the login information. It shows the loading wheel for a while and then gives an error.
8. I try to open the add-on again. It works normally, showing the profiles in the account.
9. Browse through the options. No issue.
10. I pick and episode. It informs there's a Widevine update, I let it update (unrelated to the issue).
11. When the update succeeds the loading wheel runs for a while and stops. The video doesn't start.
12. Pick different shows, and episodes. Same result. (I believe this is a different issue, I will submit a new issue about it when the login issue is fixed.)
13. Re-open the add-on several takes. Chose different folders, shows and episodes. Same result: add-on opens normally, no video actually plays.
14. Reboot the device.
15. Try to open the add-on. We're back at the beginning: login fails with message to check credentials.

**Expected behavior:** [What you expected to happen]

Login works after rebooting the device.

**Actual behavior:** [What actually happened]

Login doesn't work after reboot.

## Context (Environment)

KODI 18 Leia, OSMC alpha 17.8-258 (and five previous nightlies, always with the same result) on Raspberry Pi 3.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

## Debug log

[Attached](https://github.com/asciidisco/plugin.video.netflix/files/2152018/kodi.log)

## Other information

* The videos rarely play but occasionally they have started, although streaming very slowly and stopping several times a minute even in the worst quality. This should be unrelated and is not part of this issue. When the login is working I'll submit an issue about the streaming if the problem remains.

**Comment by Chantaz** [comment]
Same here. Tried #707 build and #629. Nothing helps.

If I install the plugin, Im able to login but not play any episode. If i restart the device, login fails...

**Comment by Chantaz** [comment]
Same here. Tried #707 build and #629. Nothing helps.

If I install the plugin, Im able to login but not play any episode. If i restart the device, login fails...

**Comment by Chantaz** [comment]
Same here

**Comment by ivantot2** [comment]
SAME

**Comment by liberty-developer** [comment]
duplicate to #438
