### ISSUE TITLE
Black screen, no audio playing on RK3328

### ISSUE THREAD

**Issue by mo123** [asciidisco/plugin.video.netflix#424]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?
Yes

**Actual behavior:** Black screen and no audio playing

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

Log
https://pastebin.com/ETx0z9GF

**Comment by liberty-developer** [comment]
There will be lot of media not playing on widevine L3 devices.
Have you set "Override HDCP" in inputstream.adaptive settings? If so, you shouldn't

**Comment by mo123** [comment]
Hi

I tested on a Widevine L1 device now.
If I open any stream, the addon just shows an error.
https://pastebin.com/XVKU86pZ

Any solution perhaps?

**Comment by mo123** [comment]
Also tried on a Widevine L1 device.
Device has HDCP 2.2 and Overwrite HDCP was not set.
After logging in it just loads for hours with a spinning circle and nothing happens.
Also tried - https://github.com/asciidisco/plugin.video.netflix/archive/d01c7835bda635f84e9ca168514772f5746770f3.zip

**Comment by caphm** [comment]
The ffmpeg video-decoder used by Kodi does not support cryptosessions:

> 17:44:55.694 T:18446744072874494240   ERROR: CDVDVideoCodecFFmpeg::Open() CryptoSessions unsuppoted!
> 17:44:55.694 T:18446744072874494240   ERROR: CVideoPlayerVideo::OpenStream - could not open video codec
> 17:44:55.695 T:18446744072874494240 WARNING: OpenStream - Unsupported stream 1. Stream disabled.

Switch to a different decoder/player backend to enable encrypted video streams.
