### ISSUE TITLE
No possibility to play videos in 1080p, smaller resolutions works fine

### ISSUE THREAD

**Issue by km4lin** [asciidisco/plugin.video.netflix#425]
*I'm submitting a ...*
  - [X] bug report

### Prerequisites

* Are you running the latest version?
Yes

### Description

I can't play a videos in 1080p. Some of them in manual video mode have possibility to play in several resolutions up to 720p but some of them for example up to 480p. There's no option for play a video in 1080p. I will be glad for any help.

### Steps to Reproduce

1. Run Kodi
2. Go to Netflix Addon
3. Play some video

**Expected behavior:** [What you expected to happen]

Play video in 1080p

**Actual behavior:** [What actually happened]

No option to play video in 1080p, only in smaller resolutions like 720p or 480p.

### Installation
* [X] I´m using the Netflix Repo

### Operating System
* [X] Windows (x86/x64)

#### Additional informatin on the environment

Kodi v. 18.0 Alpha 2

## Debug log

https://pastebin.com/qiVByQhb

## Other information

I have no problem with playing 1080p in Kodi YouTube Add-on and no problem with playing 1080p on Netflix Windows App so it is not system or hardware fault I think. I have made screenshots with settings etc.

### Screenshots
![n2](https://user-images.githubusercontent.com/24846265/42654551-48efc140-8619-11e8-8be9-e200e2489d17.png)
![n3](https://user-images.githubusercontent.com/24846265/42654552-491755fc-8619-11e8-8797-3e47539f5340.png)
![n4](https://user-images.githubusercontent.com/24846265/42654553-49435c88-8619-11e8-8107-385b0bca6cea.png)
![n5](https://user-images.githubusercontent.com/24846265/42654554-496a453c-8619-11e8-9a98-d056f92aebc0.png)

### UDPATE: I have been tested whole procedure on other PC - the same problem.

**Comment by maxcr** [comment]
read the million other threads about the same thing. Because we're saying "hey were using software encoding" neflix is saying "sucks to suck buy one of our Netflix certified devices."

https://github.com/asciidisco/plugin.video.netflix/issues/277

I suggested a possible "hack" or workaround.

**Comment by maxcr** [comment]
nvm I'm on linux. All I did was crank up minimum bitrate to 99999999 in libinput and everything is dankles now.

**Comment by Borromini** [comment]
@maxcr When you're referring to libinput, are you talking about the Inputstream Adaptive settings like in the screenshots above?

**Comment by caphm** [comment]
Closing this, as it's an inputstream issue.

**Comment by dagwieers** [comment]
There was a bug in **inpustream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259
