### ISSUE TITLE
 Yet-another script.module.pycryptodome error and 5.1 audio request

### ISSUE THREAD

**Issue by sheldonmaschmeyer** [asciidisco/plugin.video.netflix#426]
*I'm submitting a ...*
  - [X] feature request
  - [X] support request

## General infomration
Support issue: On Manjaro-arch Linux. having the script.module.pycryptodome error. It is installed (pip install pycryptodomex - in /usr/lib/python3.6/site-packages/) . I tried creating a symbolic link, still no luck. Is there an easy solution yet?

Feature Request: I know that 5.1 audio is only supported in the Windows 10 app (not the Chrome browser); someday (without waiting for Netflix themselves) might 5.1 audio be available using this plugin? More convenient than re-booting into Windows.

* [Yes ] Are you running the latest version?

**Comment by sheldonmaschmeyer** [comment]
I have both python2.7 and python3 on my system. I have installed pycryptodomex from the AUR and pip
sudo python2.7 /usr/bin/pip install pycryptodomex
Requirement already satisfied: pycryptodomex in /usr/lib/python2..7/site-packages (3.6.3)
I have also noticed that some distros use dist-packages instead of site-packages which also could be causing the error. The log is not specific.
From kodi.log :
12:24:27.804 T:139747701317888   DEBUG: ------ Window Deinit (DialogSelect.xml) ------
12:24:27.806 T:139747701317888   DEBUG: CAddonInstaller: installing 'plugin.video.netflix' version '0.13.10' from repository 'repository.netflix'
12:24:27.828 T:139747247400704   DEBUG: CAddonInstallJob[plugin.video.netflix]: requires script.module.pycryptodome version 3.4.3 which is not available
12:24:27.829 T:139747247400704   ERROR: CAddonInstallJob[plugin.video.netflix]: The dependency on script.module.pycryptodome version 3.4.3 could not be satisfied.
12:24:27.858 T:139747701317888   DEBUG: CGUIMediaWindow::GetDirectory (addons://repository.netflix/xbmc.addon.video)

**Comment by knappster1** [comment]
Just a disclaimer that I don't really know anything about this and I am just throwing ideas out there.  In case it helps, my pycryptodomex is version 3.4.3 which is what your log says is required.  Maybe it will not work with 3.6.3 which you appear to have installed.

**Comment by sheldonmaschmeyer** [comment]
That is a good hypothesis, I git cloned the repository, changed 3.4.3 to 3.6.3 
addon.xml:    <import addon="script.module.pycryptodome" version="3.6.3"/>
requirements.txt: pycryptodomex==3.6.3
But, when I do make, encounter an error:
$ make
find . -name '*.pyc' -exec rm {} +
find . -name '*.pyo' -exec rm {} +
rm -rf ./report || exit 0
mkdir ./report
rm -rf ./_build || exit 0
rm ./.coverage || exit 0
rm: cannot remove './.coverage': No such file or directory
rm -rf ./coverage || exit 0
mkdir ./coverage
flake8 --filename=./addon.py ./service.py ./setup.py ./resources/lib/utils.py ./resources/lib/MSLHttpRequestHandler.py ./resources/lib/NetflixHttpRequestHandler.py ./resources/lib/Navigation.py ./resources/lib/kodi/Dialogs.py
./resources/lib/Navigation.py:268:9: E722 do not use bare 'except'
./resources/lib/Navigation.py:430:80: E501 line too long (83 > 79 characters)
./resources/lib/Navigation.py:808:80: E501 line too long (89 > 79 characters)
make: *** [makefile:41: lint] Error 1

**Comment by knappster1** [comment]
@sheldonmaschmeyer, I am not quite sure what you did.  Did you clone the netflix addon repository or the pycryptodomex repository?  The addon does not need to be compiled.  I am pretty sure that you could just go into the addon code already installed on your machine and try to change that code and relaunch kodi.  If it bombs the addon, then you can probably just reinstall.  However, rather than trying to modify the Netflix addon, you could try to install pycryptodomex 3.4.3
Here is the PKGBUILD I used back in April when I compiled it:
https://drive.google.com/open?id=1rmGSF47AKL6q0BFt7m2rWU_yl5vlLL65
If you download it into a folder and then run
`makepkg`
It should compile into a package named "python2-pycryptodomex-3.4.3-1-x86_64.pkg.tar.xz"
And you should then be able to run
`sudo pacman -U python2-pycryptodomex-3.4.3-1-x86_64.pkg.tar.xz`

**Comment by sheldonmaschmeyer** [comment]
I tried with 3.4.3 but same error
Installing collected packages: pycryptodomex
  Found existing installation: pycryptodomex 3.6.3
    Uninstalling pycryptodomex-3.6.3:
      Successfully uninstalled pycryptodomex-3.6.3
  Running setup.py install for pycryptodomex ... done
Successfully installed pycryptodomex-3.4.3

**Comment by sheldonmaschmeyer** [comment]
It is working on my better laptop using Kodi 18 nightly build and Ubuntu 18.04. So, will try again later on tablet using the Kodi nightly build (seems to work better). The audio is in 5.1 Surround :-) Kodi is brilliant, ideal media centre setup.

**Comment by knappster1** [comment]
@sheldonmaschmeyer what version of pycryptodomex is on Ubuntu 18.04?

**Comment by sheldonmaschmeyer** [comment]
3.6.4 on 18.04.
It is likely that the version of Kodi 18 I was using is not as good as the latest (unstable) nightly build. So, uninstalled old version and installing latest version (at 44%, takes a long time to install on tablet but has a Cherry Trail CPU).

**Comment by sheldonmaschmeyer** [comment]
On Manjaro-Arch, kodi 18.0a2.r328.gc8fc7e3140c-1 is still not detecting pycryptodomex

**Comment by sheldonmaschmeyer** [comment]
Fixed it! I had to manually delete, using sudo, the inputstream-adaptive plugin (all traces), then pacaur -S kodi-addon-inputstream-adaptive-18-git 
It seems to be a permissions issue. May need to chown the kodi directories. 
Both /usr/lib/kodi/addons and /usr/share/kodi/addons

**Comment by knappster1** [comment]
I am glad to hear you figured it out and thanks for sharing your progress in case others experience the same issue.
