### ISSUE TITLE
FireTV 4K Kodi quits when starting video

### ISSUE THREAD

**Issue by xciser77** [asciidisco/plugin.video.netflix#433]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
I installed a clean nightly of Kodie 18 and the latest plugin version (0.13.10). I can login, can select a video, but when i supposed to start Kodi quits and I get the main screen of the amazon fire tv.

### Prerequisites

* [x] Are you running the latest version?

### Description
Kodi quits when video is supposed to start

### Steps to Reproduce
1. Start Netflix plugin
2. Select Account
3. Select video to play

**Expected behavior:** [What you expected to happen]
I expect the video to start playing

**Actual behavior:** [What actually happened]
Kodi quits to the main menu of the Fire TV

## Context (Environment)
Amazon Fire TV 4K, Fire OS 5.2.6.3
Kodi 18 build 30-7
Plugin 0.13.10

### Installation
Did a clean install of Kodi 18 and only installed the Netflix plugin
* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional information on the environment
I am using a Fire TV 4K from 2017 with the 32 bits version Kodi 18

## Debug log

[kodi log](https://www.dropbox.com/s/are7kdwjlqcqyi0/kodi.log?dl=0)

**Comment by caphm** [comment]
The issue lies within `inputstream.adaptive` failing to initialize the stream:

> DEBUG: AddOnLog: InputStream Adaptive: Entering encryption section
> DEBUG: AddOnLog: InputStream Adaptive: Successful instanciated media_drm: 0xad8aa810, deviceid: , systemId: 6331 security-level: L1
> DEBUG: AddOnLog: InputStream Adaptive: Initializing stream with KID: 0000000003F8366A0000000000000000
> ERROR: SOCK: Error selecting socket(s)
> ERROR: ES: Exception caught while listening for socket
> NOTICE: ES: UDP Event server stopped

Please raise the issue at https://github.com/peak3d/inputstream.adaptive, netflix addon works fine.

**Comment by liberty-developer** [comment]
1.) adb logcat -c before starting the stream
2.) adb logcat -d | pastebinit after kodi has crashed.

**Comment by caphm** [comment]
Still looks like it's a widevine or inputstream.adaptive internal error:

> java.lang.NoSuchMethodError: no non-static method "Landroid/media/MediaDrm$KeyRequest;.getRequestType()I"

> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #12 pc 00061dbc  /data/app/org.xbmc.kodi-1/lib/arm/libssd_wv.so (_ZN3jni7details16call_jint_methodEP7_JNIEnvP8_jobjectP10_jmethodIDz+52)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #13 pc 0004fd7c  /data/app/org.xbmc.kodi-1/lib/arm/libssd_wv.so (_ZN28WV_CencSingleSampleDecrypter16KeyUpdateRequestEb+324)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #14 pc 00053e10  /data/app/org.xbmc.kodi-1/lib/arm/libssd_wv.so (_ZN11WVDecrypter27CreateSingleSampleDecrypterER14AP4_DataBufferPKcPKh+184)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #15 pc 00062fc0  /data/app/org.xbmc.kodi-1/lib/arm/libinputstream.adaptive.so (_ZN7Session10initializeEv+4492)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #16 pc 000663d0  /data/app/org.xbmc.kodi-1/lib/arm/libinputstream.adaptive.so (_ZN20CInputStreamAdaptive4OpenER11INPUTSTREAM+2520)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #17 pc 00c228f8  /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so (_ZN17CInputStreamAddon4OpenEv+1088)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #18 pc 00c91340  /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so (_ZN12CVideoPlayer15OpenInputStreamEv+464)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #19 pc 00c93fd8  /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so (_ZN12CVideoPlayer7PrepareEv+312)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #20 pc 00c95670  /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so (_ZN12CVideoPlayer7ProcessEv+56)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #21 pc 00f221b8  /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so (_ZN7CThread6ActionEv+40)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #22 pc 00f214f4  /data/app/org.xbmc.kodi-1/lib/arm/libkodi.so (_ZN7CThread12staticThreadEPv+212)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #23 pc 00016707  /system/lib/libc.so (_ZL15__pthread_startPv+30)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   native: #24 pc 00014637  /system/lib/libc.so (__start_thread+6)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289]   (no managed stack frames)
> 
> F/art     ( 5341): art/runtime/runtime.cc:289] Pending exception java.lang.NoSuchMethodError thrown by 'unknown throw location'
> 
> F/art     ( 5341): art/runtime/runtime.cc:289] java.lang.NoSuchMethodError: no non-static method "Landroid/media/MediaDrm$KeyRequest;.getRequestType()I"

**Comment by azbesthu** [comment]
Same error with unofficial hbo go addon. 
Leia Alpha1 was ok, Alpha2 and Beta1 also broken.

**Comment by caphm** [comment]
Not an addon issue

**Comment by azbesthu** [comment]
Peak3d suggested to bump version check for import in this addon
https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/MSL.py#L30
