### ISSUE TITLE
Login Failed - Please Check your Credentials

### ISSUE THREAD

**Issue by joaosagrath** [asciidisco/plugin.video.netflix#435]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Login Failed - Please Check your Credentials

### Prerequisites

* [x] Are you running the latest version?
0.13.10

### Description
In a clean instalation, netflix don't connect. I've triple check mey credentials (Login and Password), and there's no sucess on onnect. 
The message is:  Login Failed - Please Check your Credentials

### Steps to Reproduce

1. [clean install kodi]
2. [install netflix add-on]
3. [open netflix add-on]
4. [input login (email)]
5. [input password]
6. [error]

**Expected behavior:** Connect to netflix

**Actual behavior:** Not connect

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment
Windows 10 full updated

## Debug log
https://pastebin.com/NpCEREEr

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by gibso** [comment]
hey guys, 

i just ran into the same problem on linux (Ubuntu).
I deleted the addon folder in userdata, after that i could successfully login.
So try to delete the folder `kodi/userdata/addon_data/plugin.video.netflix`

good luck :-)

**Comment by joaosagrath** [comment]
For me it's not work, since I've made a clean install of kodi.

**Comment by rfrayer420** [comment]
Same here using Libreelec Milhouse

**Comment by joaosagrath** [comment]
Tried today in another machine, again, clean install, same bug. Now I have 1 machine working, and 1 machine not working. WTF???

**Comment by Hutti** [comment]
Hy all,

so I checked this again today with more sleep :)

First I tried the solution from gibso, but had no luck. Second I compared the files in the directory before and after I followd this solution. So I found only the settings.xml is changing slightly, only the service ports. So I searched the web and found an older [bug report](https://github.com/asciidisco/plugin.video.netflix/issues/155) which pointed me to the ESN.
I tried to figure out what this is, without any luck. But I the info that this is generated by netflix itself. Now try to get it.
The only solution I found were to install the netflix app on my android phone and logged in my account. Here I found under "More" (in german "Mehr") and "App-Settings" (in german "App-Einstellungen"), the categorie Info, where the ESN is. My one is "NFANDROID1-PRV-P-L3-HTC==M8-and-then-many-a-long-hex-number". So I copied only the hex number in the "settings.xml" on the RPi3, typed in my e-mail and password and reboot the RPi3.
Login is working, but **no video** is playing. 
I don't know exactly what this means for the plugin or netflix, I am only an administrator and no coder :)

Hope this is helping.

**Comment by toskium** [comment]
I have the same issue with 0.13.10 and libreelec 8.90.003 however it worked once. I was able to log in and browse videos, unfortunately no more. What is interesting is that Netflix recognized the login and sent me an email about. However no more logins are possible since then. I tried changing the ESN according to Hutti's suggestion but without any success.

**Comment by Thunderbird2086** [comment]
I was able to login after I changed language to Japanese or Korean on Netflix website.

**Comment by Thunderbird2086** [comment]
It seems to be fixed magically since I am able to login successfully after changed language back to English from Netflix website.

**Comment by toskium** [comment]
@Thunderbird2086 unfortunately this does not work out for me.

**Comment by hstamas** [comment]
There was a good amount of talk concerning this add-on over on the KodiNerds forum. Unfortunately its all in German. I was able to decipher a few messages stating that they figured out a workaround and in trying it, its working for me as of right now. Give this a try:

- Uninstall the add-on.
- Reinstall, via the repository the oldest/very first version
- Try logging in (most likely will fail).
- Update to the newest release
- Try logging in again - it worked for me this time and I am able to play content.

**Comment by toskium** [comment]
@hstamas hah! Thank you very much, this actually worked!

**Comment by EatonEmmerich** [comment]
@hstamas did not work for me.

**Comment by essam315** [comment]
Try this, uninstall Kodi from windows 10 and choose "Yes, I am sure and grant permission to also delete the profile folder” when you uninstalling the program.

Then install Kodi and don't run it.

Copy this "Kodi" folder to 

C:\Users\<USERNAME>\AppData\Roaming

https://mega.nz/#!JkN1TITY!y6k0rZ2eDmf-ftDJRl69jRySkKL6BQPTPb63OaZznWo

Run Kodi and enter your email and password and play Netflix videos.

**Comment by essam315** [comment]
Try using this modified release, uninstall Kodi and choose “Yes, I am sure and grant permission to also delete the profile folder” when you uninstalling the program.
Re-install Kodi and install the add-on.

https://mega.nz/#!U9UDWIDa!WfEUUgPwKzBqXG7OLIwW2e34lE5zdR6Aldx1D4XjLX4

**Comment by allcolor** [comment]
I'm using kodi on windows 10... to make it work again, I've copied the ESN from the netflix windows application (you can see it in parameters) and put it in the settings.xml, restarted kodi and it's working again.

**Comment by caphm** [comment]
Seems like Netflix changed something on their end. I have created a PR #441 that should fix the issue.

You can try the fix by installing from this zip file: https://github.com/asciidisco/plugin.video.netflix/archive/d01c7835bda635f84e9ca168514772f5746770f3.zip

**Comment by liberty-developer** [comment]
I have commented the PR

**Comment by liberty-developer** [comment]
duplicate to #438

**Comment by evansste12432** [comment]
I installed using the latest .zip file, which was described above.  However, I'm still getting an error.  It simply says "check the log for more information".  I've uploaded the log to http://ix.io.1MwF, and have pasted it with this post.  Any ideas what the problem may be?  Is there a newer .zip file for me to install?

Thanks for your time, and I appreciate any guidance.
[Error Log.txt](https://github.com/asciidisco/plugin.video.netflix/files/3317110/Error.Log.txt)

**Comment by shockalotti** [comment]
I'm getting the same issue on Raspberry Pi 2

**Comment by evensure** [comment]
What worked for me on my Raspberry Pi with OSMC was updating the plug-in to the newest version and then updating the dependencies, too . Actually it was only one, I believe the one listed just below input stream helper, that was out of date.
