### ISSUE TITLE
Netflix login error

### ISSUE THREAD

**Issue by ivantot2** [asciidisco/plugin.video.netflix#438]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [/] support request

### Prerequisites

* [/] Are you running the latest version?

### Description\
i installed OSMC on raspberry pi
im having a wrong credentials error even tho its correct (cause ive tried a thousan times on other devices)
I had the chance to login once, selected a video, installed widevine but after installation it still wont play.
so i restarted. then tried to open the add on, it prompted a login, then the "wrong credential" problem went back

### Steps to Reproduce

1. login to netflix
2. it will say wrong credentials even if its correct 

**Expected behavior:** let me watch netflix

**Actual behavior:** credential problem

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [/] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [/] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

raspberry pi 3B
16 gb sd card
OSMC operating system

## Debug log

i uploaded the log here
[kodi.old.log](https://github.com/asciidisco/plugin.video.netflix/files/2259414/kodi.old.log)
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/2259415/kodi.log)

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by jonaslindert** [comment]
same here

**Comment by Slartibartfast27** [comment]
Same issue on my system:

- Windows 10
- Kodi 18.0 Alpha 3
- plugin.video.netflix 0.13.10

Worked before exactly 1 times. Failing after restart of Kodi. Also entered my credentials 1000 times, cleared and reinstalled plugin. Nothing working. Always get false error message "Login failed".

Any tipps what to reset/clear/do/... ?

Kodi debug log attached.
[kodi.log](https://github.com/asciidisco/plugin.video.netflix/files/2259617/kodi.log)

**Comment by fmeneuhe** [comment]
Same here on LibreELEC 9.0

**Comment by Thunderbird2086** [comment]
Probably same issue as #435 ?

**Comment by gservat** [comment]
Using latest libreelec milhouse build. Got the same issue. Tried a bunch of older versions to see if any of them worked, and none of them did. I then upgraded to the latest again (0.13.10) and I managed to log in!?

**Comment by essam315** [comment]
Try using this modified release, uninstall Kodi and choose “Yes, I am sure and grant permission to also delete the profile folder” when you uninstalling the program.
Re-install Kodi and install the add-on.

https://mega.nz/#!U9UDWIDa!WfEUUgPwKzBqXG7OLIwW2e34lE5zdR6Aldx1D4XjLX4

**Comment by Saski24** [comment]
Same here, CoreELEC 8.95.0

**Comment by marduklev** [comment]
i just switch account, give in credentials, and its working fine again to me...

**Comment by caphm** [comment]
Seems like Netflix changed something on their end. I have created a PR #441 that should fix the issue.

You can try the fix by installing from this zip file: https://github.com/asciidisco/plugin.video.netflix/archive/d01c7835bda635f84e9ca168514772f5746770f3.zip

**Comment by essam315** [comment]
@caphm
Thank you, your fix working fine, could you please check if you can help in fixing this problem here?

https://github.com/asciidisco/plugin.video.netflix/issues/365

**Comment by essam315** [comment]
@caphm
Thank you, the fix is working fine.

**Comment by ivantot2** [comment]
the fix didnt work for me, i uninstalled netflix then installed what u gave @caphm 
is there something im missing?

**Comment by essam315** [comment]
@ivantot2
Try is updated one

https://mega.nz/#!FsVEFQAJ!SGUnrAWn1iqrmiWVdubyYfDZbqpnDr1rsHP5rV4yRbM

Uninstall Kodi and make sure to choose:

“Yes, I am sure and grant permission to also delete the profile folder”
when you uninstalling the program.

Download the latest version of Kodi 18 nightly install Kodi and the plugin

**Comment by cavepopo** [comment]
I can successfully login but after a chromeos dl and update I can play anything, it looks like it is starting but nooooo....

Still on Rpi3b+ + 803 build of milhouse.

**Comment by essam315** [comment]
@cavepopo 
Try to restart Kodi, or use this version and the playback will work fine without the need for restarting Kodi

https://mega.nz/#!MsNRlA5T!Y9CBfYtlnZKIHd5EY1OmV30_r0ZlE-6NfeOk6nCueKc

Uninstall Kodi and make sure to choose:

“Yes, I am sure and grant permission to also delete the profile folder”

when you uninstalling the program.

Download the latest version of Kodi 18, install Kodi and the plugin.

**Comment by caphm** [comment]
Can't help you without a debug log guys. Please always provide a debug log in order to get support.

@ivantot2: I have amended the PR to fix the login issues, because Netflix seems to be operating in mixed mode. Try by installing https://github.com/asciidisco/plugin.video.netflix/archive/ce6043fe4b347ab566fac35c3923128c74ace8e6.zip and please post a debug log if it doesn't work.

**Comment by caphm** [comment]
You'll have to address this to Netflix, as they are the ones making changes to their Website/API. It's not a stability issue with the addon: Once there is a change on Netflix's side, it may break addon functionality until one of the maintainers/other contributors adapts the code to these changes.

So yes, if Netflix decides to change stuff about their API every other day, you will need a new patch for this as well.

That's how it works when you're using a non-official client/addon and it's not going to change in the future.

**Comment by rfrayer420** [comment]
Yeah I think I'm cancelling my Netflix subscription. Hats off to the maintaner of this plugin but I don't think anyone could possibly keep up with the way Netflix changes there API every 2 days. Rumor has it they are doing it to intentionally keep people from using these plugins.

**Comment by nidrosianDeath** [comment]
Can confirm that the zip @caphm linked to fixes the login problem at pi3+ w/ LibreELEC 8.90..003.

Seems like the getwidevine.sh script doesn't get the newest version though, but that's probably related to something else. Worked fine streaming after a newer version was downloaded from a Chrome OS binary and whatnot, luckily everything was automated so basically just to click ok to accept the download and after a few minutes it was all working (remember to reboot after the widevine is updated!).

**Comment by MilhouseVH** [comment]
As the author of `getwidevine.sh`: Stop using the `getwidevine.sh` script - it is no longer maintained and was only provided as a short term solution when the inputstream functionality was initially developed.

You should now be using the  `script.module.inpustreamhelper` add-on which does a much better job of installing the latest `libwidevinecdm.so` binary and keeping it up to date.
