### ISSUE TITLE
Netflix does not turn on and off

### ISSUE THREAD

**Issue by ozkaradag** [asciidisco/plugin.video.netflix#439]
Greetings,

I got a Netflix account, I made all the settings.
But it does not open error.

I do not know where the problem is.

I've added log files.

https://drive.google.com/open?id=1r3r4PohLUfx93rKta4ZhVKshlGMKfqGo
https://drive.google.com/open?id=1w4gnfmmWhILR6FD8T97DhD5Emlxcljdg

Thanks in advance.

Best regards...

**Comment by caphm** [comment]
You have non-ascii characters in your password. Change it to only contain ascii-compatible characters and it should work fine.

**Comment by ozkaradag** [comment]
Greetings,

It solved.

Thank you.

Best regards...
