### ISSUE TITLE
Widevine CDM is Unfortunately not available on this system archirecture

### ISSUE THREAD

**Issue by hwarang098tkd** [asciidisco/plugin.video.netflix#445]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Netflix add on cant play videos.
When i select any video --->Messages
1) "this add-on relies on the proprietary decryption module Widevine CDM for playback."
I pressed "install"
2) Error:"Widevine CDM is Unfortunately not available on this system archirecture"
3)Playback Failed

Rasp Zero 
LibreELEC (official) 8.90.003
Build Kodi 18.0-ALPHA3 git:269a24c

**Comment by MilhouseVH** [comment]
This isn't a bug, it's a fact - there is no ARMv6 widevine binary available.

Besides, the single-core ARMv6 processor in the RPi0/RPi1 cannot software decode Netflix video fast enough, so even if a widevine binary became available for ARMv6 you still wouldn't be able to watch videos without major stuttering (probably a few frames per second).

**Comment by hwarang098tkd** [comment]
Thnx .

**Comment by centuralcreations** [comment]
a widevine for Rasbian is now avaiable in the default repo, but I cannot manage to get past this error message even after installing it. Is this version of widevine need some sort of modification in the netflix plugin to use it?
