### ISSUE TITLE
Errno 111 Connection Refused on LibreElec nightly

### ISSUE THREAD

**Issue by Cyberwizzard** [asciidisco/plugin.video.netflix#446]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

Connection denied

### Steps to Reproduce

1. Open Netflix addon

**Expected behavior:**

Netflix content list

**Actual behavior:**

Error popup saying the logs should have more info.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec nightly build from 18.08.2018 for RPi2/RPi3

Also I applied the patch from #441 to get around the invalid credentials issue.

## Debug log

https://pastebin.com/sUGJCRFP

**Comment by Arpris** [comment]
You can use the patch from #438 : 
https://github.com/asciidisco/plugin.video.netflix/archive/d01c7835bda635f84e9ca168514772f5746770f3.zip

**Comment by caphm** [comment]
The background services of the addon have not started yet. Wait a little after starting Kodi and it'll work.
