### ISSUE TITLE
Movies not playing with 0.13.11

### ISSUE THREAD

**Issue by essam315** [asciidisco/plugin.video.netflix#448]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

When i try to play a movie with the release 0.13.11 i get error message, but when i try to play a TV episode it works fine.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Windows 10, Kodi 18 Leia Beta

## Debug log

https://pastebin.com/Zw2ZT5c0

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

https://image.ibb.co/ggxhxe/error.png

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
Netflix doesn't seem to return a property for all media, which produced a KeyError. Fixed in 0.13.12.
