### ISSUE TITLE
Movie playback error

### ISSUE THREAD

**Issue by janstafa** [asciidisco/plugin.video.netflix#449]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x ] Are you running the latest version?

### Description

Not able to watch any film, tv shows are ok. Movies wont start and error message is shown

### Steps to Reproduce

1. Try to watch any movie
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

libreelec 8.90.003 generic x86_64
* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://pastebin.com/Jrx9aSDp

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by essam315** [comment]
Use 0.13.12, this problem has fixed in it, I'm using 0.13.12 in windows 10 and i can confirm this problem is gone.

**Comment by ilancoll** [comment]
Not play In liberelc 9 , it login and can view the menu , but it is not play the movie

**Comment by caphm** [comment]
You are not using the latest version. This is fixed in 0.13.12.
