### ISSUE TITLE
Error: "Model device mismatch" no playback

### ISSUE THREAD

**Issue by mrfixit2001** [asciidisco/plugin.video.netflix#450]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

I can successfully login to Netflix and browse the list of movies and shows, but nothing will play. There are no errors, it just tries and then immediately stops. Here is a portion of the debug log showing the relevant error:

DEBUG: [Netflix] Error getting license: {"result": {"errorDetails": "No Details Available", "errorSubCode": 1331, "errorExternalCode": "P7", "errorDisplayMessage": "", "errorEdgeCode": 3057, "data": {"CODE": 3057, "ERROR_NAME": "ModelDeviceMismatch", "DRM_LICENSE_TYPE": "standard", "REQUEST_CONTEXT_COUNTRY": "US", "REQUEST_CONTEXT_APP_ID": 0, "CLIENT_RETRYABLE": "false", "LOCAL_MESSAGE": "Model device mismatch", "REQUEST_CONTEXT_ESN": "NFCDCH-LX-ENMW3UGR7DT2NKGUPGT70Y8J0V02MY", "REQUEST_CONTEXT_STACK": "prod", "REQUEST_CONTEXT_DEVICE_TYPE_ID": 1223, "SUCCESS": false, "ROOT_CAUSE_STACK_TRACE": "Not available.", "REQUEST_CONTEXT_CLIENT_ID": "cd8d8cec-c31d-4468-95e0-40e19028ffc8", "REQUEST_CONTEXT_ENVIRONMENT": "prod", "DESCRIPTION": "com.netflix.pbl.error.PblException: Model device mismatch\n\tat

I have tried clearing the ESN and restarting, that didn't resolve. I have also tried copying the ESN from another device, that didn't resolve either.

To provide complete logs of the issue, I started fresh and I deleted widevine and let it download again so you could see the full log of the entire process from widevine install to the error. It's too long for one pastebin so I had to split it into two.
Here's the log:
Part 1 - https://pastebin.com/cAZSTLY4
Part 2 - https://pastebin.com/dNdSzpB9

You might see a few extra unfamiliar log lines that I've added here and there when debugging, just ignore them.

I'm especially curious to understand how it selects which of those chromeos images to download, I want to be sure it's getting the right one. I am using a Linux BuildRoot environment with a 32-bit userland and 64-bit kernel. I have ensured that the installed widevine library is detected as ARM and not AARCH64, although technically both should work with this environment. I have actually tried both but get the same error.

**Comment by essam315** [comment]
Try using 0.13.12 the problems with ESN has fixed in it, at least for me with windows 10, use the latest version of Kodi v18 "Leia" nightly.

**Comment by essam315** [comment]
Try using 0.13.12, the problems with ESN have fixed in it, use the latest release of Kodi 18 nightly.

**Comment by mrfixit2001** [comment]
Latest version resolves this, but different issue now. Closing this and opening new issue.
