### ISSUE TITLE
plugin.video.netflix needs symlink to find inputstream.adaptive

### ISSUE THREAD

**Issue by RobVerduijn** [asciidisco/plugin.video.netflix#451]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [ ] support request

## General information
Running on Fedora 28 x86_64 kodi 18 last git version and inputstream.adaptive 2.2.25
### Prerequisites

* [X ] Are you running the latest version?
yes

### Description
For some reason plugin.video.netflix did not find my inputstream.addaptive installation
After creating a symlink in /usr/lib64/kodi the plugin was found and everything worked.

workaround details:
cd /usr/lib64/kodi
ln -f -s ../../share/kodi/addons addons
and all works again.

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
plugin.video.netflix finds the inputstream.addaptive plugin without the symlink

**Actual behavior:** [What actually happened]
plugin.video.netflix does not find inputstream.addaptive plugin without the symlink

## Context (Environment)
fedora 28 x86_64
kodi 18 (todays git checkout)
inputstream.adaptive 2.2.25

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
That's odd. inputstream.adaptive comes with the default Kodi installation, so the addon should not reside in the application data folder, but within the installation folder.

Could you provide a debug log please?

**Comment by asciidisco** [comment]
I´d rather suggest to close this issue here & reopen it on https://github.com/peak3d/inputstream.adaptive as this is rather likely a problem not directly related to this plugin

**Comment by RobVerduijn** [comment]
I compiled kodi 18 from source from the github repo (https://github.com/xbmc/xbmc), it works fine but there was no default input.stream adaptive in the source, so I manually compiled and added it (https://github.com/peak3d/inputstream.adaptive) and then it lands in the datadir (/usr/share/kodi/addons)

I guess I use the wrong branch (master) from the kodi github repo.

**Comment by caphm** [comment]
There you go, seems like the install procedure is slightly off when compiling from source.

**Comment by RobVerduijn** [comment]
I refactored my compilation script and now it lands in /usr/lib64/kodi/addons

Cheers
