### ISSUE TITLE
Does not keep the Subtitle settings

### ISSUE THREAD

**Issue by welldonesp** [asciidisco/plugin.video.netflix#459]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Does not maintain subtitles settings

### Prerequisites
Kodi 18 Beta
* [x] Are you running the latest version?

### Description
When I activate the subtitles and set the language and request to apply to all media, it does not keep the configuration.

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
Play the video

2. [Second Step]
Configure the subtitle settings and apply to all media

3. [and so on...]
Play another video

**Expected behavior:** [What you expected to happen]
Play all videos with subtitiles

**Actual behavior:** [What actually happened]
You must configure the subtitile for each video

## Context (Environment)
Windows 10
Kodi 18 Beta
Netflix 0.13.12

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
The "apply to all media" button is a built-in Kodi function and has nothing to do with the addon's functionality to remember subtitles across episodes of a show.
To use this, you need to export the show to your library. It currently does not work with shows that are not in the Kodi library. Then, while watching an episode, select a subtitle and enable subtitles. A little button will pop up in the lower right corner of the screen, asking if you want to save these settings. Press Enter (or select, OK, depending if you're using a remote) and it'll remember the settings.

**Comment by welldonesp** [comment]
So I need to set the caption for each episode I watch?

**Comment by caphm** [comment]
No, only once.
