### ISSUE TITLE
How to obtain the Episode_ID of a TV-Show?

### ISSUE THREAD

**Issue by Philps** [asciidisco/plugin.video.netflix#461]
As there is no API, i wonder whats the simples way to obtain a Episode_ID of a TV Show?

I could query eg. https://instantwatcher.com/title/80205258 (Money Heist/HAus des Geldes Staffel2, Episode2)   to obtain the EpisodeID; but i wonder if there is a simpler way espeicall when you have the Tv_Show ID available https://www.netflix.com/de/title/80192098

So the Tv Show ID is: 80192098
The EpisodeID is: 80205258 

To call the play_video function as requested in https://github.com/asciidisco/plugin.video.netflix/issues/454 you have to transmit the EpisodeID

any help would be much appreciated

**Comment by asciidisco** [comment]
You would need to query the Netflix API, or do it implicitly by calling the plugin route from within your plugin and parsing the output. For example query the list of episodes for a show and parse the output, like the Osmosis plugin does this: https://github.com/stereodruid/plugin.video.osmosis

**Comment by caphm** [comment]
You can retrieve episode IDs from https://www.netflix.com/api/shakti/57e85dca/metadata?movieid=TVSHOWID where TVSHOWID is the unique video id of the tv show. This will return all metadata for this show, including all seasons and episodes (and their corresponding IDs).
It also works if you pass a season's or episode's video id as the parameter (though this is probably not a use case you're looking for).

**Comment by Philps** [comment]
fantastic guys! . thought their API was discontinued.

**Comment by caphm** [comment]
Their public API was, yes. This is actually used by Netflix internally and is not documented for public use. Prepare to adapt to changes when Netflix comes up with something new ;) I recommend not hardcoding the entire request URL, but decomposing it into its component parts, so you can easily adapt when there are changes. See the source of NetflixSession.py for examples.
