### ISSUE TITLE
Netflix Plugin for WebOS OSE

### ISSUE THREAD

**Issue by suaji** [asciidisco/plugin.video.netflix#466]
Hi..

I had nothing to report. Just wanna asking, can u create this plugin for WebOS OSE too bro?..

Thanks ^_^v 

Currently only can login netflix.. But enable to play it because of no widevine..
I try to manual copy libwidevinecdm.so, libwidevinecdmadapter.so, libpepflashplayer.so into /usr/lib/chromium-browser/

But no luck ^^

**Comment by caphm** [comment]
If you can run Kodi on your platform, you can run this addon as well. Compatibility is limited by the available of widevine DRM for your system though. If there's no widevine for your system, you're unfortunately out of luck.
