### ISSUE TITLE
Disabling intro skipping does not work

### ISSUE THREAD

**Issue by HiassofT** [asciidisco/plugin.video.netflix#469]
*I'm submitting a ...*
  - [x] bug report

### Prerequisites

* [x] Are you running the latest version?

### Description

If I disable "Ask to skip intro and recap" in the addon settings "skip intro" is still shown when playing a TV show.

### Steps to Reproduce

1. disable "Ask to skip intro and recap" in Netflix addon settings
2. start a TV show

**Expected behavior:**

"Skip Intro" is not shown in the lower right corner.

**Actual behavior:**

"Skip Intro" is shown in the lower right corner.

## Context (Environment)

LibreELEC 8.90.004 (Kodi beta1 v2) on RPi3B+, Netflix addon 0.13.12 installed via repository.

## Debug log
http://ix.io/1mcb

**Comment by caphm** [comment]
Confirmed and fix on the way.

**Comment by HiassofT** [comment]
thanks a lot, version 0.13.13 works fine!
