### ISSUE TITLE
Missing Depenancies

### ISSUE THREAD

**Issue by CruxedKat** [asciidisco/plugin.video.netflix#471]
*I'm submitting a ...*
  - [/] bug report
  - [/] support request

### Prerequisites

* [/] Are you running the latest version?
Kodi 18.0-BETA1

### Description

Missing pycryptodome script and Netflix wont start ANY shows i click on just a few cycles of loading then nothing... Just sat viewing the List of movies

### Installation

* [/] I installed the plugin via zip from the Releases page
 https://koditips.com/netflix-kodi-addon/

### Operating System

* [/] RaspberyPi LIBREELEC (Leia) v8.90.004 ALPHA

**Comment by caphm** [comment]
You need to install pycryptodomex yourself (via pip).
