### ISSUE TITLE
Browsing Netflix catalogue is working, but videos can't be played

### ISSUE THREAD

**Issue by zarianu** [asciidisco/plugin.video.netflix#473]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Can't play any videos using plugin

### Prerequisites

* [x] Are you running the latest version? 0.13.12

### Description

No videos playing.

### Steps to Reproduce

1. Select Netflix Add-on
2. Browse catalog, select show, select episode
3. No fun :(

**Expected behavior:** Playing TV series

**Actual behavior:** Not playing

## Context (Environment)

LibreELEC on RPi3

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Using latest alpha of LibreELEC

## Debug log
http://ix.io/1mCv

**Comment by caphm** [comment]
Widevine is not properly installed, so not a plugin issue. If it was installed via inputstreamhelper, you might suffer from #465. See there for a possible workaround.
If you installed it yourself, you messed up. Remove it and let inputstreamhelper install it. If you're still experiencing issues, apply the workaround in #465.

**Comment by zarianu** [comment]
@caphm thank you for your prompt answer!
