### ISSUE TITLE
Video stuttering, has to re-buffer a lot

### ISSUE THREAD

**Issue by thom-github** [asciidisco/plugin.video.netflix#476]
*I'm submitting a ...*
  - [*] bug report
  - [ ] feature request
  - [ ] support request

## General information
Playing Netflix streams, the video stutters, runs slowly, to the point that osmc has to buffer again after like 10 to 15 seconds. No way to watch a stream like that.

### Prerequisites

* [*] Are you running the latest version?
Just updated to 0.13.13 this morning, no change

### Description
Much like I said above, in Netflix streams, the video is choppy, lags behind the audio badly (and progressively worse) until osmc goes to buffering again, rinse and repeat
[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
Installed latest osmc (2018.07-1) for Raspberry
2. [Second Step]
Change it's sources.list to go to nightly version
3. [Third Step]
Install plugin.video.netflix through repository
4. [Fourth Step]
Log into Netflix, stuff gets downloaded from a ChromeOS image (thats that widevine thing, right?)
5. [Fifth Step]
Playing a video, the above happens.

**Expected behavior:** [What you expected to happen]
Netflix stream to play properly
**Actual behavior:** [What actually happened]
Stream plays with choppy video, goes back to buffering ever 15 or so seconds.
## Context (Environment)
osmc, nightly version, plugin.video.netflix installed through repository
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [*] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [*] Linux (ARM) 
* [ ] Android

#### Additional informatin on the environment
Using osmc 2018.07-1, sources.list changed to nightly builds.
## Debug log
I would gladly provide logs, but I don't know where to find (relevant) logs on osmc / Kodi.

**Comment by thom-github** [comment]
If it's not already abundandly clear, I'm pretty new to bug reporting on GitHub, so sorry for anything I might have done wrong. Any feedback / help much appreciated.

**Comment by karankapoor229** [comment]
Having the same issue with my Raspberry 3B having LibreElec 8.90.004, playback is smooth with 720*480p streaming though. Maybe the problem is due to software decoding being slow at higher resolutions.

**Comment by brainfork** [comment]
I have the same set-up as @karankapoor229 and was experiencing the same issue as @thom-github, I set the InputStream Adaptive plugin Max. Resolution settings to 720p and playback works normally again.

**Comment by MilhouseVH** [comment]
> Maybe the problem is due to software decoding being slow at higher resolutions.
RPi, including RPi3+, will not software decode 1080p widevine streams without stuttering/buffering. RPi2/3/3+ is limited to 720p for Netflix, Amazon etc.

**Comment by caphm** [comment]
As Milhouse said, there is no hardware decoding with Netflix, so the max resolution is utlimately CPU bound. If there's stuttering, you need a beefier CPU.
