### ISSUE TITLE
Will not play videos with most recent nightly (as of date of filing this)

### ISSUE THREAD

**Issue by mattreecebentley** [asciidisco/plugin.video.netflix#478]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

Older alpha (25/08/2018) works fine with 13.13 or 13.12, alpha from 19/09/2018 fails for netflix playback.
Youtube playback works fine.

### Prerequisites

* [x] Are you running the latest version?

### Description

[Description of the bug or feature]

### Steps to Reproduce

Play a video.

**Actual behavior:** [What actually happened]

Video timeline appears and progresses, but no video plays.

## Context (Environment)
Win10 x64 1803
19/09/2018 kodi nightly
addon 13.13

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
Nothing we can do without a complete debug log.

**Comment by mattreecebentley** [comment]
You could install a nightly yourself.

**Comment by mattreecebentley** [comment]
Are you on Win x64 or linux?

**Comment by caphm** [comment]
I'm on Win10 x64, latest nightly. As I said, everything works fine on my end, so in order to help you I'll need a full debug log please.
