### ISSUE TITLE
[Security] Add ability to secure users credentials

### ISSUE THREAD

**Issue by asciidisco** [asciidisco/plugin.video.netflix#48]
Maybe using this little fellow over here: https://github.com/ruuk/script.module.password.storage
At least, add some kind of encryption/obfuscation, even it´s not unbreakable it would make harmful third party addons life a bit harder.
Also, lets ask the Kodi core team, if there´s a possibility to have a built in feature for this. Asking doesn't hurt ;)

**Comment by Uukrull** [comment]
The Amazon addon uses this:

https://github.com/Sandmann79/xbmc/blob/master/plugin.video.amazon-test/default.py#L1654

**Comment by asciidisco** [comment]
@Uukrull That looks interesting as well. Thanks for the pointer.

**Comment by asciidisco** [comment]
Added in `chore/code-trim` branch
