### ISSUE TITLE
Obsolete wiki for Raspberry Pi

### ISSUE THREAD

**Issue by iz8mbw** [asciidisco/plugin.video.netflix#490]
Hi.
The guide here https://github.com/asciidisco/plugin.video.netflix/wiki/Installation (linked from https://github.com/asciidisco/plugin.video.netflix/wiki) for Raspberry Pi seems to be obsolete.
When I lunch "getwidevine.sh" I receive that output:
```
*** THIS SCRIPT IS OBSOLETE ***

Any guide recommending the use of this script is out of date.

The widevine library should now be installed (and updated) by
script.module.inpustreamhelper.

script.module.inputstreamhelper will be installed automatically as a dependency
when installing video addons (Netflix etc.) from a suitable repository.

Contact the video add-on author if the video add-on does not support
script.module.inputstreamhelper.
```

Please update if needed. Many thanks.

**Comment by carlosricardocm** [comment]
HI, the installation is more easy that you think, just download this zip.
https://github.com/kodinerds/repo/raw/master/repository.netflix/repository.netflix-1.0.1.zip
Open Kodi and install the zip as repo.
Once the repositoy is installed, open the repositoty and select and install the netflix addon in the same way as another.

**Comment by iz8mbw** [comment]
Yes I know, this is the reason I'm asking to update/correct that guide: https://github.com/asciidisco/plugin.video.netflix/wiki/Installation

**Comment by carlosricardocm** [comment]
OK, my bad, in fact it will be good update the wiki

**Comment by asciidisco** [comment]
I´ve just deleted it. If someone wants to write a new one (don't think if that´s necessary anymore) a PR with an additional Markdown file containing instructions would be happily merged.
