### ISSUE TITLE
1080p on linux

### ISSUE THREAD

**Issue by dontknowcris** [asciidisco/plugin.video.netflix#493]
*I'm submitting a ...*
  - [X ] bug report
  - [ ] feature request
  - [X ] support request

## General information
OS: ubuntu linux 18.04
Kodi 18 nightly installed from kodi ppa
inputstream 2.2.28

### Prerequisites

* [X ] Are you running the latest version?

### Description

[Description of the bug or feature]
when i try to play "suits" on ubuntu linux using kodi nightly, i can't see the show in 1080p but just 480p. the same show on windows is correctly in 1080p

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
the show should be run in 1080p
**Actual behavior:** [What actually happened]
the show run in 480p
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
Some content is restricted to lower quality on certain systems (especially Linux) by the content provider. There's nothing we can do about that.
To check which resolutions are available, set stream selection to manual in the inputstream.adaptive addon and check out the list of resolutions during playback.

**Comment by caphm** [comment]
Have a look at the manifest.json in the plugin data folder after starting a video. All available resolutions are contained in this file. If they don't show up there, Netflix is not making them available to you.

**Comment by dagwieers** [comment]
There was a bug in **inpustream.adaptive** where if you selected 720p, you would get a lower quality stream. And if you selected 1080p you would get the 720p stream. It is fixed in peak3d/inputstream.adaptive#259
