### ISSUE TITLE
video is stuttering on rpi3 libreelec

### ISSUE THREAD

**Issue by tal235** [asciidisco/plugin.video.netflix#496]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Video is not fluent at all netflix videos.

### Prerequisites

* [ ] Are you running the latest version?
Yes
### Description

[Description of the bug or feature]

I installed the latest build of libreelec and netflix addon and Widevine and input adaptive, but on two different RPIs the video is not flunt, it is like that there are less frames per second than needed to be, causing it impossible to watch anything on netflix.
I have other video add-ons + pvr clients that does not have this problem.

### Steps to Reproduce

1. Play the video

**Expected behavior:** [What you expected to happen]
Video should be played fluent without any jitterings or stucks

**Actual behavior:** [What actually happened]
Video is not fluent , jitters, with less fps than neede.
## Context (Environment)

LibreELEC (official): 8.90.006 (RPi2.arm)

### Installation

* [x ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
LibreELEC (official): 8.90.006 (RPi2.arm)

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]
https://pastebin.com/vMYgN3wV
## Other information
On the same network, on a winx64 pc, on the same kodi version (18) there is no problem at all.

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by MilhouseVH** [comment]
Are you trying to play videos in 1080p? If so, Netflix/Amazon videos are software-decoded and the RPi2/3/3+ is only able to software decode 720p without stutters, so reduce your max resolution to 720p in the inputstream settings.

**Comment by tal235** [comment]
Hi
Inputstream is set to 720p

**Comment by iz8mbw** [comment]
I have same behavior so I workarounded by select 480p as resolution in inpustream.

**Comment by tal235** [comment]
480p is ok but it is bad quality for the video. I wish 720p was like that.

**Comment by asciidisco** [comment]
The RPi 3 should be able to do 720p, while the RPi can do 480p max.
Why? Because of the DRM - We can only do Software decoding/decrypting (not Hardware decoding as Kodi is able to do with most non-DRM-ish videos). So everythign must be done by the CPU & the PIs CPU can't handle more than the resolutions mentioned above.

**Comment by tal235** [comment]
> The RPi 3 should be able to do 720p, while the RPi can do 480p max.
> Why? Because of the DRM - We can only do Software decoding/decrypting (not Hardware decoding as Kodi is able to do with most non-DRM-ish videos). So everythign must be done by the CPU & the PIs CPU can't handle more than the resolutions mentioned above.

Hi,
I am having trouble to understand your answer, because I am using RPi 3, which can handle 720p but still, it seems it is not viewed as I expect it to be.
Is there any log I can attach to help figure what the problem is?
thx

**Comment by gytisgreitai** [comment]
For me RPI 3 B+ handles 720p without problems. Any hints on what hardware is required to do 1080p on Linux ? Simple Intel Celeron probably would be enough?

**Comment by iz8mbw** [comment]
Good for you, but RPI 2 is not able to handles 720p.
