### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by theboy181** [asciidisco/plugin.video.netflix#497]
Connect to the Raspberry Pi over SSH using the default user and password
Run wget http://nmacleod.com/public/libreelec/getwidevine.sh
Run sh getwidevine.sh
Reboot the Raspberry Pi

When I follow the installation instructions above, I get:

*** THIS SCRIPT IS OBSOLETE ***

Any guide recommending the use of this script is out of date.

The widevine library should now be installed (and updated) by
script.module.inpustreamhelper.

script.module.inputstreamhelper will be installed automatically as a dependency
when installing video addons (Netflix etc.) from a suitable repository.

Contact the video add-on author if the video add-on does not support
script.module.inputstreamhelper.

Netflix was working then all of a sudden it stopped. Are the install instructions out of date?

**Comment by asciidisco** [comment]
`getwidevine.sh` isn't necessary anymore, the plugin pulls in the needed Widevine lib by itself now. Just install it, like you would do with any plugin and it should be fine.
