### ISSUE TITLE
Dynamic port allocation

### ISSUE THREAD

**Issue by asciidisco** [asciidisco/plugin.video.netflix#5]
The MSL service server port is hardcoded in 2 files of the plugin (https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/KodiHelper.py#L22)[KodiHelper.py] & (https://github.com/asciidisco/plugin.video.netflix/blob/85447a5fdfc7dff80e2272d77a5f94c0eddff1af/service.py#L7)[service.py] 

a) this could lead to issues (service not starting/plugin rendered useless) if the port is blocked on the user machine (even more likely, when picking a prominent port like 8000)

b) Changing the port would require changes in multiple files (Code hygiene)

My suggestion would be, the service checking for an (http://code.activestate.com/recipes/531822-pick-unused-port/)[unused port] on first launch, pick one & persist it in the plugins shared settings (invisible setting, not something the user can change on its own).
The video.addon then grabs that port from the settings & uses it for the session.

Ones we have that port setting in place ones, the service could check (on ervery start, e.g. every Kodi start up) if that port is still available. If so, there´s no need to change the settings (to prevent not needed disc IO) & they both continue using that port. If the port is blocked, it just picks an unused one & alters the settings.
Theoretically this could lead to a race conditon, practically, this should not happen as the time from starting the service to starting the plugin should suffice.

**Comment by trummerjo** [comment]
would prefer to always use a dynamic port.
I dont think that a disk io is more expensive then checking if the choosen port is free

**Comment by asciidisco** [comment]
The plugin now reads the port from the `msl_service_port` setting, the MSL service can set it accordingly on startup

**Comment by asciidisco** [comment]
Added in c1cb01e

**Comment by trummerjo** [comment]
why bind to a port to find a free one and then bind again to the found port? isn't it possible to remove the find_port function and just bind the webserver to port 0 and save the port after starting the webserver?

**Comment by asciidisco** [comment]
I´ve read about that technique, but I´m not sure if it works cross OS (I vaguely remember reading about some Windows problems), but must admit I´m not sure about.
That being said, feel free to change anything if you think it improves the situation, I just wanted to get some traction on that topic.
