### ISSUE TITLE
Netflix Crashes on start

### ISSUE THREAD

**Issue by cupral** [asciidisco/plugin.video.netflix#504]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites
Install https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-18.0-Leia_beta3-arm64-v8a.apk
Install Netflix plugin

* [x] Are you running the latest version?

### Description
Kodi crash instantly after start

### Steps to Reproduce
1. Install https://mirrors.kodi.tv/releases/android/arm64-v8a/kodi-18.0-Leia_beta3-arm64-v8a.apk
2. Install Netflix plugin
3. Start Kodi

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [X] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [X] Android

#### Additional informatin on the environment
Google Pixel 2

## Debug log
https://pastebin.com/raw/zCSJSdGH

**Comment by caphm** [comment]
It doesn't even get to load the add-on. I'm not familiar with Kodi on Android, but from what I can gather from the log is that it probably fails during DRM initialization in Kodi startup. Are you using one of those funky Android boxes that happens to have a botched widevine implementation?

Not an add-on issue, sorry.

**Comment by cupral** [comment]
No it is official google pixel 2 device!
Moreover same behavior on nexus 5!

**Comment by caphm** [comment]
Does it work without the addon installed? The log provides no indication of any addon involvement.
