### ISSUE TITLE
Kodi 18 B4 raspberry 3+ - Cannot set credentials for netflix plugin

### ISSUE THREAD

**Issue by solnet-phiro** [asciidisco/plugin.video.netflix#511]
*I'm submitting a ...*
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Installation of plugin does not lead to working netflix flicks. 

### Prerequisites
Install the plugin on a fresh kodi 18 B4 on raspberry 3 B device. (Instructions from https://forum.kodi.tv/showthread.php?tid=329767)
Activate the  plugin and then go to Configuration tab.
* [x ] Are you running the latest version?

### Description

After a successful installation i can enable the plugin and then go into the configuration.
There is only a "Switch accounts" option in the accounts tab and no other places to set account information. When clicking "switch accounts"  the config screen closes and I get an error. (Logfile added) connection refused (From the logfile) 

### Steps to Reproduce

1. Install the plugin following (https://forum.kodi.tv/showthread.php?tid=329767) instructions
2. Activate and configure the plugin 
3. Click in the Accounts tab the Switch Accounts link. Nothing happens, after 10 seconds an error appears (Netflix error, check logfiles)

**Expected behavior:** [What you expected to happen]
Be able to set credentials and then connect and use Netflx service
**Actual behavior:** [What actually happened]
No link or tab to set credentials and "switch accounts" throws an error.
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM) (Raspberry 3B+)
* [ ] Android

#### Additional informatin on the environment
Using Kodi 18 Beta 4 from the raspberry repo. [deb http://pipplware.pplware.pt/pipplware/dists/unstable/main/binary /]
## Debug log

http://sprunge.us/hPjn6d

## Other information

Updated raspberry to the latest version and the kodi 18 B4 is the latest beta release. (As of date)

**Comment by wintuxx** [comment]
Have start the Netflix addon?
At the first start it will ask for the login.

Philip Rodrigues <notifications@github.com> schrieb am Sa., 27. Okt. 2018,
02:36:

**Comment by solnet-phiro** [comment]
Hi Wintuxx, thanks for getting back to me, yes I have started it and it threw the same exception. It did not ask me for a logon.

**Comment by mariojungwirth** [comment]
I have the same Problem. But i can Setup my account and Login. All Profiles are displayed. If i select an profile kodi crashs without any error / log. Segmentation Fault on the console.

I have the same Environment (Rasp 3b+) + updates 
Video is added. (starting Netflix plugin with successfully Login. After select a profile. crash)
[https://youtu.be/fMZnAMKWdWc](url)

**Comment by daveraver** [comment]
try to install pycryptodomex this way on raspbian:

sudo pip install pycryptodomex

it has worked on my rpi3 B 

Regards

**Comment by alistairlow** [comment]
> Hi Wintuxx, thanks for getting back to me, yes I have started it and it threw the same exception. It did not ask me for a logon.

I hit the same problem and managed to work around it by downgrading the Netflix plugin to 0.13.13.I was then able to log in and play videos. Afterwards, I was able to upgrade to 0.13.15 and everything continued to work.

**Comment by solnet-phiro** [comment]
@daveraver That did the trick for me, after installing this and rebooting the plugin started to download the chrome recovery image and then I could login and use netflix. Did I miss this in the instructions? If not we may want to add it. Thanks for your help and the issue is resolved for me.
