### ISSUE TITLE
Audio hiccups  and alternate player ie. VLC

### ISSUE THREAD

**Issue by Morph408** [asciidisco/plugin.video.netflix#514]
*I'm submitting a ...*
  - [x] bug report
  - [x] feature request
  - [] support request

## General information
While playing a movie form time to time there is some audio hiccups like actor is repeating himself.

### Prerequisites

* [YES] Are you running the latest version?

### Description

Because of the audio inconvenience I would try to run the movie in external player like vlc using the code in playercorefactory.xml but movie is loading with a huge delay. There is audio but no video.
I've exported the movie, then opened the exported file using play with...
`<playercorefactory>
  <players>
    <player name="VLC" type="ExternalPlayer" video="true">
        <filename>/usr/bin/vlc</filename>
        <args>--play-and-exit --video-on-top --fullscreen</args>
        <forceontop>false</forceontop>
        <hidexbmc>false</hidexbmc>
        <hideconsole>false</hideconsole>
        <hidecursor>false</hidecursor>
    </player>
  </players>
<playercorefactory/>`

Is there the easier way to use different player?

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

**Comment by caphm** [comment]
There is no way to use a different player because they don't support the DRM.

The audio hiccups are either a Kodi or an inputstream.adaptive issue. The add-on does not do any video/audio rendering itself. It just passes the manifest and required DRM license, everything after that is no longer the add-on's concern.
