### ISSUE TITLE
Installing Plugin Causes Kodi to Crash on Fire TV

### ISSUE THREAD

**Issue by darrylmorley** [asciidisco/plugin.video.netflix#517]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Kodi crashes on install of plugin
### Prerequisites
Kodi 18, Amazon Fire TV
* [x ] Are you running the latest version?

### Description
I have tried various versions of the kodi 18 apk, all crash after installing the plugin. Kodi is then unusable until removed and reinstalled due to crashing.

I have tried instaling the plugin from various sources including the repository and downloading the video plugin from github.

**Expected behavior:** [What you expected to happen]
Watch netflix ;)

**Actual behavior:** [What actually happened]
App crashes.

## Context (Environment)
Android Fire TV.

### Installation
Alternatives all attempted with same result.
* [x ] I installed the plugin via zip from the Releases page
* [x ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x ] Android

#### Additional informatin on the environment
Amazon Fire TV 1
[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

**Comment by caphm** [comment]
Not enough info. Please provide at least a debug log.
