### ISSUE TITLE
Help wanted. Unable to play video with my DNS service

### ISSUE THREAD

**Issue by AmandaBeuno** [asciidisco/plugin.video.netflix#520]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## General infomration
I had to travel outside of the UK for 6 month in business. To be able to access the company's VPN ( which is geo-restricted to the UK. The IT dept. installed a Smart DNS service on my laptop. I am able to log in and view my NetFlix list but I am not able to play any video. I am attaching Kodi's log after enabling "debug logging" in Kodi. I searched for the option to enable the verbose logging in the plugin but I couldn't locate it. 
### Prerequisites

* [x] Are you running the latest version?
Yes

### Description

[Description of the bug or feature]

### Steps to Reproduce

1. Run the Smart DNS service
2. Open Kodi -> Netflix addon -> pick any video

**Expected behavior:** [What you expected to happen]
A video to play.
**Actual behavior:** [What actually happened]
It tries to connect and play it but eventually nothing happens.

## Context (Environment)
Windows 10 x64
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
I am running Kodi Leia 18 Beta 2

I just installed the addon the normal way and the addon downloaded and installed all dependencies 
## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]
https://pastebin.com/raw/JKWbStHE
## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
Netflix is blocking you, because you're using a proxy. Nothing we can do about that. Playing via Netflix Homepage will not work either.

**Comment by AmandaBeuno** [comment]
Actually, playing via Netflix Homepage works like a charm. It is just that I have access to my library with me on Kodi and thought it is the better viewing experience.

**Comment by caphm** [comment]
That's strange. Is there an exception configured for your browser, such that it bypasses the DNS service?
In either case, Netflix is refusing to serve a manifest to you because it detects a proxy/VPN/whatever other stuff they are blocking.

**Comment by AmandaBeuno** [comment]
Sorry caphm for asking for help on such a specific situation. I just want you to know that it is okay if you won't offer help with my case. It is just that there is no exception configured for my browser. 

I attached the kodi.log file and if you want any further log I can send it right away. 

Thanks for the brilliant addon.

**Comment by AmandaBeuno** [comment]
Please, just let me know if you can look into it or I should put it to rest for the next 6 months till I am back in the UK.

**Comment by caphm** [comment]
You can try the beta for 0.14.0 from #519 . This should at least give you a more detailed error message. I suspect there's not much I can do about it though, as Netflix is known to be very strict when it comes to VPNs, Proxys and out-of-the-ordinary DNS setups.
