### ISSUE TITLE
Latest Update - Not Working

### ISSUE THREAD

**Issue by alligatorshoes** [asciidisco/plugin.video.netflix#530]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

Latest update prevents any video from being played.

### Prerequisites

* [x] Are you running the latest version?
Yes.

### Description

When trying to play a video I get the spinning "busy" icon but then the addon returns back to the video list.

### Steps to Reproduce

1. Try to play video.

**Expected behavior:** [What you expected to happen]
Video plays.

**Actual behavior:** [What actually happened]
Returned to video list.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec Milhouse build - latest (1114).

## Debug log

00:59:11.383 T:140565661812480   DEBUG: CAddonSettings[metadata.tvdb.com]: loading setting definitions
00:59:11.383 T:140565661812480   DEBUG: CAddonSettings[metadata.tvdb.com]: trying to load setting definitions from old format...
00:59:11.383 T:140565661812480   DEBUG: CAddonSettings[metadata.tvdb.com]: loading setting values
00:59:11.447 T:140563120899840   DEBUG: ----------------------------------------
00:59:11.447 T:140563120899840   DEBUG: Exception happened during processing of request from
00:59:11.447 T:140563120899840   DEBUG: ('127.0.0.1', 50302)
00:59:11.447 T:140563120899840   ERROR: Traceback (most recent call last):
00:59:11.448 T:140563120899840   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
00:59:11.448 T:140563120899840   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
00:59:11.448 T:140563120899840   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
00:59:11.448 T:140563120899840   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
00:59:11.448 T:140563120899840   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
00:59:11.448 T:140563120899840   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
00:59:11.448 T:140563120899840   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 67, in do_GET
00:59:11.449 T:140563120899840   ERROR:     dolby, hevc, hdr, dolbyvision)
00:59:11.449 T:140563120899840   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 221, in load_manifest
00:59:11.449 T:140563120899840   ERROR:     return self.__tranform_to_dash(data)
00:59:11.449 T:140563120899840   ERROR:   File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 307, in __tranform_to_dash
00:59:11.449 T:140563120899840   ERROR:     manifest = manifest['result']['viewables'][0]
00:59:11.449 T:140563120899840   ERROR: KeyError: 'viewables'
00:59:11.449 T:140563120899840   DEBUG: ----------------------------------------
00:59:11.449 T:140563095721728   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
00:59:11.449 T:140563095721728   ERROR: CCurlFile::Open failed with code 0 for http://localhost:35703/manifest?id=70266829&dolby=true&hevc=false&hdr=false&dolbyvision=false:
00:59:11.449 T:140563095721728   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:35703/manifest?id=70266829&dolby=true&hevc=false&hdr=false&dolbyvision=false
00:59:11.449 T:140563095721728   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:35703/manifest?id=70266829&dolby=true&hevc=false&hdr=false&dolbyvision=false)
00:59:11.449 T:140563095721728   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
00:59:11.450 T:140563095721728   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+2%2C+%27plot%27%3A+u%22Richie+and+Eddie+panic+when+the+gas+man+pays+a+visit.+Will+they+be+able+to+dismantle+the+illegal+gas+pipe+they%27ve+connected+to+next+door%27s+supply%3F%22%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Bottom%27%2C+%27title%27%3A+u%27Gas%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27British+Programmes%27%2C+%27year%27%3A+1991%2C+%27duration%27%3A+1767%7D&video_id=70266829&pin=False&start_offset=1730]
00:59:11.450 T:140563095721728  NOTICE: CVideoPlayer::OnExit()
00:59:11.450 T:140563095721728   DEBUG: AddOnLog: InputStream Adaptive: Close()
00:59:11.450 T:140563095721728   DEBUG: SECTION:UnloadDll(/usr/lib/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.3.8)
00:59:11.450 T:140563095721728    INFO: ADDON: Dll Destroyed - InputStream Adaptive
00:59:11.450 T:140563095721728   DEBUG: Thread VideoPlayer 140563095721728 terminating
00:59:11.452 T:140565671982848   DEBUG: DoWork - Saving file state for video item plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+2%2C+%27plot%27%3A+u%22Richie+and+Eddie+panic+when+the+gas+man+pays+a+visit.+Will+they+be+able+to+dismantle+the+illegal+gas+pipe+they%27ve+connected+to+next+door%27s+supply%3F%22%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27Bottom%27%2C+%27title%27%3A+u%27Gas%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27British+Programmes%27%2C+%27year%27%3A+1991%2C+%27duration%27%3A+1767%7D&video_id=70266829&pin=False&start_offset=1730
00:59:11.456 T:140565653419776   DEBUG: OnPlayBackStopped: CApplication::OnPlayBackStopped
00:59:11.459 T:140565820418176  NOTICE: CVideoPlayer::CloseFile()
00:59:11.459 T:140565820418176  NOTICE: VideoPlayer: waiting for threads to exit
00:59:11.459 T:140565820418176  NOTICE: VideoPlayer: finished waiting
00:59:11.459 T:140565820418176   DEBUG: DeleteRenderer - deleting renderer
00:59:11.459 T:140565820418176   DEBUG: LinuxRendererGL: Cleaning up GL resources
00:59:11.459 T:140565820413696   DEBUG: CAnnouncementManager - Announcement: OnStop from xbmc
00:59:11.459 T:140565820413696   DEBUG: GOT ANNOUNCEMENT, type: 1, from xbmc, message OnStop
00:59:11.463 T:140565820418176   DEBUG: Radio UECP (RDS) Processor - delete ~CDVDRadioRDSData
00:59:11.474 T:140565820418176   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
00:59:11.485 T:140564583724800   DEBUG: [plugin.video.youtube] Cleared home window properties: []

## Other information

Only seems to have happened since the latest upgrade within the last 24 hours. Oddly, downgrading to the previous version doesn't resolve things.

**Comment by hungowapower** [comment]
I have the same issue. Maybe Netflix has made some changes to prevent non approved programs from accessing it's content? Netflix has never liked Kodi.

**Comment by TVM4iN** [comment]
Today netflix blocked msl. Or tools or script can't download stream list.

**Comment by POEDaley** [comment]
Same here.  I'm able to view the video list on the netflix app but can't play them.  Started all of the sudden just as many others have said.

**Comment by hlashbrooke** [comment]
Chiming in with a +1 to say I'm having the same issue with the same error message in the logs.

**Comment by gytisgreitai** [comment]
Well the issue is clearly seen in the manifest.json: `"Playback not permitted because device request did not include a PRK profile."` So anyone know what's this PRK ?

**Comment by evantaur** [comment]
time to unsub netflix?

**Comment by jakermx** [comment]
> Well the issue is clearly seen in the manifest.json: `"Playback not permitted because device request did not include a PRK profile."` So anyone know what's this PRK ?

If you enable HEVC you solve this and then you with get another error.

**Comment by mattreecebentley** [comment]
> 
> 
> time to unsub netflix?

Certainly considering it - web interface is awful

**Comment by jakermx** [comment]
inally I have it working now... I tried a lot of things, but it was really simple:

Just Add

            #PRK Profile
            "hevc-main10-L30-dash-cenc-prk",
on the load_manifiest method

so It will looks like

def load_manifest(self, viewable_id, dolby, hevc, hdr, dolbyvision):
    """
    Loads the manifets for the given viewable_id and
    returns a mpd-XML-Manifest

    :param viewable_id: The id of of the viewable
    :return: MPD XML Manifest or False if no success
    """
    manifest_request_data = {
        'method': 'manifest',
        'lookupType': 'PREPARE',
        'viewableIds': [viewable_id],
        'profiles': [
            #PRK Profile
            "hevc-main10-L30-dash-cenc-prk",
            # Video
            "playready-h264bpl30-dash",
            "playready-h264mpl30-dash",
            "playready-h264mpl31-dash",
            "playready-h264mpl40-dash",

            # Audio
            'heaac-2-dash',

            # Subtiltes (handled separately)
            # 'dfxp-ls-sdh',
            # 'simplesdh',
            # 'nflx-cmisc',

            # Unkown
            'BIF240',
            'BIF320'
        ],
        'drmSystem': 'widevine',
        'appId': '14673889385265',
        'sessionParams': {
            'pinCapableClient': False,
            'uiplaycontext': 'null'
        },
        'sessionId': '14673889385265',
        'trackId': 0,
        'flavor': 'PRE_FETCH',
        'secureUrls': False,
        'supportPreviewContent': True,
        'forceClearStreams': False,
        'languages': ['de-DE'],
        'clientVersion': '4.0004.899.011',
        'uiVersion': 'akira'
    }
reboot your KODI and it will work...if you dont reboot it will not work.

Here is my MSL.py File, I am on LibreElec for RPi3
[MSL.zip](https://github.com/asciidisco/plugin.video.netflix/files/2587908/MSL.zip)

**Comment by stannynuytkens** [comment]
@jakermx thanks, got it working again!
