### ISSUE TITLE
Issue with netflix that started today, worked yesterday.

### ISSUE THREAD

**Issue by GavinDarkglider** [asciidisco/plugin.video.netflix#531]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
Netflix was working fine until I started getting ERROR: KeyError: 'viewables' in the log.
Attached is a stripped down debug log with the relevant information and 
### Prerequisites

* [ ] Are you running the latest version?
yes, 0.13.16
### Description

[Description of the bug or feature]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Video starts to play
**Actual behavior:** [What actually happened]
Video doesnt play
## Context (Environment)
ARM32 on AARCH64 Gentoo
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [x ] I´m using a different source (Please tell which)
github sources
### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
32 bit arm gentoo  on Nintendo Switch, using a 64bit kernel.
## Debug log

[Please include a link to your debug log (use something like [http://sprunge.u
[debug_netflix.log](https://github.com/asciidisco/plugin.video.netflix/files/2583367/debug_netflix.log)
[manifest.txt](https://github.com/asciidisco/plugin.video.netflix/files/2583383/manifest.txt)

s/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by MosDos96** [comment]
Same here! (Win10 x86)

**Comment by alorbach** [comment]
Same on librelec and 13.6 since today here (arm 32bit build).

**Comment by jakermx** [comment]
inally I have it working now... I tried a lot of things, but it was really simple:

Just Add

            #PRK Profile
            "hevc-main10-L30-dash-cenc-prk",
on the load_manifiest method

so It will looks like

def load_manifest(self, viewable_id, dolby, hevc, hdr, dolbyvision):
    """
    Loads the manifets for the given viewable_id and
    returns a mpd-XML-Manifest

    :param viewable_id: The id of of the viewable
    :return: MPD XML Manifest or False if no success
    """
    manifest_request_data = {
        'method': 'manifest',
        'lookupType': 'PREPARE',
        'viewableIds': [viewable_id],
        'profiles': [
            #PRK Profile
            "hevc-main10-L30-dash-cenc-prk",
            # Video
            "playready-h264bpl30-dash",
            "playready-h264mpl30-dash",
            "playready-h264mpl31-dash",
            "playready-h264mpl40-dash",

            # Audio
            'heaac-2-dash',

            # Subtiltes (handled separately)
            # 'dfxp-ls-sdh',
            # 'simplesdh',
            # 'nflx-cmisc',

            # Unkown
            'BIF240',
            'BIF320'
        ],
        'drmSystem': 'widevine',
        'appId': '14673889385265',
        'sessionParams': {
            'pinCapableClient': False,
            'uiplaycontext': 'null'
        },
        'sessionId': '14673889385265',
        'trackId': 0,
        'flavor': 'PRE_FETCH',
        'secureUrls': False,
        'supportPreviewContent': True,
        'forceClearStreams': False,
        'languages': ['de-DE'],
        'clientVersion': '4.0004.899.011',
        'uiVersion': 'akira'
    }
reboot your KODI and it will work...if you dont reboot it will not work.

Here is my MSL.py File, I am on LibreElec for RPi3
[MSL.zip](https://github.com/asciidisco/plugin.video.netflix/files/2587909/MSL.zip)

**Comment by caphm** [comment]
Fixed in master and ported to 0.14.0 beta.
