### ISSUE TITLE
launch errors with version 0.13.17

### ISSUE THREAD

**Issue by VanStorm** [asciidisco/plugin.video.netflix#536]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

When i click on the Netflix addon i just get an error message telling me to check the log.

### Steps to Reproduce

1. installed latest version
2. tried to open it

**Expected behavior:** the Netflix addon menu should open

**Actual behavior:** the addon crashes pointing me to the log file.

## Context (Environment)

Windows 10 Pro x64

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Kodi (18.0-RC1 Git:20181113-fce4d884b8 on Windows 10 Pro x64

## Debug log

https://pastebin.com/hCZMsK08

**Comment by stannynuytkens** [comment]
Related to https://github.com/asciidisco/plugin.video.netflix/issues/530, see fix at the bottom.

**Comment by VanStorm** [comment]
> 
> 
> Related to #530, see fix at the bottom.

the fix doesn't work for my problem. I tried it and my plugin still crashes on launch.

**Comment by jakermx** [comment]
restart your kodi, and wait 5 minutes, the internal addon proxy server its not accepting connections...

**Comment by VanStorm** [comment]
> 
> 
> restart your kodi, and wait 5 minutes, the internal addon proxy server its not accepting connections...

thank you. i worked around the problem with the merge pull request #519 and the patches mentioned in the comments.
