### ISSUE TITLE
Automatic Intro Skipping does not work in combination with add-on upnext

### ISSUE THREAD

**Issue by MeCias** [asciidisco/plugin.video.netflix#539]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

yes

### Description

In combination with the upnext add-on the automatic intro skipping function is not working after upnext started a new episode. If the automatic skipping (by default) is off you are able to manual skip.

Opened an issue with upnext as well.

https://github.com/im85288/service.upnext/issues/9

### Steps to Reproduce

1. [First Step]

Enable automatic intro skipping

2. [Second Step]

Wait until upnext started the second episode

3. [and so on...]

**Expected behavior:** [What you expected to happen]

Intro is going to be skipped

**Actual behavior:** [What actually happened]

Intro is playing, manual skipping is not offered

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec v8.90.007 ALPHA on Asus tinkerboard S

**Comment by raven6679** [comment]
I'm not having UpNext addon in Kodi, and yet "skip intro" feature is not working. 
I utilize now nVidia Shield with Android TV, this is completely fresh install with Kodi 18, official Netflix plugin repo.
Of course, option is enabled in Netflix plugin settings. But it's not working.

**Comment by caphm** [comment]
What version are you using? 0.13.x from the repo or any of the 0.14.0 betas? This should be more stable in the latest 0.14.0 beta. If you're on 0.13.x you'll have to wait for 0.14.0 to be released or switch to the beta. I won't backport any fixes into 0.13.x.

**Comment by MeCias** [comment]
Hi,
yeah sorry I missed that information. Right now I am on 0.13.18.  I tried to use 0.14 but had some issues with a samba share for the exports that I use for 0.13 to keep two installations in sync.
I understand that you won't wanna backport everything back to the old branch, maybe I give 0.14 another try during the weekend. Thanks
