### ISSUE TITLE
My list sorting order

### ISSUE THREAD

**Issue by raven6679** [asciidisco/plugin.video.netflix#541]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [X] support request

## General infomration
In "my list" folder, sorting orded is set to "default", but I really cannot tell, which characteristic is used to sort the list. It is NOT alphabetical, it is NOT by "last watched", it is not "last added". Moreover, when I select some other sorting method in left-hand menu, it is not remembered after restarting Kodi. 

### Prerequisites

* [X] Are you running the latest version?

**Expected behavior:** [What you expected to happen]
I expect to have a possibility to remember selected sorting method.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [X] Linux (ARM)
* [X] Android

#### Additional informatin on the environment
I was checking it in Windows Kodi, Android TV, Odroid C2 and Linux Mint.

**Comment by caphm** [comment]
It's the order that Netflix defines. Usually this is last added, but may change whenever Netflix feels like it.
You can change it in Kodi and it should be remembered, since the path is always the same. If it's not, it's probably a Kodi issue.

**Comment by raven6679** [comment]
Well, that's the problem, when I change sorting order to "alphabetical", after next enter to "my list" it's still "default". Kodi doesn't remeber my preference. And I have brand new, fresh instance of Kodi now, didn't change anything yet, beside adding Netflix plugin.
