### ISSUE TITLE
Continue playback from where you left off on all devices

### ISSUE THREAD

**Issue by ricardopablo** [asciidisco/plugin.video.netflix#544]
*I'm submitting a ...*
  - [ ] bug report
  - [X] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

[Hello! I wonder if you have the option to continue playing from where you left off. Because there are contents that I watch on the smartphone using the apk of netflix and I end up not watching everything for any occasion, and when I watch the same content in kodi ends up returning to the beginning of the video, instead of continuing where I left off.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [X] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by caphm** [comment]
This is already on our to-do list, but unfortunately really hard to implement.
