### ISSUE TITLE
Video playback is not working in 0.13.19

### ISSUE THREAD

**Issue by Essam315** [asciidisco/plugin.video.netflix#550]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

The video playback is not working in the release 0.13.19, when i try to play a video nothing happens, I'm not using any VPN, inputstream.adaptive is updated to the latest release 2.3.11, and everything is working fine with 0.13.18.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Kodi 18 Leia RC, Windows 10

## Debug log

https://pastebin.com/wkYMtQZA

## Other information
Here is manifest.json, it might help for fixing the problem.

[manifest.zip](https://github.com/asciidisco/plugin.video.netflix/files/2613143/manifest.zip)

In the file settings.xml in

C:\Users\Essam\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources

changing from

`<setting id="enable_vp9_profiles" type="bool" label="30086" default="false" visible="eq(-3,true)" subsetting="true"/>` 

to

`<setting id="enable_vp9_profiles" type="bool" label="30086" default="true" visible="eq(-3,true)" subsetting="true"/>`

Fixed the playback for me.

And here is a fixed release using this workaround (the fix tested with windows 10, it might not work for some others operating systems then try opening Kodi and right click on the Netflix plugin icon and choose Settings, stand on Expert and enable HEVC profiles).

use this release with Windows 10 (Only VP9 profiles are ON by default)

[plugin.video.netflix-0.13.19.FIX.zip](https://github.com/asciidisco/plugin.video.netflix/files/2613222/plugin.video.netflix-0.13.19.FIX.zip)

and use this release with non-Windows operating systems (VP9 and HEVC profiles are ON  by default)

[plugin.video.netflix-0.13.19.FIXED2.zip](https://github.com/asciidisco/plugin.video.netflix/files/2614022/plugin.video.netflix-0.13.19.FIXED2.zip)

This release should work with all the operating systems.

[plugin.video.netflix-0.13.19.ALL.zip](https://github.com/asciidisco/plugin.video.netflix/files/2616113/plugin.video.netflix-0.13.19.ALL.zip)

**Comment by alexricher** [comment]
I confirm I have the same issue on all my Kodi boxes using 0.13.19. Downgrading back to 0.13.18 makes it work again.

**Comment by c-yco** [comment]
I can also confirm:

 `15:58:34.944 T:140534131709696   DEBUG: AddOnLog: InputStream Adaptive: Searching for decrypters in: /usr/lib/x86_64-linux-gnu/kodi/addons/inputstream.adaptive/
15:58:34.953 T:140534131709696   DEBUG: AddOnLog: InputStream Adaptive: Found decrypter: /usr/lib/x86_64-linux-gnu/kodi/addons/inputstream.adaptive/libssd_wv.so
15:58:34.953 T:140534131709696   DEBUG: AddOnLog: InputStream Adaptive: Supported URN: urn:uuid:EDEF8BA9-79D6-4ACE-A3C8-27DCD51D21ED
15:58:35.099 T:140534131709696   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:56673/manifest?id=80014999&dolby=true&hevc=false&hdr=false&dolbyvision=false&vp9=false
15:58:35.099 T:140534131709696   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:56673/manifest?id=80014999&dolby=true&hevc=false&hdr=false&dolbyvision=false&vp9=false)
15:58:35.099 T:140534131709696   DEBUG: AddOnLog: InputStream Adaptive: Session::~Session()
15:58:35.099 T:140534131709696   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27season%27%3A+None%2C+%27tvshowtitle%27%3A+%27%27%2C+%27mediatype%27%3A+%27movie%27%2C+%27director%27%3A+u%27Bora+Da%5Cu011ftekin%27%2C+%27duration%27%3A+6744%2C+%27year%27%3A+2013%2C+%27genre%27%3A+u%27Deutsche+Kom%5Cxf6dien%27%2C+%27plot%27%3A+u%27Manchmal+lassen+sich+die+Fr%5Cxfcchte+krimineller+Machenschaften+erst+durch+eine+legale+Besch%5Cxe4ftigung+ernten.%27%2C+%27episode%27%3A+%27%27%2C+%27title%27%3A+u%27Fack+ju+G%5Cxf6hte%27%2C+%27mpaa%27%3A+%27FSK-12%27%2C+%27writer%27%3A+%27%27%2C+%27cast%27%3A+%5Bu%27Katja+Riemann%27%2C+u%22Elyas+M%27Barek%22%2C+u%27Aram+Arami%27%2C+u%27Jana+Pallaske%27%2C+u%27Jella+Haase%27%2C+u%27Max+von+der+Groeben%27%2C+u%27Margarita+Broich%27%2C+u%27Alwara+H%5Cxf6fels%27%2C+u%27Uschi+Glas%27%2C+u%27Karoline+Herfurth%27%5D%7D&video_id=80014999&pin=True]
15:58:35.099 T:140534131709696   DEBUG: AddOnLog: InputStream Adaptive: Close()
15:58:35.099 T:140534131709696   DEBUG: SECTION:UnloadDll(/usr/lib/x86_64-linux-gnu/kodi/addons/inputstream.adaptive/inputstream.adaptive.so.2.3.11)
15:58:35.099 T:140534131709696    INFO: ADDON: Dll Destroyed - InputStream Adaptive`

**Comment by noci2012** [comment]
Same here, the screen dims a little when playback starts... and fails:
Debug log:
http://ix.io/1upH

**Comment by Essam315** [comment]
> 
> 
> Similar issue here (RPi3B ), the screen dims a little when playback starts... and fails:
> Debug log:
> http://ix.io/1upH
> 
> The above fix doesn't work though. This was a fresh install done yesterday.
> Addition:
> Rollback to 0.13.18 does make things work.

In the fixed 0.13.19 try opening Kodi and right click on the Netflix plugin icon and choose Settings, stand on Expert Enable HEVC profiles and Disable VP9 profiles, or enable booth.

**Comment by montvid** [comment]
@Essam315 advice works - enabled hevc and vp9 and it works again! W00t!

**Comment by alexricher** [comment]
> > Similar issue here (RPi3B ), the screen dims a little when playback starts... and fails:
> > Debug log:
> > http://ix.io/1upH
> > The above fix doesn't work though. This was a fresh install done yesterday.
> > Addition:
> > Rollback to 0.13.18 does make things work.
> 
> In the fixed 0.13.19 try opening Kodi and right click on the Netflix plugin icon and choose Settings, stand on Expert Enable HEVC profiles and Disable VP9 profiles, or enable both of them.

Indeed, doing this seems to solve the issue. Tested on 2xRPi3 devices.

**Comment by noci2012** [comment]
@Essam315 advice worked. Maybe more robust error handling would be nice.
Going through debug logging doesn't seem a good way to solve settings issues.

**Comment by ksl1989** [comment]
This issue should not be closed it is still present in the most recent stable version. It's not just an informative error message, it's a bug, right now users (at least Pi users) need to into the expert settings and enable an option clearly marked for android to be able to use the addon. This issue should be open as long as that is the case in the stable build.

**Comment by Essam315** [comment]
@ksl1989
This bug has fixed here

https://github.com/asciidisco/plugin.video.netflix/commit/5d363569b025247f5005a2266e69efddb1476cc7

**Comment by ksl1989** [comment]
@Essam315 
You're right, I didn't notice that commit. Also, I hadn't tried the addon today yet, that's why I didn't realise it wasn't working anyway. Although those are different issues.

@simonbuehler This addon is not working today after a change on Netflix's side, it's not related to this issue.

**Comment by krisdeg** [comment]
same issue here on rpi 3B+
latest plugin version + latest osmc


13:23:54.483 T:1125364464 WARNING: CPythonInvoker(92, /home/osmc/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
13:24:00.970 T:1772090096 WARNING: CPythonInvoker(94, /home/osmc/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
13:24:06.665 T:1918279680  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27plot%27%3A+u%22Apr%5Cxe8s+l%27effondrement+d%27un+lyc%5Cxe9e%2C+un+constructeur+tente+de+redorer+son+image+en+proposant+de+payer+les+%5Cxe9tudes+de+trois+jeunes+victimes+dans+une+prestigieuse+%5Cxe9cole+priv%5Cxe9e.%22%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27%5Cxc9lite%27%2C+%27title%27%3A+u%27Bienvenue%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27S%5Cxe9ries+espagnoles%27%2C+%27year%27%3A+0%2C+%27duration%27%3A+3358%7D&video_id=80201009&pin=False&start_offset=3272
13:24:06.667 T:1116975856  NOTICE: Creating InputStream
13:24:07.308 T:1108587248 WARNING: CPythonInvoker(96, /home/osmc/.kodi/addons/plugin.video.netflix/addon.py): the python script "/home/osmc/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
13:24:09.585 T:1200616176   ERROR: Traceback (most recent call last):
13:24:09.586 T:1200616176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
13:24:09.586 T:1200616176   ERROR:     self.process_request(request, client_address)
13:24:09.586 T:1200616176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
13:24:09.587 T:1200616176   ERROR:     self.finish_request(request, client_address)
13:24:09.587 T:1200616176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
13:24:09.587 T:1200616176   ERROR:     self.RequestHandlerClass(request, client_address, self)
13:24:09.587 T:1200616176   ERROR:   File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
13:24:09.587 T:1200616176   ERROR:     self.handle()
13:24:09.587 T:1200616176   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
13:24:09.588 T:1200616176   ERROR:     self.handle_one_request()
13:24:09.588 T:1200616176   ERROR:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
13:24:09.588 T:1200616176   ERROR:     method()
13:24:09.588 T:1200616176   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 69, in do_GET
13:24:09.588 T:1200616176   ERROR:     dolby, hevc, hdr, dolbyvision, vp9)
13:24:09.588 T:1200616176   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 225, in load_manifest
13:24:09.588 T:1200616176   ERROR:     return self.__tranform_to_dash(data)
13:24:09.589 T:1200616176   ERROR:   File "/home/osmc/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 311, in __tranform_to_dash
13:24:09.589 T:1200616176   ERROR:     manifest = manifest['result']['viewables'][0]
13:24:09.589 T:1200616176   ERROR: KeyError: 'viewables'
13:24:09.589 T:1116975856   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
13:24:09.590 T:1116975856   ERROR: CCurlFile::Open failed with code 0 for http://localhost:35857/manifest?id=80201009&dolby=true&hevc=true&hdr=false&dolbyvision=false&vp9=false:
13:24:09.590 T:1116975856   ERROR: AddOnLog: InputStream Adaptive: Cannot download http://localhost:35857/manifest?id=80201009&dolby=true&hevc=true&hdr=false&dolbyvision=false&vp9=false
13:24:09.590 T:1116975856   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (http://localhost:35857/manifest?id=80201009&dolby=true&hevc=true&hdr=false&dolbyvision=false&vp9=false)
13:24:09.592 T:1116975856   ERROR: CVideoPlayer::OpenInputStream - error opening [plugin://plugin.video.netflix/?action=play_video&infoLabels=%7B%27rating%27%3A+0%2C+%27writer%27%3A+%27%27%2C+%27episode%27%3A+1%2C+%27plot%27%3A+u%22Apr%5Cxe8s+l%27effondrement+d%27un+lyc%5Cxe9e%2C+un+constructeur+tente+de+redorer+son+image+en+proposant+de+payer+les+%5Cxe9tudes+de+trois+jeunes+victimes+dans+une+prestigieuse+%5Cxe9cole+priv%5Cxe9e.%22%2C+%27season%27%3A+1%2C+%27tvshowtitle%27%3A+u%27%5Cxc9lite%27%2C+%27title%27%3A+u%27Bienvenue%27%2C+%27mediatype%27%3A+u%27episode%27%2C+%27mpaa%27%3A+u%27-%27%2C+%27director%27%3A+%27%27%2C+%27genre%27%3A+u%27S%5Cxe9ries+espagnoles%27%2C+%27year%27%3A+0%2C+%27duration%27%3A+3358%7D&video_id=80201009&pin=False&start_offset=3272]
13:24:09.592 T:1116975856  NOTICE: CVideoPlayer::OnExit()
13:24:09.722 T:1918279680  NOTICE: CVideoPlayer::CloseFile()
13:24:09.723 T:1918279680  NOTICE: VideoPlayer: waiting for threads to exit
13:24:09.723 T:1918279680  NOTICE: VideoPlayer: finished waiting
13:24:09.744 T:1918279680 WARNING: OnMessage: Suspiciously long time to handle GUI_MSG_PLAYBACK_STARTED (3.06s)


PS: sorry if ive missed something im new here :-)

**Comment by Essam315** [comment]
@krisdeg
This is a closed topic for a different problem, the plugin is not working now because of the problem in #555, upload your debug log to 

https://pastebin.com/api

and post the link with your problem here

https://github.com/asciidisco/plugin.video.netflix/issues/555

use Netflix plugin 0.13.18, because the official 0.13.19 is broken for a different problem.

https://github.com/asciidisco/plugin.video.netflix/archive/0.13.18.zip
