### ISSUE TITLE
Restoring subtitles with ID does not work

### ISSUE THREAD

**Issue by peak3d** [asciidisco/plugin.video.netflix#556]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
If enabled in settings, netflix addon tries to set subtitle / audio settings for a complete series.
Because Number and position of subtitles can change between seasons / episodes, working with internal id's is dangerous and wrong

15:37:32.672 T:18446744073002981680   DEBUG: [Netflix] StreamContinuityManager: Restored subtitle to {u'index': 1, u'name': u'', u'language': u'ger'}

### Steps to Reproduce

1. Play Prison Break season 3, save Audio / Sub settings
2. Play Prison Break season 4

**Expected behavior:** [What you expected to happen]
With sub set to ger in season 3, expected is that subs are played ger in season 4, too

**Actual behavior:** [What actually happened]
subs in season 4 are played in english, because no forced subs are in season 4 and indices vary.

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [X] Android

## Debug log

http://paste.ubuntu.com/p/bDVSvDBkz9/

**Comment by peak3d** [comment]
@caphm from kodi code it should be possible to select subs with index -1

**Comment by Essam315** [comment]
@peak3d
Sorry to ask, do you have a working release from 0.13.19 now, or this is just an old Debug log.

**Comment by peak3d** [comment]
@Essam315 Just tried latest master version on wetek HUB without any issues.
I currently don't use the beta version, but I would suggest to reinstall / or logout and try again.

**Comment by Essam315** [comment]
@peak3d
I did a clean install many times, but all the releases are down for me and for many others, could you please look in this post.

https://github.com/asciidisco/plugin.video.netflix/issues/555

https://github.com/asciidisco/plugin.video.netflix/issues/553

https://forum.kodi.tv/showthread.php?tid=329767&page=28

**Comment by Essam315** [comment]
It seems that the plugin is working on the android only now, i hope this might help fixing the problem.

https://forum.kodi.tv/showthread.php?tid=329767&pid=2795423#pid2795423

**Comment by peak3d** [comment]
@Essam315  MSLv2 is currently under development, I don't think that any change in inputstream.adaptive is needed.
Do I read right that you have code to convert subs from the new JSON to DASH in MSLv2 ?

**Comment by Essam315** [comment]
@peak3d
No, i just used a workaround to generate the subtitles links in Webvtt format in manifest.json,

**Comment by Essam315** [comment]
@peak3d No, I just used a workaround to generate the subtitles links in webvtt format in manifest.json.

And here is the manifest.json of the movie Sarajevo (2014).

[manifest.zip](https://github.com/asciidisco/plugin.video.netflix/files/2624355/manifest.zip)

**Comment by Essam315** [comment]
@peak3d No, i have not such code.
