### ISSUE TITLE
Frequent freezes on RPi3+

### ISSUE THREAD

**Issue by ant9000** [asciidisco/plugin.video.netflix#564]
*I'm submitting a ...*
  - [x] bug report

## General infomration

Running on OSMC with an updated beta of Kodi 18.

### Prerequisites

I have updated via git to 0.13.20 (otherwise Netflix is broken); but I had the same problem with 0.13.18.

### Description

No TV show ends without freezing at least once during playback. The playback is unresponsive for 20 - 60 seconds (at times even more), during which the CPU is idling and no network traffic appears. Kodi is still responsive, but the video player controls won't do anything. Trying to stop the video makes everything freeze until the end of the stalling phase - but eventually the system recovers correctly.

I've successfully used version 0.14.0 from Caphm, which does not exhibit this problem unless I turn on the IPC setting - so I imagine my issue could be related to that.

### Steps to Reproduce

Play anything and wait - in three weeks I haven't been able to watch one single movie without a freeze,

### Installation

First time I've installed the plugin from Netflix Repo; then upgraded code via git.

### Operating System

* [ x] Linux (ARM)

**Comment by roopeh** [comment]
I'm running smoothly on my RPi 3 with 0.13.20. I have set max resolution general and secure decoders to 720p from inputstream settings, and I have enabled everything from 'expert' section in Netflix plugin's settings. 
Which version of inputstream do you have btw? I have latest Milhouse's (Libreelec) which ships with 2.3.12.

**Comment by jakermx** [comment]
RPI3:~ # cat kodi.log  | grep inputstr
12:13:52.520 T:1938226720  NOTICE: ADDON: inputstream.adaptive v999.2.3.11 installed
12:13:52.520 T:1938226720  NOTICE: ADDON: inputstream.rtmp v999.2.0.4 installed
12:13:52.520 T:1938226720  NOTICE: ADDON: kodi.binary.instance.inputstream v2.0.8 installed
12:13:52.522 T:1938226720  NOTICE: ADDON: script.module.inputstreamhelper v0.3.3 installed
RPI3:~ # uname -a
Linux RPI3 4.19.4 #1 SMP Fri Nov 23 21:03:25 GMT 2018 armv7l GNU/Linux

**Comment by jakermx** [comment]
I have RPI3 B+, with PoE Hat Running 1080p videos it freezes sometimes, but if I use WiFi it dont...but the GPU and CPU temp goes pretty high, it is not recommend to run them on RPI, so 720p works for me

**Comment by ant9000** [comment]
I'm using 720x480, and the total CPU load is about 30% - I don't think the freezes depend on the CPU. I will look for differences in inputstream.adaptive, and report back.

Thx a lot!

**Comment by ant9000** [comment]
I've been using the overlay screen to determine video resolution, and always seen it low. My subscription does not entitle me to more than 720 (height, I know), so I assumed there was no need to explicitly define a cap in inputstream (version is 2.3.11, BTW). Knowing that it works for you I've followed your advice and defined 720 as max in the addon - played for more than one hour and a half without issues. Need to test more for being sure, but that config alone seems to have solved the freezes. Thanks a bunch!
