### ISSUE TITLE
HTTP request errors, no videos playing

### ISSUE THREAD

**Issue by kuba2k2** [asciidisco/plugin.video.netflix#565]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?
I'm running the latest version from MSL2 branch. 

### Description

Video playing doesn't work, nothing happens. Sometimes the plugin doesn't open at all.

### Steps to Reproduce

1. Open Netflix
2. Play a video

**Expected behavior:** [What you expected to happen]
I expect the video to play

**Actual behavior:** [What actually happened]
The video doesn't play, a grey background shows for a second, then it goes back to normal background, and progress bar just disappears.
Sometimes the plugin doesn't run at all ("Netflix error" when trying to open).

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [x] I´m using a different source (Please tell which)
I'm running the latest version from MSL2 branch. Installed from ZIP.

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

 Raspberry Pi 3, Raspbian Stretch, Kodi 18 RC1 latest version from this thread
[https://www.raspberrypi.org/forums/viewtopic.php?t=222954](https://www.raspberrypi.org/forums/viewtopic.php?t=222954)

## Debug log

When the video doesn't play:
[https://pastebin.com/ARtiDqXy](https://pastebin.com/ARtiDqXy)
When Netflix wasn't opening at all:
[https://pastebin.com/ir2TKZad](https://pastebin.com/ir2TKZad)

**Comment by jakermx** [comment]
Use master 0.13.20 since msl2 ins not the last one... unistall cleaning settings and reinstall..

**Comment by roopeh** [comment]
Have you tried master branch?
