### ISSUE TITLE
Can not open specific directories

### ISSUE THREAD

**Issue by gabbello** [asciidisco/plugin.video.netflix#576]
*I'm submitting a ...*
  - [x ] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
kodi 18 rc1
### Prerequisites

* [ x] Are you running the latest version?

### Description
I can not get to various sections in the menu (e.g. "Continue watching", "Genre" etc)

### Steps to Reproduce
1. Try to open some directories like "Continue watching shows for user X", "Genre", etc.
2. Most of the times the Working icon will appear but the directory does not open

Some directories never open (e.g. Genre), some open all the time (E.g. Documentaries)

**Expected behavior:** [What you expected to happen]
Open the directory and show the list of items
**Actual behavior:** [What actually happened]

E.g. log output when I can not open " "Continue watching shows..."
```
20:42:08.173 T:1386095344 WARNING: CPythonInvoker(23, /root/.kodi/addons/plugin.video.netflix/addon.py): the python script "/root/.kodi/addons/plugin.video.netflix/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE,N9XBMCAddon9xbmcaddon5AddonE
20:42:08.183 T:1520431856   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?action=video_list&type=continueWatching&video_list_id=b6e456f1-0577-4c52-aa94-f97cdebcf4af_42864075X3XX1544299765377
20:42:08.185 T:1900084880   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?action=video_list&type=continueWatching&video_list_id=b6e456f1-0577-4c52-aa94-f97cdebcf4af_42864075X3XX1544299765377) failed
```

## Context (Environment)
raspberry pi 3

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by jakermx** [comment]
Try adding the timeout parameter for open_url calls, on Navigation.py

**Comment by jakermx** [comment]
Edit the line 1053 of the Navigation.py file, add the timeout parameter and set it to 60 seconds, it is enough, but it could delay some other actions in case of real timeouts.. but it will solve your issue.
data = urllib2.urlopen(full_url , timeout = 60 ).read()

**Comment by gabbello** [comment]
thank you very much. Indeed it solved the issue.

**Comment by peno64** [comment]
Why was this change not added in the latest version (0.13.22)
At least as a setting in the addon options?
I also had to add the timeout to 60 to solve this issue si I guess alot of people have this and not everyone knows how to do this.
Is there a negative site in adding this timeout parameter to the open call?
