### ISSUE TITLE
Missing subtitles lines for some shows

### ISSUE THREAD

**Issue by gabbello** [asciidisco/plugin.video.netflix#578]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
For some of the shows the subtitles appear all in CAPS and don't show second line on the screen.
### Prerequisites

* [x] Are you running the latest version?

### Description

On laptop (in browser) all is fine.
I used network inspector to see how the subtitle file looks and indeed the CAPS part is at it comes from netflix
e.g. below:
```
<tt xmlns:tt="http://www.w3.org/ns/ttml" xmlns:ttm="http://www.w3.org/ns/ttml#metadata" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" xmlns:tts="http://www.w3.org/ns/ttml#styling" xmlns="http://www.w3.org/ns/ttml" ttp:cellResolution="40 19" ttp:pixelAspectRatio="1 1" ttp:tickRate="10000000" ttp:timeBase="media" tts:extent="640px 480px" xml:lang="">
<head>
<ttp:profile use="http://netflix.com/ttml/profile/dfxp-ls-sdh"/>
<styling>
<style tts:color="white" tts:fontFamily="monospaceSansSerif" tts:fontSize="100%" xml:id="style0"/>
<style tts:color="white" tts:fontFamily="monospaceSansSerif" tts:fontSize="100%" tts:fontStyle="italic" xml:id="style_0"/>
</styling>
<layout>
<region xml:id="region_00">
<style tts:textAlign="left"/>
<style tts:displayAlign="center"/>
<style tts:backgroundColor="transparent"/>
</region>
<region xml:id="region_01">
<style tts:textAlign="left"/>
<style tts:displayAlign="center"/>
<style tts:backgroundColor="transparent"/>
</region>
<region xml:id="region_02">
<style tts:textAlign="left"/>
<style tts:displayAlign="center"/>
<style tts:backgroundColor="transparent"/>
</region>
</layout>
</head>
<body style="style0">
<div xml:space="preserve">
<p begin="26673333t" end="39592916t" region="region_00" tts:extent="40.00% 5.33%" tts:origin="47.50% 73.96%" xml:id="subtitle0">WHOA, WHOA, WHOA.</p>
<p begin="26673333t" end="39592916t" region="region_01" tts:extent="10.00% 5.33%" tts:origin="10.00% 79.29%" xml:id="subtitle1">
<span style="style_0">(Amy)</span>
</p>
<p begin="26673333t" end="39592916t" region="region_02" tts:extent="10.00% 5.33%" tts:origin="10.00% 84.62%" xml:id="subtitle2">
<span style="style_0">WHOA!</span>
</p>
<p begin="40000000t" end="52502499t" region="region_00" tts:extent="15.00% 5.33%" tts:origin="25.00% 84.62%" xml:id="subtitle3">SETTLE.</p>
<p begin="52919583t" end="68341666t" region="region_00" tts:extent="30.00% 5.33%" tts:origin="32.50% 84.62%" xml:id="subtitle4">SORRY, SARGE.</p>
<p begin="68758750t" end="99592916t" region="region_00" tts:extent="67.50% 5.33%" tts:origin="15.00% 84.62%" xml:id="subtitle5">UGH, HALLOWEEN IS THE WORST.</p>
<p begin="100000000t" end="119592916t" region="region_00" tts:extent="40.00% 5.33%" tts:origin="10.00% 79.29%" xml:id="subtitle6">EVERYONE'S DRUNK,</p>
<p begin="100000000t" end="119592916t" region="region_01" tts:extent="35.00% 5.33%" tts:origin="10.00% 84.62%" xml:id="subtitle7">WEARING A MASK,</p>
<p begin="120000000t" end="135839166t" region="region_00" tts:extent="57.50% 5.33%" tts:origin="10.00% 84.62%" xml:id="subtitle8">AND CARRYING A FAKE GUN.</p>
<p begin="136256250t" end="157507499t" region="region_00" tts:extent="57.50% 5.33%" tts:origin="10.00% 79.29%" xml:id="subtitle9">PLUS ALL THE GIRLS THINK</p>
<p begin="136256250t" end="157507499t" region="region_01" tts:extent="57.50% 5.33%" tts:origin="10.00% 84.62%" xml:id="subtitle10">THEY HAVE TO DRESS SEXY.</p>
<p begin="157924583t" end="187507499t" region="region_00" tts:extent="62.50% 5.33%" tts:origin="25.00% 79.29%" xml:id="subtitle11">I KNOW, THAT IS THE WORST.</p>
<p begin="157924583t" end="187507499t" region="region_01" tts:extent="52.50% 5.33%" tts:origin="35.00% 84.62%" xml:id="subtitle12">PLEASE MAKE THEM STOP.</p>
```

here the lines: "WEARING A MASK" and "PLEASE MAKE THEM STOP." are not appearing.
I noticed that in browser these lines are shown as second line of the subtitle, while on kodi and raspberry there are never 2 lines.  

I tired changing subtitle position and playing with font size but it did not help.
Note that on other shows (where subtitles are not caps) I can see 2 lines of subtitles per screen.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]
Show all show subtitles
**Actual behavior:** [What actually happened]

## Context (Environment)
kodi 18 rc1
raspberyy pi3
### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by gabbello** [comment]
For better understanding see how it looks on browser (on kodi second line is missing):
file:///home/olga/Desktop/Screenshot%20from%202018-12-11%2023-57-08.png

**Comment by gabbello** [comment]
See how it looks in browser. In kodi second line is missing:

**Comment by Essam315** [comment]
In Netflix plugin 0.13.21, go to this folder

C:\Users\Essam\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib

and open "MSLv2.py", then replace

`        if ia_addon and self.nx_common.compare_versions(map(int, ia_addon.getAddonInfo('version').split('.')), [2, 3, 8]) >= 0:
            profiles.append('webvtt-lssdh-ios8')
        else:
            profiles.append('simplesdh')`

with

`        if ia_addon and self.nx_common.compare_versions(map(int, ia_addon.getAddonInfo('version').split('.')), [2, 3, 8]) >= 0:
            profiles.append('simplesdh')
        else:
            profiles.append('simplesdh')`

**Comment by Essam315** [comment]
@jakermx This problem happens because the WebVTT subtitles in English language used by Netflix have many of the alignments tags {\an1} to {\an8} (only a few subtitles and usually are closed captions), and the subtitles loses them after converting the subtitles from WebVTT to SRT format, so we get two lines at the same time in the same position, the solution for this problem is to force the English subtitles to use 'simplesdh' only.

See here.

![webvtt1](https://user-images.githubusercontent.com/42877866/49851158-db66fd80-fde8-11e8-8d23-727d755712c5.jpg)


![webvtt2](https://user-images.githubusercontent.com/42877866/49851170-e6ba2900-fde8-11e8-98c0-cf5c8867b255.jpg)

**Comment by jakermx** [comment]
Gotcha

**Comment by Essam315** [comment]
If you are playing the video in windowed mode, try playing it in full screen mode, go to "Settings", "System", "Display", from "Display mode" choose "Full screen".

![full1](https://user-images.githubusercontent.com/42877866/49854659-88df0e80-fdf3-11e8-895a-3e39c6ae7cde.jpg)

![sub1](https://user-images.githubusercontent.com/42877866/49854927-597cd180-fdf4-11e8-8de5-6f5b204cc9a1.jpg)


![sub2](https://user-images.githubusercontent.com/42877866/49854941-600b4900-fdf4-11e8-9994-75e64a3db0f7.jpg)

**Comment by Essam315** [comment]
If you are playing the video in windowed mode, try playing it in full screen mode, go to "Settings", "System", "Display", from "Display mode" choose "Full screen".

![full1](https://user-images.githubusercontent.com/42877866/49854659-88df0e80-fdf3-11e8-895a-3e39c6ae7cde.jpg)



![fullsub](https://user-images.githubusercontent.com/42877866/49856997-06a61880-fdfa-11e8-89b9-3d7b0a1f71e5.jpg)



![fullsub2](https://user-images.githubusercontent.com/42877866/49857187-94820380-fdfa-11e8-91d9-e578fd4d95fe.jpg)



@jakermx I have found that when the lines have the same timing, they just get displayed in an order by its number in the subtitle file on the same screen, i was using Kodi in windowed mode and the lines were overlapping for me, when i switched to full screen mode everything became just fine.

![333](https://user-images.githubusercontent.com/42877866/49859752-02c9c480-fe01-11e8-9a4c-114b45749fda.png)


![srt11](https://user-images.githubusercontent.com/42877866/49859431-348e5b80-fe00-11e8-94fd-cab41fed7bfc.jpg)


![sub1](https://user-images.githubusercontent.com/42877866/49859441-3c4e0000-fe00-11e8-9fd1-c67b4f5c4121.jpg)


![sub2](https://user-images.githubusercontent.com/42877866/49859455-4243e100-fe00-11e8-835e-e46b8437f2a9.jpg)

**Comment by gabbello** [comment]
Where are all the comments on this issue from @Essam315?

Anyway I managed to fix this by doing by modifying in "MSLv2.py";

```
if ia_addon and self.nx_common.compare_versions(map(int, ia_addon.getAddonInfo('version').split('.')), [2, 3, 8]) >= 0: profiles.append('webvtt-lssdh-ios8') else: profiles.append('simplesdh')
```
with
```
if ia_addon and self.nx_common.compare_versions(map(int, ia_addon.getAddonInfo('version').split('.')), [2, 3, 8]) >= 0: profiles.append('simplesdh') else: profiles.append('simplesdh')  
```

Setting the Display mode to Full screen (In "Settings", "System", "Display", from "Display mode") might also work, but I don't have this option on raspberry installation.

**Comment by Renoise2** [comment]
Gabello, signed up on Github just to be able to say THANK YOU! The incomplete subtitles were making me crazy.
