### ISSUE TITLE
video / audio desync

### ISSUE THREAD

**Issue by qqkami** [asciidisco/plugin.video.netflix#584]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information / description
getting video/audo desync with latest libwidevine update and it also causes the video to skip forward for a few second every now and then (roughly every 10-15 seconds)

### Prerequisites

* [yes] Are you running the latest version?

[Description of the bug or feature]

### Steps to Reproduce

1. open netflix
2. had to install the new libwidevine
3. suddenly videos desync from audio and skip forward

**Expected behavior:**
expected to be able to watch videos without any issues

**Actual behavior:**
video and audio starts desyncing and skips forward constantly (every few seconds and it skips for about 2-3 seconds)

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

(I tried it via zip and repo)

running on
raspberry pi 3+ running kodi 18 / libreelec millhouse (worked before recent widevine update)

**Comment by Endtt** [comment]
I have the same problem when i set 480p and than i wont have this problem but more than 480 p causes this problem please try this

**Comment by qqkami** [comment]
i tested it with 2 movies that were both 1080p apparently.. i now maxed it out to 720p and it's working again - before the update I didn't even see the 1080p option, weird.

also weird that it works for me on 720p and for you everything above 480p seems to cause issues

**Comment by jakermx** [comment]
RPI does not work fine running 1080p videos, it is recommended to use up to 720p resolutions... because DASH and Widevine are software based codec, not available for hardware yet....
