### ISSUE TITLE
[Inputstream] Video playback not working for all Videos

### ISSUE THREAD

**Issue by reey** [asciidisco/plugin.video.netflix#59]
I'm using the latest libreelec agile build from Raybuntu for the odroid c2 (f5f6292)..
I'm watching Marvels Iron fist at the moment but I'm not able to completly watch Episode 9..
I was able to start it, but then it aborted..
If I now try to continue watching or start the episode from the beginning, I'm receiving this in my log:

> 17:45:23.493 T:4111863808  NOTICE: VideoPlayer: Opening: http://localhost:34323/manifest?id=80002561
17:45:23.493 T:4111863808 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
17:45:23.497 T:3550307232  NOTICE: Creating InputStream
17:45:25.671 T:3550307232  NOTICE: Creating Demuxer
17:45:25.672 T:3550307232  NOTICE: Opening stream: 1 source: 256
17:45:26.069 T:3550307232  NOTICE: Creating video codec with codec id: 28
17:45:26.069 T:3550307232  NOTICE: Creating video thread
17:45:26.069 T:3558695840  NOTICE: running thread: video_thread
17:45:26.070 T:3550307232  NOTICE: Opening stream: 2 source: 256
17:45:26.151 T:3550307232  NOTICE: Finding audio codec for: 86057
17:45:26.151 T:3550307232  NOTICE: Creating audio thread
17:45:26.151 T:3567084448  NOTICE: running thread: CVideoPlayerAudio::Process()
17:45:26.152 T:3550307232  NOTICE: Opening stream: 14 source: 256
17:45:26.650 T:3550307232  NOTICE: Opening stream: 1 source: 256
17:45:26.650 T:3550307232  NOTICE: Creating video codec with codec id: 28
17:45:26.656 T:3550307232  NOTICE: Opening stream: 2 source: 256
17:45:26.656 T:3558695840   ERROR: CVideoPlayerVideo::OpenStream - Invalid framerate 0, using forced 25fps and just trust timestamps
17:45:26.656 T:3550307232  NOTICE: Closing stream player 3
17:45:26.657 T:3550307232  NOTICE: Opening stream: 14 source: 256
17:45:26.729 T:3550307232  NOTICE: Opening stream: 1 source: 256
17:45:26.730 T:3550307232  NOTICE: Opening stream: 2 source: 256
17:45:26.730 T:3550307232  NOTICE: Finding audio codec for: 86057
17:45:26.730 T:3550307232  NOTICE: Closing stream player 3
17:45:26.730 T:3550307232  NOTICE: Opening stream: 14 source: 256
17:45:26.737 T:3567084448  NOTICE: Creating audio stream (codec id: 86057, channels: 6, sample rate: 48000, pass-through)
17:45:26.899 T:4111863808  NOTICE: Using GL_TEXTURE_2D
17:45:26.938 T:4111863808  NOTICE: GL: Selecting Single Pass YUV 2 RGB shader
17:45:26.954 T:4111863808  NOTICE: GL: NPOT texture support detected
17:45:27.020 T:3550307232   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
17:45:27.020 T:3550307232 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
17:45:27.207 T:3550307232   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)

**Comment by reey** [comment]
Here the debug log:

> 18:12:31.979 T:4115402752   DEBUG: CRenderManager::Configure - 4
18:12:32.011 T:4115402752   DEBUG: Activating window ID: 12005
18:12:32.012 T:4115402752   DEBUG: ------ Window Deinit (MyVideoNav.xml) ------
18:12:32.012 T:4115402752   DEBUG: FreeVisualisation() done
18:12:32.013 T:4115402752   DEBUG: ------ Window Init (VideoFullScreen.xml) ------
18:12:32.013 T:4115402752    INFO: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
18:12:32.130 T:3544699808   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
18:12:32.139 T:3544699808   DEBUG: AddOnLog: InputStream Adaptive: Download https://ipv4_1-mce0-c004.1.fra001.dev.ix.nflxvideo.net/?o=AQHQDrVPRafbtT3RIGsdgLvmaPrqgmIqyCC1kr-9-jWzq8WA2_6noOIKXX1BYPHSR2dNrc-YSDTjLcmqj8t0ia9QKbtR8Qi7tNrtgWOJj2nxo0RvJiS6U5cl-f0oH_qVlyaWqWrNE2ZO5Jy5vfEKpR0S62Ywwjg&v=3&e=1492575040&t=E1IGOjqsvJC9M77_jhpRshkf01k finished, average download speed: 5550122.1846
18:12:32.140 T:3544699808   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Connection: keep-alive'
18:12:32.140 T:3544699808   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Range: bytes=319181-1414382'
18:12:32.140 T:3544699808   DEBUG: CurlFile::Open(0xd72a5210) https://ipv4_1-mce0-c004.1.fra001.dev.ix.nflxvideo.net/?o=AQHQDrVPRafbtT3RIGsdgLvmaPrqgmIqyCC1kr-9-jWzq8WA2_6noOIKXX1BYPHSR2dNrc-YSDTjLcmqj8t0ia9QKbtR8Qi7tNrtgWOJj2nxo0RvJiS6U5cl-f0oH_qVlyaWqWrNE2ZO5Jy5vfEKpR0S62Ywwjg&v=3&e=1492575040&t=E1IGOjqsvJC9M77_jhpRshkf01k
18:12:32.944 T:3544699808   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
18:12:32.944 T:3544699808 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
18:12:33.141 T:3544699808   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
18:12:33.145 T:3544699808   DEBUG: AddOnLog: InputStream Adaptive: Download https://ipv4_1-mce0-c004.1.fra001.dev.ix.nflxvideo.net/?o=AQHQDrVPRafbtT3RIGsdgLvmaPrqgmIqyCC1kr-9-jWzq8WA2_6noOIKXX1BYPHSR2dNrc-YSDTjLcmqj8t0ia9QKbtR8Qi7tNrtgWOJj2nxo0RvJiS6U5cl-f0oH_qVlyaWqWrNE2ZO5Jy5vfEKpR0S62Ywwjg&v=3&e=1492575040&t=E1IGOjqsvJC9M77_jhpRshkf01k finished, average download speed: 0.0000
18:12:33.145 T:3544699808   DEBUG: CVideoPlayer::HandleMessages - player started 1
18:12:33.145 T:3544699808   DEBUG: CVideoPlayer::HandleMessages - player started 2
18:12:33.145 T:3544699808   DEBUG: CVideoPlayer::SetCaching - caching state 3
18:12:33.145 T:3544699808   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
18:12:33.145 T:3544699808   DEBUG: CVideoPlayer::SetCaching - caching state 0
18:12:33.145 T:3544699808   DEBUG: CDVDClock::SetSpeedAdjust - adjusted:0.000000
18:12:33.145 T:3544699808   DEBUG: VideoPlayer::Sync - Audio - pts: 128000.000000, cache: 310441.516570, totalcache: 600000.023842
18:12:33.145 T:3544699808   DEBUG: VideoPlayer::Sync - Video - pts: 41708.000000, cache: 50000.000000, totalcache: 100000.000000
18:12:33.146 T:3536311200   DEBUG: CVideoPlayerAudio - CDVDMsg::GENERAL_RESYNC(-182441.516570)
18:12:33.146 T:3536311200   DEBUG: CDVDAudio::Resume - resume audio stream
18:12:33.146 T:3574956960   DEBUG: CVideoPlayerVideo - CDVDMsg::GENERAL_RESYNC(-182441.516570)
18:12:33.146 T:3574956960   DEBUG: CVideoPlayerVideo::CalcDropRequirement - hurry: 0
18:12:33.146 T:3544699808   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Connection: keep-alive'
18:12:33.146 T:3544699808   DEBUG: CurlFile::ParseAndCorrectUrl() adding custom header option 'Range: bytes=170452-219766'
18:12:33.146 T:3544699808   DEBUG: CurlFile::Open(0xd72a5210) https://ipv4_1-mce0-c004.1.fra001.dev.ix.nflxvideo.net/?o=AQHQDrVPRafbtT3RIGsdgbjkbvXtgmIqyDe1kr-9-jWzq8WA2_6noOIKXX1BYPHSR2dNrc-YSDTjLcmqj8t0ia9QKbtR8Qi7tNrtgWOJj2nxo0RvJiS6U5cl-f0oH_qVlyaWqWrNF3ABsPWyheQaoFxS-y191A&v=3&e=1492575040&t=htO4H5qD16Icn7wG2ePdwduPEp0
18:12:33.148 T:4093146016   DEBUG: ActiveAE - start sync of audio stream
18:12:33.149 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 83416
18:12:33.153 T:3574956960   DEBUG: CVideoPlayerVideo::CalcDropRequirement - hurry: 1
18:12:33.159 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 125124
18:12:33.168 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 166833
18:12:33.174 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 208541
18:12:33.272 T:4093146016   DEBUG: ActiveAE::SyncStream - average error of -54.213400, start adjusting
18:12:33.273 T:4093146016   DEBUG: ActiveAE::SyncStream - average error -22.213400 below threshold of 30.000000
18:12:33.369 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 250249
18:12:33.382 T:3544699808   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
18:12:33.382 T:3544699808 WARNING: CCurlFile::FillBuffer - Reconnect, (re)try 1
18:12:33.432 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 291958
18:12:33.470 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 333666
18:12:33.504 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 375375
18:12:33.536 T:3574956960   DEBUG: CAddonVideoCodec: GetPicture::VC_PICTURE with pts 417083
18:12:33.560 T:3544699808   ERROR: CCurlFile::FillBuffer - Failed: Requested range was not delivered by the server(33)
18:12:33.561 T:3544699808   DEBUG: AddOnLog: InputStream Adaptive: Download https://ipv4_1-mce0-c004.1.fra001.dev.ix.nflxvideo.net/?o=AQHQDrVPRafbtT3RIGsdgbjkbvXtgmIqyDe1kr-9-jWzq8WA2_6noOIKXX1BYPHSR2dNrc-YSDTjLcmqj8t0ia9QKbtR8Qi7tNrtgWOJj2nxo0RvJiS6U5cl-f0oH_qVlyaWqWrNF3ABsPWyheQaoFxS-y191A&v=3&e=1492575040&t=htO4H5qD16Icn7wG2ePdwduPEp0 finished, average download speed: 0.0000

**Comment by asciidisco** [comment]
We´ve seen this behaviour before when the Frankfurt based CDN node is used:
...ipv4_1-mce0-c004.1.[b]fra001[/b].dev.ix.nflxvideo.net/?...

I´ll put in @liberty-developer as this is more of an inputstream related issue (if at all).

**Comment by reey** [comment]
I was able to watch it yesterday evening..

**Comment by asciidisco** [comment]
@reey Yes, that´s the problem with it. Maybe you were on a different CDN node or the FRA one wasn't as polluted as when you first tried. There could be many reasons why it worked, or better, why it didn't worked in the first place :(
