### ISSUE TITLE
No subtitles at all

### ISSUE THREAD

**Issue by lococola** [asciidisco/plugin.video.netflix#592]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

I have a Raspberry Pi 3 with the latest LibreElec alpha release (LibreELEC-RPi2.arm-8.90.009) which has Kodi 18, and I am running the latest version of this Netflix plugin. Subtitles are for some reason not available for any film or series, whether they are Netflix Originals or not. 

In the player settings I changed Preferred subtitle language to English, but I've also tried Forced Only and other options, it doesn't make a difference.

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

### Screenshots
![img_20181224_123336](https://user-images.githubusercontent.com/46095318/50398698-ea9b6300-0779-11e9-96b6-b429c476215e.jpg)

**Comment by Essam315** [comment]
This post might help you.

https://github.com/asciidisco/plugin.video.netflix/issues/542

**Comment by lococola** [comment]
Thanks. Turns out I wasn't running the latest version of Inputstream Adaptive. Updated that, rebooted and now I can select subtitles and audio channels again! Issue resolved.
