### ISSUE TITLE
Error with script.module.pycryptodome

### ISSUE THREAD

**Issue by slebo93** [asciidisco/plugin.video.netflix#594]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General infomration

I have Rasp pi  3+ and OSMC installed.

### Prerequisites

* [X] Are you running the latest version?
I believe so, yes.

### Description

I followed this guide to install the Netflix addon: 
https://www.makeuseof.com/tag/netflix-amazon-video-plex-raspberry-pi/

When i got the last step where i install Netflix from the Netflix Addon Repository i get the following error:  "The dependency on script.module.pycryptodome version 3.4.3 could not be satisfied"

After searching around i can see that im not the only one with this issue, some are suggesting to install LibreELEC 9 to fix the problem. However i cannot find an answer too if this solves the problem neither a guide to show how to install the libreELEC. 

So my question is, how do i come around this problem so that i can get the Netflix addon to work on OSMC?

### Steps to Reproduce

1. [First Step]:
 install OSMC on rasp pi 3+, follow the guide above

2. [Second Step] 
install the netflix addon from repository

3. [and so on...] 
u should get the error about pycryptodome

**Expected behavior:** [What you expected to happen] that it installed the addon.

**Actual behavior:** [What actually happened]  I get the following error:  "The dependency on script.module.pycryptodome version 3.4.3 could not be satisfied"

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

OSMC on rasp pi 3+

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
Im afraid im not familiar with LibreElec.
 
Best regards

//Slebo

**Comment by jakermx** [comment]
Are you sure yiu are running Kodi 18(Laia)?
I have RPI 2 and 3 and I can install and running it smoothly

**Comment by slebo93** [comment]
> Are you sure yiu are running Kodi 18(Laia)?
> I have RPI 2 and 3 and I can install and running it smoothly

Hey mate, thank you for the quick reply. Im not sure wether or not OSMC is build on Kodi 18, but what i have installed is the newest version of OSMC installed.

https://osmc.tv/

**Comment by zjoasan** [comment]
slebo93, in order to get Leia (kodi v.18) on OSMC, Go here and read for instructions https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631

**Comment by slebo93** [comment]
> slebo93, in order to get Leia (kodi v.18) on OSMC, Go here and read for instructions https://discourse.osmc.tv/t/testing-kodi-18-leia-builds-for-raspberry-pi/20631

Thank u Zjoasan, after installing Leia / kodi V18 it works and runs really great. thank  u
