### ISSUE TITLE
pycryptodomex 3.4.3 needed 

### ISSUE THREAD

**Issue by balexhu** [asciidisco/plugin.video.netflix#596]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [X] support request

I am running the latest OSMC on my Raspberry Pi 3 model B and I wanted to watch series and movies on Netflix with this plugin. I installed the Pycryptodomex (with the command "pip install pycryptodomex"  and the repository, after that I tried to install the latest version of the plugin(0.13.21.) but the process failed because of this error: 

script.module.pycryptodome version 3.4.3 could not be satisfied. 
However I've already installed it but the version 3.7.2

Is there any way to downgrade it? Or did I make any mistake? 

Please consider that I'm really beginner at this stuff, but I would like to improve.

**Comment by jakermx** [comment]
Are you sure you are running Kodi 18?
