### ISSUE TITLE
Videos stuttering, depending of their frame rate

### ISSUE THREAD

**Issue by Badsheep** [asciidisco/plugin.video.netflix#600]
*I'm submitting a ...*
  - [x] bug report

### Prerequisites

* [ ] Are you running the latest version?

I'm using an test version of Memphiz, named "kodi-20190104-0921308d-scriptobs_race-x86_64"

_BUT it's the same with all the recent versions, like rc3 or rc4._

### Description

I noticed that some Netflix videos are stuttering, on a old iMac from 2009 and on a recent MacBook Pro from 2017.

Settings :  fullscreen mode, with a video projector plugged in mirroring, in 1080p.
Auto adjust frame rate who works nicely :

24fps       >  my hdmi output switches to 24fps
25fps       >  my hdmi output switches to 50fps
23,976fps >  my hdmi output switches to 60fps

(24,50 & 60 are the 3 modes proposed by this video projector)
_All the speeds are correctly detected and applied to the hdmi output, whether I use the local files or streaming._

Here's the problem :

On the old iMac :

- all my local video files are fluid on the video projector (in 24fps, 23,976fps, or 25fps).
 the classical format I read is h264 in 1080p

- in the Netflix add-on : 24fps are perfectly fluid, others formats (23,976fps and 25fps) are stuttering.

Strange no ?

And more strange :

On the recent MacBook Pro, when I plug my videoprojector on it
(mirroring, 1080p, using a dodocool hub)

- all the local video files are fluid
- in the Netflix Add-on, it's the opposite !!!!  23,976fps and 25fps are fluid, but 24fps is stuttering !!!!!

crazy no ?
Any help ?
I'll post Logs as soon as possible.

### Operating System

* [x] OSX (x86/x64)

#### Additional informatin on the environment

Mac os 10.13.6

**Comment by Badsheep** [comment]
I'd like to precise something strange, by the way :
It switches of frame rate output WITHOUT NOTHING declared in the whitelist.
Is it normal ?

**Comment by Badsheep** [comment]
Here's [my log](url
http://78.194.163.41:30916/share/bFxJgRUu2HoQOQ9I/kodi%20Badsheep.log). (sorry it's too big (1Mo) to go on hastebin or similar...)

I did the following steps :

- read a 23,976 movie (stuttering) ("chicago princess")
- read a 24 movie (perfectly fluid) ("moi césar")
- read a 25 movie (stuttering) ("Blanche Gardin")

All at 1080p.
Video Component in Verbose Logging mode.

Thank you very much !!

**Comment by peak3d** [comment]
1,) Because of DRM restrictions Netflix is decoded using CPU, our device will  not have enough power to decode 1080p in realtime. YT / Others have less restrictions and h/w decoder is used.

2.) If whitelist is empty, kodi uses same logic as 17.x, switch refreshrate, but no resolution.
-> No bug, its a feature

**Comment by Badsheep** [comment]
Hello,

Thanks for answering so fast !

2) Ok cool I didn't know. I was trying to understand how the whitelist is
working.

1) Well I don't think so because I desactivated hardware acceleration...
And the computer is really able to read 1080p24, 1080p25 from Youtube
without any stutters


Le lun. 14 janv. 2019 à 08:53, Markus Pfau <notifications@github.com> a
écrit :

**Comment by peak3d** [comment]
Then you'll have to provide a debug log, enable video component debugging, and play a netflix movie some seconds

**Comment by Badsheep** [comment]
It's [here](https://github.com/asciidisco/plugin.video.netflix/issues/600#issuecomment-453459342).

**Comment by peak3d** [comment]
Have you enabed "Sync Playback To display" in settings::player::video ?

**Comment by Badsheep** [comment]
Yes I tried, without success (it changes nothing).
The auto frame rates works perfectly, I don't think the problem comes from here...

**Comment by Badsheep** [comment]
Ok well I think I have to accept the idea that this iMac is too old... 
Still it's very strange for all the reasons given (CPU not high, Youtube working perfectly,...)

**Comment by Badsheep** [comment]
Netflix can play 24fps movie (French/European  movies like "Moi césar" for example)

In Netflix I found 23,976fps (American movies, falsy called 24fps in the states)
24fps (French/European movies)
25fps (French European TV shows, for example the show of "Blanche Gardin")

All rates are correctly detected by Kodi, and it sets the right frame rate in the HMDI output.
It's just that ONLY the 24fps are correctly played.

**Comment by peak3d** [comment]
To be sure that audio does not play into your issue you can select Media:Video in inputstream.adaptive settings and verify if the the video without audio plays fine. I see some A/V corrections in log.

**Comment by Badsheep** [comment]
ok I think I already tested that but I test right away.

**Comment by peak3d** [comment]
You could also try forum.kodi.tv, there are other Mac users which may arrived your issue, too

**Comment by Badsheep** [comment]
I already did :)

**Comment by Badsheep** [comment]
OK I tested with only video, same issue...

**Comment by Badsheep** [comment]
Hello,

Well to be precise, no it's at all a hickup every second or something like that. ( I know that kind of issues as I work in sound for movies, and I know what it looks like when it's a repetitive drop frame...) 

No, in my case, it looks more like it's in slow motion all the time...
Let me just explain something I noticed, in case it might help : 

When I set logging on, it displays the realtime rate (and others stuff) on the top left of the screen.

When I'm reading a 24fps, the frame rate constantly hesitate between 23,4 and 24,4, and it's perfectly fluid (I think the display is wrong and the real frame rate is a perfect 24)

When I 'm reading a 23,967 movie, the rate switches to 60fps (NTSC): that's the frequency allowed by my video projector, and it's working absolutely well when I'm reading a 23,976fps local video file, or a 1080p23,976 source from Youtube (the display "hesitates" between 59,5 and 60,5, and the movie is perfectly fluid).

But in the case of the Netflix plugin, the real fps hesitates between about 42 to 46fps...
And that's really the impression I have when I watch.
And the CPU is around 70%, like it's always when I'm reading 1080p movies, local or via streaming.

I do the new logging right now.

**Comment by Badsheep** [comment]
[There it is](https://paste.kodi.tv/hahahogiye.kodi).

I played a 23,967 movie (stutters) , then a 24 movie (fluid).

**Comment by peak3d** [comment]
Yes, looks odd, I'll try to reproduce on my windows device

**Comment by Badsheep** [comment]
hm hm...

I don't really understand what you said but I'm glad you pointed a problem :)

**Comment by peak3d** [comment]
It's quite simple, there is a lop which renders GUI and video, on every VSYNC this loop should be visited and it checks if there is a new video frame to render.
If this loop is too slow (misses VSYNCS, e.g. arrives only 30 times a second), Video frames could be  too late and will be dropped.

**Comment by Badsheep** [comment]
Hello,

I just checked, and the loops are alright...

I tested a 24fps after the 23,976fps, and the values you found were about the 24fps.

So in the case of 23,976, it's 16ms : 

10:41:36.218 T:140735637267328   DEBUG: PrepareNextRender: frameOnScreen: 343498536.815350 renderPts: 343565203.487103 nextFramePts: 343593250.000000 -> diff: -28046.512897  render: 0 forceNext: 0
10:41:36.252 T:140735637267328   DEBUG: PrepareNextRender: frameOnScreen: 343531964.464350 renderPts: 343598631.136103 nextFramePts: 343593250.000000 -> diff: 5381.136103  render: 1 forceNext: 0
10:41:36.269 T:140735637267328   DEBUG: PrepareNextRender: frameOnScreen: 343549214.378350 renderPts: 343615881.050103 nextFramePts: 343634958.000000 -> diff: -19076.949897

And in 24fps it's 41ms : (your example)

0:42:10.057 T:140735637267328 DEBUG: PrepareNextRender: frameOnScreen: 3896329.285129 renderPts: 4062669.682978 nextFramePts: 4041666.000000 -> diff: 21003.682978 render: 1 forceNext: 0
10:42:10.098 T:140735637267328 DEBUG: PrepareNextRender: frameOnScreen: 3937676.479129 renderPts: 4104016.876978 nextFramePts: 4083333.000000 -> diff: 20683.876978 render: 1 forceNext: 0
10:42:10.140 T:140735637267328 DEBUG: PrepareNextRender: frameOnScreen: 3979390.094129 renderPts: 4145730.491978 nextFramePts: 4125000.000000 -> diff: 20730.491978 render: 1 forceNext: 0

The problem doesn't come from here

**Comment by Badsheep** [comment]
> Edit: I guess 23.97 on 24 Hz (Sync playback enabled) plays smooth, right?

no it doesn't work...

**Comment by peak3d** [comment]
> no it doesn't work...
Is no answer :-)

10:41:36.218 ...
10:41:36.252 ...

^^ This is more than 16, for me it is NOT Ok.

**Comment by Badsheep** [comment]
And sorry if I wasn't clear : the 23,976 with sync playback doesn't play smooth with 24.
it plays exactly the same than with 60.

**Comment by Badsheep** [comment]
OK I'm back after a few tests : 

YES you're right, when I set my screen frequency at 24fps, with auto frame rate OFF : 

- 24fps are perfect 
- 23,976 have an image drop every like 40 seconds (which is normal)
- 25fps have an image drop every second (which is normal too)

All that is true with local video files and Netflix add-on.

Now just to test I set my screen frequency to 60fps :  The 23,976 videos of Netflix are stuttering like before.

So what indues stuttering my config is to do 23,976 > 60Hz, but ONLY with Netflix ad-on (local videos and streaming from Youtube have no problem)

**Comment by peak3d** [comment]
Could be color conversion for example, but should be investigated by Mac user with same h/w as you have (widevine does not output NV12), could be that it is s/w converted / convered by shader which takes time.

**Comment by Badsheep** [comment]
OK thanks again for your help...

As you mentioned "color", I tried to play a bit with the images options in Kodi...

And in fact when I enable "dithering", the 23,976 is much smoother !!
(with the original configuration, auto frame rate ON, with a 60Hz hdmi output)
Strange, no ?

And the other strange thing is that the rate displayed on top left seems completely false (it's written below 40, but it'a really really more fluid than before - it must be very close of 60Hz I think)

But it doesn't work with 25Hz videos (or is less effective).

**Comment by Badsheep** [comment]
I use a workaround, I did a whitelist with 1080p24 and 50Hz (and removed the 60Hz).
Then overrided the 23,976 to play at 24 using the advancedsettings.xml
As I mostly watch 23,976 or 24fps on Netflix, it's ok.

Still if one day anybody finds the bug, it would be cool !
I'm sure it could improve the plugin performance, not only for old iMac but for everybody...

Anyway thanks again Peak3d for your help !

**Comment by Badsheep** [comment]
Hello,

If it can help anybody to find a solution for this problem, I noticed that when I press "O" during the playback (to display the playback information), the video is darker (which is normal)... BUT FLUID !

Strange no ?

It changes the speed of playback, as it can be saw by displaying the debug informations.

For example in my test of 25fps video ("Blanche Gardin")

- attempting to display at 50Hz (the screen frequency), it stutters and plays at around 38fps
(as it can be saw by displaying the debug informations)
- but when I hit "O", the fps goes to 25fps... and the video is playing perfectly.

It's the same with 23,976 videos, it's basically stuttering but it's fluid when I hit "O".

**Comment by Badsheep** [comment]
Seems fixed with Leia 18.2 !!

Now it stutters a little bit, but I'm quite sure it's related with the venerable age of my iMac...
But the problem described in the beginning of the thread is gone...

And the behavior when I hit "O" is more normal : it slows the system and stutters more.

So I think this bug was related to kodi itself and can be marked as solved.
