### ISSUE TITLE
Refactor GitHub tracking

### ISSUE THREAD

**Issue by mcallegari** [asciidisco/plugin.video.netflix#63]
Hi, not really an issue, but just worth to be mentioned.
I am following your refactor progresses (thanks for that !) and I noticed all the commits are named
"fixup! chore(refactor): Refactors plugin for easier maintanance: Adheres to python styleguides. Adds unit tests"

I mean, does it really make sense in a versioning system to name all the commits the same ?
You are loosing important information about what a commit actually changed. At least on GitHub.

I guess you're using a system (Karma ?) that produces this result.
Just my 2 cents. You can close this.
Thanks

**Comment by asciidisco** [comment]
@mcallegari Valid point of view. I´m myself a fan of atomic commits, but for this huge makeover of a codebase (and as I wasn't sure what will be touch during this eventually) I´ve decided to go through the pain of rewriting the history afterwards (when everything´s done) & to group changes/behaviours into valid commits before the merge (see https://robots.thoughtbot.com/autosquashing-git-commits).

As I´m the only one working on the branch, this seemed reasonable, as I hope to have a way clearer history in the master once this thing is merged.
I´m not sure if everything will play out as planned, as I´ve never done this on the scale of changes I´m doing here, but at least it looked like a valid guineapig to give it a try ;D
