### ISSUE TITLE
Integration with UpNext not working

### ISSUE THREAD

**Issue by shtrom** [asciidisco/plugin.video.netflix#630]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

## General infomration

I don't seem to be able to get the UpNext integration going. This is probably something silly I'm doing, but I can't work it out.

I've read #506 and #539. Both, as well as https://github.com/im85288/service.upnext/wiki/Video-Addons-with-Integration seem to indicate that UpNext is fully supported. What surprises me, going through the code of this addon, is that there are only [two uses of the AddonSignals](https://github.com/asciidisco/plugin.video.netflix/search?q=Signals&unscoped_q=Signals) plugin, and neither seem to use the [data that the UpNext plugin expects](https://github.com/im85288/service.upnext/wiki/Data-to-Send).

### Prerequisites

* [x] Are you running the latest version? -> v0.13.21 / service.upnext service.upnext v1.0.0 (this matches what's on their `master`)

### Description

This is probably just me not doing the right thing, but I can't work out what.

### Steps to Reproduce

1. Install service.upnext
2. Install plugin.video.netflix
3. Play a video in Netflix until the end

**Expected behavior:** [What you expected to happen]

The UpNext addon is triggered.

**Actual behavior:** [What actually happened]

Nothing happens.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo -> repository.netflix v1.0.1 
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [X] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

LibreElec 9.0.0

## Debug log

There's nothing notable in the debug log (searching for `netflix` and `upnext` strings)

**Comment by im85288** [comment]
This is only working with the beta version of the add on and onwards. Works fine from my recent tests

**Comment by shtrom** [comment]
Ah, cool. It might be worth mentioning the version (and source repo) at https://github.com/im85288/service.upnext/wiki/Video-Addons-with-Integration.

I'll close this issue. Thanks!
