### ISSUE TITLE
Plugin returns an error when trying to log in

### ISSUE THREAD

**Issue by kraghot** [asciidisco/plugin.video.netflix#644]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description

Error is presented when selecting a profile and only Search and Exported sections are present.

### Steps to Reproduce

1. Open Netflix
2. Select any profile

**Expected behavior:** Everything loading normally

**Actual behavior:** Only search and exported load and they don't work/are empty

## Context (Environment)

Ubuntu 18.04
Kodi nighty repo
NUC C7I5BNH

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [X] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

https://pastebin.com/hKhTXJ3h

**Comment by peak3d** [comment]
duplicate to #640 and #641 pls. close this issue.
