### ISSUE TITLE
How to select video quality

### ISSUE THREAD

**Issue by null-von-sushi** [asciidisco/plugin.video.netflix#649]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

I tried playing a few episodes but a lot of them lag like crazy (video) while the audio continues on. So in the end you have a laggy video with out-of-sync audio. Is there any way to select the stream quality?  

### Steps to Reproduce

Try watching something, like the second episode of 'Love, Death & Robots' (the one with the tree robots going around looking at human stuff). 

**Expected behavior:** [What you expected to happen]

Either play smoothly, or let me pick a lower quality.

**Actual behavior:** [What actually happened]

Lags like crazy

## Context (Environment)

Presumably you also need to own hardware that's not overpowered. I have a 1080p TV and use a HP Thin Client to watch stuff. While it's not great, it never really did this before, it only seems to do this with netflix.

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [x] I´m using a different source (Please tell which)

[That mediafire folder](https://www.mediafire.com/folder/vifnw8ve44bi7/KodiNetflixAddon#824883rxzl2ve)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Using Kodi from the repositories, on Arch Linux on openbox.

**Comment by jakermx** [comment]
On Input Stream Adaptive Config Screen select manual , instead of automatic, and it will start playing with the lower resolution available so you could change it on video submenu while playing

**Comment by null-von-sushi** [comment]
Yes, that worked. Thank you! I can now watch it as low as glorious 240p :grin: 
Weird that the netflix playback is handled by another plugin (I don't actually remember installing) though.

Anyways, thanks again!
