### ISSUE TITLE
VIdeo Does not play. MACOSX

### ISSUE THREAD

**Issue by KodiNewbie** [asciidisco/plugin.video.netflix#65]
Video does not appear on screen. All i can hear is the audio. Any suggestions? 
EDIT: 
Workaround a lot. Now its working. Awesome. :-)

**Comment by KodiNewbie** [comment]
Full LOG https://pastebin.com/5aZynmDb
Kodi (18.0-ALPHA1 Git:20170429-f5f5a7f03b-di) with modified repo url; linked to agile_fix branch of inputstream.adaptive
Inuputstream.adaptive.version 1.0.8 (Aglie_FIX ) [https://github.com/Uukrull/inputstream.adaptive/tree/agile_fix](url)
Libwidevine 1.4.8.962

I've built the Kodi from link you have mentioned. (It really takes hell lotta time bruh). Then I changed the binary-addon repo url linked to my repo in which i linked default inpustream.adaptive to **alige_fix** branch. 

After couple of hours of experimenting and time consuming process **i finally bulit my installer.** :-)
After I  installed the app, i installed this Netflix plugin. But it's not working for me at all.
Tried several hours but aint happening anything.
So decided to step back to the last known working config where I was able to get audio but not video. And guess what, **it's not working** either.
Could you please tell me where I'm going wrong?

**Comment by tornadochaser** [comment]
I´m facing the same issue. I can play every title I choose, no video, just audio. Could you please describe, what you did? Thanks :)

**Comment by mishac** [comment]
I've got the same issue on Ubuntu 17.04.  Any info on how you fixed it would be appreciated!

**Comment by trummerjo** [comment]
> Open an issue with a titles that summarises your problems and include:
> Kodi version (git sha as long as we´re on agile only)
> Inputstream.adaptive version (git sha as long as we´re on the agile branch)
> Your OS and OS version
> Libwedevine version
> A Kodi debug log that represents your issue

**Comment by asciidisco** [comment]
@KodiNewbie @tornadochaser @mishac Are you all sure that you use the agile fork of Kodi? The behaviour you´re describing is the same as when I try to run the plugin with Kodi 17 or the regular Kodi 18 nightlies?

**Comment by asciidisco** [comment]
Works for me with latest Kodi 18 Nightly & Inputstream v2 on Mac.
