### ISSUE TITLE
Show TV / more 42 episodes

### ISSUE THREAD

**Issue by bast69** [asciidisco/plugin.video.netflix#655]
*I'm submitting a ...*
  - [ ] bug report

## General infomration
have you solved this issue ? for an exemple "fairy tail" have 52 episodes in season 3.
thanks for your work
## Prerequisites

* [ ] Are you running the latest version?
Yes
### Description
They are only 42 episodes instead of 52...
Issue #288

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [X ] I installed the plugin via zip from the Releases page
* [ x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ x] Linux (ARM) raspberry pi 3b
* [ ] Android

#### Additional informatin on the environment
Libreelec 9.0.1

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by Essam31** [comment]
To fix this problem in 0.13.22 in `NetflixSession.py` replace

`def fetch_episodes_by_season(self, season_id, list_from=-1, list_to=40)`

with

`def fetch_episodes_by_season(self, season_id, list_from=-1, list_to=200)`

or use 0.14.0 beta from here, this problem fixed in this release.

https://codeload.github.com/CastagnaIT/plugin.video.netflix/zip/master

https://github.com/CastagnaIT/plugin.video.netflix

**Comment by jakermx** [comment]
Try 0.14beta23

**Comment by bast69** [comment]
I appied this change and it works 👍 
https://github.com/asciidisco/plugin.video.netflix/pull/401#issuecomment-397327979
