### ISSUE TITLE
Background service not available

### ISSUE THREAD

**Issue by JeroenTuinstra** [asciidisco/plugin.video.netflix#658]
*I'm submitting a ...*
  - [*] bug report
  - [ ] feature request
  - [ ] support request

## General information
Latest Kodi, latest beta Netflix: 0.14.0~beta23. Execution timin enabled

### Prerequisites

 [*] Are you running the latest version?

### Description

At startup Netflix Addon error:
"The requested action timed out. The background service may not yet be available if you just started Kodi/the addon. In this case try again in a moment"

Execution timing is enabled. And after several minutes a general Netflix error occures (Netflix Addon Error: see log file). 

**Expected behavior:** [What you expected to happen]

No errors, off course ;-)

### Installation

[*] I installed the plugin via zip from the Releases page
[ ] I´m using the Netflix Repo
[ ] I´m using a different source (Please tell which)

### Operating System

 [*] Linux (x86/x64)
 [ ] OSX (x86/x64)
 [ ] Windows (x86/x64)
 [ ] Linux (ARM)
 [ ] Android

#### Additional informatin on the environment

It is a LibreElec installation

## Debug log

http://ix.io/1EAI

**Comment by jakermx** [comment]
Add timeout parameter to the openurl call, on line 76 on ipc.py

You got this error
File "/storage/.kodi/addons/plugin.video.netflix/resources/lib/common/ipc.py", line 76, in make_http_call

it it this....

urllib2.urlopen(url=url, data=json.dumps(data)).read(),

change it to:

urllib2.urlopen(url=url, data=json.dumps(data), timeout=60).read(),


:)

**Comment by JeroenTuinstra** [comment]
I have added your suggestion, but no difference. Still the same error. I have uninstalled the addon, reset the computer, installed that latest addon version from here: https://github.com/CastagnaIT/plugin.video.netflix 

Now I cannot login, get the error at every turn you start netflix. Background services cannot start, and I understand because I cannot login. Basically these latest updates/beta's have rendered the plugin unusable. 

Log file: http://ix.io/1EYP

**Comment by jakermx** [comment]
have you tried using defaults?

Why did you enable execution timing?

**Comment by JeroenTuinstra** [comment]
Yep tried both, did not help. Have found a workaround and it works now: 
Uninstalled the plugin and installed version 0.13.22 (https://github.com/asciidisco/plugin.video.netflix)
Then reset the computer, and it asked for credentials
Updated to version 0.14.0~beta23 (https://github.com/asciidisco/plugin.video.netflix)
Reset the computer and it asked again for credentials.
It all seems to work now. 

This is the log file: http://ix.io/1EZ5

**Comment by JeroenTuinstra** [comment]
Previously I tried execution timing, because it gave this error that the background services were not started. I read somewhere that execution timing might help with that. However with or without execution timing, it did not matter. But as you can see the previous post, it is working now  ... somehow.
