### ISSUE TITLE
UpNext feature

### ISSUE THREAD

**Issue by 416eddie** [asciidisco/plugin.video.netflix#661]
*I'm submitting a ...*
  
  - [ ] feature request

Would it be possible to integrate UpNext like Seren add on has?

**Comment by jakermx** [comment]
If you install it, after install netflix addon ,you will see UpNext Integration on Playback Settings... but it does the same if you select Play from here on the contect menu while selecting the starting point...

**Comment by jakermx** [comment]
Not sure if it work on 0.13.22, but it works en 0.14b23

**Comment by 416eddie** [comment]
How do I get version 0.14b23

**Comment by jakermx** [comment]
Go Pull Requests then select Release 0.14.0 and find some links there, or use

Last one commited
https://github.com/CastagnaIT/plugin.video.netflix
Cheers

**Comment by jakermx** [comment]
Clone it as ZIP and install it from ZIP... remember to uninstall 0.13.x and say yes when asked to  remove settings, very important.... remove the repository where you get .013.x or disable autoupdate

**Comment by 416eddie** [comment]
Thanks
