### ISSUE TITLE
LibreELEC milhouse build nightly

### ISSUE THREAD

**Issue by iLLiac4** [asciidisco/plugin.video.netflix#67]
Form me netflix is not working i can list the series but nothing happens when i try to play them.

https://forum.libreelec.tv/thread/8860-netflix-and-tidal/#post52384

**Comment by marcelveldt** [comment]
That's because the Milhouse build is not based on the Agile branch but on the Kodi main.
You'll have to wait until the changes in the Agile branch are merged upstream or compile LibreElec yourself.
