### ISSUE TITLE
Cannot download the plugin | Website offline

### ISSUE THREAD

**Issue by GioPan04** [asciidisco/plugin.video.netflix#681]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description
I downloaded and installed the "Netflix Addon Repository" to install this plugin, but when I click on "Install from repository" and "Netflix Addon Repository" I get an error saying "Could not connect to repository."

### Steps to Reproduce

1. Download zip from [kodinerds repo](https://github.com/kodinerds/repo/blob/master/repository.netflix/repository.netflix-1.0.1.zip)
2. Install it with Kodi via Settings>Add-on Browser>Install from zip file>Select the zip you have download and install it
3. Settings>Add-on Browser>Install from repository>Select "Netflix Addon Repository"
4. You have the error.

**Expected behavior:** Download and install the plugin

**Actual behavior:** I get this error: "Could not connect to repository."

### Installation

* [ ] I installed the plugin via zip from the Releases page
* [x] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [x] Linux (ARM)
* [ ] Android

**Comment by spqr2001** [comment]
Same behauvior here , any updates out there ?

**Comment by GioPan04** [comment]
The only solution that I found is use  [this](https://github.com/CastagnaIT/plugin.video.netflix) repo...
