### ISSUE TITLE
Not listing videos on selected profile

### ISSUE THREAD

**Issue by thexholo** [asciidisco/plugin.video.netflix#686]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
when select profile, not listing videos
### Prerequisites

* [x] Are you running the latest version?

### Description
when I select any profile it does not list the categories or movies and it shows a message indicating that I check the log for more detail

### Steps to Reproduce

1. [First Step]
Instal kodi 18.2 on Android TV
2. [Second Step]
Install addon netflix 0.13.22 zip
3. [Third Step]
Launch Netflix and into credential, after list profiles.
4. [Fourt Step]
Select anyone profile

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [x] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log
http://paste.kodi.tv/ulamarigok

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by jakermx** [comment]
0.13.22 is not working, please upgrade it to 0.13.23 or 0.14.5..

**Comment by thexholo** [comment]
thanks, i am update to fix!
