### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by bagheerah** [asciidisco/plugin.video.netflix#687]
*I'm submitting a ...*
  - support request

### Prerequisites

* [ ] Are you running the latest version?
Yes

### Description
Three days ago it was working fine, then, since saturday, when entering the addon it requests user mail and password, but when I set them I get a message saying "please, check your credentials". I've made sure the credentials are correct by inserting them via copy-paste.

### Steps to Reproduce
just run the addon

**Expected behavior:** [What you expected to happen]
It should start

**Actual behavior:** [What actually happened]
It asks for credentials

### Installation

* [x] I installed the plugin via zip from the Releases page

### Operating System

* [x] Windows (x86/x64)

#### Additional informatin on the environment

windows 8.1 kodi Leia

## Debug log

https://drive.google.com/file/d/1-EZM7j4n4aWfD-6mLS_cw6gLTkIgPj4z/view?usp=sharing

**Comment by rdinkel** [comment]
same on pi 3b+, kodi 18, 22 feb build. it ran without changes in settings the last 4 months.

**Comment by marcnl** [comment]
Same issue here with 18.1 on a RPi 3B+ and 2x Kodi 18.1 on Win10 x64 (but I do get an email notification from Netflix for a "successful login").

**Comment by marcnl** [comment]
> Same issue here with 18.1 on a RPi 3B+ and 2x Kodi 18.1 on Win10 x64 (but I do get an email notification from Netflix for a "successful login").

Uninstalled the latest version I got from the repo, downloaded the ZIP file for 0.13.23, installed it manually and everything works fine again (on Win10, didn't try on my RPi's yet).

**Comment by bagheerah** [comment]
> 
> 
> > Same issue here with 18.1 on a RPi 3B+ and 2x Kodi 18.1 on Win10 x64 (but I do get an email notification from Netflix for a "successful login").
> 
> Uninstalled the latest version I got from the repo, downloaded the ZIP file for 0.13.23, installed it manually and everything works fine again (on Win10, didn't try on my RPi's yet).

I also get the notification from Netflix for a "successful Login". 
I have uninstalled the addon and installed the zip download: "version bump 0.13.23" from here. It still keeps doing the same. But I've noticed the version number I see in the addon information isn't 0.13.23, but 0.14.      Shouldn't it be 0.13.23 ??????
How do I install the addon manually,  Just copy paste?

**Comment by bagheerah** [comment]
I have tried uninstalling and then reinstalling 0.13.23 but preventing it from updating to 0.14 and now it works.
Thanks, marcnl.

**Comment by bagheerah** [comment]
I will close the post if nothing happens in a couple of days.

**Comment by andrewj720** [comment]
Same issue here ("check your credentials") with v14.0 on 18.1 (Ubuntu 18.04). Haven't tried the downgrade to v13.x yet though.

**Comment by marcnl** [comment]
> > Same issue here with 18.1 on a RPi 3B+ and 2x Kodi 18.1 on Win10 x64 (but I do get an email notification from Netflix for a "successful login").
> 
> Uninstalled the latest version I got from the repo, downloaded the ZIP file for 0.13.23, installed it manually and everything works fine again (on Win10, didn't try on my RPi's yet).

Uninstall and reinstall 0.13.23 from ZIP file on RPi3 running 18.1 on Raspbian also works fine.

**Comment by rdinkel** [comment]
can confirm. use  0.13.23 on pi 3b+. remove during uninstall the settings to prevent issues

**Comment by stareye72** [comment]
I have deleted the settngs running 0.13.23 but can't login on libreelec geneiric.
