### ISSUE TITLE
Plugin updates to 0.14.0 which has an issue with login

### ISSUE THREAD

**Issue by PascalBrouwers** [asciidisco/plugin.video.netflix#692]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [x] Are you running the latest version?

### Description

plugin updates to version 0.14.0, but that version has a problem with login which was fixed in 0.13.23

### Steps to Reproduce

1. Allow auto-update
2. Plugin updates to 0.14.0 (no idea where it get's this from)
3. Login
4. Get login error with correct login credentials

**Expected behavior:** [What you expected to happen]
Login correctly

**Actual behavior:** [What actually happened]
Get login error with correct login credentials

### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

Kodi 18.2
* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]
LibreElec 9.0.2 / Kodi 18.2

## Debug log

http://sprunge.us/bSFKkF

**Comment by ShadowBr0ther** [comment]
Hello. Try this version:
https://github.com/CastagnaIT/plugin.video.netflix/releases
Those are updated and working fine. (Current version: 0.14.6)

**Comment by PascalBrouwers** [comment]
Ah, tnx!
