### ISSUE TITLE
Series does not play.

### ISSUE THREAD

**Issue by MrMilk23** [asciidisco/plugin.video.netflix#699]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

### Prerequisites

* [X] Are you running the latest version?

### Description
If I want to play certain series like "You Me Her" I get an error message and it doesn't play the episode. (So far, he just doesn't want to play "You Me Her.")
Other series like "Designated Survivor" can be played without any problems.

### Steps to Reproduce

1.Start Kodi
2.Start Netflix Addon"
3. My List
4 Click on "You Me Her" then S01/02/03/04
5. Click on Episode

**Expected behavior:** 
That the series "You Me Her" will be played

**Actual behavior:**
I get an error message and he doesn't play the show. (I should look into the logs)

## Context (Environment)
Win 10 x64
Kodi 18.3 x64
### Installation

* [X] I installed the plugin via zip from the Releases page
* [X] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

https://zerobin.net/?3aa7530a23142045#WdXLN+Eh+Peqth0eGXKxfIAYYldozC404qWi9RoDNpE=

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by jakermx** [comment]
Are you trying to polay it from Netflix Interface or from Shorcut,/Library/Exported file?

**Comment by jakermx** [comment]
Delete your cache directory, I think it is not up to date or it is corrupted..., yo can rename the whole folder if you want to test...

C:\Users\_YourCurrentWindowsUser_\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix\cache


Keep us posted.

**Comment by MrMilk23** [comment]
Direct access via Netflix does not work.
And it doesn't work via export either.

I don't have a cache folder in C:\Users\D3sktop\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.netflix

I already reinstalled Netflix and it didn't work either.

**Comment by jakermx** [comment]
Please try 0.16 daily build, be sure to uninstall and select yes o remove settings.... and then restart, once done, install he new version , and reboot again....

**Comment by MrMilk23** [comment]
> 
> 
> Please try 0.16 daily build, be sure to uninstall and select yes o remove settings.... and then restart, once done, install he new version , and reboot again....

0.16 of what?
You mean 0.13.16?

Do you have a link for me ?

**Comment by jakermx** [comment]
Sorry, since I have a brand new left hand, I usually do a lot of typo errors

**Comment by jakermx** [comment]
this is the link 

https://www.mediafire.com/folder/vifnw8ve44bi7/KodiNetflixAddon#824883rxzl2ve

Please uninstall, remove settings, reboot, then install and reboot, and finally, run and add credentials.

**Comment by MrMilk23** [comment]
I've tested this, and now the series is playing.
https://github.com/jakermx/plugin.video.netflix_0.14.x/releases/tag/v0.14.6

Looks like everything's working out again.

**Comment by jakermx** [comment]
dont forget to close the issue when you are pleaced/satisfited wth the solution..

I would also recommned to remove the netflix repository, since you are on the devel side...
