### ISSUE TITLE
Video attributes: "watched" vs "playcount"

### ISSUE THREAD

**Issue by tilman2** [asciidisco/plugin.video.netflix#70]
I noticed that episode dictionaries hold a "playcount" key (int), whereas videos (movies?) hold a "watched" key (boolean).

Both of these dictionary types are processed by KodiHelper._generate_entry_info(), which only checks for the "watched" key: https://github.com/asciidisco/plugin.video.netflix/blob/master/resources/lib/KodiHelper.py#L771

This seems wrong. We probably should either:
 a) use "watched" xor "playcount" only in the dictionaries (populated in NetflixSession) or
 b) check for both keys in KodiHelper._generate_entry_info().

I like b) less because then you'd need to figure out which of the two gets priority (their values might contradict each other... e.g. watched=False, playcount=1).

**Comment by asciidisco** [comment]
I´ll already have a fix for this in code that isn't commited yet. Will be fixed in the next release.

**Comment by asciidisco** [comment]
Closing this in favour of https://github.com/asciidisco/plugin.video.netflix/issues/54
