### ISSUE TITLE
When I try to start the addon it just tells me it failed. Logs show something about a connection being refused.

### ISSUE THREAD

**Issue by henrikx** [asciidisco/plugin.video.netflix#71]
Here's my full log:

> 20:40:11.000 T:139896556124416  NOTICE: special://profile/ is mapped to: 
> special://masterprofile/
> 20:40:11.000 T:139896556124416  NOTICE: -----------------------------------------------------------------------
> 20:40:11.000 T:139896556124416  NOTICE: Starting Kodi (18.0-ALPHA1 Git:20170605-e62f501). Platform: Linux x86 64-bit
> 20:40:11.000 T:139896556124416  NOTICE: Using Release Kodi x64 build
> 20:40:11.000 T:139896556124416  NOTICE: Kodi compiled Jun 12 2017 by GCC 6.3.1 for Linux x86 64-bit version 4.10.1 (264705)
> 20:40:11.000 T:139896556124416  NOTICE: Running on Arch Linux 0.0, kernel: Linux x86 64-bit version 4.10.13-1-ARCH
> 20:40:11.001 T:139896556124416  NOTICE: FFmpeg version/source: 3.3
> 20:40:11.001 T:139896556124416  NOTICE: Host CPU: Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz, 8 cores available
> 20:40:11.001 T:139896556124416  NOTICE: special://xbmc/ is mapped to: /usr/local/share/kodi
> 20:40:11.001 T:139896556124416  NOTICE: special://xbmcbin/ is mapped to: /usr/local/lib64/kodi
> 20:40:11.001 T:139896556124416  NOTICE: special://xbmcbinaddons/ is mapped to: /usr/local/lib64/kodi/addons
> 20:40:11.001 T:139896556124416  NOTICE: special://masterprofile/ is mapped to: /home/henrik/.kodi/userdata
> 20:40:11.001 T:139896556124416  NOTICE: special://envhome/ is mapped to: /home/henrik
> 20:40:11.001 T:139896556124416  NOTICE: special://home/ is mapped to: /home/henrik/.kodi
> 20:40:11.001 T:139896556124416  NOTICE: special://temp/ is mapped to: /home/henrik/.kodi/temp
> 20:40:11.001 T:139896556124416  NOTICE: special://logpath/ is mapped to: /home/henrik/.kodi/temp
> 20:40:11.001 T:139896556124416  NOTICE: The executable running is: /usr/local/lib64/kodi/kodi.bin
> 20:40:11.001 T:139896556124416  NOTICE: Local hostname: heBridge
> 20:40:11.001 T:139896556124416  NOTICE: Log File is located: /home/henrik/.kodi/temp//kodi.log
> 20:40:11.001 T:139896556124416  NOTICE: -----------------------------------------------------------------------
> 20:40:11.082 T:139896556124416   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - Egenskap «OnLowBattery» finnes ikke
> 20:40:11.087 T:139896556124416   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - Egenskap «CanSuspend» finnes ikke
> 20:40:11.088 T:139896556124416   ERROR: DBus: Error org.freedesktop.DBus.Error.InvalidArgs - Egenskap «CanHibernate» finnes ikke
> 20:40:11.093 T:139896556124416  NOTICE: load settings...
> 20:40:11.140 T:139896556124416  NOTICE: Found 1 Lists of Devices
> 20:40:11.140 T:139896556124416  NOTICE: Enumerated PULSE devices:
> 20:40:11.140 T:139896556124416  NOTICE:     Device 1
> 20:40:11.140 T:139896556124416  NOTICE:         m_deviceName      : Default
> 20:40:11.140 T:139896556124416  NOTICE:         m_displayName     : Default
> 20:40:11.140 T:139896556124416  NOTICE:         m_displayNameExtra: Default Output Device (PULSEAUDIO)
> 20:40:11.140 T:139896556124416  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 20:40:11.140 T:139896556124416  NOTICE:         m_channels        : FL, FR
> 20:40:11.140 T:139896556124416  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
> 20:40:11.140 T:139896556124416  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
> 20:40:11.140 T:139896556124416  NOTICE:         m_streamTypes     : No passthrough capabilities
> 20:40:11.140 T:139896556124416  NOTICE:     Device 2
> 20:40:11.140 T:139896556124416  NOTICE:         m_deviceName      : alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1
> 20:40:11.140 T:139896556124416  NOTICE:         m_displayName     : GF116 High Definition Audio Controller Digital Stereo (HDMI 2)
> 20:40:11.140 T:139896556124416  NOTICE:         m_displayNameExtra: HDMI / DisplayPort 2 (PULSEAUDIO)
> 20:40:11.140 T:139896556124416  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 20:40:11.140 T:139896556124416  NOTICE:         m_channels        : FL, FR
> 20:40:11.140 T:139896556124416  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
> 20:40:11.140 T:139896556124416  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
> 20:40:11.140 T:139896556124416  NOTICE:         m_streamTypes     : No passthrough capabilities
> 20:40:11.140 T:139896556124416  NOTICE:     Device 3
> 20:40:11.140 T:139896556124416  NOTICE:         m_deviceName      : alsa_output.pci-0000_00_1b.0.analog-stereo
> 20:40:11.140 T:139896556124416  NOTICE:         m_displayName     : Built-in Audio Analog Stereo
> 20:40:11.140 T:139896556124416  NOTICE:         m_displayNameExtra: Speakers (PULSEAUDIO)
> 20:40:11.140 T:139896556124416  NOTICE:         m_deviceType      : AE_DEVTYPE_PCM
> 20:40:11.140 T:139896556124416  NOTICE:         m_channels        : FL, FR
> 20:40:11.140 T:139896556124416  NOTICE:         m_sampleRates     : 5512,8000,11025,16000,22050,32000,44100,48000,64000,88200,96000,176400,192000,384000
> 20:40:11.140 T:139896556124416  NOTICE:         m_dataFormats     : AE_FMT_U8,AE_FMT_S16NE,AE_FMT_S24NE3,AE_FMT_S24NE4,AE_FMT_S32NE,AE_FMT_FLOAT
> 20:40:11.140 T:139896556124416  NOTICE:         m_streamTypes     : No passthrough capabilities
> 20:40:11.145 T:139896556124416  NOTICE: No settings file to load (special://xbmc/system/advancedsettings.xml)
> 20:40:11.146 T:139896556124416  NOTICE: No settings file to load (special://masterprofile/advancedsettings.xml)
> 20:40:11.146 T:139896556124416  NOTICE: Default Video Player: VideoPlayer
> 20:40:11.146 T:139896556124416  NOTICE: Default Audio Player: paplayer
> 20:40:11.146 T:139896556124416  NOTICE: Disabled debug logging due to GUI setting. Level 0.
> 20:40:11.146 T:139896556124416  NOTICE: Log level changed to "LOG_LEVEL_NORMAL"
> 20:40:11.146 T:139896556124416  NOTICE: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
> 20:40:11.146 T:139896556124416  NOTICE: Loaded playercorefactory configuration
> 20:40:11.146 T:139896556124416  NOTICE: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
> 20:40:11.146 T:139896556124416  NOTICE: special://masterprofile/playercorefactory.xml does not exist. Skipping.
> 20:40:11.147 T:139896556124416  NOTICE: LoadFromXML - unable to load:/home/henrik/.kodi/userdata/wakeonlan.xml
> 18:40:11.154 T:139896556124416  NOTICE: Running database version Addons27
> 18:40:11.546 T:139895895717632  NOTICE: PulseAudio: Opened device alsa_output.pci-0000_01_00.1.hdmi-stereo-extra1 in pcm mode with Buffersize 150 ms
> 18:40:11.902 T:139896556124416  NOTICE: Checking resolution 16
> 18:40:12.168 T:139896556124416   ERROR: Failed to determine egl config for visual info
> 18:40:12.168 T:139896556124416 WARNING: Visual 0x2f4 of the window is not suitable, looking for another one...
> 18:40:12.168 T:139896556124416  NOTICE: Using visual 0x21
> 18:40:12.174 T:139896556124416   ERROR: VAAPI::CheckSuccess error: unknown libva error
> 18:40:12.174 T:139896556124416  NOTICE: GL_VENDOR = nouveau
> 18:40:12.174 T:139896556124416  NOTICE: GL_RENDERER = Gallium 0.4 on NVCF
> 18:40:12.174 T:139896556124416  NOTICE: GL_VERSION = 3.0 Mesa 17.0.5
> 18:40:12.174 T:139896556124416  NOTICE: GL_SHADING_LANGUAGE_VERSION = 1.30
> 18:40:12.174 T:139896556124416  NOTICE: GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_ATI_fragment_shader GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_EXT_depth_bounds_test GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_float GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_AMD_performance_monitor GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_texture_lod GL_ARB_texture_cube_map_array GL_ARB_texture_gather GL_ARB_texture_multisample GL_ARB_texture_query_lod GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_shader_precision GL_ARB_texture_compression_bptc GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_NV_vdpau_interop GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shader_atomic_counters GL_ARB_shader_image_load_store GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_clear_buffer_object GL_ARB_compute_shader GL_ARB_copy_image GL_ARB_explicit_uniform_location GL_ARB_framebuffer_no_attachments GL_ARB_invalidate_subdata GL_ARB_program_interface_query GL_ARB_robust_buffer_access_behavior GL_ARB_shader_image_size GL_ARB_shader_storage_buffer_object GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_texture_view GL_ARB_vertex_attrib_binding GL_KHR_debug GL_KHR_robustness GL_ARB_buffer_storage GL_ARB_clear_texture GL_ARB_compute_variable_group_size GL_ARB_internalformat_query2 GL_ARB_multi_bind GL_ARB_query_buffer_object GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_stencil8 GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_clip_control GL_ARB_conditional_render_inverted GL_ARB_cull_distance GL_ARB_derivative_control GL_ARB_get_texture_sub_image GL_ARB_pipeline_statistics_query GL_ARB_shader_texture_image_samples GL_ARB_texture_barrier GL_EXT_polygon_offset_clamp GL_KHR_context_flush_control GL_KHR_robust_buffer_access_behavior GL_ARB_shader_atomic_counter_ops GL_EXT_window_rectangles GL_MESA_shader_integer_functions
> 18:40:12.253 T:139895912503040  NOTICE: Running database version Addons27
> 18:40:12.254 T:139895912503040  NOTICE: Running database version ViewModes6
> 18:40:12.255 T:139895912503040  NOTICE: Running database version Textures13
> 18:40:12.257 T:139895912503040  NOTICE: Running database version MyMusic65
> 18:40:12.261 T:139895912503040  NOTICE: Running database version MyVideos108
> 18:40:12.262 T:139895912503040  NOTICE: Running database version TV30
> 18:40:12.262 T:139895912503040  NOTICE: Running database version Epg11
> 18:40:12.266 T:139896556124416  NOTICE: start dvd mediatype detection
> 18:40:12.282 T:139896556124416  NOTICE:   load skin from: /usr/local/share/kodi/addons/skin.estuary (version: 2.0.1)
> 18:40:12.401 T:139896556124416 WARNING: JSONRPC: Could not parse type "Setting.Details.SettingList"
> 18:40:12.458 T:139896556124416  NOTICE: Register - new joystickemulation device registered on application->1: Keyboard player (0000:0000)
> 18:40:12.464 T:139896556124416  NOTICE: initialize done
> 18:40:12.464 T:139896556124416  NOTICE: Running the application...
> 18:40:12.468 T:139896556124416  NOTICE: starting zeroconf publishing
> 18:40:12.468 T:139896556124416  NOTICE: CWebServer[8080]: Started
> 18:40:12.468 T:139896556124416  NOTICE: starting upnp client
> 18:40:12.470 T:139896556124416  NOTICE: starting upnp server
> 18:40:12.471 T:139896556124416  NOTICE: starting upnp renderer
> 18:40:12.473 T:139893829252864  NOTICE: ES: Starting UDP Event server on port 9777
> 18:40:12.473 T:139893829252864  NOTICE: UDP: Listening on port 9777 (ipv6 : true)
> 18:40:12.473 T:139896556124416   ERROR: JSONRPC Server: Failed to connect to sdpd
> 18:40:12.808 T:139895056889600  NOTICE: Twitch: Service: Start
> 18:40:12.993 T:139894626166528  NOTICE: [plugin.video.youtube] Startup: detected Krypton (Kodi-18.0), setting DASH_SUPPORT_BUILTIN = False, DASH_SUPPORT_ADDON = True
> 18:40:13.018 T:139895048496896  NOTICE: Skin Helper Service --> Skin Helper Service version 1.1.3 started
> 18:40:13.022 T:139892990408448  NOTICE: Skin Helper Service --> WebService - start helper webservice on port 52307
> 18:40:38.684 T:139895040104192   ERROR: CAddonInfo: tried to create add-on info with invalid data (id='script.xbmc.subtitles', type='0')
> 18:40:38.684 T:139895040104192   ERROR: CAddonDatabase: failed to build script.xbmc.subtitles
> 18:40:42.149 T:139895040104192   ERROR: GetDirectory - Error getting
> 18:41:00.527 T:139895018379008   ERROR: Previous line repeats 2 times.
> 18:41:00.527 T:139895018379008   ERROR: CAddonInfo: tried to create add-on info with invalid data (id='script.xbmc.subtitles', type='0')
> 18:41:00.527 T:139895018379008   ERROR: CAddonDatabase: failed to build script.xbmc.subtitles
> 18:41:07.706 T:139896556124416   ERROR: CAddonInfo: tried to create add-on info with invalid data (id='script.xbmc.subtitles', type='0')
> 18:41:07.706 T:139896556124416   ERROR: CAddonDatabase: failed to build script.xbmc.subtitles
> 18:41:25.555 T:139895887324928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.ImportError'>
>                                             Error Contents: No module named Cryptodome.PublicKey
>                                             Traceback (most recent call last):
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/service.py", line 11, in <module>
>                                                 from resources.lib.MSLHttpRequestHandler import MSLHttpRequestHandler
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/MSLHttpRequestHandler.py", line 9, in <module>
>                                                 from MSL import MSL
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/MSL.py", line 19, in <module>
>                                                 from Cryptodome.PublicKey import RSA
>                                             ImportError: No module named Cryptodome.PublicKey
>                                             -->End of Python script error report<--
> 18:41:27.546 T:139895912503040   ERROR: CAddonInfo: tried to create add-on info with invalid data (id='script.xbmc.subtitles', type='0')
> 18:41:27.546 T:139895912503040   ERROR: CAddonDatabase: failed to build script.xbmc.subtitles
> 18:41:29.686 T:139895912503040   ERROR: GetDirectory - Error getting
> 18:41:40.702 T:139895887324928   ERROR: Previous line repeats 6 times.
> 18:41:40.702 T:139895887324928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.URLError'>
>                                             Error Contents: <urlopen error [Errno 111] Connection refused>
>                                             Traceback (most recent call last):
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/addon.py", line 37, in <module>
>                                                 navigation.router(paramstring=sys.argv[2][1:])
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 25, in wrapped
>                                                 result = f(*args, **kwargs)
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 66, in router
>                                                 options = self.before_routing_action(params=params)
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 25, in wrapped
>                                                 result = f(*args, **kwargs)
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 399, in before_routing_action
>                                                 if self.check_for_designated_profile_change(params=params):
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 425, in check_for_designated_profile_change
>                                                 user_data = self.call_netflix_service({'method': 'get_user_data'})
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 534, in call_netflix_service
>                                                 data = urllib2.urlopen(full_url).read()
>                                               File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>                                                 return opener.open(url, data, timeout)
>                                               File "/usr/lib/python2.7/urllib2.py", line 429, in open
>                                                 response = self._open(req, data)
>                                               File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>                                                 '_open', req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                                 result = func(*args)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
>                                                 return self.do_open(httplib.HTTPConnection, req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>                                                 raise URLError(err)
>                                             URLError: <urlopen error [Errno 111] Connection refused>
>                                             -->End of Python script error report<--
> 18:41:40.727 T:139896556124416   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?content_type=video
> 18:41:40.728 T:139896556124416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?content_type=video) failed
> 18:41:46.416 T:139896556124416   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
> 18:41:46.644 T:139895887324928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.URLError'>
>                                             Error Contents: <urlopen error [Errno 111] Connection refused>
>                                             Traceback (most recent call last):
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/addon.py", line 37, in <module>
>                                                 navigation.router(paramstring=sys.argv[2][1:])
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 25, in wrapped
>                                                 result = f(*args, **kwargs)
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 60, in router
>                                                 if self.call_netflix_service({'method': 'is_logged_in'}) != True:
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 534, in call_netflix_service
>                                                 data = urllib2.urlopen(full_url).read()
>                                               File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>                                                 return opener.open(url, data, timeout)
>                                               File "/usr/lib/python2.7/urllib2.py", line 429, in open
>                                                 response = self._open(req, data)
>                                               File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>                                                 '_open', req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                                 result = func(*args)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
>                                                 return self.do_open(httplib.HTTPConnection, req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>                                                 raise URLError(err)
>                                             URLError: <urlopen error [Errno 111] Connection refused>
>                                             -->End of Python script error report<--
> 18:41:46.657 T:139896556124416   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?content_type=video
> 18:41:46.657 T:139896556124416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?content_type=video) failed
> 18:41:52.894 T:139895887324928   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <class 'urllib2.URLError'>
>                                             Error Contents: <urlopen error [Errno 111] Connection refused>
>                                             Traceback (most recent call last):
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/addon.py", line 37, in <module>
>                                                 navigation.router(paramstring=sys.argv[2][1:])
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/utils.py", line 25, in wrapped
>                                                 result = f(*args, **kwargs)
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 60, in router
>                                                 if self.call_netflix_service({'method': 'is_logged_in'}) != True:
>                                               File "/home/henrik/.kodi/addons/plugin.video.netflix/resources/lib/Navigation.py", line 534, in call_netflix_service
>                                                 data = urllib2.urlopen(full_url).read()
>                                               File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
>                                                 return opener.open(url, data, timeout)
>                                               File "/usr/lib/python2.7/urllib2.py", line 429, in open
>                                                 response = self._open(req, data)
>                                               File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>                                                 '_open', req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>                                                 result = func(*args)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
>                                                 return self.do_open(httplib.HTTPConnection, req)
>                                               File "/usr/lib/python2.7/urllib2.py", line 1198, in do_open
>                                                 raise URLError(err)
>                                             URLError: <urlopen error [Errno 111] Connection refused>
>                                             -->End of Python script error report<--
> 18:41:52.902 T:139896556124416   ERROR: GetDirectory - Error getting plugin://plugin.video.netflix/?content_type=video
> 18:41:52.902 T:139896556124416   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.netflix/?content_type=video) failed
>

**Comment by henrikx** [comment]
Nevermind I fixed it. If you're having this issue yourself, make sure you installed pycryptodome and pycryptoeomex using pip2 instead of pip. Kodi uses python2 instead of python3 so you need to make sure the module is installed for the right version of python.

**Comment by zombielinux** [comment]
I should note its not 'pycryptoeomex' but rather 'pycryptodomex'
