### ISSUE TITLE
Add atmos support

### ISSUE THREAD

**Issue by rguedes** [asciidisco/plugin.video.netflix#73]
Add atmos support: 
https://media.netflix.com/en/company-blog/dolby-atmos-coming-to-netflix

**Comment by piotrasd** [comment]
+1

**Comment by asciidisco** [comment]
I´ll check if we get the data in the manifest, if so, the possibility to add this for Android should be given.

**Comment by piotrasd** [comment]
audio is not crypted by DRM so maybe also in linux ?

**Comment by asciidisco** [comment]
It all depends on what we´re given in the manifest. to pass the ESN check fro Netflix, we need to send a User Agent that matches the decryption method used (which is the widevine lib extracted from the browser except for Android). So, if we´re lucky & Netflix is sloppy, we get the audio stream on other systems as well in the manifest file. If not (which I sadly believe will be the case), we only have a chance on Android.
Netflix just tightened their security measures in that regard, which we needed to adapt to.

**Comment by piotrasd** [comment]
ok thx for exmplain, i will keep corssed fingers :) anyway

**Comment by piotrasd** [comment]
i checked manifest and no atmos on linux :(

**Comment by asciidisco** [comment]
Tried a couple of combinations & none of them gave me manifests with Atmos support. I guess they´ll figure this out depending on the device id given in the ESN for Android.
Closing this for now.

**Comment by maniacgit** [comment]
As far as I know Atmos is currently only support on theXbox One. I've just tried the native Netflix App on the Shield and it only offers me 5.1.

**Comment by rguedes** [comment]
@asciidisco Use this ESN: NFANDROID1-PRV-SONYANDROIDTV2017-SONYBRAVIA=4K=GB and add this profile: ddplus-atmos-dash

Search by Atmos on netflix to get titles with Atmos support

**Comment by Wuschel-Wuschel** [comment]
Does @rguedes's remark help at maybe achieving Atmos support?

**Comment by rguedes** [comment]
@Wuschel-Wuschel last time I check, it works

**Comment by Wuschel-Wuschel** [comment]
Can you check again, please? If it works, can this be implemented in regular fashion to provide Atmos with all the Kodi-Netflix setups out there, @asciidisco?

**Comment by rguedes** [comment]
ESN didn't work. But if you add ddplus-atmos-dash to profile list, will works

**Comment by Wuschel-Wuschel** [comment]
That has to be done manually or can this be achieved with a neat little settings option for everyone?

**Comment by Ch1llb0** [comment]
@asciidisco, any news on this?

**Comment by irond13** [comment]
@rguedes Where do you set that profile?

**Comment by irond13** [comment]
@rguedes I've figured it out, and it works!

@Ch1llb0  I've submitted a pull request here: https://github.com/asciidisco/plugin.video.netflix/pull/678
