### ISSUE TITLE
Netflix not playing any shows or movies

### ISSUE THREAD

**Issue by Slotherer** [asciidisco/plugin.video.netflix#750]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General infomration
I'm using kodi 18.9 on libreelec and I just updated to the newest version of this plugin but the error stays unchanged.
### Prerequisites

* [x] Are you running the latest version? Yes, I updated to the newes verion after the bug first appeared.

### Description

yesterday i updated widevine. after that i was not able to play any show. I can navigate normaly to the episode i want to watch but wenn i try to start it, it loads for a second, stops and then starts again for a second. After that nothing happens. 

### Steps to Reproduce

1. Start Kodi 18.9 on libreelec
2. Open the Netflix plugin and choose any episode of any show.

**Expected behavior:** The stream should start

**Actual behavior:** The screen turns slightly darker and the loading circle appears, goes back to normal after a sec, starts loading again and goes back to normal

## Context (Environment)
libreelec 9.2.6
### Installation

* [x] I installed the plugin via zip from the Releases page
* [ ] I´m using the Netflix Repo
* [ ] I´m using a different source (Please tell which)

### Operating System

* [x] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

http://ix.io/3njS

**Comment by Slotherer** [comment]
Found out how to upload the log
http://ix.io/3njS

**Comment by jlckodi** [comment]
I have the same problem. I have installed kodi on raspberry with raspbian s/o.

**Comment by jlckodi** [comment]
Hi Soltherer.

I find the solution on this link: https://github.com/CastagnaIT/plugin.video.netflix/issues/1154

I have executed the following step and now my netflix running fine:

Go to Add-ons > My add-ons > Program add-ons > InputStream Helper > Configure > Restore Widevine CDM Library

I have restored the previous release of Widevine.

Regards

**Comment by Slotherer** [comment]
Hey jlckodi,
Thanks a lot that worked perfectly.
