### ISSUE TITLE
Cache settings?

### ISSUE THREAD

**Issue by iLLiac4** [asciidisco/plugin.video.netflix#76]
After some testing it on kodi it plays fine. The only problem is that after some time it starts to be choppy because of buffer. Watching it on smart tv or with chrome it buffers it so it plays without problem. In addon it seems that it does not use any buffer.

**Comment by asciidisco** [comment]
@iLLiac4 Debug Log?

**Comment by asciidisco** [comment]
https://forum.kodi.tv/showthread.php?tid=298462&pid=2616747#pid2616747

**Comment by iLLiac4** [comment]
Ok seems to be fixed. It works now also with 1037U.
I am still interested if this addon reads settings from kodi for buffering or. does it use its own settings.

TNX

**Comment by asciidisco** [comment]
@liberty-developer Can you shed some light on this? I don't know how exactly Inputstream does the buffering...

**Comment by asciidisco** [comment]
Some explanation can be found here: https://github.com/peak3d/inputstream.adaptive/issues/8

**Comment by betomoretti** [comment]
Hey, I'm not sure that this it's the right place and sorry if I'm doing a mistake. So, I would like to ask if it's possible to modify the cache buffer size.
