### ISSUE TITLE
Playing any Netflix video crashes Kodi under Windows 10 16241

### ISSUE THREAD

**Issue by bartolomesoriano** [asciidisco/plugin.video.netflix#78]
Running Leia nightly from 17 July 32-bit under Windows 10 Pro 16241.  Inputstream.adaptive is version 2.0.4. Whenever I try to play a video through the Netflix plugin, Kodi crashes.  Here is a link to the Kodi debug log: https://1drv.ms/u/s!AlII29kkG6TFh_IS3-ij7gKzF25Hvg.  Hopefully you can figure out what is going on, thank you.

**Comment by asciidisco** [comment]
Mhh,
I can't find something suspicious in the log. It looks fine for me.
Have you tried with another Kodi build (from the 15th or 16th maybe).
I don't have the hardware here to try & reproduce this but I´ll ask around & report back, if I find someone who can.

**Comment by asciidisco** [comment]
There´s some problem with the python.dll stuff in the 32-bit Windows Nightlies at the moment. Last suitable version should be this one: http://mirrors.kodi.tv/nightlies/windows/win32/master/KodiSetup-20170706-391fab1632-master-x86.exe

**Comment by bartolomesoriano** [comment]
@asciidisco thanks, I will try with an older nightly and see how it goes.

**Comment by asciidisco** [comment]
@bartolomesoriano Should be fixed with this nights build: https://github.com/xbmc/xbmc/pull/12512
