### ISSUE TITLE
[Video Playback] "The Last Kingdom" - Playing for few minutes and stalls

### ISSUE THREAD

**Issue by autogun** [asciidisco/plugin.video.netflix#90]
Netflix v0.11.20 on RPi3/LibreELEC #0810, 11-Aug-2017
Debug log: http://sprunge.us/igUi
No problems playing other titles

**Comment by asciidisco** [comment]
Hmm, I´ll forward this to @liberty-developer. Maybe he has a clue on what´s going on.

**Comment by asciidisco** [comment]
@autogun Have you had the chance to retest this with the latest Kodi/Inputstream/Widevine/Netflix Plugin combo?

**Comment by asciidisco** [comment]
Ping :)

**Comment by autogun** [comment]
I've upgraded everything to the latest version and was about to check but couldn't find "The Last Kingdom" in Netflix library anymore.

Oh well, watta bummer. :-(

**Comment by asciidisco** [comment]
Oh noes. Closing this then, if the error ever comes up again, please don't hesitate & reopen :)
