### ISSUE TITLE
[Repo] SSL Cert for https://johtru.com/repo/repo_files/ is expired

### ISSUE THREAD

**Issue by turbomettwurst** [asciidisco/plugin.video.netflix#92]
not much else to say, kodi currently crashes when trying to query the repo

**Comment by trummerjo** [comment]
I'll renew the cert ...
Kodi really crashes? If so, you should submit an issue to kodi too.

**Comment by turbomettwurst** [comment]
will do when it's confirmed working with a valid cert. 
Have not properly checked it's due to the certificate.

**Comment by turbomettwurst** [comment]
on a related note, if you need help with that, i'd be happy to...

**Comment by trummerjo** [comment]
sorry for the delay...
The certificate is now renewed!
