### ISSUE TITLE
[Refactor] Standalone library

### ISSUE THREAD

**Issue by oschwand** [asciidisco/plugin.video.netflix#96]
Do you think it would be possible to separate the Kodi-specific parts so that this implementation would be usable as a standalone library, for example to use with mpv or youtube-dl ?

I just had a quick look in the `resources/lib/` directory, but I am not familiar enough with the internal of Kodi plugins to have an idea if it is easily possible or not.

**Comment by asciidisco** [comment]
With the https://github.com/asciidisco/plugin.video.netflix/tree/chore/code-trim/resources/lib branch (that I haven't really found the time working on lately) I planned to factor out 2 libraries out of the plugin.

1) Some kind of generic framework that deals with all Kodi (18) related things & could be reused for other plugins
2) A library that contains all Netflix API related things (most probably the thing you want)

But (I don't know a thing about mpv or youtube-dl, so take this with a grain of salt), without something like https://github.com/peak3d/inputstream.adaptive build for those tools, you probably wouldn't have much luck playing a video. That library actually does the hard work of interfacing with the DRM decoder & decrypter to basically give you a proper video stream to watch.

Also, youtube-dl looks like a tool that is mainly used to download videos, not saying that this is impossible for DRMed content like you get from Netflix, but it probably is not legal to do so. I´m not saying you´re after that specifically, but I wouldn't support something like this. With this plugin we´re trying to stay within legal bounds as much as possible, which also means respecting the DRM protection of the content. Not trying to be harsh, or put words in your mouth, so please don't get me wrong, I just wanted to clarify that.

**Comment by oschwand** [comment]
Thanks for your detailed answer (the notification got lost somewhere and I am reading it only today).

I was not aware of the existence of inputstream.adaptive and of the work done by this component, I will have a look.

Concerning your legal concerns, youtube-dl is not anymore only a download tool but also a streaming client used as a backend for other media player (such as mpv). I don't know the position of netflix about third party clients but the problem may be also the existence of the --dump-video flag of mpv (or equivalent features of any player). Anyway, as soon as an libre part is involded somewhere, the drm are fucked-up...

I personally do not want to download anything, it is the exact contrary: I would be happy to not download anything and to stream the netflix contents to my client of choice.
