### ISSUE TITLE
Poor Video Quality on LibreElec

### ISSUE THREAD

**Issue by jpg73** [asciidisco/plugin.video.netflix#97]
Dear, 
I succeed to make Netflix works, but the video quality is poor ( compared to the one I get from Chromium
Strange to see in kodi.log that the resolution selected is  480x360 ( and I'm using HD TV)
HEre are info requested:
**_Kodi version (git sha if possible)_** 
Starting Kodi (18.0-ALPHA1 Git:67137d6). Platform: Linux x86 64-bit
**_Inputstream.adaptive version (git sha if possible)_** 
Ver999.2.0.7
_**Your OS and OS version**_
Kodi compiled Aug 10 2017 by GCC 7.1.1 for Linux x86 64-bit version 4.12.5 (265221)
Running on LibreELEC (Milhouse): devel-20170810020806-#0809-gfb748cf [Build #0809] 9.0, kernel: Linux x86 64-bit version 4.12.5
FFmpeg version/source: ffmpeg-3.3-kodi
Host CPU: Intel(R) Atom(TM) x5-E8000 CPU @ 1.04GHz, 4 cores available
**_Libwedevine version_**
No idea ! I'm using the download tool at the bottom of this link https://github.com/asciidisco/plugin.video.netflix/issues/30
**_KodiLOG_**
see https://pastebin.com/cbq9CnGj
Thanks in advance
JP

**Comment by trummerjo** [comment]
Try to change the streamselection in the inputstream.adaptive addon to manual and check if you can select a better video quality while playing.

**Comment by jpg73** [comment]
That's great! it works in manu mode 
Thanks a lot
JP
